package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey

internal val englishCorePlayTexts = mapOf(
    TextKey.GreetingPlayer to "Hello, {player}!", TextKey.ReadyForRecord to "Ready to set a new record?",
    TextKey.GameRooms to "Game rooms", TextKey.Ready to "Ready", TextKey.Matchmaking to "Matchmaking",
    TextKey.MatchFound to "Match found", TextKey.FindingOpponent to "Finding an opponent…",
    TextKey.RankedMatchmakingHint to "Prioritising players near your Elo.",
    TextKey.CasualMatchmakingHint to "Finding players in the same mode.", TextKey.EloRange to "Elo range",
    TextKey.NoEloImpact to "No Elo impact", TextKey.CancelMatchmaking to "CANCEL MATCHMAKING",
    TextKey.GuestNameTitle to "What should we call you?", TextKey.GuestNameDescription to "This name is only used for this play session.",
    TextKey.EnterNickname to "Enter nickname", TextKey.SaveNameProgressDescription to "Create an account to keep your name, Elo and history on Android/iOS.",
    TextKey.RoomLinkUnavailable to "The linked room no longer exists or is full.", TextKey.ChooseRoomType to "Choose room type",
    TextKey.DefaultRoomName to "{player}'s room", TextKey.PublicRooms to "PUBLIC ROOMS", TextKey.FindOpponent to "Find the right opponent",
    TextKey.PublicRoomsDescription to "Create a private room or join a waiting room.", TextKey.SaveProgressEmail to "SAVE PROGRESS WITH EMAIL",
    TextKey.SearchRooms to "Search room or host name", TextKey.All to "All", TextKey.Waiting to "Waiting",
    TextKey.RoomCount to "{count} rooms", TextKey.Reconnecting to "Reconnecting…", TextKey.AuthenticatingSession to "Authenticating session…",
    TextKey.Connecting to "Connecting…", TextKey.NoWaitingRooms to "No rooms are waiting. Create one or pull down to refresh.",
    TextKey.NoMatchingRooms to "No rooms match these filters.", TextKey.EnterRoomCode to "Enter room code",
    TextKey.PasteRoomCode to "Paste the code shared by the host.", TextKey.RoomCode to "Room code", TextKey.FindRoom to "FIND ROOM",
    TextKey.RoomCodeNotFound to "No room was found with this code.", TextKey.CreateNewRoom to "Create new room",
    TextKey.YouAreHost to "You will be the host.", TextKey.RoomName to "Room name", TextKey.Public to "Public", TextKey.Private to "Private",
    TextKey.PrivatePasswordRequired to "Players need a password.", TextKey.PublicNoPassword to "Anyone can join without a password.",
    TextKey.RoomPassword to "Room password", TextKey.RankedEloImpact to "Ranked · Affects Elo",
    TextKey.CasualNoEloImpact to "Casual · No Elo impact", TextKey.PrivateRoom to "Private room", TextKey.PublicRoom to "Public room",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ENTER",
    TextKey.JoinPrivateRoom to "Private room", TextKey.JoinRoomTitle to "Join room",
    TextKey.PrivateJoinDescription to "Enter the password to join “{room}”.", TextKey.PublicJoinDescription to "{room} • Hosted by {host}",
    TextKey.JoinedRoomCode to "ROOM CODE • {code}", TextKey.JoinedRoom to "IN ROOM", TextKey.ShareCodeHint to "Share the code to invite friends.",
    TextKey.WaitHostStart to "Wait for the host to start the match.", TextKey.PlayersTitle to "Players", TextKey.BlueTeam to "Blue Team",
    TextKey.RedTeam to "Red Team", TextKey.You to "You", TextKey.TeammateNumber to "Teammate {number}", TextKey.Teammate to "Teammate",
    TextKey.OpponentNumber to "Opponent {number}", TextKey.Opponent to "Opponent", TextKey.WaitingPlayer to "Waiting…",
    TextKey.HostYou to "Host • You", TextKey.Guest to "Guest", TextKey.Host to "Host", TextKey.WaitingForPlayer to "Waiting for player…",
    TextKey.ModeNumberCount to "{mode} • 50 numbers", TextKey.ShareRoomCode to "SHARE ROOM CODE", TextKey.ShareSheetError to "Could not open sharing. Please try again.",
    TextKey.CancelReady to "CANCEL READY", TextKey.ReadyAction to "READY", TextKey.WaitingForReady to "Waiting for everyone to be ready…",
    TextKey.InviteFriends to "INVITE FRIENDS", TextKey.Kick to "KICK", TextKey.CloseRoom to "CLOSE ROOM", TextKey.LeaveRoom to "LEAVE ROOM",
    TextKey.ReadyStatus to "READY", TextKey.WaitingStatus to "WAITING", TextKey.LatencyGood to "{latency} ms • Good",
    TextKey.LatencyStable to "{latency} ms • Stable", TextKey.LatencySlow to "{latency} ms • Slow",
    TextKey.OpponentReady to "OPPONENT READY", TextKey.MatchStarting to "The match is about to start",
    TextKey.LocalPlayerLabel to "YOU", TextKey.OpponentLabel to "OPPONENT",

    TextKey.ReactionHappy to "Happy", TextKey.ReactionLaugh to "Laugh", TextKey.ReactionFire to "On fire",
    TextKey.ReactionVictory to "Victory", TextKey.ReactionLove to "Love", TextKey.ReactionSpeed to "Speed up",
    TextKey.ExitMatchTitle to "Leave match?", TextKey.ForfeitCasualDescription to "Leaving now counts as a loss.",
    TextKey.ForfeitRankedDescription to "Leaving now counts as a loss and costs Elo.", TextKey.ExitMatch to "LEAVE MATCH",
    TextKey.ContinuePlaying to "KEEP PLAYING", TextKey.GameHeader to "{mode} · {matchType}", TextKey.GameDefaultRoom to "50-number match",
    TextKey.GameDisconnected to "Connection lost. Reconnecting…", TextKey.GameReconnecting to "Reconnecting to the match…",
    TextKey.TieScoreWarning to "Scores are tied — the next turn matters!", TextKey.CloseScoreWarning to "Neck and neck — only {difference} points apart",
    TextKey.LivesCount to "{count} lives", TextKey.PaceProgress to "PACE {current}/{total}", TextKey.SpeedValue to "SPEED  {speed}",
    TextKey.SendReaction to "Send reaction", TextKey.CorrectWrongSummary to "Correct {correct}  ·  Wrong {wrong}",
    TextKey.Measuring to "Measuring", TextKey.YourTeam to "YOUR TEAM", TextKey.OpponentTeam to "OPPONENT TEAM",
    TextKey.Versus to "VS", TextKey.NextNumber to "NEXT NUMBER",

    TextKey.BlockPlayerTitle to "BLOCK {player}?", TextKey.BlockPlayerDescription to "You will no longer be able to add each other, send invites or rematch.",
    TextKey.Block to "BLOCK", TextKey.RematchInviteTitle to "REMATCH INVITE", TextKey.RematchInviteDescription to "{player} wants a rematch.",
    TextKey.Processing to "PROCESSING…", TextKey.Accept to "ACCEPT", TextKey.Decline to "DECLINE", TextKey.DrawResult to "DRAW!",
    TextKey.VictoryResult to "VICTORY!", TextKey.DefeatResult to "DEFEAT", TextKey.ForfeitResultDescription to "You left the match and forfeited.",
    TextKey.DrawResultDescription to "Both sides finished with the same score.", TextKey.VictoryResultDescription to "You won the match!",
    TextKey.OpposingTeamVictoryDescription to "The opposing team won.", TextKey.OpponentVictoryDescription to "{player} won the match.",
    TextKey.MatchResultTitle to "Match result", TextKey.GameResultSubtitle to "{mode} • {matchType}", TextKey.ShareResult to "SHARE RESULT",
    TextKey.ShareResultError to "Could not create the share image. Please try again.", TextKey.ReturnToLobby to "Return to lobby",
    TextKey.PlayerYou to "{player} (You)", TextKey.Draw to "Draw", TextKey.Win to "Win", TextKey.Loss to "Loss", TextKey.ResultLabel to "RESULT",
    TextKey.PlacementProgress to "Placement {played}/{required}", TextKey.MatchReward to "Match reward", TextKey.FinalMatch to "Final",
    TextKey.SemifinalMatch to "Semifinal", TextKey.TournamentFinishedDescription to "Tournament complete. Open the bracket to see the champion.",
    TextKey.BracketUpdatedDescription to "Bracket updated. The next match will be created automatically.", TextKey.ViewBracket to "View bracket",
    TextKey.YourSummary to "Your summary", TextKey.AverageReaction to "Avg. reaction", TextKey.Accuracy to "Accuracy",
    TextKey.CorrectWrongDuration to "Correct {correct} • Wrong {wrong} • {duration}", TextKey.PaceAnalysis to "Pace analysis",
    TextKey.InsufficientPaceAnalysis to "Not enough data to identify fastest and slowest segments.",
    TextKey.PaceSegmentHint to "Each segment contains up to 10 numbers you found.", TextKey.Fastest to "Fastest", TextKey.Slowest to "Slowest",
    TextKey.TurnRange to "Turns {start}–{end}", TextKey.RankedNoRematch to "Ranked matches do not support rematches. Return to the lobby to find a new opponent.",
    TextKey.Rematch to "Rematch", TextKey.ResponseSeconds to "{seconds} seconds left to respond", TextKey.OpponentLeft to "OPPONENT LEFT",
    TextKey.WaitingForResponse to "WAITING FOR RESPONSE", TextKey.Invited to "INVITED", TextKey.SendingShort to "Sending…",
    TextKey.InviteRematch to "Invite to rematch", TextKey.LoginForSocial to "Log in to add or block players.", TextKey.AddFriend to "Add friend",
    TextKey.AcceptFriend to "Accept friend", TextKey.FriendRequestSent to "Friend request sent", TextKey.AlreadyFriends to "Already friends",
    TextKey.Blocked to "Blocked", TextKey.LoadingInfo to "Loading info", TextKey.ShareResultCaption to "Fast To Win result: {player} {playerScore} – {opponentScore} {opponent} • {mode}",
    TextKey.ShareTimeLabel to "TIME", TextKey.ShareAccuracyLabel to "ACCURACY", TextKey.ShareSlogan to "See fast • Tap fast • Win",
    TextKey.ShareResultSheetTitle to "Share result",

    TextKey.PracticeHeader to "Practice · {mode}", TextKey.OfflineNoElo to "Offline • No Elo impact",
    TextKey.CorrectBoardCompleted to "Correct, board completed", TextKey.CorrectNextTarget to "Correct, next target {target}",
    TextKey.WrongNeedTarget to "Wrong, find {target}", TextKey.Target to "Target", TextKey.Score to "Score", TextKey.Remaining to "Remaining",
    TextKey.Time to "Time", TextKey.Lives to "Lives", TextKey.ComboLabel to "Combo", TextKey.Pace to "Pace", TextKey.EndPractice to "FINISH",
    TextKey.FoundAllNumbers to "You found all 50 numbers", TextKey.SurvivalEnded to "You used all 3 wrong-tap chances",
    TextKey.SpeedUpEnded to "You ran out of time for the next target", TextKey.TimeBonusEnded to "Your accumulated time ran out",
    TextKey.TimeAttackEnded to "60 seconds are up", TextKey.ChallengeEnded to "Challenge complete", TextKey.Completed to "COMPLETED",
    TextKey.PracticeCompletionSummary to "{message}. {score} points · {mode}.", TextKey.ChallengeCode to "Challenge code",
    TextKey.ChallengeCodeHint to "Friends can enter this code to play the same number board.", TextKey.PracticeNoElo to "Practice results do not affect Elo.",
    TextKey.ShareChallenge to "SHARE CHALLENGE", TextKey.ReplaySameBoard to "REPLAY SAME BOARD", TextKey.CreateNewChallenge to "CREATE NEW CHALLENGE",
    TextKey.ReturnHome to "RETURN HOME", TextKey.Reaction to "Reaction", TextKey.CorrectWrong to "Correct / Wrong",
    TextKey.AveragePerNumber to "Average per number", TextKey.PracticeHeroTitle to "OFFLINE PRACTICE",
    TextKey.PracticeHeroDescription to "Train your reactions every day without affecting Elo.", TextKey.PracticeNoServerNeeded to "No Elo impact and no server connection needed.",
    TextKey.StartNewPractice to "Start new practice", TextKey.HaveChallengeCode to "Have a challenge code?", TextKey.PlayChallenge to "Play challenge",
    TextKey.InvalidChallengeCode to "The code is invalid or mistyped.", TextKey.ChallengeModeUnlock to "{mode} unlocks at level {level}.",
    TextKey.ChallengeShareText to "{practice} • {mode}\nI scored {score} points in {time}.\nOpen: {link}\nCode: {code}", TextKey.ShareChallengeSheetTitle to "Share challenge",
    TextKey.RoomShareText to "Join “{room}” on Fast To Win:\n{link}\nFor a private room, enter the password sent by the host.",
    TextKey.InvalidRoomIdCode to "invalid_room_id", TextKey.InvalidChallengeCodeCode to "invalid_challenge_code"
)

internal val vietnameseCorePlayTexts = mapOf(
    TextKey.GreetingPlayer to "Xin chào, {player}!", TextKey.ReadyForRecord to "Sẵn sàng phá kỷ lục mới?",
    TextKey.GameRooms to "Phòng chơi", TextKey.Ready to "Sẵn sàng", TextKey.Matchmaking to "Ghép đối thủ", TextKey.MatchFound to "Đã ghép trận",
    TextKey.FindingOpponent to "Đang tìm đối thủ…", TextKey.RankedMatchmakingHint to "Ưu tiên người chơi có Elo gần bạn.",
    TextKey.CasualMatchmakingHint to "Đang ghép người chơi cùng chế độ.", TextKey.EloRange to "Khoảng Elo", TextKey.NoEloImpact to "Không ảnh hưởng Elo",
    TextKey.CancelMatchmaking to "HỦY GHÉP TRẬN", TextKey.GuestNameTitle to "Bạn muốn được gọi là gì?",
    TextKey.GuestNameDescription to "Tên này chỉ dùng trong phiên chơi hiện tại.", TextKey.EnterNickname to "Nhập biệt danh",
    TextKey.SaveNameProgressDescription to "Tạo tài khoản để giữ tên, Elo và lịch sử trên Android/iOS.",
    TextKey.RoomLinkUnavailable to "Phòng trong liên kết không còn tồn tại hoặc đã đủ người.", TextKey.ChooseRoomType to "Chọn loại phòng",
    TextKey.DefaultRoomName to "Phòng của {player}", TextKey.PublicRooms to "PHÒNG CÔNG KHAI", TextKey.FindOpponent to "Tìm đối thủ phù hợp",
    TextKey.PublicRoomsDescription to "Tạo phòng riêng hoặc tham gia phòng đang chờ.", TextKey.SaveProgressEmail to "LƯU TIẾN TRÌNH BẰNG EMAIL",
    TextKey.SearchRooms to "Tìm tên phòng hoặc chủ phòng", TextKey.All to "Tất cả", TextKey.Waiting to "Đang chờ", TextKey.RoomCount to "{count} phòng",
    TextKey.Reconnecting to "Đang kết nối lại…", TextKey.AuthenticatingSession to "Đang xác thực phiên chơi…", TextKey.Connecting to "Đang kết nối…",
    TextKey.NoWaitingRooms to "Chưa có phòng đang chờ. Hãy tạo phòng mới hoặc kéo xuống để làm mới.",
    TextKey.NoMatchingRooms to "Không tìm thấy phòng phù hợp với bộ lọc.", TextKey.EnterRoomCode to "Nhập mã phòng",
    TextKey.PasteRoomCode to "Dán mã được chủ phòng chia sẻ.", TextKey.RoomCode to "Mã phòng", TextKey.FindRoom to "TÌM PHÒNG",
    TextKey.RoomCodeNotFound to "Không tìm thấy phòng với mã này.", TextKey.CreateNewRoom to "Tạo phòng mới", TextKey.YouAreHost to "Bạn sẽ là chủ phòng.",
    TextKey.RoomName to "Tên phòng", TextKey.Public to "Công khai", TextKey.Private to "Riêng tư",
    TextKey.PrivatePasswordRequired to "Người chơi cần nhập mật khẩu.", TextKey.PublicNoPassword to "Mọi người có thể tham gia, không cần mật khẩu.",
    TextKey.RoomPassword to "Mật khẩu phòng", TextKey.RankedEloImpact to "Đấu xếp hạng · Có ảnh hưởng Elo",
    TextKey.CasualNoEloImpact to "Đấu thường · Không ảnh hưởng Elo", TextKey.PrivateRoom to "Phòng riêng", TextKey.PublicRoom to "Phòng công khai",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "VÀO", TextKey.JoinPrivateRoom to "Phòng riêng",
    TextKey.JoinRoomTitle to "Tham gia phòng", TextKey.PrivateJoinDescription to "Nhập mật khẩu để tham gia “{room}”.",
    TextKey.PublicJoinDescription to "{room} • Chủ phòng {host}", TextKey.JoinedRoomCode to "MÃ PHÒNG • {code}", TextKey.JoinedRoom to "ĐÃ VÀO PHÒNG",
    TextKey.ShareCodeHint to "Chia sẻ mã để mời bạn bè.", TextKey.WaitHostStart to "Chờ chủ phòng bắt đầu trận.", TextKey.PlayersTitle to "Người chơi",
    TextKey.BlueTeam to "Đội Xanh", TextKey.RedTeam to "Đội Đỏ", TextKey.You to "Bạn", TextKey.TeammateNumber to "Đồng đội {number}",
    TextKey.Teammate to "Đồng đội", TextKey.OpponentNumber to "Đối thủ {number}", TextKey.Opponent to "Đối thủ", TextKey.WaitingPlayer to "Đang chờ…",
    TextKey.HostYou to "Chủ phòng • Bạn", TextKey.Guest to "Khách", TextKey.Host to "Chủ phòng", TextKey.WaitingForPlayer to "Đang chờ người chơi…",
    TextKey.ModeNumberCount to "{mode} • 50 số", TextKey.ShareRoomCode to "CHIA SẺ MÃ PHÒNG", TextKey.ShareSheetError to "Không thể mở bảng chia sẻ. Vui lòng thử lại.",
    TextKey.CancelReady to "HỦY SẴN SÀNG", TextKey.ReadyAction to "SẴN SÀNG", TextKey.WaitingForReady to "Đang chờ người khác sẵn sàng…",
    TextKey.InviteFriends to "MỜI BẠN BÈ", TextKey.Kick to "MỜI RA", TextKey.CloseRoom to "ĐÓNG PHÒNG", TextKey.LeaveRoom to "RỜI PHÒNG",
    TextKey.ReadyStatus to "SẴN SÀNG", TextKey.WaitingStatus to "ĐANG CHỜ", TextKey.LatencyGood to "{latency} ms • Tốt",
    TextKey.LatencyStable to "{latency} ms • Ổn định", TextKey.LatencySlow to "{latency} ms • Chậm", TextKey.OpponentReady to "ĐỐI THỦ ĐÃ SẴN SÀNG",
    TextKey.MatchStarting to "Trận đấu sắp bắt đầu", TextKey.LocalPlayerLabel to "BẠN", TextKey.OpponentLabel to "ĐỐI THỦ",

    TextKey.ReactionHappy to "Vui vẻ", TextKey.ReactionLaugh to "Cười lớn", TextKey.ReactionFire to "Bùng cháy", TextKey.ReactionVictory to "Chiến thắng",
    TextKey.ReactionLove to "Yêu thích", TextKey.ReactionSpeed to "Tăng tốc", TextKey.ExitMatchTitle to "Rời trận?",
    TextKey.ForfeitCasualDescription to "Chủ động rời trận sẽ bị xử thua.", TextKey.ForfeitRankedDescription to "Chủ động rời trận sẽ bị xử thua và mất Elo.",
    TextKey.ExitMatch to "RỜI TRẬN", TextKey.ContinuePlaying to "TIẾP TỤC CHƠI", TextKey.GameHeader to "{mode} · {matchType}",
    TextKey.GameDefaultRoom to "Ván đấu 50 số", TextKey.GameDisconnected to "Mất kết nối. Đang thử kết nối lại…",
    TextKey.GameReconnecting to "Đang kết nối lại trận đấu…", TextKey.TieScoreWarning to "Đang hòa điểm — lượt tiếp theo rất quan trọng!",
    TextKey.CloseScoreWarning to "Bám rất sát — chỉ cách nhau {difference} điểm", TextKey.LivesCount to "{count} mạng",
    TextKey.PaceProgress to "NHỊP {current}/{total}", TextKey.SpeedValue to "TỐC ĐỘ  {speed}", TextKey.SendReaction to "Gửi biểu cảm",
    TextKey.CorrectWrongSummary to "Đúng {correct}  ·  Sai {wrong}", TextKey.Measuring to "Đang đo", TextKey.YourTeam to "ĐỘI CỦA BẠN",
    TextKey.OpponentTeam to "ĐỘI ĐỐI THỦ", TextKey.Versus to "ĐẤU", TextKey.NextNumber to "SỐ TIẾP THEO",

    TextKey.BlockPlayerTitle to "CHẶN {player}?", TextKey.BlockPlayerDescription to "Hai người sẽ không thể kết bạn, gửi lời mời hoặc đấu lại.",
    TextKey.Block to "CHẶN", TextKey.RematchInviteTitle to "MỜI ĐẤU LẠI", TextKey.RematchInviteDescription to "{player} muốn đấu lại với bạn.",
    TextKey.Processing to "ĐANG XỬ LÝ…", TextKey.Accept to "CHẤP NHẬN", TextKey.Decline to "TỪ CHỐI", TextKey.DrawResult to "HÒA!",
    TextKey.VictoryResult to "CHIẾN THẮNG!", TextKey.DefeatResult to "THUA CUỘC", TextKey.ForfeitResultDescription to "Bạn đã chủ động rời trận và bị xử thua.",
    TextKey.DrawResultDescription to "Hai bên ngang điểm sau trận đấu.", TextKey.VictoryResultDescription to "Bạn đã giành chiến thắng!",
    TextKey.OpposingTeamVictoryDescription to "Đội đối thủ đã giành chiến thắng.", TextKey.OpponentVictoryDescription to "{player} đã giành chiến thắng.",
    TextKey.MatchResultTitle to "Kết quả trận", TextKey.GameResultSubtitle to "{mode} • {matchType}", TextKey.ShareResult to "CHIA SẺ KẾT QUẢ",
    TextKey.ShareResultError to "Không thể tạo ảnh chia sẻ. Vui lòng thử lại.", TextKey.ReturnToLobby to "Về sảnh",
    TextKey.PlayerYou to "{player} (Bạn)", TextKey.Draw to "Hòa", TextKey.Win to "Thắng", TextKey.Loss to "Thua", TextKey.ResultLabel to "KẾT QUẢ",
    TextKey.PlacementProgress to "Phân hạng {played}/{required}", TextKey.MatchReward to "Thưởng trận", TextKey.FinalMatch to "Trận chung kết",
    TextKey.SemifinalMatch to "Trận bán kết", TextKey.TournamentFinishedDescription to "Giải đấu đã hoàn tất. Mở nhánh đấu để xem nhà vô địch.",
    TextKey.BracketUpdatedDescription to "Nhánh đấu đã được cập nhật. Trận tiếp theo sẽ được tạo tự động.", TextKey.ViewBracket to "Xem nhánh đấu",
    TextKey.YourSummary to "Tóm tắt của bạn", TextKey.AverageReaction to "Phản xạ TB", TextKey.Accuracy to "Chính xác",
    TextKey.CorrectWrongDuration to "Đúng {correct} • Sai {wrong} • {duration}", TextKey.PaceAnalysis to "Phân tích nhịp chơi",
    TextKey.InsufficientPaceAnalysis to "Chưa đủ dữ liệu để phân tích chặng nhanh và chậm.", TextKey.PaceSegmentHint to "Mỗi chặng gồm tối đa 10 số bạn đã tìm.",
    TextKey.Fastest to "Nhanh nhất", TextKey.Slowest to "Chậm nhất", TextKey.TurnRange to "Lượt {start}–{end}",
    TextKey.RankedNoRematch to "Trận xếp hạng không hỗ trợ đấu lại. Hãy về sảnh để ghép một đối thủ mới.", TextKey.Rematch to "Đấu lại",
    TextKey.ResponseSeconds to "Còn {seconds} giây để phản hồi", TextKey.OpponentLeft to "ĐỐI THỦ ĐÃ RỜI", TextKey.WaitingForResponse to "ĐANG CHỜ PHẢN HỒI",
    TextKey.Invited to "ĐÃ MỜI", TextKey.SendingShort to "Đang gửi…", TextKey.InviteRematch to "Mời đấu lại",
    TextKey.LoginForSocial to "Đăng nhập để kết bạn hoặc chặn người chơi.", TextKey.AddFriend to "Kết bạn", TextKey.AcceptFriend to "Chấp nhận kết bạn",
    TextKey.FriendRequestSent to "Đã gửi lời mời", TextKey.AlreadyFriends to "Đã là bạn bè", TextKey.Blocked to "Đã chặn", TextKey.LoadingInfo to "Đang tải thông tin",
    TextKey.ShareResultCaption to "Kết quả Fast To Win: {player} {playerScore} – {opponentScore} {opponent} • {mode}", TextKey.ShareTimeLabel to "THỜI GIAN",
    TextKey.ShareAccuracyLabel to "CHÍNH XÁC", TextKey.ShareSlogan to "Nhanh mắt • Nhanh tay • Chiến thắng", TextKey.ShareResultSheetTitle to "Chia sẻ kết quả",

    TextKey.PracticeHeader to "Luyện tập · {mode}", TextKey.OfflineNoElo to "Ngoại tuyến • Không ảnh hưởng Elo",
    TextKey.CorrectBoardCompleted to "Đúng, đã hoàn thành bàn số", TextKey.CorrectNextTarget to "Đúng, mục tiêu tiếp theo {target}",
    TextKey.WrongNeedTarget to "Sai, cần tìm {target}", TextKey.Target to "Mục tiêu", TextKey.Score to "Điểm", TextKey.Remaining to "Còn lại",
    TextKey.Time to "Thời gian", TextKey.Lives to "Mạng", TextKey.ComboLabel to "Combo", TextKey.Pace to "Nhịp", TextKey.EndPractice to "KẾT THÚC",
    TextKey.FoundAllNumbers to "Bạn đã tìm đủ 50 số", TextKey.SurvivalEnded to "Bạn đã hết 3 lượt bấm sai",
    TextKey.SpeedUpEnded to "Bạn không kịp tìm mục tiêu tiếp theo", TextKey.TimeBonusEnded to "Bạn đã hết thời gian tích lũy",
    TextKey.TimeAttackEnded to "Hết 60 giây", TextKey.ChallengeEnded to "Thử thách đã kết thúc", TextKey.Completed to "HOÀN THÀNH",
    TextKey.PracticeCompletionSummary to "{message}. {score} điểm · {mode}.", TextKey.ChallengeCode to "Mã thử thách",
    TextKey.ChallengeCodeHint to "Bạn bè nhập mã này để chơi đúng cùng một bàn số.", TextKey.PracticeNoElo to "Kết quả luyện tập không ảnh hưởng Elo.",
    TextKey.ShareChallenge to "CHIA SẺ THỬ THÁCH", TextKey.ReplaySameBoard to "CHƠI LẠI CÙNG BÀN",
    TextKey.CreateNewChallenge to "TẠO THỬ THÁCH MỚI", TextKey.ReturnHome to "VỀ TRANG CHỦ", TextKey.Reaction to "Phản xạ",
    TextKey.CorrectWrong to "Đúng / Sai", TextKey.AveragePerNumber to "Trung bình mỗi số", TextKey.PracticeHeroTitle to "LUYỆN TẬP OFFLINE",
    TextKey.PracticeHeroDescription to "Rèn phản xạ mỗi ngày mà không ảnh hưởng Elo.", TextKey.PracticeNoServerNeeded to "Không ảnh hưởng Elo và không cần kết nối máy chủ.",
    TextKey.StartNewPractice to "Bắt đầu luyện tập mới", TextKey.HaveChallengeCode to "Có mã thử thách?", TextKey.PlayChallenge to "Chơi thử thách",
    TextKey.InvalidChallengeCode to "Mã không hợp lệ hoặc đã nhập sai.", TextKey.ChallengeModeUnlock to "Chế độ {mode} mở khóa ở cấp {level}.",
    TextKey.ChallengeShareText to "{practice} • {mode}\nMình đạt {score} điểm trong {time}.\nMở trực tiếp: {link}\nMã thử thách: {code}", TextKey.ShareChallengeSheetTitle to "Chia sẻ thử thách",
    TextKey.RoomShareText to "Tham gia phòng “{room}” trên Fast To Win:\n{link}\nNếu phòng riêng tư, hãy nhập mật khẩu do chủ phòng gửi riêng.",
    TextKey.InvalidRoomIdCode to "invalid_room_id", TextKey.InvalidChallengeCodeCode to "invalid_challenge_code"
)

internal val germanCorePlayTexts = mapOf(
    TextKey.GameRooms to "Spielräume", TextKey.PublicRooms to "ÖFFENTLICHE RÄUME", TextKey.FindOpponent to "Passenden Gegner finden",
    TextKey.PublicRoomsDescription to "Erstelle einen privaten Raum oder tritt einem offenen Raum bei.", TextKey.CreateRoom to "Raum erstellen",
    TextKey.JoinRoom to "Raum beitreten", TextKey.All to "Alle", TextKey.Waiting to "Wartend", TextKey.SearchRooms to "Raum oder Host suchen"
)

internal val japaneseCorePlayTexts = mapOf(
    TextKey.Ranked to "ランク戦", TextKey.Casual to "通常戦", TextKey.GameHeader to "{mode} · {matchType}",
    TextKey.NextNumber to "次の数字", TextKey.ExitMatchTitle to "対戦を終了しますか？", TextKey.ExitMatch to "対戦を終了",
    TextKey.ContinuePlaying to "プレイを続ける", TextKey.GameDefaultRoom to "50数字対戦", TextKey.SendReaction to "リアクションを送る",
    TextKey.CorrectWrongSummary to "正解 {correct}  ·  ミス {wrong}", TextKey.Measuring to "計測中", TextKey.YourTeam to "あなたのチーム",
    TextKey.OpponentTeam to "相手チーム", TextKey.OpponentLabel to "対戦相手", TextKey.LocalPlayerLabel to "あなた"
)

internal val russianCorePlayTexts = mapOf(
    TextKey.Ranked to "Рейтинг", TextKey.Casual to "Обычная", TextKey.DrawResult to "НИЧЬЯ!", TextKey.VictoryResult to "ПОБЕДА!",
    TextKey.DefeatResult to "ПОРАЖЕНИЕ", TextKey.MatchResultTitle to "Результат матча", TextKey.ShareResult to "ПОДЕЛИТЬСЯ РЕЗУЛЬТАТОМ",
    TextKey.ReturnToLobby to "Вернуться в лобби", TextKey.Draw to "Ничья", TextKey.Win to "Победа", TextKey.Loss to "Поражение",
    TextKey.YourSummary to "Ваш результат", TextKey.AverageReaction to "Средняя реакция", TextKey.Accuracy to "Точность",
    TextKey.PaceAnalysis to "Анализ темпа", TextKey.Fastest to "Самый быстрый", TextKey.Slowest to "Самый медленный",
    TextKey.Rematch to "Реванш", TextKey.InviteRematch to "Предложить реванш", TextKey.MatchReward to "Награда за матч"
)

internal val thaiCorePlayTexts = mapOf(
    TextKey.PracticeHeader to "ฝึกซ้อม · {mode}", TextKey.OfflineNoElo to "ออฟไลน์ • ไม่กระทบ Elo", TextKey.Target to "เป้าหมาย",
    TextKey.Score to "คะแนน", TextKey.Remaining to "เหลือ", TextKey.Time to "เวลา", TextKey.Lives to "ชีวิต", TextKey.ComboLabel to "คอมโบ",
    TextKey.Pace to "จังหวะ", TextKey.EndPractice to "จบ", TextKey.CorrectBoardCompleted to "ถูกต้อง จบกระดานแล้ว",
    TextKey.CorrectNextTarget to "ถูกต้อง เป้าหมายถัดไป {target}", TextKey.WrongNeedTarget to "ผิด ต้องหา {target}",
    TextKey.Completed to "เสร็จสิ้น", TextKey.ChallengeCode to "รหัสชาเลนจ์", TextKey.PracticeNoElo to "ผลการฝึกไม่กระทบ Elo",
    TextKey.ShareChallenge to "แชร์ชาเลนจ์", TextKey.ReplaySameBoard to "เล่นกระดานเดิมอีกครั้ง", TextKey.CreateNewChallenge to "สร้างชาเลนจ์ใหม่",
    TextKey.ReturnHome to "กลับหน้าหลัก", TextKey.Reaction to "การตอบสนอง", TextKey.CorrectWrong to "ถูก / ผิด",
    TextKey.AveragePerNumber to "เฉลี่ยต่อตัวเลข", TextKey.PracticeHeroTitle to "ฝึกออฟไลน์",
    TextKey.PracticeHeroDescription to "ฝึกการตอบสนองทุกวันโดยไม่กระทบ Elo", TextKey.PracticeNoServerNeeded to "ไม่กระทบ Elo และไม่ต้องเชื่อมต่อเซิร์ฟเวอร์",
    TextKey.StartNewPractice to "เริ่มฝึกใหม่", TextKey.HaveChallengeCode to "มีรหัสชาเลนจ์ไหม?", TextKey.PlayChallenge to "เล่นชาเลนจ์",
    TextKey.InvalidChallengeCode to "รหัสไม่ถูกต้องหรือพิมพ์ผิด"
)

internal val simplifiedChineseCorePlayTexts = emptyMap<TextKey, String>()
internal val koreanCorePlayTexts = emptyMap<TextKey, String>()
internal val spanishCorePlayTexts = emptyMap<TextKey, String>()
internal val brazilianPortugueseCorePlayTexts = emptyMap<TextKey, String>()
internal val frenchCorePlayTexts = emptyMap<TextKey, String>()
internal val indonesianCorePlayTexts = emptyMap<TextKey, String>()
