package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey

internal val englishCorePlayTexts = mapOf(
    TextKey.GreetingPlayer to "Hello, {player}!", TextKey.ReadyForRecord to "Ready to set a new record?",
    TextKey.GameRooms to "Game rooms", TextKey.Ready to "Ready", TextKey.Matchmaking to "Matchmaking",
    TextKey.MatchFound to "Match found", TextKey.FindingOpponent to "Finding an opponent…",
    TextKey.RankedMatchmakingHint to "Prioritising players near your Elo.",
    TextKey.CasualMatchmakingHint to "Finding players in the same mode.", TextKey.EloRange to "Elo range",
    TextKey.NoEloImpact to "No Elo impact", TextKey.CancelMatchmaking to "CANCEL MATCHMAKING",
    TextKey.GuestNameTitle to "What should we call you?", TextKey.GuestNameDescription to "This name is only used for this play session.",
    TextKey.EnterNickname to "Enter nickname", TextKey.SaveNameProgressDescription to "Create an account to keep your name, Elo and history on Android/iOS.",
    TextKey.RoomLinkUnavailable to "The linked room no longer exists or is full.", TextKey.ChooseRoomType to "Choose room type",
    TextKey.DefaultRoomName to "{player}'s room", TextKey.PublicRooms to "PUBLIC ROOMS", TextKey.FindOpponent to "Find the right opponent",
    TextKey.PublicRoomsDescription to "Create a private room or join a waiting room.", TextKey.SaveProgressEmail to "SAVE PROGRESS WITH EMAIL",
    TextKey.SearchRooms to "Search room or host name", TextKey.All to "All", TextKey.Waiting to "Waiting",
    TextKey.RoomCount to "{count} rooms", TextKey.Reconnecting to "Reconnecting…", TextKey.AuthenticatingSession to "Authenticating session…",
    TextKey.Connecting to "Connecting…", TextKey.NoWaitingRooms to "No rooms are waiting. Create one or pull down to refresh.",
    TextKey.NoMatchingRooms to "No rooms match these filters.", TextKey.EnterRoomCode to "Enter room code",
    TextKey.PasteRoomCode to "Paste the code shared by the host.", TextKey.RoomCode to "Room code", TextKey.FindRoom to "FIND ROOM",
    TextKey.RoomCodeNotFound to "No room was found with this code.", TextKey.CreateNewRoom to "Create new room",
    TextKey.YouAreHost to "You will be the host.", TextKey.RoomName to "Room name", TextKey.Public to "Public", TextKey.Private to "Private",
    TextKey.PrivatePasswordRequired to "Players need a password.", TextKey.PublicNoPassword to "Anyone can join without a password.",
    TextKey.RoomPassword to "Room password", TextKey.RankedEloImpact to "Ranked · Affects Elo",
    TextKey.CasualNoEloImpact to "Casual · No Elo impact", TextKey.PrivateRoom to "Private room", TextKey.PublicRoom to "Public room",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ENTER",
    TextKey.JoinPrivateRoom to "Private room", TextKey.JoinRoomTitle to "Join room",
    TextKey.PrivateJoinDescription to "Enter the password to join “{room}”.", TextKey.PublicJoinDescription to "{room} • Hosted by {host}",
    TextKey.JoinedRoomCode to "ROOM CODE • {code}", TextKey.JoinedRoom to "IN ROOM", TextKey.ShareCodeHint to "Share the code to invite friends.",
    TextKey.WaitHostStart to "Wait for the host to start the match.", TextKey.PlayersTitle to "Players", TextKey.BlueTeam to "Blue Team",
    TextKey.RedTeam to "Red Team", TextKey.You to "You", TextKey.TeammateNumber to "Teammate {number}", TextKey.Teammate to "Teammate",
    TextKey.OpponentNumber to "Opponent {number}", TextKey.Opponent to "Opponent", TextKey.WaitingPlayer to "Waiting…",
    TextKey.HostYou to "Host • You", TextKey.Guest to "Guest", TextKey.Host to "Host", TextKey.WaitingForPlayer to "Waiting for player…",
    TextKey.ModeNumberCount to "{mode} • 50 numbers", TextKey.ShareRoomCode to "SHARE ROOM CODE", TextKey.ShareSheetError to "Could not open sharing. Please try again.",
    TextKey.CancelReady to "CANCEL READY", TextKey.ReadyAction to "READY", TextKey.WaitingForReady to "Waiting for everyone to be ready…",
    TextKey.InviteFriends to "INVITE FRIENDS", TextKey.Kick to "KICK", TextKey.CloseRoom to "CLOSE ROOM", TextKey.LeaveRoom to "LEAVE ROOM",
    TextKey.ReadyStatus to "READY", TextKey.WaitingStatus to "WAITING", TextKey.LatencyGood to "{latency} ms • Good",
    TextKey.LatencyStable to "{latency} ms • Stable", TextKey.LatencySlow to "{latency} ms • Slow",
    TextKey.OpponentReady to "OPPONENT READY", TextKey.MatchStarting to "The match is about to start",
    TextKey.LocalPlayerLabel to "YOU", TextKey.OpponentLabel to "OPPONENT",

    TextKey.ReactionHappy to "Happy", TextKey.ReactionLaugh to "Laugh", TextKey.ReactionFire to "On fire",
    TextKey.ReactionVictory to "Victory", TextKey.ReactionLove to "Love", TextKey.ReactionSpeed to "Speed up",
    TextKey.ExitMatchTitle to "Leave match?", TextKey.ForfeitCasualDescription to "Leaving now counts as a loss.",
    TextKey.ForfeitRankedDescription to "Leaving now counts as a loss and costs Elo.", TextKey.ExitMatch to "LEAVE MATCH",
    TextKey.ContinuePlaying to "KEEP PLAYING", TextKey.GameHeader to "{mode} · {matchType}", TextKey.GameDefaultRoom to "50-number match",
    TextKey.GameDisconnected to "Connection lost. Reconnecting…", TextKey.GameReconnecting to "Reconnecting to the match…",
    TextKey.TieScoreWarning to "Scores are tied — the next turn matters!", TextKey.CloseScoreWarning to "Neck and neck — only {difference} points apart",
    TextKey.LivesCount to "{count} lives", TextKey.PaceProgress to "PACE {current}/{total}", TextKey.SpeedValue to "SPEED  {speed}",
    TextKey.SendReaction to "Send reaction", TextKey.CorrectWrongSummary to "Correct {correct}  ·  Wrong {wrong}",
    TextKey.Measuring to "Measuring", TextKey.YourTeam to "YOUR TEAM", TextKey.OpponentTeam to "OPPONENT TEAM",
    TextKey.Versus to "VS", TextKey.NextNumber to "NEXT NUMBER",

    TextKey.BlockPlayerTitle to "BLOCK {player}?", TextKey.BlockPlayerDescription to "You will no longer be able to add each other, send invites or rematch.",
    TextKey.Block to "BLOCK", TextKey.RematchInviteTitle to "REMATCH INVITE", TextKey.RematchInviteDescription to "{player} wants a rematch.",
    TextKey.Processing to "PROCESSING…", TextKey.Accept to "ACCEPT", TextKey.Decline to "DECLINE", TextKey.DrawResult to "DRAW!",
    TextKey.VictoryResult to "VICTORY!", TextKey.DefeatResult to "DEFEAT", TextKey.ForfeitResultDescription to "You left the match and forfeited.",
    TextKey.DrawResultDescription to "Both sides finished with the same score.", TextKey.VictoryResultDescription to "You won the match!",
    TextKey.OpposingTeamVictoryDescription to "The opposing team won.", TextKey.OpponentVictoryDescription to "{player} won the match.",
    TextKey.MatchResultTitle to "Match result", TextKey.GameResultSubtitle to "{mode} • {matchType}", TextKey.ShareResult to "SHARE RESULT",
    TextKey.ShareResultError to "Could not create the share image. Please try again.", TextKey.ReturnToLobby to "Return to lobby",
    TextKey.PlayerYou to "{player} (You)", TextKey.Draw to "Draw", TextKey.Win to "Win", TextKey.Loss to "Loss", TextKey.ResultLabel to "RESULT",
    TextKey.PlacementProgress to "Placement {played}/{required}", TextKey.MatchReward to "Match reward", TextKey.FinalMatch to "Final",
    TextKey.SemifinalMatch to "Semifinal", TextKey.TournamentFinishedDescription to "Tournament complete. Open the bracket to see the champion.",
    TextKey.BracketUpdatedDescription to "Bracket updated. The next match will be created automatically.", TextKey.ViewBracket to "View bracket",
    TextKey.YourSummary to "Your summary", TextKey.AverageReaction to "Avg. reaction", TextKey.Accuracy to "Accuracy",
    TextKey.CorrectWrongDuration to "Correct {correct} • Wrong {wrong} • {duration}", TextKey.PaceAnalysis to "Pace analysis",
    TextKey.InsufficientPaceAnalysis to "Not enough data to identify fastest and slowest segments.",
    TextKey.PaceSegmentHint to "Each segment contains up to 10 numbers you found.", TextKey.Fastest to "Fastest", TextKey.Slowest to "Slowest",
    TextKey.TurnRange to "Turns {start}–{end}", TextKey.RankedNoRematch to "Ranked matches do not support rematches. Return to the lobby to find a new opponent.",
    TextKey.Rematch to "Rematch", TextKey.ResponseSeconds to "{seconds} seconds left to respond", TextKey.OpponentLeft to "OPPONENT LEFT",
    TextKey.WaitingForResponse to "WAITING FOR RESPONSE", TextKey.Invited to "INVITED", TextKey.SendingShort to "Sending…",
    TextKey.InviteRematch to "Invite to rematch", TextKey.LoginForSocial to "Log in to add or block players.", TextKey.AddFriend to "Add friend",
    TextKey.AcceptFriend to "Accept friend", TextKey.FriendRequestSent to "Friend request sent", TextKey.AlreadyFriends to "Already friends",
    TextKey.Blocked to "Blocked", TextKey.LoadingInfo to "Loading info", TextKey.ShareResultCaption to "Fast To Win result: {player} {playerScore} – {opponentScore} {opponent} • {mode}",
    TextKey.ShareTimeLabel to "TIME", TextKey.ShareAccuracyLabel to "ACCURACY", TextKey.ShareSlogan to "See fast • Tap fast • Win",
    TextKey.ShareResultSheetTitle to "Share result",

    TextKey.PracticeHeader to "Practice · {mode}", TextKey.OfflineNoElo to "Offline • No Elo impact",
    TextKey.CorrectBoardCompleted to "Correct, board completed", TextKey.CorrectNextTarget to "Correct, next target {target}",
    TextKey.WrongNeedTarget to "Wrong, find {target}", TextKey.Target to "Target", TextKey.Score to "Score", TextKey.Remaining to "Remaining",
    TextKey.Time to "Time", TextKey.Lives to "Lives", TextKey.ComboLabel to "Combo", TextKey.Pace to "Pace", TextKey.EndPractice to "FINISH",
    TextKey.FoundAllNumbers to "You found all 50 numbers", TextKey.SurvivalEnded to "You used all 3 wrong-tap chances",
    TextKey.SpeedUpEnded to "You ran out of time for the next target", TextKey.TimeBonusEnded to "Your accumulated time ran out",
    TextKey.TimeAttackEnded to "60 seconds are up", TextKey.ChallengeEnded to "Challenge complete", TextKey.Completed to "COMPLETED",
    TextKey.PracticeCompletionSummary to "{message}. {score} points · {mode}.", TextKey.ChallengeCode to "Challenge code",
    TextKey.ChallengeCodeHint to "Friends can enter this code to play the same number board.", TextKey.PracticeNoElo to "Practice results do not affect Elo.",
    TextKey.ShareChallenge to "SHARE CHALLENGE", TextKey.ReplaySameBoard to "REPLAY SAME BOARD", TextKey.CreateNewChallenge to "CREATE NEW CHALLENGE",
    TextKey.ReturnHome to "RETURN HOME", TextKey.Reaction to "Reaction", TextKey.CorrectWrong to "Correct / Wrong",
    TextKey.AveragePerNumber to "Average per number", TextKey.PracticeHeroTitle to "OFFLINE PRACTICE",
    TextKey.PracticeHeroDescription to "Train your reactions every day without affecting Elo.", TextKey.PracticeNoServerNeeded to "No Elo impact and no server connection needed.",
    TextKey.StartNewPractice to "Start new practice", TextKey.HaveChallengeCode to "Have a challenge code?", TextKey.PlayChallenge to "Play challenge",
    TextKey.InvalidChallengeCode to "The code is invalid or mistyped.", TextKey.ChallengeModeUnlock to "{mode} unlocks at level {level}.",
    TextKey.ChallengeShareText to "{practice} • {mode}\nI scored {score} points in {time}.\nOpen: {link}\nCode: {code}", TextKey.ShareChallengeSheetTitle to "Share challenge",
    TextKey.RoomShareText to "Join “{room}” on Fast To Win:\n{link}\nFor a private room, enter the password sent by the host.",
    TextKey.InvalidRoomIdCode to "invalid_room_id", TextKey.InvalidChallengeCodeCode to "invalid_challenge_code"
)

internal val vietnameseCorePlayTexts = mapOf(
    TextKey.GreetingPlayer to "Xin chào, {player}!", TextKey.ReadyForRecord to "Sẵn sàng phá kỷ lục mới?",
    TextKey.GameRooms to "Phòng chơi", TextKey.Ready to "Sẵn sàng", TextKey.Matchmaking to "Ghép đối thủ", TextKey.MatchFound to "Đã ghép trận",
    TextKey.FindingOpponent to "Đang tìm đối thủ…", TextKey.RankedMatchmakingHint to "Ưu tiên người chơi có Elo gần bạn.",
    TextKey.CasualMatchmakingHint to "Đang ghép người chơi cùng chế độ.", TextKey.EloRange to "Khoảng Elo", TextKey.NoEloImpact to "Không ảnh hưởng Elo",
    TextKey.CancelMatchmaking to "HỦY GHÉP TRẬN", TextKey.GuestNameTitle to "Bạn muốn được gọi là gì?",
    TextKey.GuestNameDescription to "Tên này chỉ dùng trong phiên chơi hiện tại.", TextKey.EnterNickname to "Nhập biệt danh",
    TextKey.SaveNameProgressDescription to "Tạo tài khoản để giữ tên, Elo và lịch sử trên Android/iOS.",
    TextKey.RoomLinkUnavailable to "Phòng trong liên kết không còn tồn tại hoặc đã đủ người.", TextKey.ChooseRoomType to "Chọn loại phòng",
    TextKey.DefaultRoomName to "Phòng của {player}", TextKey.PublicRooms to "PHÒNG CÔNG KHAI", TextKey.FindOpponent to "Tìm đối thủ phù hợp",
    TextKey.PublicRoomsDescription to "Tạo phòng riêng hoặc tham gia phòng đang chờ.", TextKey.SaveProgressEmail to "LƯU TIẾN TRÌNH BẰNG EMAIL",
    TextKey.SearchRooms to "Tìm tên phòng hoặc chủ phòng", TextKey.All to "Tất cả", TextKey.Waiting to "Đang chờ", TextKey.RoomCount to "{count} phòng",
    TextKey.Reconnecting to "Đang kết nối lại…", TextKey.AuthenticatingSession to "Đang xác thực phiên chơi…", TextKey.Connecting to "Đang kết nối…",
    TextKey.NoWaitingRooms to "Chưa có phòng đang chờ. Hãy tạo phòng mới hoặc kéo xuống để làm mới.",
    TextKey.NoMatchingRooms to "Không tìm thấy phòng phù hợp với bộ lọc.", TextKey.EnterRoomCode to "Nhập mã phòng",
    TextKey.PasteRoomCode to "Dán mã được chủ phòng chia sẻ.", TextKey.RoomCode to "Mã phòng", TextKey.FindRoom to "TÌM PHÒNG",
    TextKey.RoomCodeNotFound to "Không tìm thấy phòng với mã này.", TextKey.CreateNewRoom to "Tạo phòng mới", TextKey.YouAreHost to "Bạn sẽ là chủ phòng.",
    TextKey.RoomName to "Tên phòng", TextKey.Public to "Công khai", TextKey.Private to "Riêng tư",
    TextKey.PrivatePasswordRequired to "Người chơi cần nhập mật khẩu.", TextKey.PublicNoPassword to "Mọi người có thể tham gia, không cần mật khẩu.",
    TextKey.RoomPassword to "Mật khẩu phòng", TextKey.RankedEloImpact to "Đấu xếp hạng · Có ảnh hưởng Elo",
    TextKey.CasualNoEloImpact to "Đấu thường · Không ảnh hưởng Elo", TextKey.PrivateRoom to "Phòng riêng", TextKey.PublicRoom to "Phòng công khai",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "VÀO", TextKey.JoinPrivateRoom to "Phòng riêng",
    TextKey.JoinRoomTitle to "Tham gia phòng", TextKey.PrivateJoinDescription to "Nhập mật khẩu để tham gia “{room}”.",
    TextKey.PublicJoinDescription to "{room} • Chủ phòng {host}", TextKey.JoinedRoomCode to "MÃ PHÒNG • {code}", TextKey.JoinedRoom to "ĐÃ VÀO PHÒNG",
    TextKey.ShareCodeHint to "Chia sẻ mã để mời bạn bè.", TextKey.WaitHostStart to "Chờ chủ phòng bắt đầu trận.", TextKey.PlayersTitle to "Người chơi",
    TextKey.BlueTeam to "Đội Xanh", TextKey.RedTeam to "Đội Đỏ", TextKey.You to "Bạn", TextKey.TeammateNumber to "Đồng đội {number}",
    TextKey.Teammate to "Đồng đội", TextKey.OpponentNumber to "Đối thủ {number}", TextKey.Opponent to "Đối thủ", TextKey.WaitingPlayer to "Đang chờ…",
    TextKey.HostYou to "Chủ phòng • Bạn", TextKey.Guest to "Khách", TextKey.Host to "Chủ phòng", TextKey.WaitingForPlayer to "Đang chờ người chơi…",
    TextKey.ModeNumberCount to "{mode} • 50 số", TextKey.ShareRoomCode to "CHIA SẺ MÃ PHÒNG", TextKey.ShareSheetError to "Không thể mở bảng chia sẻ. Vui lòng thử lại.",
    TextKey.CancelReady to "HỦY SẴN SÀNG", TextKey.ReadyAction to "SẴN SÀNG", TextKey.WaitingForReady to "Đang chờ người khác sẵn sàng…",
    TextKey.InviteFriends to "MỜI BẠN BÈ", TextKey.Kick to "MỜI RA", TextKey.CloseRoom to "ĐÓNG PHÒNG", TextKey.LeaveRoom to "RỜI PHÒNG",
    TextKey.ReadyStatus to "SẴN SÀNG", TextKey.WaitingStatus to "ĐANG CHỜ", TextKey.LatencyGood to "{latency} ms • Tốt",
    TextKey.LatencyStable to "{latency} ms • Ổn định", TextKey.LatencySlow to "{latency} ms • Chậm", TextKey.OpponentReady to "ĐỐI THỦ ĐÃ SẴN SÀNG",
    TextKey.MatchStarting to "Trận đấu sắp bắt đầu", TextKey.LocalPlayerLabel to "BẠN", TextKey.OpponentLabel to "ĐỐI THỦ",

    TextKey.ReactionHappy to "Vui vẻ", TextKey.ReactionLaugh to "Cười lớn", TextKey.ReactionFire to "Bùng cháy", TextKey.ReactionVictory to "Chiến thắng",
    TextKey.ReactionLove to "Yêu thích", TextKey.ReactionSpeed to "Tăng tốc", TextKey.ExitMatchTitle to "Rời trận?",
    TextKey.ForfeitCasualDescription to "Chủ động rời trận sẽ bị xử thua.", TextKey.ForfeitRankedDescription to "Chủ động rời trận sẽ bị xử thua và mất Elo.",
    TextKey.ExitMatch to "RỜI TRẬN", TextKey.ContinuePlaying to "TIẾP TỤC CHƠI", TextKey.GameHeader to "{mode} · {matchType}",
    TextKey.GameDefaultRoom to "Ván đấu 50 số", TextKey.GameDisconnected to "Mất kết nối. Đang thử kết nối lại…",
    TextKey.GameReconnecting to "Đang kết nối lại trận đấu…", TextKey.TieScoreWarning to "Đang hòa điểm — lượt tiếp theo rất quan trọng!",
    TextKey.CloseScoreWarning to "Bám rất sát — chỉ cách nhau {difference} điểm", TextKey.LivesCount to "{count} mạng",
    TextKey.PaceProgress to "NHỊP {current}/{total}", TextKey.SpeedValue to "TỐC ĐỘ  {speed}", TextKey.SendReaction to "Gửi biểu cảm",
    TextKey.CorrectWrongSummary to "Đúng {correct}  ·  Sai {wrong}", TextKey.Measuring to "Đang đo", TextKey.YourTeam to "ĐỘI CỦA BẠN",
    TextKey.OpponentTeam to "ĐỘI ĐỐI THỦ", TextKey.Versus to "ĐẤU", TextKey.NextNumber to "SỐ TIẾP THEO",

    TextKey.BlockPlayerTitle to "CHẶN {player}?", TextKey.BlockPlayerDescription to "Hai người sẽ không thể kết bạn, gửi lời mời hoặc đấu lại.",
    TextKey.Block to "CHẶN", TextKey.RematchInviteTitle to "MỜI ĐẤU LẠI", TextKey.RematchInviteDescription to "{player} muốn đấu lại với bạn.",
    TextKey.Processing to "ĐANG XỬ LÝ…", TextKey.Accept to "CHẤP NHẬN", TextKey.Decline to "TỪ CHỐI", TextKey.DrawResult to "HÒA!",
    TextKey.VictoryResult to "CHIẾN THẮNG!", TextKey.DefeatResult to "THUA CUỘC", TextKey.ForfeitResultDescription to "Bạn đã chủ động rời trận và bị xử thua.",
    TextKey.DrawResultDescription to "Hai bên ngang điểm sau trận đấu.", TextKey.VictoryResultDescription to "Bạn đã giành chiến thắng!",
    TextKey.OpposingTeamVictoryDescription to "Đội đối thủ đã giành chiến thắng.", TextKey.OpponentVictoryDescription to "{player} đã giành chiến thắng.",
    TextKey.MatchResultTitle to "Kết quả trận", TextKey.GameResultSubtitle to "{mode} • {matchType}", TextKey.ShareResult to "CHIA SẺ KẾT QUẢ",
    TextKey.ShareResultError to "Không thể tạo ảnh chia sẻ. Vui lòng thử lại.", TextKey.ReturnToLobby to "Về sảnh",
    TextKey.PlayerYou to "{player} (Bạn)", TextKey.Draw to "Hòa", TextKey.Win to "Thắng", TextKey.Loss to "Thua", TextKey.ResultLabel to "KẾT QUẢ",
    TextKey.PlacementProgress to "Phân hạng {played}/{required}", TextKey.MatchReward to "Thưởng trận", TextKey.FinalMatch to "Trận chung kết",
    TextKey.SemifinalMatch to "Trận bán kết", TextKey.TournamentFinishedDescription to "Giải đấu đã hoàn tất. Mở nhánh đấu để xem nhà vô địch.",
    TextKey.BracketUpdatedDescription to "Nhánh đấu đã được cập nhật. Trận tiếp theo sẽ được tạo tự động.", TextKey.ViewBracket to "Xem nhánh đấu",
    TextKey.YourSummary to "Tóm tắt của bạn", TextKey.AverageReaction to "Phản xạ TB", TextKey.Accuracy to "Chính xác",
    TextKey.CorrectWrongDuration to "Đúng {correct} • Sai {wrong} • {duration}", TextKey.PaceAnalysis to "Phân tích nhịp chơi",
    TextKey.InsufficientPaceAnalysis to "Chưa đủ dữ liệu để phân tích chặng nhanh và chậm.", TextKey.PaceSegmentHint to "Mỗi chặng gồm tối đa 10 số bạn đã tìm.",
    TextKey.Fastest to "Nhanh nhất", TextKey.Slowest to "Chậm nhất", TextKey.TurnRange to "Lượt {start}–{end}",
    TextKey.RankedNoRematch to "Trận xếp hạng không hỗ trợ đấu lại. Hãy về sảnh để ghép một đối thủ mới.", TextKey.Rematch to "Đấu lại",
    TextKey.ResponseSeconds to "Còn {seconds} giây để phản hồi", TextKey.OpponentLeft to "ĐỐI THỦ ĐÃ RỜI", TextKey.WaitingForResponse to "ĐANG CHỜ PHẢN HỒI",
    TextKey.Invited to "ĐÃ MỜI", TextKey.SendingShort to "Đang gửi…", TextKey.InviteRematch to "Mời đấu lại",
    TextKey.LoginForSocial to "Đăng nhập để kết bạn hoặc chặn người chơi.", TextKey.AddFriend to "Kết bạn", TextKey.AcceptFriend to "Chấp nhận kết bạn",
    TextKey.FriendRequestSent to "Đã gửi lời mời", TextKey.AlreadyFriends to "Đã là bạn bè", TextKey.Blocked to "Đã chặn", TextKey.LoadingInfo to "Đang tải thông tin",
    TextKey.ShareResultCaption to "Kết quả Fast To Win: {player} {playerScore} – {opponentScore} {opponent} • {mode}", TextKey.ShareTimeLabel to "THỜI GIAN",
    TextKey.ShareAccuracyLabel to "CHÍNH XÁC", TextKey.ShareSlogan to "Nhanh mắt • Nhanh tay • Chiến thắng", TextKey.ShareResultSheetTitle to "Chia sẻ kết quả",

    TextKey.PracticeHeader to "Luyện tập · {mode}", TextKey.OfflineNoElo to "Ngoại tuyến • Không ảnh hưởng Elo",
    TextKey.CorrectBoardCompleted to "Đúng, đã hoàn thành bàn số", TextKey.CorrectNextTarget to "Đúng, mục tiêu tiếp theo {target}",
    TextKey.WrongNeedTarget to "Sai, cần tìm {target}", TextKey.Target to "Mục tiêu", TextKey.Score to "Điểm", TextKey.Remaining to "Còn lại",
    TextKey.Time to "Thời gian", TextKey.Lives to "Mạng", TextKey.ComboLabel to "Combo", TextKey.Pace to "Nhịp", TextKey.EndPractice to "KẾT THÚC",
    TextKey.FoundAllNumbers to "Bạn đã tìm đủ 50 số", TextKey.SurvivalEnded to "Bạn đã hết 3 lượt bấm sai",
    TextKey.SpeedUpEnded to "Bạn không kịp tìm mục tiêu tiếp theo", TextKey.TimeBonusEnded to "Bạn đã hết thời gian tích lũy",
    TextKey.TimeAttackEnded to "Hết 60 giây", TextKey.ChallengeEnded to "Thử thách đã kết thúc", TextKey.Completed to "HOÀN THÀNH",
    TextKey.PracticeCompletionSummary to "{message}. {score} điểm · {mode}.", TextKey.ChallengeCode to "Mã thử thách",
    TextKey.ChallengeCodeHint to "Bạn bè nhập mã này để chơi đúng cùng một bàn số.", TextKey.PracticeNoElo to "Kết quả luyện tập không ảnh hưởng Elo.",
    TextKey.ShareChallenge to "CHIA SẺ THỬ THÁCH", TextKey.ReplaySameBoard to "CHƠI LẠI CÙNG BÀN",
    TextKey.CreateNewChallenge to "TẠO THỬ THÁCH MỚI", TextKey.ReturnHome to "VỀ TRANG CHỦ", TextKey.Reaction to "Phản xạ",
    TextKey.CorrectWrong to "Đúng / Sai", TextKey.AveragePerNumber to "Trung bình mỗi số", TextKey.PracticeHeroTitle to "LUYỆN TẬP OFFLINE",
    TextKey.PracticeHeroDescription to "Rèn phản xạ mỗi ngày mà không ảnh hưởng Elo.", TextKey.PracticeNoServerNeeded to "Không ảnh hưởng Elo và không cần kết nối máy chủ.",
    TextKey.StartNewPractice to "Bắt đầu luyện tập mới", TextKey.HaveChallengeCode to "Có mã thử thách?", TextKey.PlayChallenge to "Chơi thử thách",
    TextKey.InvalidChallengeCode to "Mã không hợp lệ hoặc đã nhập sai.", TextKey.ChallengeModeUnlock to "Chế độ {mode} mở khóa ở cấp {level}.",
    TextKey.ChallengeShareText to "{practice} • {mode}\nMình đạt {score} điểm trong {time}.\nMở trực tiếp: {link}\nMã thử thách: {code}", TextKey.ShareChallengeSheetTitle to "Chia sẻ thử thách",
    TextKey.RoomShareText to "Tham gia phòng “{room}” trên Fast To Win:\n{link}\nNếu phòng riêng tư, hãy nhập mật khẩu do chủ phòng gửi riêng.",
    TextKey.InvalidRoomIdCode to "invalid_room_id", TextKey.InvalidChallengeCodeCode to "invalid_challenge_code"
)

internal val germanCorePlayTexts = mapOf(
    TextKey.GameRooms to "Spielräume", TextKey.PublicRooms to "ÖFFENTLICHE RÄUME", TextKey.FindOpponent to "Passenden Gegner finden",
    TextKey.PublicRoomsDescription to "Erstelle einen privaten Raum oder tritt einem offenen Raum bei.", TextKey.CreateRoom to "Raum erstellen",
    TextKey.JoinRoom to "Raum beitreten", TextKey.All to "Alle", TextKey.Waiting to "Wartend", TextKey.SearchRooms to "Raum oder Host suchen",
    TextKey.WaitHostStart to "Warte, bis der Host das Match startet.", TextKey.CancelReady to "BEREITSCHAFT AUFHEBEN",
    TextKey.ReadyAction to "BEREIT", TextKey.WaitingForReady to "Warten, bis alle bereit sind…",
    TextKey.InviteFriends to "FREUNDE EINLADEN", TextKey.Kick to "ENTFERNEN", TextKey.CloseRoom to "RAUM SCHLIESSEN",
    TextKey.LeaveRoom to "RAUM VERLASSEN", TextKey.ReadyStatus to "BEREIT", TextKey.WaitingStatus to "WARTET",
    TextKey.PlayersTitle to "Spieler", TextKey.BlueTeam to "Blaues Team", TextKey.RedTeam to "Rotes Team", TextKey.You to "Du",
    TextKey.Teammate to "Mitspieler", TextKey.Opponent to "Gegner", TextKey.WaitingPlayer to "Wartet…",
    TextKey.HostYou to "Host • Du", TextKey.Guest to "Gast", TextKey.Host to "Host", TextKey.WaitingForPlayer to "Warte auf Spieler…",
    TextKey.EnterRoomCode to "Raumcode eingeben", TextKey.PasteRoomCode to "Füge den vom Host geteilten Code ein.", TextKey.RoomCode to "Raumcode",
    TextKey.FindRoom to "RAUM SUCHEN", TextKey.RoomCodeNotFound to "Mit diesem Code wurde kein Raum gefunden.", TextKey.CreateNewRoom to "Neuen Raum erstellen",
    TextKey.RoomName to "Raumname", TextKey.Public to "Öffentlich", TextKey.Private to "Privat", TextKey.RoomPassword to "Raumpasswort",
    TextKey.JoinRoomTitle to "Raum beitreten", TextKey.PrivatePasswordRequired to "Spieler benötigen ein Passwort.",
    TextKey.PublicNoPassword to "Jeder kann ohne Passwort beitreten.", TextKey.RankedEloImpact to "Rangliste · Beeinflusst Elo",
    TextKey.CasualNoEloImpact to "Normal · Kein Elo-Einfluss", TextKey.PrivateRoom to "Privater Raum", TextKey.PublicRoom to "Öffentlicher Raum",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "BETRETEN", TextKey.JoinPrivateRoom to "Privater Raum",
    TextKey.PrivateJoinDescription to "Gib das Passwort ein, um „{room}“ beizutreten.", TextKey.PublicJoinDescription to "{room} • Host: {host}",
    TextKey.JoinedRoomCode to "RAUMCODE • {code}", TextKey.JoinedRoom to "IM RAUM", TextKey.ShareCodeHint to "Teile den Code, um Freunde einzuladen.",
    TextKey.ModeNumberCount to "{mode} • 50 Zahlen", TextKey.ShareRoomCode to "RAUMCODE TEILEN",
    TextKey.ShareSheetError to "Teilen konnte nicht geöffnet werden. Versuche es erneut.", TextKey.LatencyGood to "{latency} ms • Gut",
    TextKey.LatencyStable to "{latency} ms • Stabil", TextKey.LatencySlow to "{latency} ms • Langsam",
    TextKey.OpponentReady to "GEGNER BEREIT", TextKey.MatchStarting to "Das Match beginnt gleich"
)

internal val japaneseCorePlayTexts = mapOf(
    TextKey.Ranked to "ランク戦", TextKey.Casual to "通常戦", TextKey.GameHeader to "{mode} · {matchType}",
    TextKey.NextNumber to "次の数字", TextKey.ExitMatchTitle to "対戦を終了しますか？", TextKey.ExitMatch to "対戦を終了",
    TextKey.ContinuePlaying to "プレイを続ける", TextKey.GameDefaultRoom to "50数字対戦", TextKey.SendReaction to "リアクションを送る",
    TextKey.CorrectWrongSummary to "正解 {correct}  ·  ミス {wrong}", TextKey.Measuring to "計測中", TextKey.YourTeam to "あなたのチーム",
    TextKey.OpponentTeam to "相手チーム", TextKey.OpponentLabel to "対戦相手", TextKey.LocalPlayerLabel to "あなた",
    TextKey.WaitHostStart to "ホストが対戦を開始するまでお待ちください。", TextKey.CancelReady to "準備を解除",
    TextKey.ReadyAction to "準備完了", TextKey.WaitingForReady to "全員の準備完了を待っています…",
    TextKey.InviteFriends to "フレンドを招待", TextKey.Kick to "退出させる", TextKey.CloseRoom to "ルームを閉じる",
    TextKey.LeaveRoom to "ルームを退出", TextKey.ReadyStatus to "準備完了", TextKey.WaitingStatus to "待機中",
    TextKey.PlayersTitle to "プレイヤー", TextKey.BlueTeam to "ブルーチーム", TextKey.RedTeam to "レッドチーム", TextKey.You to "あなた",
    TextKey.Teammate to "チームメイト", TextKey.Opponent to "対戦相手", TextKey.WaitingPlayer to "待機中…",
    TextKey.HostYou to "ホスト • あなた", TextKey.Guest to "ゲスト", TextKey.Host to "ホスト", TextKey.WaitingForPlayer to "プレイヤーを待っています…",
    TextKey.EnterRoomCode to "ルームコードを入力", TextKey.PasteRoomCode to "ホストが共有したコードを貼り付けてください。", TextKey.RoomCode to "ルームコード",
    TextKey.FindRoom to "ルームを検索", TextKey.RoomCodeNotFound to "このコードのルームが見つかりません。", TextKey.CreateNewRoom to "新しいルームを作成",
    TextKey.RoomName to "ルーム名", TextKey.Public to "公開", TextKey.Private to "非公開", TextKey.RoomPassword to "ルームパスワード",
    TextKey.JoinRoomTitle to "ルームに参加", TextKey.PrivatePasswordRequired to "参加者はパスワードが必要です。",
    TextKey.PublicNoPassword to "誰でもパスワードなしで参加できます。", TextKey.RankedEloImpact to "ランク戦 · Eloに影響",
    TextKey.CasualNoEloImpact to "通常戦 · Eloに影響なし", TextKey.PrivateRoom to "非公開ルーム", TextKey.PublicRoom to "公開ルーム",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "入室", TextKey.JoinPrivateRoom to "非公開ルーム",
    TextKey.PrivateJoinDescription to "「{room}」に参加するにはパスワードを入力してください。", TextKey.PublicJoinDescription to "{room} • ホスト {host}",
    TextKey.JoinedRoomCode to "ルームコード • {code}", TextKey.JoinedRoom to "ルーム参加中", TextKey.ShareCodeHint to "コードを共有してフレンドを招待しましょう。",
    TextKey.ModeNumberCount to "{mode} • 50個の数字", TextKey.ShareRoomCode to "ルームコードを共有",
    TextKey.ShareSheetError to "共有画面を開けませんでした。もう一度お試しください。", TextKey.LatencyGood to "{latency} ms • 良好",
    TextKey.LatencyStable to "{latency} ms • 安定", TextKey.LatencySlow to "{latency} ms • 遅い",
    TextKey.OpponentReady to "対戦相手は準備完了", TextKey.MatchStarting to "まもなく対戦開始"
)

internal val russianCorePlayTexts = mapOf(
    TextKey.Ranked to "Рейтинг", TextKey.Casual to "Обычная", TextKey.DrawResult to "НИЧЬЯ!", TextKey.VictoryResult to "ПОБЕДА!",
    TextKey.DefeatResult to "ПОРАЖЕНИЕ", TextKey.MatchResultTitle to "Результат матча", TextKey.ShareResult to "ПОДЕЛИТЬСЯ РЕЗУЛЬТАТОМ",
    TextKey.ReturnToLobby to "Вернуться в лобби", TextKey.Draw to "Ничья", TextKey.Win to "Победа", TextKey.Loss to "Поражение",
    TextKey.YourSummary to "Ваш результат", TextKey.AverageReaction to "Средняя реакция", TextKey.Accuracy to "Точность",
    TextKey.PaceAnalysis to "Анализ темпа", TextKey.Fastest to "Самый быстрый", TextKey.Slowest to "Самый медленный",
    TextKey.Rematch to "Реванш", TextKey.InviteRematch to "Предложить реванш", TextKey.MatchReward to "Награда за матч",
    TextKey.WaitHostStart to "Дождитесь, пока ведущий начнёт матч.", TextKey.CancelReady to "ОТМЕНИТЬ ГОТОВНОСТЬ",
    TextKey.ReadyAction to "ГОТОВ", TextKey.WaitingForReady to "Ожидание готовности всех игроков…",
    TextKey.InviteFriends to "ПРИГЛАСИТЬ ДРУЗЕЙ", TextKey.Kick to "ИСКЛЮЧИТЬ", TextKey.CloseRoom to "ЗАКРЫТЬ КОМНАТУ",
    TextKey.LeaveRoom to "ПОКИНУТЬ КОМНАТУ", TextKey.ReadyStatus to "ГОТОВ", TextKey.WaitingStatus to "ОЖИДАНИЕ",
    TextKey.PlayersTitle to "Игроки", TextKey.BlueTeam to "Синяя команда", TextKey.RedTeam to "Красная команда", TextKey.You to "Вы",
    TextKey.Teammate to "Союзник", TextKey.Opponent to "Соперник", TextKey.WaitingPlayer to "Ожидание…",
    TextKey.HostYou to "Ведущий • Вы", TextKey.Guest to "Гость", TextKey.Host to "Ведущий", TextKey.WaitingForPlayer to "Ожидание игрока…",
    TextKey.EnterRoomCode to "Введите код комнаты", TextKey.PasteRoomCode to "Вставьте код, которым поделился ведущий.", TextKey.RoomCode to "Код комнаты",
    TextKey.FindRoom to "НАЙТИ КОМНАТУ", TextKey.RoomCodeNotFound to "Комната с таким кодом не найдена.", TextKey.CreateNewRoom to "Создать новую комнату",
    TextKey.RoomName to "Название комнаты", TextKey.Public to "Открытая", TextKey.Private to "Закрытая", TextKey.RoomPassword to "Пароль комнаты",
    TextKey.JoinRoomTitle to "Войти в комнату", TextKey.PrivatePasswordRequired to "Игрокам нужен пароль.",
    TextKey.PublicNoPassword to "Любой может войти без пароля.", TextKey.RankedEloImpact to "Рейтинг · Влияет на Elo",
    TextKey.CasualNoEloImpact to "Обычная · Не влияет на Elo", TextKey.PrivateRoom to "Закрытая комната", TextKey.PublicRoom to "Открытая комната",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ВОЙТИ", TextKey.JoinPrivateRoom to "Закрытая комната",
    TextKey.PrivateJoinDescription to "Введите пароль, чтобы войти в «{room}».", TextKey.PublicJoinDescription to "{room} • Ведущий: {host}",
    TextKey.JoinedRoomCode to "КОД КОМНАТЫ • {code}", TextKey.JoinedRoom to "В КОМНАТЕ", TextKey.ShareCodeHint to "Поделитесь кодом, чтобы пригласить друзей.",
    TextKey.ModeNumberCount to "{mode} • 50 чисел", TextKey.ShareRoomCode to "ПОДЕЛИТЬСЯ КОДОМ",
    TextKey.ShareSheetError to "Не удалось открыть меню «Поделиться». Попробуйте ещё раз.", TextKey.LatencyGood to "{latency} ms • Хорошо",
    TextKey.LatencyStable to "{latency} ms • Стабильно", TextKey.LatencySlow to "{latency} ms • Медленно",
    TextKey.OpponentReady to "СОПЕРНИК ГОТОВ", TextKey.MatchStarting to "Матч скоро начнётся"
)

internal val thaiCorePlayTexts = mapOf(
    TextKey.PracticeHeader to "ฝึกซ้อม · {mode}", TextKey.OfflineNoElo to "ออฟไลน์ • ไม่กระทบ Elo", TextKey.Target to "เป้าหมาย",
    TextKey.Score to "คะแนน", TextKey.Remaining to "เหลือ", TextKey.Time to "เวลา", TextKey.Lives to "ชีวิต", TextKey.ComboLabel to "คอมโบ",
    TextKey.Pace to "จังหวะ", TextKey.EndPractice to "จบ", TextKey.CorrectBoardCompleted to "ถูกต้อง จบกระดานแล้ว",
    TextKey.CorrectNextTarget to "ถูกต้อง เป้าหมายถัดไป {target}", TextKey.WrongNeedTarget to "ผิด ต้องหา {target}",
    TextKey.Completed to "เสร็จสิ้น", TextKey.ChallengeCode to "รหัสชาเลนจ์", TextKey.PracticeNoElo to "ผลการฝึกไม่กระทบ Elo",
    TextKey.ShareChallenge to "แชร์ชาเลนจ์", TextKey.ReplaySameBoard to "เล่นกระดานเดิมอีกครั้ง", TextKey.CreateNewChallenge to "สร้างชาเลนจ์ใหม่",
    TextKey.ReturnHome to "กลับหน้าหลัก", TextKey.Reaction to "การตอบสนอง", TextKey.CorrectWrong to "ถูก / ผิด",
    TextKey.AveragePerNumber to "เฉลี่ยต่อตัวเลข", TextKey.PracticeHeroTitle to "ฝึกออฟไลน์",
    TextKey.PracticeHeroDescription to "ฝึกการตอบสนองทุกวันโดยไม่กระทบ Elo", TextKey.PracticeNoServerNeeded to "ไม่กระทบ Elo และไม่ต้องเชื่อมต่อเซิร์ฟเวอร์",
    TextKey.StartNewPractice to "เริ่มฝึกใหม่", TextKey.HaveChallengeCode to "มีรหัสชาเลนจ์ไหม?", TextKey.PlayChallenge to "เล่นชาเลนจ์",
    TextKey.InvalidChallengeCode to "รหัสไม่ถูกต้องหรือพิมพ์ผิด", TextKey.WaitHostStart to "รอให้โฮสต์เริ่มการแข่งขัน",
    TextKey.CancelReady to "ยกเลิกพร้อม", TextKey.ReadyAction to "พร้อม", TextKey.WaitingForReady to "กำลังรอให้ทุกคนพร้อม…",
    TextKey.InviteFriends to "เชิญเพื่อน", TextKey.Kick to "นำออก", TextKey.CloseRoom to "ปิดห้อง",
    TextKey.LeaveRoom to "ออกจากห้อง", TextKey.ReadyStatus to "พร้อม", TextKey.WaitingStatus to "รอ",
    TextKey.PlayersTitle to "ผู้เล่น", TextKey.BlueTeam to "ทีมสีน้ำเงิน", TextKey.RedTeam to "ทีมสีแดง", TextKey.You to "คุณ",
    TextKey.Teammate to "เพื่อนร่วมทีม", TextKey.Opponent to "คู่แข่ง", TextKey.WaitingPlayer to "กำลังรอ…",
    TextKey.HostYou to "โฮสต์ • คุณ", TextKey.Guest to "ผู้เล่นรับเชิญ", TextKey.Host to "โฮสต์", TextKey.WaitingForPlayer to "กำลังรอผู้เล่น…",
    TextKey.EnterRoomCode to "กรอกรหัสห้อง", TextKey.PasteRoomCode to "วางรหัสที่โฮสต์แชร์", TextKey.RoomCode to "รหัสห้อง",
    TextKey.FindRoom to "ค้นหาห้อง", TextKey.RoomCodeNotFound to "ไม่พบห้องที่ใช้รหัสนี้", TextKey.CreateNewRoom to "สร้างห้องใหม่",
    TextKey.RoomName to "ชื่อห้อง", TextKey.Public to "สาธารณะ", TextKey.Private to "ส่วนตัว", TextKey.RoomPassword to "รหัสผ่านห้อง",
    TextKey.JoinRoomTitle to "เข้าร่วมห้อง", TextKey.PrivatePasswordRequired to "ผู้เล่นต้องใช้รหัสผ่าน",
    TextKey.PublicNoPassword to "ทุกคนเข้าร่วมได้โดยไม่ต้องใช้รหัสผ่าน", TextKey.RankedEloImpact to "จัดอันดับ · มีผลต่อ Elo",
    TextKey.CasualNoEloImpact to "ทั่วไป · ไม่มีผลต่อ Elo", TextKey.PrivateRoom to "ห้องส่วนตัว", TextKey.PublicRoom to "ห้องสาธารณะ",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "เข้า", TextKey.JoinPrivateRoom to "ห้องส่วนตัว",
    TextKey.PrivateJoinDescription to "กรอกรหัสผ่านเพื่อเข้าร่วม “{room}”", TextKey.PublicJoinDescription to "{room} • โฮสต์ {host}",
    TextKey.JoinedRoomCode to "รหัสห้อง • {code}", TextKey.JoinedRoom to "อยู่ในห้อง", TextKey.ShareCodeHint to "แชร์รหัสเพื่อเชิญเพื่อน",
    TextKey.ModeNumberCount to "{mode} • 50 ตัวเลข", TextKey.ShareRoomCode to "แชร์รหัสห้อง",
    TextKey.ShareSheetError to "ไม่สามารถเปิดการแชร์ได้ โปรดลองอีกครั้ง", TextKey.LatencyGood to "{latency} ms • ดี",
    TextKey.LatencyStable to "{latency} ms • เสถียร", TextKey.LatencySlow to "{latency} ms • ช้า",
    TextKey.OpponentReady to "คู่แข่งพร้อมแล้ว", TextKey.MatchStarting to "การแข่งขันกำลังจะเริ่ม"
)

internal val simplifiedChineseCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "等待房主开始比赛。", TextKey.CancelReady to "取消准备", TextKey.ReadyAction to "准备",
    TextKey.WaitingForReady to "等待所有人准备…", TextKey.InviteFriends to "邀请好友", TextKey.Kick to "踢出",
    TextKey.CloseRoom to "关闭房间", TextKey.LeaveRoom to "离开房间", TextKey.ReadyStatus to "已准备", TextKey.WaitingStatus to "等待中",
    TextKey.PlayersTitle to "玩家", TextKey.BlueTeam to "蓝队", TextKey.RedTeam to "红队", TextKey.You to "你",
    TextKey.Teammate to "队友", TextKey.Opponent to "对手", TextKey.WaitingPlayer to "等待中…",
    TextKey.HostYou to "房主 • 你", TextKey.Guest to "客人", TextKey.Host to "房主", TextKey.WaitingForPlayer to "等待玩家…",
    TextKey.EnterRoomCode to "输入房间代码", TextKey.PasteRoomCode to "粘贴房主分享的代码。", TextKey.RoomCode to "房间代码",
    TextKey.FindRoom to "查找房间", TextKey.RoomCodeNotFound to "未找到使用此代码的房间。", TextKey.CreateNewRoom to "创建新房间",
    TextKey.RoomName to "房间名称", TextKey.Public to "公开", TextKey.Private to "私密", TextKey.RoomPassword to "房间密码",
    TextKey.JoinRoomTitle to "加入房间", TextKey.PrivatePasswordRequired to "玩家需要输入密码。",
    TextKey.PublicNoPassword to "任何人无需密码即可加入。", TextKey.RankedEloImpact to "排位赛 · 影响 Elo",
    TextKey.CasualNoEloImpact to "休闲赛 · 不影响 Elo", TextKey.PrivateRoom to "私密房间", TextKey.PublicRoom to "公开房间",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "进入", TextKey.JoinPrivateRoom to "私密房间",
    TextKey.PrivateJoinDescription to "输入密码加入“{room}”。", TextKey.PublicJoinDescription to "{room} • 房主 {host}",
    TextKey.JoinedRoomCode to "房间代码 • {code}", TextKey.JoinedRoom to "已加入房间", TextKey.ShareCodeHint to "分享代码以邀请好友。",
    TextKey.ModeNumberCount to "{mode} • 50个数字", TextKey.ShareRoomCode to "分享房间代码", TextKey.ShareSheetError to "无法打开分享，请重试。",
    TextKey.LatencyGood to "{latency} ms • 良好", TextKey.LatencyStable to "{latency} ms • 稳定", TextKey.LatencySlow to "{latency} ms • 较慢",
    TextKey.OpponentReady to "对手已准备", TextKey.MatchStarting to "比赛即将开始"
)
internal val koreanCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "방장이 경기를 시작할 때까지 기다리세요.", TextKey.CancelReady to "준비 취소", TextKey.ReadyAction to "준비",
    TextKey.WaitingForReady to "모두가 준비되기를 기다리는 중…", TextKey.InviteFriends to "친구 초대", TextKey.Kick to "내보내기",
    TextKey.CloseRoom to "방 닫기", TextKey.LeaveRoom to "방 나가기", TextKey.ReadyStatus to "준비 완료", TextKey.WaitingStatus to "대기 중",
    TextKey.PlayersTitle to "플레이어", TextKey.BlueTeam to "블루 팀", TextKey.RedTeam to "레드 팀", TextKey.You to "나",
    TextKey.Teammate to "팀원", TextKey.Opponent to "상대", TextKey.WaitingPlayer to "대기 중…",
    TextKey.HostYou to "방장 • 나", TextKey.Guest to "게스트", TextKey.Host to "방장", TextKey.WaitingForPlayer to "플레이어를 기다리는 중…",
    TextKey.EnterRoomCode to "방 코드 입력", TextKey.PasteRoomCode to "방장이 공유한 코드를 붙여넣으세요.", TextKey.RoomCode to "방 코드",
    TextKey.FindRoom to "방 찾기", TextKey.RoomCodeNotFound to "이 코드에 해당하는 방을 찾을 수 없습니다.", TextKey.CreateNewRoom to "새 방 만들기",
    TextKey.RoomName to "방 이름", TextKey.Public to "공개", TextKey.Private to "비공개", TextKey.RoomPassword to "방 비밀번호",
    TextKey.JoinRoomTitle to "방 참가", TextKey.PrivatePasswordRequired to "플레이어는 비밀번호가 필요합니다.",
    TextKey.PublicNoPassword to "누구나 비밀번호 없이 참가할 수 있습니다.", TextKey.RankedEloImpact to "랭크전 · Elo에 영향",
    TextKey.CasualNoEloImpact to "일반전 · Elo에 영향 없음", TextKey.PrivateRoom to "비공개 방", TextKey.PublicRoom to "공개 방",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "입장", TextKey.JoinPrivateRoom to "비공개 방",
    TextKey.PrivateJoinDescription to "“{room}” 방에 참가하려면 비밀번호를 입력하세요.", TextKey.PublicJoinDescription to "{room} • 방장 {host}",
    TextKey.JoinedRoomCode to "방 코드 • {code}", TextKey.JoinedRoom to "방 참가 중", TextKey.ShareCodeHint to "코드를 공유해 친구를 초대하세요.",
    TextKey.ModeNumberCount to "{mode} • 숫자 50개", TextKey.ShareRoomCode to "방 코드 공유", TextKey.ShareSheetError to "공유 창을 열 수 없습니다. 다시 시도하세요.",
    TextKey.LatencyGood to "{latency} ms • 좋음", TextKey.LatencyStable to "{latency} ms • 안정적", TextKey.LatencySlow to "{latency} ms • 느림",
    TextKey.OpponentReady to "상대 준비 완료", TextKey.MatchStarting to "곧 경기가 시작됩니다"
)
internal val spanishCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "Espera a que el anfitrión inicie la partida.", TextKey.CancelReady to "CANCELAR LISTO", TextKey.ReadyAction to "LISTO",
    TextKey.WaitingForReady to "Esperando a que todos estén listos…", TextKey.InviteFriends to "INVITAR AMIGOS", TextKey.Kick to "EXPULSAR",
    TextKey.CloseRoom to "CERRAR SALA", TextKey.LeaveRoom to "SALIR DE LA SALA", TextKey.ReadyStatus to "LISTO", TextKey.WaitingStatus to "EN ESPERA",
    TextKey.PlayersTitle to "Jugadores", TextKey.BlueTeam to "Equipo azul", TextKey.RedTeam to "Equipo rojo", TextKey.You to "Tú",
    TextKey.Teammate to "Compañero", TextKey.Opponent to "Oponente", TextKey.WaitingPlayer to "Esperando…",
    TextKey.HostYou to "Anfitrión • Tú", TextKey.Guest to "Invitado", TextKey.Host to "Anfitrión", TextKey.WaitingForPlayer to "Esperando jugador…",
    TextKey.EnterRoomCode to "Introduce el código de la sala", TextKey.PasteRoomCode to "Pega el código compartido por el anfitrión.", TextKey.RoomCode to "Código de sala",
    TextKey.FindRoom to "BUSCAR SALA", TextKey.RoomCodeNotFound to "No se encontró ninguna sala con este código.", TextKey.CreateNewRoom to "Crear nueva sala",
    TextKey.RoomName to "Nombre de la sala", TextKey.Public to "Pública", TextKey.Private to "Privada", TextKey.RoomPassword to "Contraseña de la sala",
    TextKey.JoinRoomTitle to "Unirse a la sala", TextKey.PrivatePasswordRequired to "Los jugadores necesitan una contraseña.",
    TextKey.PublicNoPassword to "Cualquiera puede unirse sin contraseña.", TextKey.RankedEloImpact to "Clasificatoria · Afecta al Elo",
    TextKey.CasualNoEloImpact to "Casual · No afecta al Elo", TextKey.PrivateRoom to "Sala privada", TextKey.PublicRoom to "Sala pública",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ENTRAR", TextKey.JoinPrivateRoom to "Sala privada",
    TextKey.PrivateJoinDescription to "Introduce la contraseña para unirte a “{room}”.", TextKey.PublicJoinDescription to "{room} • Anfitrión: {host}",
    TextKey.JoinedRoomCode to "CÓDIGO DE SALA • {code}", TextKey.JoinedRoom to "EN LA SALA", TextKey.ShareCodeHint to "Comparte el código para invitar a tus amigos.",
    TextKey.ModeNumberCount to "{mode} • 50 números", TextKey.ShareRoomCode to "COMPARTIR CÓDIGO DE SALA",
    TextKey.ShareSheetError to "No se pudo abrir el menú para compartir. Inténtalo de nuevo.", TextKey.LatencyGood to "{latency} ms • Buena",
    TextKey.LatencyStable to "{latency} ms • Estable", TextKey.LatencySlow to "{latency} ms • Lenta",
    TextKey.OpponentReady to "OPONENTE LISTO", TextKey.MatchStarting to "La partida está a punto de comenzar"
)
internal val brazilianPortugueseCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "Aguarde o anfitrião iniciar a partida.", TextKey.CancelReady to "CANCELAR PRONTO", TextKey.ReadyAction to "PRONTO",
    TextKey.WaitingForReady to "Aguardando todos ficarem prontos…", TextKey.InviteFriends to "CONVIDAR AMIGOS", TextKey.Kick to "EXPULSAR",
    TextKey.CloseRoom to "FECHAR SALA", TextKey.LeaveRoom to "SAIR DA SALA", TextKey.ReadyStatus to "PRONTO", TextKey.WaitingStatus to "AGUARDANDO",
    TextKey.PlayersTitle to "Jogadores", TextKey.BlueTeam to "Equipe Azul", TextKey.RedTeam to "Equipe Vermelha", TextKey.You to "Você",
    TextKey.Teammate to "Companheiro", TextKey.Opponent to "Adversário", TextKey.WaitingPlayer to "Aguardando…",
    TextKey.HostYou to "Anfitrião • Você", TextKey.Guest to "Convidado", TextKey.Host to "Anfitrião", TextKey.WaitingForPlayer to "Aguardando jogador…",
    TextKey.EnterRoomCode to "Digite o código da sala", TextKey.PasteRoomCode to "Cole o código compartilhado pelo anfitrião.", TextKey.RoomCode to "Código da sala",
    TextKey.FindRoom to "ENCONTRAR SALA", TextKey.RoomCodeNotFound to "Nenhuma sala foi encontrada com este código.", TextKey.CreateNewRoom to "Criar nova sala",
    TextKey.RoomName to "Nome da sala", TextKey.Public to "Pública", TextKey.Private to "Privada", TextKey.RoomPassword to "Senha da sala",
    TextKey.JoinRoomTitle to "Entrar na sala", TextKey.PrivatePasswordRequired to "Os jogadores precisam de uma senha.",
    TextKey.PublicNoPassword to "Qualquer pessoa pode entrar sem senha.", TextKey.RankedEloImpact to "Ranqueada · Afeta o Elo",
    TextKey.CasualNoEloImpact to "Casual · Não afeta o Elo", TextKey.PrivateRoom to "Sala privada", TextKey.PublicRoom to "Sala pública",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ENTRAR", TextKey.JoinPrivateRoom to "Sala privada",
    TextKey.PrivateJoinDescription to "Digite a senha para entrar em “{room}”.", TextKey.PublicJoinDescription to "{room} • Anfitrião: {host}",
    TextKey.JoinedRoomCode to "CÓDIGO DA SALA • {code}", TextKey.JoinedRoom to "NA SALA", TextKey.ShareCodeHint to "Compartilhe o código para convidar amigos.",
    TextKey.ModeNumberCount to "{mode} • 50 números", TextKey.ShareRoomCode to "COMPARTILHAR CÓDIGO DA SALA",
    TextKey.ShareSheetError to "Não foi possível abrir o compartilhamento. Tente novamente.", TextKey.LatencyGood to "{latency} ms • Boa",
    TextKey.LatencyStable to "{latency} ms • Estável", TextKey.LatencySlow to "{latency} ms • Lenta",
    TextKey.OpponentReady to "ADVERSÁRIO PRONTO", TextKey.MatchStarting to "A partida está prestes a começar"
)
internal val frenchCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "Attends que l’hôte lance la partie.", TextKey.CancelReady to "ANNULER PRÊT", TextKey.ReadyAction to "PRÊT",
    TextKey.WaitingForReady to "En attente que tout le monde soit prêt…", TextKey.InviteFriends to "INVITER DES AMIS", TextKey.Kick to "EXCLURE",
    TextKey.CloseRoom to "FERMER LE SALON", TextKey.LeaveRoom to "QUITTER LE SALON", TextKey.ReadyStatus to "PRÊT", TextKey.WaitingStatus to "EN ATTENTE",
    TextKey.PlayersTitle to "Joueurs", TextKey.BlueTeam to "Équipe bleue", TextKey.RedTeam to "Équipe rouge", TextKey.You to "Toi",
    TextKey.Teammate to "Coéquipier", TextKey.Opponent to "Adversaire", TextKey.WaitingPlayer to "En attente…",
    TextKey.HostYou to "Hôte • Toi", TextKey.Guest to "Invité", TextKey.Host to "Hôte", TextKey.WaitingForPlayer to "En attente d’un joueur…",
    TextKey.EnterRoomCode to "Saisis le code du salon", TextKey.PasteRoomCode to "Colle le code partagé par l’hôte.", TextKey.RoomCode to "Code du salon",
    TextKey.FindRoom to "TROUVER LE SALON", TextKey.RoomCodeNotFound to "Aucun salon trouvé avec ce code.", TextKey.CreateNewRoom to "Créer un nouveau salon",
    TextKey.RoomName to "Nom du salon", TextKey.Public to "Public", TextKey.Private to "Privé", TextKey.RoomPassword to "Mot de passe du salon",
    TextKey.JoinRoomTitle to "Rejoindre le salon", TextKey.PrivatePasswordRequired to "Les joueurs ont besoin d’un mot de passe.",
    TextKey.PublicNoPassword to "Tout le monde peut rejoindre sans mot de passe.", TextKey.RankedEloImpact to "Classé · Affecte l’Elo",
    TextKey.CasualNoEloImpact to "Amical · Aucun impact sur l’Elo", TextKey.PrivateRoom to "Salon privé", TextKey.PublicRoom to "Salon public",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "ENTRER", TextKey.JoinPrivateRoom to "Salon privé",
    TextKey.PrivateJoinDescription to "Saisis le mot de passe pour rejoindre « {room} ».", TextKey.PublicJoinDescription to "{room} • Hôte : {host}",
    TextKey.JoinedRoomCode to "CODE DU SALON • {code}", TextKey.JoinedRoom to "DANS LE SALON", TextKey.ShareCodeHint to "Partage le code pour inviter tes amis.",
    TextKey.ModeNumberCount to "{mode} • 50 nombres", TextKey.ShareRoomCode to "PARTAGER LE CODE DU SALON",
    TextKey.ShareSheetError to "Impossible d’ouvrir le partage. Réessaie.", TextKey.LatencyGood to "{latency} ms • Bonne",
    TextKey.LatencyStable to "{latency} ms • Stable", TextKey.LatencySlow to "{latency} ms • Lente",
    TextKey.OpponentReady to "ADVERSAIRE PRÊT", TextKey.MatchStarting to "La partie va commencer"
)
internal val indonesianCorePlayTexts = mapOf(
    TextKey.WaitHostStart to "Tunggu host memulai pertandingan.", TextKey.CancelReady to "BATAL SIAP", TextKey.ReadyAction to "SIAP",
    TextKey.WaitingForReady to "Menunggu semua pemain siap…", TextKey.InviteFriends to "UNDANG TEMAN", TextKey.Kick to "KELUARKAN",
    TextKey.CloseRoom to "TUTUP RUANG", TextKey.LeaveRoom to "KELUAR DARI RUANG", TextKey.ReadyStatus to "SIAP", TextKey.WaitingStatus to "MENUNGGU",
    TextKey.PlayersTitle to "Pemain", TextKey.BlueTeam to "Tim Biru", TextKey.RedTeam to "Tim Merah", TextKey.You to "Kamu",
    TextKey.Teammate to "Rekan tim", TextKey.Opponent to "Lawan", TextKey.WaitingPlayer to "Menunggu…",
    TextKey.HostYou to "Host • Kamu", TextKey.Guest to "Tamu", TextKey.Host to "Host", TextKey.WaitingForPlayer to "Menunggu pemain…",
    TextKey.EnterRoomCode to "Masukkan kode ruang", TextKey.PasteRoomCode to "Tempel kode yang dibagikan host.", TextKey.RoomCode to "Kode ruang",
    TextKey.FindRoom to "CARI RUANG", TextKey.RoomCodeNotFound to "Ruang dengan kode ini tidak ditemukan.", TextKey.CreateNewRoom to "Buat ruang baru",
    TextKey.RoomName to "Nama ruang", TextKey.Public to "Publik", TextKey.Private to "Privat", TextKey.RoomPassword to "Kata sandi ruang",
    TextKey.JoinRoomTitle to "Gabung ruang", TextKey.PrivatePasswordRequired to "Pemain memerlukan kata sandi.",
    TextKey.PublicNoPassword to "Siapa pun dapat bergabung tanpa kata sandi.", TextKey.RankedEloImpact to "Peringkat · Memengaruhi Elo",
    TextKey.CasualNoEloImpact to "Kasual · Tidak memengaruhi Elo", TextKey.PrivateRoom to "Ruang privat", TextKey.PublicRoom to "Ruang publik",
    TextKey.RoomListSummary to "{host} • {mode} • {matchType}", TextKey.EnterRoom to "MASUK", TextKey.JoinPrivateRoom to "Ruang privat",
    TextKey.PrivateJoinDescription to "Masukkan kata sandi untuk bergabung ke “{room}”.", TextKey.PublicJoinDescription to "{room} • Host {host}",
    TextKey.JoinedRoomCode to "KODE RUANG • {code}", TextKey.JoinedRoom to "DI DALAM RUANG", TextKey.ShareCodeHint to "Bagikan kode untuk mengundang teman.",
    TextKey.ModeNumberCount to "{mode} • 50 angka", TextKey.ShareRoomCode to "BAGIKAN KODE RUANG",
    TextKey.ShareSheetError to "Tidak dapat membuka menu berbagi. Coba lagi.", TextKey.LatencyGood to "{latency} ms • Bagus",
    TextKey.LatencyStable to "{latency} ms • Stabil", TextKey.LatencySlow to "{latency} ms • Lambat",
    TextKey.OpponentReady to "LAWAN SIAP", TextKey.MatchStarting to "Pertandingan akan segera dimulai"
)
