package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey

internal val englishGameplayTexts = mapOf(
    TextKey.ModeClassicTitle to "Classic", TextKey.ModeClassicDescription to "Find the numbers from 1 to 50",
    TextKey.ModeRandomTitle to "Random", TextKey.ModeRandomDescription to "Targets appear in an unexpected order",
    TextKey.ModeTimeBonusTitle to "Time Bonus", TextKey.ModeTimeBonusDescription to "Correct +2 seconds, wrong -3 seconds",
    TextKey.ModeSpeedUpTitle to "Speed Up", TextKey.ModeSpeedUpDescription to "Time for each target gradually decreases",
    TextKey.ModeSurvivalTitle to "Survival", TextKey.ModeSurvivalDescription to "Lose after 3 wrong taps",
    TextKey.ModeComboTitle to "Combo", TextKey.ModeComboDescription to "Consecutive correct taps multiply your score",
    TextKey.ModeTimeAttackTitle to "60-second Rush", TextKey.ModeTimeAttackDescription to "Legacy mode: score as much as possible in 60 seconds",
    TextKey.ModeTeamTitle to "Team 2v2", TextKey.ModeTeamDescription to "Two teams compete on the same number board",
    TextKey.ChooseMatchType to "Choose match type", TextKey.ChooseRankedMode to "Choose ranked mode",
    TextKey.ChooseCasualMode to "Choose casual mode", TextKey.GuestMode to "GUEST MODE",
    TextKey.Ranked to "Ranked", TextKey.Casual to "Casual", TextKey.RegisterToPlayOnline to "Create an account to find online opponents.",
    TextKey.CasualOrRankedDescription to "Play casual to practise or ranked to gain Elo.",
    TextKey.LoginToPlay to "LOG IN TO PLAY", TextKey.PlayNow to "PLAY NOW", TextKey.Explore to "Explore",
    TextKey.FeaturesAndActivities to "Features and activities", TextKey.Tournament to "Tournament",
    TextKey.RegisterToJoin to "Create an account to join", TextKey.TournamentDescription to "Private 4, 8 or 16-player knockout tournaments",
    TextKey.Shop to "Shop", TextKey.ShopDiscoveryDescription to "Unlock number faces, boards and new items",
    TextKey.OfflinePracticeTitle to "Offline practice", TextKey.OfflinePracticeDescription to "Train with a 50-number board without affecting Elo",
    TextKey.SaveProgress to "SAVE PROGRESS", TextKey.SaveProgressDescription to "Create an account to keep your Elo, history and friends on Android/iOS.",
    TextKey.ExitGuestMode to "EXIT GUEST MODE", TextKey.ChooseCompetitionType to "Choose how to compete",
    TextKey.CreateRoom to "Create room", TextKey.JoinRoom to "Join room", TextKey.Friends to "Friends",
    TextKey.RegisterToAddFriends to "Create an account to add friends", TextKey.OnlineFriends to "{count} friends online",
    TextKey.YourRank to "Your rank is #{rank}", TextKey.ViewEloLeaderboard to "View Elo leaderboard",
    TextKey.Level to "Level {level}", TextKey.PlacementPending to "Placement pending",
    TextKey.DailyCheckInSevenDays to "7-day check-in", TextKey.CheckInStreak to "{count}-day streak",
    TextKey.DayLabel to "Day", TextKey.ClaimDayReward to "CLAIM DAY {day} REWARD", TextKey.Home to "Home",
    TextKey.HarderModesUnlock to "Harder modes unlock as you level up.", TextKey.UnlockAtLevel to "Unlocks at level {level}",
    TextKey.ChooseMatchScoring to "Choose how this match affects your results.", TextKey.CasualMatch to "Casual match",
    TextKey.CasualMatchDescription to "Practise your skills without affecting Elo", TextKey.RankedMatch to "Ranked match",
    TextKey.RankedMatchDescription to "Wins and losses change your Elo", TextKey.ConnectionDisconnected to "Not connected to the server",
    TextKey.ConnectionConnecting to "Connecting to the server…", TextKey.ConnectionAuthenticating to "Authenticating account…",
    TextKey.ConnectionConnected to "Connected", TextKey.ConnectionReconnecting to "Connection lost. Retrying…"
) + englishCorePlayTexts

internal val vietnameseGameplayTexts = mapOf(
    TextKey.ModeClassicTitle to "Cổ điển", TextKey.ModeClassicDescription to "Tìm các số từ 1 đến 50",
    TextKey.ModeRandomTitle to "Ngẫu nhiên", TextKey.ModeRandomDescription to "Mục tiêu xuất hiện theo thứ tự bất ngờ",
    TextKey.ModeTimeBonusTitle to "Thưởng thời gian", TextKey.ModeTimeBonusDescription to "Đúng +2 giây, sai -3 giây",
    TextKey.ModeSpeedUpTitle to "Tăng tốc", TextKey.ModeSpeedUpDescription to "Thời gian cho mỗi mục tiêu giảm dần",
    TextKey.ModeSurvivalTitle to "Sinh tồn", TextKey.ModeSurvivalDescription to "Hết 3 mạng khi bấm sai sẽ thua",
    TextKey.ModeComboTitle to "Combo", TextKey.ModeComboDescription to "Chuỗi bấm đúng liên tục nhân điểm",
    TextKey.ModeTimeAttackTitle to "Đua 60 giây", TextKey.ModeTimeAttackDescription to "Chế độ cũ: ghi nhiều điểm trong 60 giây",
    TextKey.ModeTeamTitle to "Đồng đội 2v2", TextKey.ModeTeamDescription to "Hai đội thi đấu cùng một bảng số",
    TextKey.ChooseMatchType to "Chọn loại trận", TextKey.ChooseRankedMode to "Chọn chế độ xếp hạng",
    TextKey.ChooseCasualMode to "Chọn chế độ đấu thường", TextKey.GuestMode to "CHẾ ĐỘ KHÁCH",
    TextKey.Ranked to "Xếp hạng", TextKey.Casual to "Đấu thường", TextKey.RegisterToPlayOnline to "Đăng ký tài khoản để ghép đối thủ trực tuyến.",
    TextKey.CasualOrRankedDescription to "Đấu thường để luyện tập hoặc xếp hạng để tăng Elo.",
    TextKey.LoginToPlay to "ĐĂNG NHẬP ĐỂ CHƠI", TextKey.PlayNow to "CHƠI NGAY", TextKey.Explore to "Khám phá",
    TextKey.FeaturesAndActivities to "Tính năng và hoạt động", TextKey.Tournament to "Đấu giải",
    TextKey.RegisterToJoin to "Đăng ký để tham gia", TextKey.TournamentDescription to "Giải riêng 4, 8 hoặc 16 người loại trực tiếp",
    TextKey.Shop to "Cửa hàng", TextKey.ShopDiscoveryDescription to "Mở khóa mặt số, bàn số và vật phẩm mới",
    TextKey.OfflinePracticeTitle to "Luyện tập offline", TextKey.OfflinePracticeDescription to "Rèn tốc độ với bàn 50 số, không ảnh hưởng Elo",
    TextKey.SaveProgress to "LƯU TIẾN TRÌNH", TextKey.SaveProgressDescription to "Tạo tài khoản để giữ Elo, lịch sử và bạn bè trên Android/iOS.",
    TextKey.ExitGuestMode to "THOÁT CHẾ ĐỘ KHÁCH", TextKey.ChooseCompetitionType to "Chọn cách thi đấu",
    TextKey.CreateRoom to "Tạo phòng", TextKey.JoinRoom to "Tham gia", TextKey.Friends to "Bạn bè",
    TextKey.RegisterToAddFriends to "Đăng ký để kết bạn", TextKey.OnlineFriends to "{count} người trực tuyến",
    TextKey.YourRank to "Bạn đang hạng #{rank}", TextKey.ViewEloLeaderboard to "Xem bảng Elo",
    TextKey.Level to "Cấp {level}", TextKey.PlacementPending to "Đang phân hạng",
    TextKey.DailyCheckInSevenDays to "Điểm danh 7 ngày", TextKey.CheckInStreak to "Chuỗi {count} ngày",
    TextKey.DayLabel to "Ngày", TextKey.ClaimDayReward to "NHẬN THƯỞNG NGÀY {day}", TextKey.Home to "Trang chủ",
    TextKey.HarderModesUnlock to "Chế độ khó hơn sẽ được mở khóa theo cấp độ.", TextKey.UnlockAtLevel to "Mở khóa ở cấp {level}",
    TextKey.ChooseMatchScoring to "Chọn cách trận đấu được tính kết quả.", TextKey.CasualMatch to "Đấu thường",
    TextKey.CasualMatchDescription to "Luyện kỹ năng, không ảnh hưởng Elo", TextKey.RankedMatch to "Đấu xếp hạng",
    TextKey.RankedMatchDescription to "Thắng hoặc thua sẽ thay đổi Elo", TextKey.ConnectionDisconnected to "Chưa kết nối máy chủ",
    TextKey.ConnectionConnecting to "Đang kết nối máy chủ…", TextKey.ConnectionAuthenticating to "Đang xác thực tài khoản…",
    TextKey.ConnectionConnected to "Đã kết nối", TextKey.ConnectionReconnecting to "Mất kết nối, đang thử lại…"
) + vietnameseCorePlayTexts

internal val germanGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Klassisch", TextKey.ModeClassicDescription to "Finde die Zahlen von 1 bis 50",
    TextKey.ModeRandomTitle to "Zufällig", TextKey.ModeRandomDescription to "Ziele erscheinen in unerwarteter Reihenfolge",
    TextKey.ModeTimeBonusTitle to "Zeitbonus", TextKey.ModeTimeBonusDescription to "Richtig +2 Sekunden, falsch -3 Sekunden",
    TextKey.ModeSpeedUpTitle to "Beschleunigung", TextKey.ModeSpeedUpDescription to "Die Zeit pro Ziel wird kürzer",
    TextKey.ModeSurvivalTitle to "Überleben", TextKey.ModeSurvivalDescription to "Nach 3 Fehlern ist das Spiel vorbei",
    TextKey.ModeComboDescription to "Mehrere richtige Treffer erhöhen die Punkte",
    TextKey.ModeTimeAttackTitle to "60-Sekunden-Rennen", TextKey.ModeTimeAttackDescription to "Klassischer Modus: möglichst viele Punkte in 60 Sekunden",
    TextKey.ModeTeamTitle to "Team 2v2", TextKey.ModeTeamDescription to "Zwei Teams spielen auf demselben Zahlenfeld",
    TextKey.ChooseMatchType to "Spielart wählen", TextKey.ChooseRankedMode to "Ranglistenmodus wählen",
    TextKey.ChooseCasualMode to "Freien Modus wählen", TextKey.GuestMode to "GASTMODUS", TextKey.Ranked to "Rangliste",
    TextKey.Casual to "Freies Spiel", TextKey.RegisterToPlayOnline to "Erstelle ein Konto, um Online-Gegner zu finden.",
    TextKey.CasualOrRankedDescription to "Übe frei oder steigere dein Elo in der Rangliste.", TextKey.LoginToPlay to "ZUM SPIELEN ANMELDEN",
    TextKey.PlayNow to "JETZT SPIELEN", TextKey.Explore to "Entdecken", TextKey.FeaturesAndActivities to "Funktionen und Aktivitäten",
    TextKey.Tournament to "Turnier", TextKey.RegisterToJoin to "Zum Mitmachen Konto erstellen",
    TextKey.TournamentDescription to "Private K.-o.-Turniere für 4, 8 oder 16 Spieler", TextKey.Shop to "Shop",
    TextKey.ShopDiscoveryDescription to "Zahlenflächen, Spielfelder und neue Gegenstände freischalten",
    TextKey.OfflinePracticeTitle to "Offline-Training", TextKey.OfflinePracticeDescription to "Mit 50 Zahlen trainieren, ohne Elo zu beeinflussen",
    TextKey.SaveProgress to "FORTSCHRITT SPEICHERN", TextKey.SaveProgressDescription to "Erstelle ein Konto, um Elo, Verlauf und Freunde auf Android/iOS zu behalten.",
    TextKey.ExitGuestMode to "GASTMODUS BEENDEN", TextKey.ChooseCompetitionType to "Wettkampfart wählen",
    TextKey.CreateRoom to "Raum erstellen", TextKey.JoinRoom to "Raum beitreten", TextKey.Friends to "Freunde",
    TextKey.RegisterToAddFriends to "Konto erstellen, um Freunde hinzuzufügen", TextKey.OnlineFriends to "{count} Freunde online",
    TextKey.YourRank to "Dein Rang ist #{rank}", TextKey.ViewEloLeaderboard to "Elo-Rangliste anzeigen", TextKey.Level to "Level {level}",
    TextKey.PlacementPending to "Einstufung läuft", TextKey.DailyCheckInSevenDays to "7-Tage-Check-in",
    TextKey.CheckInStreak to "Serie: {count} Tage", TextKey.DayLabel to "Tag", TextKey.ClaimDayReward to "BELOHNUNG FÜR TAG {day} HOLEN",
    TextKey.Home to "Start", TextKey.HarderModesUnlock to "Schwierigere Modi werden mit höheren Levels freigeschaltet.",
    TextKey.UnlockAtLevel to "Ab Level {level}", TextKey.ChooseMatchScoring to "Wähle, wie das Spiel gewertet wird.",
    TextKey.CasualMatch to "Freies Spiel", TextKey.CasualMatchDescription to "Üben ohne Einfluss auf Elo",
    TextKey.RankedMatch to "Ranglistenspiel", TextKey.RankedMatchDescription to "Siege und Niederlagen verändern dein Elo",
    TextKey.ConnectionDisconnected to "Nicht mit dem Server verbunden", TextKey.ConnectionConnecting to "Verbindung zum Server…",
    TextKey.ConnectionAuthenticating to "Konto wird geprüft…", TextKey.ConnectionConnected to "Verbunden",
    TextKey.ConnectionReconnecting to "Verbindung verloren. Neuer Versuch…"
) + germanCorePlayTexts

internal val japaneseGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "クラシック", TextKey.ModeClassicDescription to "1から50までの数字を探す",
    TextKey.ModeRandomTitle to "ランダム", TextKey.ModeRandomDescription to "次の数字がランダムに表示されます",
    TextKey.ModeTimeBonusTitle to "タイムボーナス", TextKey.ModeTimeBonusDescription to "正解で+2秒、不正解で-3秒",
    TextKey.ModeSpeedUpTitle to "スピードアップ", TextKey.ModeSpeedUpDescription to "数字ごとの制限時間が徐々に短くなります",
    TextKey.ModeSurvivalTitle to "サバイバル", TextKey.ModeSurvivalDescription to "3回間違えると敗北",
    TextKey.ModeComboDescription to "連続正解でスコア倍率アップ", TextKey.ModeTimeAttackTitle to "60秒ラッシュ",
    TextKey.ModeTimeAttackDescription to "旧モード：60秒で高得点を目指す", TextKey.ModeTeamTitle to "チーム2v2",
    TextKey.ModeTeamDescription to "2チームが同じ数字ボードで対戦", TextKey.ChooseMatchType to "対戦タイプを選択",
    TextKey.ChooseRankedMode to "ランク戦モードを選択", TextKey.ChooseCasualMode to "通常戦モードを選択",
    TextKey.GuestMode to "ゲストモード", TextKey.Ranked to "ランク戦", TextKey.Casual to "通常戦",
    TextKey.RegisterToPlayOnline to "アカウントを作成してオンライン対戦を始めましょう。",
    TextKey.CasualOrRankedDescription to "通常戦で練習、ランク戦でEloを上げよう。", TextKey.LoginToPlay to "ログインしてプレイ",
    TextKey.PlayNow to "今すぐプレイ", TextKey.Explore to "見つける", TextKey.FeaturesAndActivities to "機能とアクティビティ",
    TextKey.Tournament to "トーナメント", TextKey.RegisterToJoin to "参加にはアカウントが必要です",
    TextKey.TournamentDescription to "4・8・16人のプライベート勝ち抜き戦", TextKey.Shop to "ショップ",
    TextKey.ShopDiscoveryDescription to "数字面、ボード、新アイテムをアンロック", TextKey.OfflinePracticeTitle to "オフライン練習",
    TextKey.OfflinePracticeDescription to "Eloに影響せず50数字ボードで練習", TextKey.SaveProgress to "進行を保存",
    TextKey.SaveProgressDescription to "アカウントを作成してElo、履歴、フレンドをAndroid/iOS間で保存。",
    TextKey.ExitGuestMode to "ゲストモードを終了", TextKey.ChooseCompetitionType to "対戦方法を選択", TextKey.CreateRoom to "ルーム作成",
    TextKey.JoinRoom to "ルーム参加", TextKey.Friends to "フレンド", TextKey.RegisterToAddFriends to "フレンド追加にはアカウントが必要です",
    TextKey.OnlineFriends to "オンラインのフレンド：{count}人", TextKey.YourRank to "現在の順位：#{rank}",
    TextKey.ViewEloLeaderboard to "Eloランキングを見る", TextKey.Level to "レベル {level}", TextKey.PlacementPending to "順位決定中",
    TextKey.DailyCheckInSevenDays to "7日間チェックイン", TextKey.CheckInStreak to "{count}日連続",
    TextKey.DayLabel to "日", TextKey.ClaimDayReward to "{day}日目の報酬を受け取る", TextKey.Home to "ホーム",
    TextKey.HarderModesUnlock to "レベルアップすると高難度モードが解放されます。", TextKey.UnlockAtLevel to "レベル{level}で解放",
    TextKey.ChooseMatchScoring to "対戦結果への反映方法を選択。", TextKey.CasualMatch to "通常戦",
    TextKey.CasualMatchDescription to "Eloに影響せず練習", TextKey.RankedMatch to "ランク戦",
    TextKey.RankedMatchDescription to "勝敗でEloが変動", TextKey.ConnectionDisconnected to "サーバーに未接続",
    TextKey.ConnectionConnecting to "サーバーに接続中…", TextKey.ConnectionAuthenticating to "アカウント確認中…",
    TextKey.ConnectionConnected to "接続済み", TextKey.ConnectionReconnecting to "接続が切れました。再試行中…"
) + japaneseCorePlayTexts

internal val simplifiedChineseGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "经典", TextKey.ModeClassicDescription to "按顺序寻找1到50",
    TextKey.ModeRandomTitle to "随机", TextKey.ModeRandomDescription to "目标数字随机出现", TextKey.ModeTimeBonusTitle to "时间奖励",
    TextKey.ModeTimeBonusDescription to "正确+2秒，错误-3秒", TextKey.ModeSpeedUpTitle to "加速",
    TextKey.ModeSpeedUpDescription to "每个目标的时间逐渐缩短", TextKey.ModeSurvivalTitle to "生存",
    TextKey.ModeSurvivalDescription to "点错3次即失败", TextKey.ModeComboDescription to "连续答对可获得分数加成",
    TextKey.ModeTimeAttackTitle to "60秒冲刺", TextKey.ModeTimeAttackDescription to "经典模式：60秒内尽量得分",
    TextKey.ModeTeamTitle to "2v2组队", TextKey.ModeTeamDescription to "两队在同一数字棋盘上竞技",
    TextKey.ChooseMatchType to "选择比赛类型", TextKey.ChooseRankedMode to "选择排位模式", TextKey.ChooseCasualMode to "选择普通模式",
    TextKey.GuestMode to "游客模式", TextKey.Ranked to "排位", TextKey.Casual to "普通",
    TextKey.RegisterToPlayOnline to "创建账号后即可匹配在线对手。", TextKey.CasualOrRankedDescription to "普通赛练习，排位赛提升Elo。",
    TextKey.LoginToPlay to "登录后开始", TextKey.PlayNow to "立即开始", TextKey.Explore to "探索", TextKey.FeaturesAndActivities to "功能与活动",
    TextKey.Tournament to "锦标赛", TextKey.RegisterToJoin to "创建账号后参加", TextKey.TournamentDescription to "4、8或16人的私人淘汰赛",
    TextKey.Shop to "商店", TextKey.ShopDiscoveryDescription to "解锁数字面、棋盘和新物品", TextKey.OfflinePracticeTitle to "离线练习",
    TextKey.OfflinePracticeDescription to "使用50数字棋盘练习，不影响Elo", TextKey.SaveProgress to "保存进度",
    TextKey.SaveProgressDescription to "创建账号，在Android/iOS上保留Elo、历史和好友。", TextKey.ExitGuestMode to "退出游客模式",
    TextKey.ChooseCompetitionType to "选择竞技方式", TextKey.CreateRoom to "创建房间", TextKey.JoinRoom to "加入房间", TextKey.Friends to "好友",
    TextKey.RegisterToAddFriends to "创建账号后添加好友", TextKey.OnlineFriends to "{count}位好友在线", TextKey.YourRank to "你的排名是#{rank}",
    TextKey.ViewEloLeaderboard to "查看Elo排行榜", TextKey.Level to "等级 {level}", TextKey.PlacementPending to "定位中",
    TextKey.DailyCheckInSevenDays to "7日签到", TextKey.CheckInStreak to "连续{count}天", TextKey.DayLabel to "第",
    TextKey.ClaimDayReward to "领取第{day}天奖励", TextKey.Home to "主页", TextKey.HarderModesUnlock to "升级后可解锁更难的模式。",
    TextKey.UnlockAtLevel to "{level}级解锁", TextKey.ChooseMatchScoring to "选择比赛如何计入结果。", TextKey.CasualMatch to "普通赛",
    TextKey.CasualMatchDescription to "练习技巧，不影响Elo", TextKey.RankedMatch to "排位赛", TextKey.RankedMatchDescription to "胜负会改变Elo",
    TextKey.ConnectionDisconnected to "未连接服务器", TextKey.ConnectionConnecting to "正在连接服务器…",
    TextKey.ConnectionAuthenticating to "正在验证账号…", TextKey.ConnectionConnected to "已连接", TextKey.ConnectionReconnecting to "连接中断，正在重试…"
) + simplifiedChineseCorePlayTexts

internal val koreanGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "클래식", TextKey.ModeClassicDescription to "1부터 50까지 숫자 찾기", TextKey.ModeRandomTitle to "랜덤",
    TextKey.ModeRandomDescription to "목표 숫자가 무작위로 표시됩니다", TextKey.ModeTimeBonusTitle to "시간 보너스",
    TextKey.ModeTimeBonusDescription to "정답 +2초, 오답 -3초", TextKey.ModeSpeedUpTitle to "가속",
    TextKey.ModeSpeedUpDescription to "목표 제한 시간이 점점 줄어듭니다", TextKey.ModeSurvivalTitle to "서바이벌",
    TextKey.ModeSurvivalDescription to "3번 틀리면 패배", TextKey.ModeComboDescription to "연속 정답으로 점수 배율 증가",
    TextKey.ModeTimeAttackTitle to "60초 러시", TextKey.ModeTimeAttackDescription to "기존 모드: 60초 동안 최고 점수 도전",
    TextKey.ModeTeamTitle to "팀 2v2", TextKey.ModeTeamDescription to "두 팀이 같은 숫자판에서 대결",
    TextKey.ChooseMatchType to "경기 유형 선택", TextKey.ChooseRankedMode to "랭크 모드 선택", TextKey.ChooseCasualMode to "일반 모드 선택",
    TextKey.GuestMode to "게스트 모드", TextKey.Ranked to "랭크", TextKey.Casual to "일반전",
    TextKey.RegisterToPlayOnline to "계정을 만들고 온라인 상대를 찾아보세요.", TextKey.CasualOrRankedDescription to "일반전으로 연습하거나 랭크전으로 Elo를 올리세요.",
    TextKey.LoginToPlay to "로그인하고 플레이", TextKey.PlayNow to "지금 플레이", TextKey.Explore to "둘러보기",
    TextKey.FeaturesAndActivities to "기능 및 활동", TextKey.Tournament to "토너먼트", TextKey.RegisterToJoin to "계정을 만들고 참가",
    TextKey.TournamentDescription to "4·8·16인 비공개 토너먼트", TextKey.Shop to "상점", TextKey.ShopDiscoveryDescription to "숫자 앞면, 보드와 새 아이템 잠금 해제",
    TextKey.OfflinePracticeTitle to "오프라인 연습", TextKey.OfflinePracticeDescription to "Elo 영향 없이 50 숫자판 훈련",
    TextKey.SaveProgress to "진행 저장", TextKey.SaveProgressDescription to "계정을 만들어 Android/iOS에서 Elo, 기록과 친구를 보관하세요.",
    TextKey.ExitGuestMode to "게스트 모드 종료", TextKey.ChooseCompetitionType to "경기 방식 선택", TextKey.CreateRoom to "방 만들기",
    TextKey.JoinRoom to "방 참가", TextKey.Friends to "친구", TextKey.RegisterToAddFriends to "계정을 만들고 친구 추가",
    TextKey.OnlineFriends to "온라인 친구 {count}명", TextKey.YourRank to "현재 순위 #{rank}", TextKey.ViewEloLeaderboard to "Elo 순위 보기",
    TextKey.Level to "레벨 {level}", TextKey.PlacementPending to "배치 진행 중", TextKey.DailyCheckInSevenDays to "7일 출석",
    TextKey.CheckInStreak to "{count}일 연속", TextKey.DayLabel to "일", TextKey.ClaimDayReward to "{day}일차 보상 받기", TextKey.Home to "홈",
    TextKey.HarderModesUnlock to "레벨이 오르면 더 어려운 모드가 열립니다.", TextKey.UnlockAtLevel to "레벨 {level}에서 해제",
    TextKey.ChooseMatchScoring to "경기 결과 반영 방식을 선택하세요.", TextKey.CasualMatch to "일반전",
    TextKey.CasualMatchDescription to "Elo 영향 없이 연습", TextKey.RankedMatch to "랭크전", TextKey.RankedMatchDescription to "승패에 따라 Elo 변동",
    TextKey.ConnectionDisconnected to "서버에 연결되지 않음", TextKey.ConnectionConnecting to "서버 연결 중…",
    TextKey.ConnectionAuthenticating to "계정 인증 중…", TextKey.ConnectionConnected to "연결됨", TextKey.ConnectionReconnecting to "연결이 끊겼습니다. 재시도 중…"
) + koreanCorePlayTexts

internal val spanishGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Clásico", TextKey.ModeClassicDescription to "Encuentra los números del 1 al 50", TextKey.ModeRandomTitle to "Aleatorio",
    TextKey.ModeRandomDescription to "Los objetivos aparecen en orden inesperado", TextKey.ModeTimeBonusTitle to "Tiempo extra",
    TextKey.ModeTimeBonusDescription to "Acierto +2 segundos, error -3 segundos", TextKey.ModeSpeedUpTitle to "Aceleración",
    TextKey.ModeSpeedUpDescription to "El tiempo por objetivo disminuye", TextKey.ModeSurvivalTitle to "Supervivencia",
    TextKey.ModeSurvivalDescription to "Pierdes tras 3 errores", TextKey.ModeComboDescription to "Los aciertos seguidos multiplican la puntuación",
    TextKey.ModeTimeAttackTitle to "Reto de 60 segundos", TextKey.ModeTimeAttackDescription to "Modo clásico: consigue puntos durante 60 segundos",
    TextKey.ModeTeamTitle to "Equipo 2v2", TextKey.ModeTeamDescription to "Dos equipos compiten en el mismo tablero",
    TextKey.ChooseMatchType to "Elige el tipo de partida", TextKey.ChooseRankedMode to "Elige modo clasificatorio",
    TextKey.ChooseCasualMode to "Elige modo casual", TextKey.GuestMode to "MODO INVITADO", TextKey.Ranked to "Clasificatoria", TextKey.Casual to "Casual",
    TextKey.RegisterToPlayOnline to "Crea una cuenta para buscar rivales en línea.", TextKey.CasualOrRankedDescription to "Practica en casual o gana Elo en clasificatoria.",
    TextKey.LoginToPlay to "INICIA SESIÓN PARA JUGAR", TextKey.PlayNow to "JUGAR AHORA", TextKey.Explore to "Explorar",
    TextKey.FeaturesAndActivities to "Funciones y actividades", TextKey.Tournament to "Torneo", TextKey.RegisterToJoin to "Crea una cuenta para participar",
    TextKey.TournamentDescription to "Torneos privados de eliminación para 4, 8 o 16 jugadores", TextKey.Shop to "Tienda",
    TextKey.ShopDiscoveryDescription to "Desbloquea caras numéricas, tableros y objetos", TextKey.OfflinePracticeTitle to "Práctica sin conexión",
    TextKey.OfflinePracticeDescription to "Entrena con 50 números sin afectar al Elo", TextKey.SaveProgress to "GUARDAR PROGRESO",
    TextKey.SaveProgressDescription to "Crea una cuenta para guardar Elo, historial y amigos en Android/iOS.", TextKey.ExitGuestMode to "SALIR DEL MODO INVITADO",
    TextKey.ChooseCompetitionType to "Elige cómo competir", TextKey.CreateRoom to "Crear sala", TextKey.JoinRoom to "Unirse a sala",
    TextKey.Friends to "Amigos", TextKey.RegisterToAddFriends to "Crea una cuenta para añadir amigos", TextKey.OnlineFriends to "{count} amigos conectados",
    TextKey.YourRank to "Tu puesto es #{rank}", TextKey.ViewEloLeaderboard to "Ver clasificación Elo", TextKey.Level to "Nivel {level}",
    TextKey.PlacementPending to "Clasificación pendiente", TextKey.DailyCheckInSevenDays to "Registro de 7 días", TextKey.CheckInStreak to "Racha de {count} días",
    TextKey.DayLabel to "Día", TextKey.ClaimDayReward to "RECLAMAR RECOMPENSA DEL DÍA {day}", TextKey.Home to "Inicio",
    TextKey.HarderModesUnlock to "Los modos difíciles se desbloquean al subir de nivel.", TextKey.UnlockAtLevel to "Se desbloquea en nivel {level}",
    TextKey.ChooseMatchScoring to "Elige cómo cuenta esta partida.", TextKey.CasualMatch to "Partida casual",
    TextKey.CasualMatchDescription to "Practica sin afectar al Elo", TextKey.RankedMatch to "Partida clasificatoria",
    TextKey.RankedMatchDescription to "Las victorias y derrotas cambian tu Elo", TextKey.ConnectionDisconnected to "Sin conexión al servidor",
    TextKey.ConnectionConnecting to "Conectando al servidor…", TextKey.ConnectionAuthenticating to "Autenticando cuenta…",
    TextKey.ConnectionConnected to "Conectado", TextKey.ConnectionReconnecting to "Conexión perdida. Reintentando…"
) + spanishCorePlayTexts

internal val brazilianPortugueseGameplayTexts = spanishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Clássico", TextKey.ModeClassicDescription to "Encontre os números de 1 a 50", TextKey.ModeRandomTitle to "Aleatório",
    TextKey.ModeRandomDescription to "Os alvos aparecem em ordem inesperada", TextKey.ModeTimeBonusTitle to "Bônus de tempo",
    TextKey.ModeTimeBonusDescription to "Acerto +2 segundos, erro -3 segundos", TextKey.ModeSpeedUpTitle to "Aceleração",
    TextKey.ModeSpeedUpDescription to "O tempo por alvo diminui", TextKey.ModeSurvivalTitle to "Sobrevivência",
    TextKey.ModeSurvivalDescription to "Você perde após 3 erros", TextKey.ModeComboDescription to "Acertos seguidos multiplicam a pontuação",
    TextKey.ModeTimeAttackTitle to "Corrida de 60 segundos", TextKey.ModeTimeAttackDescription to "Modo clássico: marque pontos por 60 segundos",
    TextKey.ModeTeamTitle to "Equipe 2v2", TextKey.ModeTeamDescription to "Duas equipes competem no mesmo tabuleiro",
    TextKey.ChooseMatchType to "Escolha o tipo de partida", TextKey.ChooseRankedMode to "Escolha o modo ranqueado",
    TextKey.ChooseCasualMode to "Escolha o modo casual", TextKey.GuestMode to "MODO CONVIDADO", TextKey.Ranked to "Ranqueada", TextKey.Casual to "Casual",
    TextKey.RegisterToPlayOnline to "Crie uma conta para encontrar adversários online.", TextKey.CasualOrRankedDescription to "Pratique no casual ou ganhe Elo no ranqueado.",
    TextKey.LoginToPlay to "ENTRE PARA JOGAR", TextKey.PlayNow to "JOGAR AGORA", TextKey.Explore to "Explorar",
    TextKey.FeaturesAndActivities to "Recursos e atividades", TextKey.Tournament to "Torneio", TextKey.RegisterToJoin to "Crie uma conta para participar",
    TextKey.TournamentDescription to "Torneios privados eliminatórios para 4, 8 ou 16 jogadores", TextKey.Shop to "Loja",
    TextKey.ShopDiscoveryDescription to "Desbloqueie faces numéricas, tabuleiros e itens", TextKey.OfflinePracticeTitle to "Treino offline",
    TextKey.OfflinePracticeDescription to "Treine com 50 números sem afetar o Elo", TextKey.SaveProgress to "SALVAR PROGRESSO",
    TextKey.SaveProgressDescription to "Crie uma conta para salvar Elo, histórico e amigos no Android/iOS.", TextKey.ExitGuestMode to "SAIR DO MODO CONVIDADO",
    TextKey.ChooseCompetitionType to "Escolha como competir", TextKey.CreateRoom to "Criar sala", TextKey.JoinRoom to "Entrar na sala",
    TextKey.Friends to "Amigos", TextKey.RegisterToAddFriends to "Crie uma conta para adicionar amigos", TextKey.OnlineFriends to "{count} amigos online",
    TextKey.YourRank to "Sua posição é #{rank}", TextKey.ViewEloLeaderboard to "Ver ranking Elo", TextKey.Level to "Nível {level}",
    TextKey.PlacementPending to "Classificação pendente", TextKey.DailyCheckInSevenDays to "Check-in de 7 dias", TextKey.CheckInStreak to "Sequência de {count} dias",
    TextKey.DayLabel to "Dia", TextKey.ClaimDayReward to "RESGATAR RECOMPENSA DO DIA {day}", TextKey.Home to "Início",
    TextKey.HarderModesUnlock to "Modos mais difíceis são liberados ao subir de nível.", TextKey.UnlockAtLevel to "Libera no nível {level}",
    TextKey.ChooseMatchScoring to "Escolha como esta partida conta.", TextKey.CasualMatch to "Partida casual",
    TextKey.CasualMatchDescription to "Pratique sem afetar o Elo", TextKey.RankedMatch to "Partida ranqueada",
    TextKey.RankedMatchDescription to "Vitórias e derrotas alteram o Elo", TextKey.ConnectionDisconnected to "Sem conexão com o servidor",
    TextKey.ConnectionConnecting to "Conectando ao servidor…", TextKey.ConnectionAuthenticating to "Autenticando conta…",
    TextKey.ConnectionConnected to "Conectado", TextKey.ConnectionReconnecting to "Conexão perdida. Tentando novamente…"
) + brazilianPortugueseCorePlayTexts

internal val frenchGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Classique", TextKey.ModeClassicDescription to "Trouvez les nombres de 1 à 50", TextKey.ModeRandomTitle to "Aléatoire",
    TextKey.ModeRandomDescription to "Les cibles apparaissent dans un ordre inattendu", TextKey.ModeTimeBonusTitle to "Bonus de temps",
    TextKey.ModeTimeBonusDescription to "Bonne réponse +2 secondes, erreur -3 secondes", TextKey.ModeSpeedUpTitle to "Accélération",
    TextKey.ModeSpeedUpDescription to "Le temps par cible diminue", TextKey.ModeSurvivalTitle to "Survie",
    TextKey.ModeSurvivalDescription to "Vous perdez après 3 erreurs", TextKey.ModeComboDescription to "Les bonnes réponses consécutives multiplient le score",
    TextKey.ModeTimeAttackTitle to "Rush de 60 secondes", TextKey.ModeTimeAttackDescription to "Mode classique : marquez un maximum en 60 secondes",
    TextKey.ModeTeamTitle to "Équipe 2v2", TextKey.ModeTeamDescription to "Deux équipes jouent sur la même grille",
    TextKey.ChooseMatchType to "Choisir le type de partie", TextKey.ChooseRankedMode to "Choisir le mode classé",
    TextKey.ChooseCasualMode to "Choisir le mode amical", TextKey.GuestMode to "MODE INVITÉ", TextKey.Ranked to "Classé", TextKey.Casual to "Amical",
    TextKey.RegisterToPlayOnline to "Créez un compte pour trouver des adversaires en ligne.", TextKey.CasualOrRankedDescription to "Entraînez-vous en amical ou gagnez de l'Elo en classé.",
    TextKey.LoginToPlay to "SE CONNECTER POUR JOUER", TextKey.PlayNow to "JOUER", TextKey.Explore to "Explorer",
    TextKey.FeaturesAndActivities to "Fonctions et activités", TextKey.Tournament to "Tournoi", TextKey.RegisterToJoin to "Créer un compte pour participer",
    TextKey.TournamentDescription to "Tournois privés à élimination pour 4, 8 ou 16 joueurs", TextKey.Shop to "Boutique",
    TextKey.ShopDiscoveryDescription to "Débloquez des faces numériques, grilles et objets", TextKey.OfflinePracticeTitle to "Entraînement hors ligne",
    TextKey.OfflinePracticeDescription to "Entraînez-vous sur 50 nombres sans modifier l'Elo", TextKey.SaveProgress to "SAUVEGARDER LA PROGRESSION",
    TextKey.SaveProgressDescription to "Créez un compte pour garder Elo, historique et amis sur Android/iOS.", TextKey.ExitGuestMode to "QUITTER LE MODE INVITÉ",
    TextKey.ChooseCompetitionType to "Choisir comment jouer", TextKey.CreateRoom to "Créer une salle", TextKey.JoinRoom to "Rejoindre une salle",
    TextKey.Friends to "Amis", TextKey.RegisterToAddFriends to "Créez un compte pour ajouter des amis", TextKey.OnlineFriends to "{count} amis en ligne",
    TextKey.YourRank to "Votre rang est #{rank}", TextKey.ViewEloLeaderboard to "Voir le classement Elo", TextKey.Level to "Niveau {level}",
    TextKey.PlacementPending to "Classement en cours", TextKey.DailyCheckInSevenDays to "Connexion sur 7 jours", TextKey.CheckInStreak to "Série de {count} jours",
    TextKey.DayLabel to "Jour", TextKey.ClaimDayReward to "RÉCUPÉRER LA RÉCOMPENSE DU JOUR {day}", TextKey.Home to "Accueil",
    TextKey.HarderModesUnlock to "Les modes difficiles se débloquent avec les niveaux.", TextKey.UnlockAtLevel to "Débloqué au niveau {level}",
    TextKey.ChooseMatchScoring to "Choisissez comment cette partie est comptée.", TextKey.CasualMatch to "Partie amicale",
    TextKey.CasualMatchDescription to "S'entraîner sans modifier l'Elo", TextKey.RankedMatch to "Partie classée",
    TextKey.RankedMatchDescription to "Les victoires et défaites modifient l'Elo", TextKey.ConnectionDisconnected to "Non connecté au serveur",
    TextKey.ConnectionConnecting to "Connexion au serveur…", TextKey.ConnectionAuthenticating to "Authentification du compte…",
    TextKey.ConnectionConnected to "Connecté", TextKey.ConnectionReconnecting to "Connexion perdue. Nouvelle tentative…"
) + frenchCorePlayTexts

internal val indonesianGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Klasik", TextKey.ModeClassicDescription to "Temukan angka 1 sampai 50", TextKey.ModeRandomTitle to "Acak",
    TextKey.ModeRandomDescription to "Target muncul dalam urutan tak terduga", TextKey.ModeTimeBonusTitle to "Bonus waktu",
    TextKey.ModeTimeBonusDescription to "Benar +2 detik, salah -3 detik", TextKey.ModeSpeedUpTitle to "Percepat",
    TextKey.ModeSpeedUpDescription to "Waktu tiap target makin singkat", TextKey.ModeSurvivalTitle to "Bertahan",
    TextKey.ModeSurvivalDescription to "Kalah setelah 3 kali salah", TextKey.ModeComboDescription to "Jawaban benar beruntun melipatgandakan skor",
    TextKey.ModeTimeAttackTitle to "Kejar 60 detik", TextKey.ModeTimeAttackDescription to "Mode lama: raih skor sebanyak mungkin dalam 60 detik",
    TextKey.ModeTeamTitle to "Tim 2v2", TextKey.ModeTeamDescription to "Dua tim bermain di papan angka yang sama",
    TextKey.ChooseMatchType to "Pilih jenis pertandingan", TextKey.ChooseRankedMode to "Pilih mode peringkat",
    TextKey.ChooseCasualMode to "Pilih mode kasual", TextKey.GuestMode to "MODE TAMU", TextKey.Ranked to "Peringkat", TextKey.Casual to "Kasual",
    TextKey.RegisterToPlayOnline to "Buat akun untuk mencari lawan online.", TextKey.CasualOrRankedDescription to "Berlatih di kasual atau naikkan Elo di peringkat.",
    TextKey.LoginToPlay to "MASUK UNTUK BERMAIN", TextKey.PlayNow to "MAIN SEKARANG", TextKey.Explore to "Jelajahi",
    TextKey.FeaturesAndActivities to "Fitur dan aktivitas", TextKey.Tournament to "Turnamen", TextKey.RegisterToJoin to "Buat akun untuk ikut",
    TextKey.TournamentDescription to "Turnamen privat sistem gugur 4, 8, atau 16 pemain", TextKey.Shop to "Toko",
    TextKey.ShopDiscoveryDescription to "Buka muka angka, papan, dan item baru", TextKey.OfflinePracticeTitle to "Latihan offline",
    TextKey.OfflinePracticeDescription to "Berlatih dengan 50 angka tanpa memengaruhi Elo", TextKey.SaveProgress to "SIMPAN PROGRES",
    TextKey.SaveProgressDescription to "Buat akun untuk menyimpan Elo, riwayat, dan teman di Android/iOS.", TextKey.ExitGuestMode to "KELUAR MODE TAMU",
    TextKey.ChooseCompetitionType to "Pilih cara bertanding", TextKey.CreateRoom to "Buat ruang", TextKey.JoinRoom to "Gabung ruang",
    TextKey.Friends to "Teman", TextKey.RegisterToAddFriends to "Buat akun untuk menambah teman", TextKey.OnlineFriends to "{count} teman online",
    TextKey.YourRank to "Peringkatmu #{rank}", TextKey.ViewEloLeaderboard to "Lihat papan Elo", TextKey.Level to "Level {level}",
    TextKey.PlacementPending to "Penempatan berlangsung", TextKey.DailyCheckInSevenDays to "Check-in 7 hari", TextKey.CheckInStreak to "Rangkaian {count} hari",
    TextKey.DayLabel to "Hari", TextKey.ClaimDayReward to "AMBIL HADIAH HARI {day}", TextKey.Home to "Beranda",
    TextKey.HarderModesUnlock to "Mode lebih sulit terbuka saat level naik.", TextKey.UnlockAtLevel to "Terbuka di level {level}",
    TextKey.ChooseMatchScoring to "Pilih cara pertandingan dihitung.", TextKey.CasualMatch to "Pertandingan kasual",
    TextKey.CasualMatchDescription to "Berlatih tanpa memengaruhi Elo", TextKey.RankedMatch to "Pertandingan peringkat",
    TextKey.RankedMatchDescription to "Menang atau kalah mengubah Elo", TextKey.ConnectionDisconnected to "Belum terhubung ke server",
    TextKey.ConnectionConnecting to "Menghubungkan ke server…", TextKey.ConnectionAuthenticating to "Mengautentikasi akun…",
    TextKey.ConnectionConnected to "Terhubung", TextKey.ConnectionReconnecting to "Koneksi terputus. Mencoba lagi…"
) + indonesianCorePlayTexts

internal val thaiGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "คลาสสิก", TextKey.ModeClassicDescription to "ค้นหาตัวเลข 1 ถึง 50", TextKey.ModeRandomTitle to "สุ่ม",
    TextKey.ModeRandomDescription to "เป้าหมายปรากฏแบบไม่เรียงลำดับ", TextKey.ModeTimeBonusTitle to "โบนัสเวลา",
    TextKey.ModeTimeBonusDescription to "ถูก +2 วินาที ผิด -3 วินาที", TextKey.ModeSpeedUpTitle to "เร่งความเร็ว",
    TextKey.ModeSpeedUpDescription to "เวลาของแต่ละเป้าหมายจะลดลง", TextKey.ModeSurvivalTitle to "เอาตัวรอด",
    TextKey.ModeSurvivalDescription to "แพ้เมื่อกดผิด 3 ครั้ง", TextKey.ModeComboDescription to "กดถูกต่อเนื่องเพื่อเพิ่มตัวคูณคะแนน",
    TextKey.ModeTimeAttackTitle to "เร่ง 60 วินาที", TextKey.ModeTimeAttackDescription to "โหมดเดิม: ทำคะแนนให้มากที่สุดใน 60 วินาที",
    TextKey.ModeTeamTitle to "ทีม 2v2", TextKey.ModeTeamDescription to "สองทีมแข่งบนกระดานตัวเลขเดียวกัน",
    TextKey.ChooseMatchType to "เลือกประเภทการแข่งขัน", TextKey.ChooseRankedMode to "เลือกโหมดจัดอันดับ",
    TextKey.ChooseCasualMode to "เลือกโหมดทั่วไป", TextKey.GuestMode to "โหมดผู้เยี่ยมชม", TextKey.Ranked to "จัดอันดับ", TextKey.Casual to "ทั่วไป",
    TextKey.RegisterToPlayOnline to "สร้างบัญชีเพื่อค้นหาคู่แข่งออนไลน์", TextKey.CasualOrRankedDescription to "ฝึกในโหมดทั่วไปหรือเพิ่ม Elo ในโหมดจัดอันดับ",
    TextKey.LoginToPlay to "เข้าสู่ระบบเพื่อเล่น", TextKey.PlayNow to "เล่นเลย", TextKey.Explore to "สำรวจ",
    TextKey.FeaturesAndActivities to "ฟีเจอร์และกิจกรรม", TextKey.Tournament to "ทัวร์นาเมนต์", TextKey.RegisterToJoin to "สร้างบัญชีเพื่อเข้าร่วม",
    TextKey.TournamentDescription to "ทัวร์นาเมนต์ส่วนตัวแบบแพ้คัดออก 4, 8 หรือ 16 คน", TextKey.Shop to "ร้านค้า",
    TextKey.ShopDiscoveryDescription to "ปลดล็อกหน้าตัวเลข กระดาน และไอเทมใหม่", TextKey.OfflinePracticeTitle to "ฝึกออฟไลน์",
    TextKey.OfflinePracticeDescription to "ฝึกกับกระดาน 50 ตัวเลขโดยไม่กระทบ Elo", TextKey.SaveProgress to "บันทึกความคืบหน้า",
    TextKey.SaveProgressDescription to "สร้างบัญชีเพื่อเก็บ Elo ประวัติ และเพื่อนบน Android/iOS", TextKey.ExitGuestMode to "ออกจากโหมดผู้เยี่ยมชม",
    TextKey.ChooseCompetitionType to "เลือกวิธีแข่งขัน", TextKey.CreateRoom to "สร้างห้อง", TextKey.JoinRoom to "เข้าร่วมห้อง",
    TextKey.Friends to "เพื่อน", TextKey.RegisterToAddFriends to "สร้างบัญชีเพื่อเพิ่มเพื่อน", TextKey.OnlineFriends to "เพื่อนออนไลน์ {count} คน",
    TextKey.YourRank to "อันดับของคุณคือ #{rank}", TextKey.ViewEloLeaderboard to "ดูอันดับ Elo", TextKey.Level to "เลเวล {level}",
    TextKey.PlacementPending to "กำลังจัดอันดับ", TextKey.DailyCheckInSevenDays to "เช็กอิน 7 วัน", TextKey.CheckInStreak to "ต่อเนื่อง {count} วัน",
    TextKey.DayLabel to "วัน", TextKey.ClaimDayReward to "รับรางวัลวันที่ {day}", TextKey.Home to "หน้าหลัก",
    TextKey.HarderModesUnlock to "โหมดที่ยากขึ้นจะปลดล็อกเมื่อเลเวลสูงขึ้น", TextKey.UnlockAtLevel to "ปลดล็อกที่เลเวล {level}",
    TextKey.ChooseMatchScoring to "เลือกวิธีนับผลการแข่งขัน", TextKey.CasualMatch to "การแข่งขันทั่วไป",
    TextKey.CasualMatchDescription to "ฝึกโดยไม่กระทบ Elo", TextKey.RankedMatch to "การแข่งขันจัดอันดับ",
    TextKey.RankedMatchDescription to "ชนะหรือแพ้จะเปลี่ยน Elo", TextKey.ConnectionDisconnected to "ยังไม่เชื่อมต่อเซิร์ฟเวอร์",
    TextKey.ConnectionConnecting to "กำลังเชื่อมต่อเซิร์ฟเวอร์…", TextKey.ConnectionAuthenticating to "กำลังยืนยันบัญชี…",
    TextKey.ConnectionConnected to "เชื่อมต่อแล้ว", TextKey.ConnectionReconnecting to "การเชื่อมต่อขาด กำลังลองใหม่…"
) + thaiCorePlayTexts

internal val russianGameplayTexts = englishGameplayTexts + mapOf(
    TextKey.ModeClassicTitle to "Классика", TextKey.ModeClassicDescription to "Найдите числа от 1 до 50", TextKey.ModeRandomTitle to "Случайно",
    TextKey.ModeRandomDescription to "Цели появляются в случайном порядке", TextKey.ModeTimeBonusTitle to "Бонус времени",
    TextKey.ModeTimeBonusDescription to "Верно +2 секунды, ошибка -3 секунды", TextKey.ModeSpeedUpTitle to "Ускорение",
    TextKey.ModeSpeedUpDescription to "Время на каждую цель сокращается", TextKey.ModeSurvivalTitle to "Выживание",
    TextKey.ModeSurvivalDescription to "Поражение после 3 ошибок", TextKey.ModeComboDescription to "Серия верных нажатий умножает очки",
    TextKey.ModeTimeAttackTitle to "Рывок 60 секунд", TextKey.ModeTimeAttackDescription to "Старый режим: наберите максимум за 60 секунд",
    TextKey.ModeTeamTitle to "Команда 2v2", TextKey.ModeTeamDescription to "Две команды играют на одном поле",
    TextKey.ChooseMatchType to "Выберите тип матча", TextKey.ChooseRankedMode to "Выберите рейтинговый режим",
    TextKey.ChooseCasualMode to "Выберите обычный режим", TextKey.GuestMode to "ГОСТЕВОЙ РЕЖИМ", TextKey.Ranked to "Рейтинг", TextKey.Casual to "Обычная",
    TextKey.RegisterToPlayOnline to "Создайте аккаунт для поиска соперников онлайн.", TextKey.CasualOrRankedDescription to "Тренируйтесь в обычной игре или повышайте Elo в рейтинге.",
    TextKey.LoginToPlay to "ВОЙТИ И ИГРАТЬ", TextKey.PlayNow to "ИГРАТЬ", TextKey.Explore to "Обзор",
    TextKey.FeaturesAndActivities to "Функции и события", TextKey.Tournament to "Турнир", TextKey.RegisterToJoin to "Создайте аккаунт для участия",
    TextKey.TournamentDescription to "Закрытые турниры на 4, 8 или 16 игроков", TextKey.Shop to "Магазин",
    TextKey.ShopDiscoveryDescription to "Открывайте числовые рубашки, поля и предметы", TextKey.OfflinePracticeTitle to "Тренировка офлайн",
    TextKey.OfflinePracticeDescription to "Тренируйтесь на поле из 50 чисел без влияния на Elo", TextKey.SaveProgress to "СОХРАНИТЬ ПРОГРЕСС",
    TextKey.SaveProgressDescription to "Создайте аккаунт, чтобы хранить Elo, историю и друзей на Android/iOS.", TextKey.ExitGuestMode to "ВЫЙТИ ИЗ ГОСТЕВОГО РЕЖИМА",
    TextKey.ChooseCompetitionType to "Выберите формат игры", TextKey.CreateRoom to "Создать комнату", TextKey.JoinRoom to "Войти в комнату",
    TextKey.Friends to "Друзья", TextKey.RegisterToAddFriends to "Создайте аккаунт, чтобы добавлять друзей", TextKey.OnlineFriends to "Друзей онлайн: {count}",
    TextKey.YourRank to "Ваше место: #{rank}", TextKey.ViewEloLeaderboard to "Открыть таблицу Elo", TextKey.Level to "Уровень {level}",
    TextKey.PlacementPending to "Калибровка", TextKey.DailyCheckInSevenDays to "Вход 7 дней", TextKey.CheckInStreak to "Серия: {count} дней",
    TextKey.DayLabel to "День", TextKey.ClaimDayReward to "ЗАБРАТЬ НАГРАДУ ЗА ДЕНЬ {day}", TextKey.Home to "Главная",
    TextKey.HarderModesUnlock to "Сложные режимы открываются с новыми уровнями.", TextKey.UnlockAtLevel to "Откроется на уровне {level}",
    TextKey.ChooseMatchScoring to "Выберите, как учитывать результат матча.", TextKey.CasualMatch to "Обычный матч",
    TextKey.CasualMatchDescription to "Тренировка без влияния на Elo", TextKey.RankedMatch to "Рейтинговый матч",
    TextKey.RankedMatchDescription to "Победы и поражения меняют Elo", TextKey.ConnectionDisconnected to "Нет соединения с сервером",
    TextKey.ConnectionConnecting to "Подключение к серверу…", TextKey.ConnectionAuthenticating to "Проверка аккаунта…",
    TextKey.ConnectionConnected to "Подключено", TextKey.ConnectionReconnecting to "Соединение потеряно. Повтор…"
) + russianCorePlayTexts
