package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey

internal val englishProtocolMessageTexts = mapOf(
    TextKey.ServerAuthRequired to "Sign in to continue.",
    TextKey.ServerRateLimited to "Too many requests. Try again in {seconds} seconds.",
    TextKey.ServerInvalidRequest to "The request is invalid. Please try again.",
    TextKey.ServerSessionExpired to "Your session has expired. Please sign in again.",
    TextKey.ServerProtocolMismatch to "This app version is no longer compatible. Please update the app.",
    TextKey.ServerEmailNotVerified to "Verify your email to continue.",
    TextKey.ServerRoomNotFound to "This room is no longer available.",
    TextKey.ServerWrongPassword to "The room password is incorrect.",
    TextKey.ServerRoomFull to "The room is full or the match has started.",
    TextKey.ServerNotInRoom to "You are not in this room.",
    TextKey.ServerHostRequired to "Only the owner can perform this action.",
    TextKey.ServerModeLocked to "This feature is still locked.",
    TextKey.ServerNotEnoughGold to "You do not have enough Gold.",
    TextKey.ServerPlayerBusy to "The player is busy in another room or tournament.",
    TextKey.ServerResourceNotFound to "The requested item could not be found.",
    TextKey.ServerAlreadyExists to "This request has already been processed.",
    TextKey.ServerUnavailable to "The service is temporarily unavailable. Please try again.",
    TextKey.ServerActionFailed to "The action could not be completed. Please try again.",
    TextKey.ServerInvalidInput to "The information provided is invalid.",
    TextKey.ServerInvitationExpired to "This invitation has expired.",
    TextKey.PasswordChanged to "Password updated.",
    TextKey.PasswordResetSent to "Password reset instructions have been sent.",
    TextKey.PasswordResetCompleted to "Password reset. You can sign in now.",
    TextKey.EmailVerificationSent to "A verification code has been sent to your email.",
    TextKey.EmailVerified to "Your email has been verified.",
    TextKey.SessionRevoked to "The selected device has been signed out.",
    TextKey.AllSessionsRevoked to "All devices have been signed out.",
    TextKey.AccountDeleted to "Your account has been deleted.",
    TextKey.NotificationFriendRequestMessage to "{player} wants to be your friend.",
    TextKey.NotificationRoomInvitationMessage to "{player} invited you to {room}.",
    TextKey.NotificationAchievementMessage to "{title}: {description}",
    TextKey.NotificationCosmeticMessage to "You unlocked {item}.",
    TextKey.NotificationMissionMessage to "{mission} • Claim {reward}.",
    TextKey.TournamentCreatedNotice to "Created a private {players}-player tournament.",
    TextKey.TournamentInvitationSentNotice to "Tournament invitation sent.",
    TextKey.TournamentInvitationDeclinedNotice to "Tournament invitation declined.",
    TextKey.TournamentInvitationDeclinedByFriendNotice to "A friend declined the tournament invitation.",
    TextKey.TournamentJoinedNotice to "Joined {tournament}.",
    TextKey.TournamentCancelledNotice to "The host cancelled the tournament.",
    TextKey.TournamentLeftNotice to "You left the tournament.",
    TextKey.FriendRequestSentNotice to "Friend request sent.",
    TextKey.FriendRequestCancelledNotice to "Friend request cancelled.",
    TextKey.FriendRequestAcceptedNotice to "Friend request accepted.",
    TextKey.FriendRequestDeclinedNotice to "Friend request declined.",
    TextKey.FriendRemovedNotice to "Friend removed.",
    TextKey.PlayerBlockedNotice to "Player blocked.",
    TextKey.PlayerUnblockedNotice to "Player unblocked.",
    TextKey.RoomInvitationDeclinedNotice to "Room invitation declined.",
    TextKey.RoomInvitationDeclinedByFriendNotice to "Your friend declined the room invitation.",
    TextKey.RoomKickedNotice to "The host removed you from the room.",
    TextKey.ResultsLeftNotice to "You left the results screen.",
    TextKey.RoomHostLeftNotice to "The host left the room.",
    TextKey.RoomPlayerLeftNotice to "{player} left the room.",
    TextKey.RoomDisconnectedTooLongNotice to "A player was disconnected for too long.",
    TextKey.ClanCreatedNotice to "Clan created.",
    TextKey.ClanJoinRequestedNotice to "Request sent. Waiting for the clan leader.",
    TextKey.ClanJoinApprovedOwnerNotice to "Approved {player}.",
    TextKey.ClanJoinRejectedOwnerNotice to "Declined {player}.",
    TextKey.ClanJoinApprovedNotice to "Your request to join {clan} was approved.",
    TextKey.ClanJoinRejectedNotice to "Your request to join {clan} was declined.",
    TextKey.ClanLeftNotice to "You left the clan.",
    TextKey.SeasonDefaultName to "Season {season}",
    TextKey.SeasonDefaultRewardDescription to "Gold and Gems based on your highest rank",
    TextKey.AchievementFirstWinTitle to "First victory",
    TextKey.AchievementFirstWinDescription to "Win your first match",
    TextKey.NotificationClanJoinRequestMessage to "{player} wants to join {clan}.",
    TextKey.NotificationClanJoinApprovedTitle to "Clan request approved",
    TextKey.NotificationClanJoinRejectedTitle to "Clan request declined",
    TextKey.NotificationClanInvitationMessage to "{player} invited you to join {clan}.",
    TextKey.SeasonInitialName to "Opening Season"
)

internal val vietnameseProtocolMessageTexts = englishProtocolMessageTexts + mapOf(
    TextKey.ServerAuthRequired to "Hãy đăng nhập để tiếp tục.",
    TextKey.ServerRateLimited to "Bạn thao tác quá nhanh. Vui lòng thử lại sau {seconds} giây.",
    TextKey.ServerInvalidRequest to "Yêu cầu không hợp lệ. Vui lòng thử lại.",
    TextKey.ServerSessionExpired to "Phiên đăng nhập đã hết hạn. Vui lòng đăng nhập lại.",
    TextKey.ServerProtocolMismatch to "Phiên bản ứng dụng không còn tương thích. Vui lòng cập nhật ứng dụng.",
    TextKey.ServerEmailNotVerified to "Hãy xác minh email để tiếp tục.",
    TextKey.ServerRoomNotFound to "Phòng không còn khả dụng.",
    TextKey.ServerWrongPassword to "Mật khẩu phòng không đúng.",
    TextKey.ServerRoomFull to "Phòng đã đầy hoặc trận đấu đã bắt đầu.",
    TextKey.ServerNotInRoom to "Bạn không ở trong phòng này.",
    TextKey.ServerHostRequired to "Chỉ chủ phòng hoặc bang chủ mới có thể thực hiện thao tác này.",
    TextKey.ServerModeLocked to "Tính năng này chưa được mở khóa.",
    TextKey.ServerNotEnoughGold to "Bạn không đủ Vàng.",
    TextKey.ServerPlayerBusy to "Người chơi đang bận ở phòng hoặc giải khác.",
    TextKey.ServerResourceNotFound to "Không tìm thấy dữ liệu được yêu cầu.",
    TextKey.ServerAlreadyExists to "Yêu cầu này đã được xử lý.",
    TextKey.ServerUnavailable to "Dịch vụ tạm thời không khả dụng. Vui lòng thử lại.",
    TextKey.ServerActionFailed to "Không thể hoàn tất thao tác. Vui lòng thử lại.",
    TextKey.ServerInvalidInput to "Thông tin đã nhập không hợp lệ.",
    TextKey.ServerInvitationExpired to "Lời mời đã hết hạn.",
    TextKey.PasswordChanged to "Đã cập nhật mật khẩu.",
    TextKey.PasswordResetSent to "Đã gửi hướng dẫn đặt lại mật khẩu.",
    TextKey.PasswordResetCompleted to "Đã đặt lại mật khẩu. Bạn có thể đăng nhập ngay.",
    TextKey.EmailVerificationSent to "Mã xác minh đã được gửi tới email của bạn.",
    TextKey.EmailVerified to "Email của bạn đã được xác minh.",
    TextKey.SessionRevoked to "Đã đăng xuất thiết bị đã chọn.",
    TextKey.AllSessionsRevoked to "Đã đăng xuất tất cả thiết bị.",
    TextKey.AccountDeleted to "Tài khoản của bạn đã được xóa.",
    TextKey.NotificationFriendRequestMessage to "{player} muốn kết bạn với bạn.",
    TextKey.NotificationRoomInvitationMessage to "{player} mời bạn vào phòng {room}.",
    TextKey.NotificationAchievementMessage to "{title}: {description}",
    TextKey.NotificationCosmeticMessage to "Bạn đã mở khóa {item}.",
    TextKey.NotificationMissionMessage to "{mission} • Nhận {reward}.",
    TextKey.TournamentCreatedNotice to "Đã tạo giải riêng {players} người.",
    TextKey.TournamentInvitationSentNotice to "Đã gửi lời mời tham gia giải.",
    TextKey.TournamentInvitationDeclinedNotice to "Đã từ chối lời mời giải đấu.",
    TextKey.TournamentInvitationDeclinedByFriendNotice to "Một người bạn đã từ chối lời mời giải đấu.",
    TextKey.TournamentJoinedNotice to "Đã tham gia giải {tournament}.",
    TextKey.TournamentCancelledNotice to "Chủ giải đã hủy giải đấu.",
    TextKey.TournamentLeftNotice to "Đã rời giải đấu.",
    TextKey.FriendRequestSentNotice to "Đã gửi lời mời kết bạn.",
    TextKey.FriendRequestCancelledNotice to "Đã hủy lời mời kết bạn.",
    TextKey.FriendRequestAcceptedNotice to "Đã chấp nhận lời mời kết bạn.",
    TextKey.FriendRequestDeclinedNotice to "Đã từ chối lời mời kết bạn.",
    TextKey.FriendRemovedNotice to "Đã hủy kết bạn.",
    TextKey.PlayerBlockedNotice to "Đã chặn người chơi.",
    TextKey.PlayerUnblockedNotice to "Đã bỏ chặn người chơi.",
    TextKey.RoomInvitationDeclinedNotice to "Đã từ chối lời mời vào phòng.",
    TextKey.RoomInvitationDeclinedByFriendNotice to "Bạn bè đã từ chối lời mời vào phòng.",
    TextKey.RoomKickedNotice to "Chủ phòng đã mời bạn ra khỏi phòng.",
    TextKey.ResultsLeftNotice to "Bạn đã rời màn kết quả.",
    TextKey.RoomHostLeftNotice to "Chủ phòng đã rời phòng.",
    TextKey.RoomPlayerLeftNotice to "{player} đã rời phòng.",
    TextKey.RoomDisconnectedTooLongNotice to "Người chơi đã mất kết nối quá lâu.",
    TextKey.ClanCreatedNotice to "Tạo clan thành công.",
    TextKey.ClanJoinRequestedNotice to "Đã gửi yêu cầu. Chờ bang chủ duyệt.",
    TextKey.ClanJoinApprovedOwnerNotice to "Đã duyệt {player}.",
    TextKey.ClanJoinRejectedOwnerNotice to "Đã từ chối {player}.",
    TextKey.ClanJoinApprovedNotice to "Yêu cầu vào clan {clan} đã được duyệt.",
    TextKey.ClanJoinRejectedNotice to "Yêu cầu vào clan {clan} đã bị từ chối.",
    TextKey.ClanLeftNotice to "Đã rời clan.",
    TextKey.SeasonDefaultName to "Mùa {season}",
    TextKey.SeasonDefaultRewardDescription to "Vàng và Gem theo bậc xếp hạng cao nhất",
    TextKey.AchievementFirstWinTitle to "Khởi đầu chiến thắng",
    TextKey.AchievementFirstWinDescription to "Giành chiến thắng đầu tiên",
    TextKey.NotificationClanJoinRequestMessage to "{player} muốn vào bang {clan}.",
    TextKey.NotificationClanJoinApprovedTitle to "Đã vào bang",
    TextKey.NotificationClanJoinRejectedTitle to "Yêu cầu bị từ chối",
    TextKey.NotificationClanInvitationMessage to "{player} mời bạn vào bang {clan}.",
    TextKey.SeasonInitialName to "Mùa Khởi Đầu"
)

private fun protocolMessageTranslations(vararg values: String): Map<TextKey, String> {
    require(values.size == englishProtocolMessageTexts.size) {
        "Expected ${englishProtocolMessageTexts.size} protocol translations, received ${values.size}."
    }
    return englishProtocolMessageTexts.keys.zip(values).toMap()
}

internal val germanProtocolMessageTexts = protocolMessageTranslations(
    "Melde dich an, um fortzufahren.", "Zu viele Anfragen. Versuche es in {seconds} Sekunden erneut.",
    "Die Anfrage ist ungültig. Bitte versuche es erneut.", "Deine Sitzung ist abgelaufen. Bitte melde dich erneut an.",
    "Diese App-Version ist nicht mehr kompatibel. Bitte aktualisiere die App.", "Bestätige deine E-Mail-Adresse, um fortzufahren.",
    "Dieser Raum ist nicht mehr verfügbar.", "Das Raumpasswort ist falsch.", "Der Raum ist voll oder das Spiel hat begonnen.",
    "Du bist nicht in diesem Raum.", "Nur der Besitzer kann diese Aktion ausführen.", "Diese Funktion ist noch gesperrt.",
    "Du hast nicht genug Gold.", "Der Spieler ist in einem anderen Raum oder Turnier beschäftigt.",
    "Das angeforderte Element wurde nicht gefunden.", "Diese Anfrage wurde bereits bearbeitet.",
    "Der Dienst ist vorübergehend nicht verfügbar. Bitte versuche es erneut.", "Die Aktion konnte nicht abgeschlossen werden. Bitte versuche es erneut.",
    "Die eingegebenen Informationen sind ungültig.", "Diese Einladung ist abgelaufen.", "Passwort aktualisiert.",
    "Anweisungen zum Zurücksetzen des Passworts wurden gesendet.", "Passwort zurückgesetzt. Du kannst dich jetzt anmelden.",
    "Ein Bestätigungscode wurde an deine E-Mail-Adresse gesendet.", "Deine E-Mail-Adresse wurde bestätigt.",
    "Das ausgewählte Gerät wurde abgemeldet.", "Alle Geräte wurden abgemeldet.", "Dein Konto wurde gelöscht.",
    "{player} möchte mit dir befreundet sein.", "{player} hat dich in {room} eingeladen.", "{title}: {description}",
    "Du hast {item} freigeschaltet.", "{mission} • Hole {reward} ab.", "Privates Turnier für {players} Spieler erstellt.",
    "Turniereinladung gesendet.", "Turniereinladung abgelehnt.", "Ein Freund hat die Turniereinladung abgelehnt.",
    "{tournament} beigetreten.", "Der Gastgeber hat das Turnier abgesagt.", "Du hast das Turnier verlassen.",
    "Freundschaftsanfrage gesendet.", "Freundschaftsanfrage abgebrochen.", "Freundschaftsanfrage angenommen.",
    "Freundschaftsanfrage abgelehnt.", "Freund entfernt.", "Spieler blockiert.", "Spieler entsperrt.",
    "Raumeinladung abgelehnt.", "Dein Freund hat die Raumeinladung abgelehnt.", "Der Gastgeber hat dich aus dem Raum entfernt.",
    "Du hast den Ergebnisbildschirm verlassen.", "Der Gastgeber hat den Raum verlassen.", "{player} hat den Raum verlassen.",
    "Ein Spieler war zu lange getrennt.", "Clan erstellt.", "Anfrage gesendet. Warte auf den Clan-Anführer.",
    "{player} wurde angenommen.", "{player} wurde abgelehnt.", "Deine Anfrage für {clan} wurde angenommen.",
    "Deine Anfrage für {clan} wurde abgelehnt.", "Du hast den Clan verlassen.", "Saison {season}",
    "Gold und Gems basierend auf deinem höchsten Rang", "Erster Sieg", "Gewinne dein erstes Spiel",
    "{player} möchte {clan} beitreten.", "Clan-Anfrage angenommen", "Clan-Anfrage abgelehnt", "{player} hat dich eingeladen, {clan} beizutreten.",
    "Startsaison"
)

internal val japaneseProtocolMessageTexts = protocolMessageTranslations(
    "続行するにはログインしてください。", "リクエストが多すぎます。{seconds}秒後にもう一度お試しください。",
    "リクエストが無効です。もう一度お試しください。", "セッションの有効期限が切れました。もう一度ログインしてください。",
    "このアプリのバージョンは対応していません。アプリを更新してください。", "続行するにはメールアドレスを確認してください。",
    "このルームは利用できません。", "ルームのパスワードが違います。", "ルームが満員か、対戦が始まっています。",
    "このルームに参加していません。", "この操作はオーナーのみ実行できます。", "この機能はまだロックされています。",
    "ゴールドが足りません。", "プレイヤーは別のルームまたは大会に参加中です。", "要求された項目が見つかりません。",
    "このリクエストはすでに処理されています。", "サービスを一時的に利用できません。もう一度お試しください。",
    "操作を完了できませんでした。もう一度お試しください。", "入力内容が正しくありません。", "この招待の有効期限は切れています。",
    "パスワードを更新しました。", "パスワード再設定の案内を送信しました。", "パスワードを再設定しました。ログインできます。",
    "確認コードをメールに送信しました。", "メールアドレスを確認しました。", "選択した端末からログアウトしました。",
    "すべての端末からログアウトしました。", "アカウントを削除しました。", "{player}さんからフレンド申請が届きました。",
    "{player}さんが{room}に招待しました。", "{title}：{description}", "{item}をアンロックしました。",
    "{mission} • {reward}を受け取れます。", "{players}人用のプライベート大会を作成しました。", "大会への招待を送信しました。",
    "大会への招待を辞退しました。", "フレンドが大会への招待を辞退しました。", "{tournament}に参加しました。",
    "主催者が大会を中止しました。", "大会から退出しました。", "フレンド申請を送信しました。", "フレンド申請を取り消しました。",
    "フレンド申請を承認しました。", "フレンド申請を拒否しました。", "フレンドを解除しました。", "プレイヤーをブロックしました。",
    "プレイヤーのブロックを解除しました。", "ルームへの招待を辞退しました。", "フレンドがルームへの招待を辞退しました。",
    "ホストによってルームから退出させられました。", "結果画面から退出しました。", "ホストがルームを退出しました。",
    "{player}さんがルームを退出しました。", "プレイヤーの切断時間が長すぎました。", "クランを作成しました。",
    "申請を送信しました。クランリーダーの承認をお待ちください。", "{player}さんを承認しました。", "{player}さんを拒否しました。",
    "{clan}への参加申請が承認されました。", "{clan}への参加申請が拒否されました。", "クランを脱退しました。",
    "シーズン{season}", "最高ランクに応じたゴールドとGem", "初勝利", "最初の対戦に勝利する",
    "{player}さんが{clan}への参加を希望しています。", "クラン申請が承認されました", "クラン申請が拒否されました", "{player}さんが{clan}に招待しました。",
    "開幕シーズン"
)

internal val simplifiedChineseProtocolMessageTexts = protocolMessageTranslations(
    "请登录后继续。", "请求过于频繁，请在{seconds}秒后重试。", "请求无效，请重试。", "登录已过期，请重新登录。",
    "当前应用版本已不兼容，请更新应用。", "请验证邮箱后继续。", "该房间已不可用。", "房间密码错误。",
    "房间已满或比赛已经开始。", "你不在该房间中。", "只有房主可以执行此操作。", "该功能尚未解锁。",
    "你的金币不足。", "该玩家正在其他房间或锦标赛中。", "找不到请求的内容。", "该请求已处理。",
    "服务暂时不可用，请重试。", "无法完成操作，请重试。", "输入的信息无效。", "该邀请已过期。",
    "密码已更新。", "密码重置说明已发送。", "密码已重置，现在可以登录。", "验证码已发送至你的邮箱。",
    "邮箱验证成功。", "所选设备已退出登录。", "所有设备均已退出登录。", "你的账号已删除。",
    "{player}想加你为好友。", "{player}邀请你加入{room}。", "{title}：{description}", "你已解锁{item}。",
    "{mission} • 领取{reward}。", "已创建{players}人私人锦标赛。", "锦标赛邀请已发送。", "已拒绝锦标赛邀请。",
    "一位好友拒绝了锦标赛邀请。", "已加入{tournament}。", "房主取消了锦标赛。", "你已退出锦标赛。",
    "好友申请已发送。", "好友申请已取消。", "好友申请已接受。", "好友申请已拒绝。", "已删除好友。",
    "已屏蔽玩家。", "已取消屏蔽玩家。", "已拒绝房间邀请。", "你的好友拒绝了房间邀请。",
    "房主将你移出了房间。", "你已离开结果页面。", "房主已离开房间。", "{player}已离开房间。",
    "一名玩家断线时间过长。", "战队创建成功。", "申请已发送，等待战队队长审批。", "已批准{player}。",
    "已拒绝{player}。", "你加入{clan}的申请已获批准。", "你加入{clan}的申请已被拒绝。", "你已退出战队。",
    "第{season}赛季", "根据最高段位获得金币和Gem", "首场胜利", "赢得首场比赛",
    "{player}想加入{clan}。", "战队申请已批准", "战队申请已拒绝", "{player}邀请你加入{clan}。",
    "起始赛季"
)

internal val koreanProtocolMessageTexts = protocolMessageTranslations(
    "계속하려면 로그인하세요.", "요청이 너무 많습니다. {seconds}초 후 다시 시도하세요.", "잘못된 요청입니다. 다시 시도하세요.",
    "세션이 만료되었습니다. 다시 로그인하세요.", "이 앱 버전은 더 이상 호환되지 않습니다. 앱을 업데이트하세요.",
    "계속하려면 이메일을 인증하세요.", "이 방은 더 이상 이용할 수 없습니다.", "방 비밀번호가 올바르지 않습니다.",
    "방이 가득 찼거나 경기가 시작되었습니다.", "이 방에 참여하고 있지 않습니다.", "방장만 이 작업을 수행할 수 있습니다.",
    "이 기능은 아직 잠겨 있습니다.", "골드가 부족합니다.", "플레이어가 다른 방이나 토너먼트에 참여 중입니다.",
    "요청한 항목을 찾을 수 없습니다.", "이미 처리된 요청입니다.", "서비스를 일시적으로 사용할 수 없습니다. 다시 시도하세요.",
    "작업을 완료할 수 없습니다. 다시 시도하세요.", "입력한 정보가 올바르지 않습니다.", "초대가 만료되었습니다.",
    "비밀번호가 변경되었습니다.", "비밀번호 재설정 안내를 보냈습니다.", "비밀번호가 재설정되었습니다. 이제 로그인할 수 있습니다.",
    "인증 코드를 이메일로 보냈습니다.", "이메일 인증이 완료되었습니다.", "선택한 기기에서 로그아웃했습니다.",
    "모든 기기에서 로그아웃했습니다.", "계정이 삭제되었습니다.", "{player}님이 친구 요청을 보냈습니다.",
    "{player}님이 {room}에 초대했습니다.", "{title}: {description}", "{item}을(를) 잠금 해제했습니다.",
    "{mission} • {reward} 받기.", "{players}인 비공개 토너먼트를 만들었습니다.", "토너먼트 초대를 보냈습니다.",
    "토너먼트 초대를 거절했습니다.", "친구가 토너먼트 초대를 거절했습니다.", "{tournament}에 참가했습니다.",
    "방장이 토너먼트를 취소했습니다.", "토너먼트에서 나갔습니다.", "친구 요청을 보냈습니다.", "친구 요청을 취소했습니다.",
    "친구 요청을 수락했습니다.", "친구 요청을 거절했습니다.", "친구를 삭제했습니다.", "플레이어를 차단했습니다.",
    "플레이어 차단을 해제했습니다.", "방 초대를 거절했습니다.", "친구가 방 초대를 거절했습니다.",
    "방장이 회원님을 방에서 내보냈습니다.", "결과 화면에서 나갔습니다.", "방장이 방을 나갔습니다.",
    "{player}님이 방을 나갔습니다.", "플레이어의 연결이 너무 오래 끊겼습니다.", "클랜을 만들었습니다.",
    "가입 요청을 보냈습니다. 클랜장의 승인을 기다리세요.", "{player}님을 승인했습니다.", "{player}님을 거절했습니다.",
    "{clan} 가입 요청이 승인되었습니다.", "{clan} 가입 요청이 거절되었습니다.", "클랜에서 나갔습니다.",
    "시즌 {season}", "최고 티어에 따른 골드와 Gem", "첫 승리", "첫 경기에서 승리하세요",
    "{player}님이 {clan} 가입을 요청했습니다.", "클랜 가입 승인", "클랜 가입 거절", "{player}님이 {clan}에 초대했습니다.",
    "시작 시즌"
)

internal val spanishProtocolMessageTexts = protocolMessageTranslations(
    "Inicia sesión para continuar.", "Demasiadas solicitudes. Inténtalo de nuevo en {seconds} segundos.",
    "La solicitud no es válida. Inténtalo de nuevo.", "Tu sesión ha caducado. Vuelve a iniciar sesión.",
    "Esta versión de la aplicación ya no es compatible. Actualiza la aplicación.", "Verifica tu correo para continuar.",
    "Esta sala ya no está disponible.", "La contraseña de la sala es incorrecta.", "La sala está llena o la partida ya comenzó.",
    "No estás en esta sala.", "Solo el propietario puede realizar esta acción.", "Esta función todavía está bloqueada.",
    "No tienes suficiente Oro.", "El jugador está ocupado en otra sala o torneo.", "No se encontró el elemento solicitado.",
    "Esta solicitud ya fue procesada.", "El servicio no está disponible temporalmente. Inténtalo de nuevo.",
    "No se pudo completar la acción. Inténtalo de nuevo.", "La información proporcionada no es válida.", "Esta invitación ha caducado.",
    "Contraseña actualizada.", "Se enviaron las instrucciones para restablecer la contraseña.",
    "Contraseña restablecida. Ya puedes iniciar sesión.", "Se envió un código de verificación a tu correo.",
    "Tu correo ha sido verificado.", "Se cerró la sesión del dispositivo seleccionado.", "Se cerró la sesión de todos los dispositivos.",
    "Tu cuenta fue eliminada.", "{player} quiere ser tu amigo.", "{player} te invitó a {room}.", "{title}: {description}",
    "Desbloqueaste {item}.", "{mission} • Reclama {reward}.", "Se creó un torneo privado para {players} jugadores.",
    "Invitación al torneo enviada.", "Invitación al torneo rechazada.", "Un amigo rechazó la invitación al torneo.",
    "Te uniste a {tournament}.", "El anfitrión canceló el torneo.", "Abandonaste el torneo.", "Solicitud de amistad enviada.",
    "Solicitud de amistad cancelada.", "Solicitud de amistad aceptada.", "Solicitud de amistad rechazada.", "Amigo eliminado.",
    "Jugador bloqueado.", "Jugador desbloqueado.", "Invitación a la sala rechazada.", "Tu amigo rechazó la invitación a la sala.",
    "El anfitrión te expulsó de la sala.", "Saliste de la pantalla de resultados.", "El anfitrión salió de la sala.",
    "{player} salió de la sala.", "Un jugador estuvo desconectado demasiado tiempo.", "Clan creado.",
    "Solicitud enviada. Espera la aprobación del líder del clan.", "Se aprobó a {player}.", "Se rechazó a {player}.",
    "Se aprobó tu solicitud para unirte a {clan}.", "Se rechazó tu solicitud para unirte a {clan}.", "Abandonaste el clan.",
    "Temporada {season}", "Oro y Gemas según tu rango más alto", "Primera victoria", "Gana tu primera partida",
    "{player} quiere unirse a {clan}.", "Solicitud de clan aprobada", "Solicitud de clan rechazada", "{player} te invitó a unirte a {clan}.",
    "Temporada inicial"
)

internal val brazilianPortugueseProtocolMessageTexts = protocolMessageTranslations(
    "Entre para continuar.", "Muitas solicitações. Tente novamente em {seconds} segundos.",
    "A solicitação é inválida. Tente novamente.", "Sua sessão expirou. Entre novamente.",
    "Esta versão do app não é mais compatível. Atualize o app.", "Verifique seu e-mail para continuar.",
    "Esta sala não está mais disponível.", "A senha da sala está incorreta.", "A sala está cheia ou a partida começou.",
    "Você não está nesta sala.", "Somente o proprietário pode realizar esta ação.", "Este recurso ainda está bloqueado.",
    "Você não tem Ouro suficiente.", "O jogador está ocupado em outra sala ou torneio.", "O item solicitado não foi encontrado.",
    "Esta solicitação já foi processada.", "O serviço está temporariamente indisponível. Tente novamente.",
    "Não foi possível concluir a ação. Tente novamente.", "As informações fornecidas são inválidas.", "Este convite expirou.",
    "Senha atualizada.", "As instruções para redefinir a senha foram enviadas.", "Senha redefinida. Você já pode entrar.",
    "Um código de verificação foi enviado ao seu e-mail.", "Seu e-mail foi verificado.", "O dispositivo selecionado foi desconectado.",
    "Todos os dispositivos foram desconectados.", "Sua conta foi excluída.", "{player} quer ser seu amigo.",
    "{player} convidou você para {room}.", "{title}: {description}", "Você desbloqueou {item}.",
    "{mission} • Resgate {reward}.", "Torneio privado para {players} jogadores criado.", "Convite para o torneio enviado.",
    "Convite para o torneio recusado.", "Um amigo recusou o convite para o torneio.", "Você entrou em {tournament}.",
    "O anfitrião cancelou o torneio.", "Você saiu do torneio.", "Solicitação de amizade enviada.",
    "Solicitação de amizade cancelada.", "Solicitação de amizade aceita.", "Solicitação de amizade recusada.",
    "Amigo removido.", "Jogador bloqueado.", "Jogador desbloqueado.", "Convite para a sala recusado.",
    "Seu amigo recusou o convite para a sala.", "O anfitrião removeu você da sala.", "Você saiu da tela de resultados.",
    "O anfitrião saiu da sala.", "{player} saiu da sala.", "Um jogador ficou desconectado por tempo demais.",
    "Clã criado.", "Solicitação enviada. Aguarde o líder do clã.", "{player} foi aprovado.", "{player} foi recusado.",
    "Sua solicitação para entrar em {clan} foi aprovada.", "Sua solicitação para entrar em {clan} foi recusada.",
    "Você saiu do clã.", "Temporada {season}", "Ouro e Gemas com base no seu maior ranque", "Primeira vitória", "Vença sua primeira partida",
    "{player} quer entrar em {clan}.", "Solicitação de clã aprovada", "Solicitação de clã recusada", "{player} convidou você para entrar em {clan}.",
    "Temporada inaugural"
)

internal val frenchProtocolMessageTexts = protocolMessageTranslations(
    "Connectez-vous pour continuer.", "Trop de requêtes. Réessayez dans {seconds} secondes.",
    "La requête est invalide. Veuillez réessayer.", "Votre session a expiré. Veuillez vous reconnecter.",
    "Cette version de l’application n’est plus compatible. Veuillez mettre l’application à jour.",
    "Vérifiez votre adresse e-mail pour continuer.", "Cette salle n’est plus disponible.", "Le mot de passe de la salle est incorrect.",
    "La salle est pleine ou la partie a commencé.", "Vous n’êtes pas dans cette salle.",
    "Seul le propriétaire peut effectuer cette action.", "Cette fonctionnalité est encore verrouillée.",
    "Vous n’avez pas assez d’Or.", "Le joueur est occupé dans une autre salle ou un autre tournoi.",
    "L’élément demandé est introuvable.", "Cette demande a déjà été traitée.",
    "Le service est temporairement indisponible. Veuillez réessayer.", "Impossible de terminer l’action. Veuillez réessayer.",
    "Les informations fournies sont invalides.", "Cette invitation a expiré.", "Mot de passe mis à jour.",
    "Les instructions de réinitialisation du mot de passe ont été envoyées.",
    "Mot de passe réinitialisé. Vous pouvez maintenant vous connecter.", "Un code de vérification a été envoyé à votre adresse e-mail.",
    "Votre adresse e-mail a été vérifiée.", "L’appareil sélectionné a été déconnecté.", "Tous les appareils ont été déconnectés.",
    "Votre compte a été supprimé.", "{player} souhaite devenir votre ami.", "{player} vous a invité dans {room}.",
    "{title} : {description}", "Vous avez débloqué {item}.", "{mission} • Récupérez {reward}.",
    "Tournoi privé de {players} joueurs créé.", "Invitation au tournoi envoyée.", "Invitation au tournoi refusée.",
    "Un ami a refusé l’invitation au tournoi.", "Vous avez rejoint {tournament}.", "L’hôte a annulé le tournoi.",
    "Vous avez quitté le tournoi.", "Demande d’ami envoyée.", "Demande d’ami annulée.", "Demande d’ami acceptée.",
    "Demande d’ami refusée.", "Ami supprimé.", "Joueur bloqué.", "Joueur débloqué.", "Invitation à la salle refusée.",
    "Votre ami a refusé l’invitation à la salle.", "L’hôte vous a retiré de la salle.", "Vous avez quitté l’écran des résultats.",
    "L’hôte a quitté la salle.", "{player} a quitté la salle.", "Un joueur est resté déconnecté trop longtemps.",
    "Clan créé.", "Demande envoyée. Attendez l’accord du chef de clan.", "{player} a été accepté.", "{player} a été refusé.",
    "Votre demande pour rejoindre {clan} a été acceptée.", "Votre demande pour rejoindre {clan} a été refusée.",
    "Vous avez quitté le clan.", "Saison {season}", "Or et Gemmes selon votre meilleur rang", "Première victoire", "Remportez votre première partie",
    "{player} souhaite rejoindre {clan}.", "Demande de clan acceptée", "Demande de clan refusée", "{player} vous a invité à rejoindre {clan}.",
    "Saison inaugurale"
)

internal val indonesianProtocolMessageTexts = protocolMessageTranslations(
    "Masuk untuk melanjutkan.", "Terlalu banyak permintaan. Coba lagi dalam {seconds} detik.",
    "Permintaan tidak valid. Silakan coba lagi.", "Sesi Anda telah berakhir. Silakan masuk kembali.",
    "Versi aplikasi ini tidak lagi kompatibel. Perbarui aplikasi.", "Verifikasi email untuk melanjutkan.",
    "Room ini tidak lagi tersedia.", "Kata sandi room salah.", "Room penuh atau pertandingan sudah dimulai.",
    "Anda tidak berada di room ini.", "Hanya pemilik yang dapat melakukan tindakan ini.", "Fitur ini masih terkunci.",
    "Gold Anda tidak cukup.", "Pemain sedang sibuk di room atau turnamen lain.", "Item yang diminta tidak ditemukan.",
    "Permintaan ini sudah diproses.", "Layanan sementara tidak tersedia. Silakan coba lagi.",
    "Tindakan tidak dapat diselesaikan. Silakan coba lagi.", "Informasi yang diberikan tidak valid.", "Undangan ini telah kedaluwarsa.",
    "Kata sandi diperbarui.", "Petunjuk pengaturan ulang kata sandi telah dikirim.",
    "Kata sandi telah diatur ulang. Anda sekarang dapat masuk.", "Kode verifikasi telah dikirim ke email Anda.",
    "Email Anda telah diverifikasi.", "Perangkat yang dipilih telah dikeluarkan.", "Semua perangkat telah dikeluarkan.",
    "Akun Anda telah dihapus.", "{player} ingin menjadi teman Anda.", "{player} mengundang Anda ke {room}.",
    "{title}: {description}", "Anda membuka {item}.", "{mission} • Klaim {reward}.",
    "Turnamen privat untuk {players} pemain telah dibuat.", "Undangan turnamen dikirim.", "Undangan turnamen ditolak.",
    "Seorang teman menolak undangan turnamen.", "Anda bergabung dengan {tournament}.", "Host membatalkan turnamen.",
    "Anda keluar dari turnamen.", "Permintaan pertemanan dikirim.", "Permintaan pertemanan dibatalkan.",
    "Permintaan pertemanan diterima.", "Permintaan pertemanan ditolak.", "Teman dihapus.", "Pemain diblokir.",
    "Blokir pemain dibuka.", "Undangan room ditolak.", "Teman Anda menolak undangan room.",
    "Host mengeluarkan Anda dari room.", "Anda keluar dari layar hasil.", "Host keluar dari room.",
    "{player} keluar dari room.", "Seorang pemain terputus terlalu lama.", "Klan dibuat.",
    "Permintaan dikirim. Tunggu persetujuan ketua klan.", "{player} disetujui.", "{player} ditolak.",
    "Permintaan Anda untuk bergabung dengan {clan} disetujui.", "Permintaan Anda untuk bergabung dengan {clan} ditolak.",
    "Anda keluar dari klan.", "Musim {season}", "Gold dan Gem berdasarkan peringkat tertinggi Anda", "Kemenangan pertama", "Menangkan pertandingan pertama Anda",
    "{player} ingin bergabung dengan {clan}.", "Permintaan klan disetujui", "Permintaan klan ditolak", "{player} mengundang Anda bergabung dengan {clan}.",
    "Musim perdana"
)

internal val thaiProtocolMessageTexts = protocolMessageTranslations(
    "เข้าสู่ระบบเพื่อดำเนินการต่อ", "มีคำขอมากเกินไป โปรดลองอีกครั้งใน {seconds} วินาที",
    "คำขอไม่ถูกต้อง โปรดลองอีกครั้ง", "เซสชันหมดอายุ โปรดเข้าสู่ระบบอีกครั้ง",
    "แอปเวอร์ชันนี้ไม่รองรับแล้ว โปรดอัปเดตแอป", "ยืนยันอีเมลเพื่อดำเนินการต่อ",
    "ห้องนี้ไม่พร้อมใช้งานแล้ว", "รหัสผ่านห้องไม่ถูกต้อง", "ห้องเต็มหรือการแข่งขันเริ่มแล้ว",
    "คุณไม่ได้อยู่ในห้องนี้", "เฉพาะเจ้าของเท่านั้นที่ทำรายการนี้ได้", "ฟีเจอร์นี้ยังล็อกอยู่",
    "คุณมี Gold ไม่เพียงพอ", "ผู้เล่นกำลังอยู่ในห้องหรือทัวร์นาเมนต์อื่น", "ไม่พบรายการที่ต้องการ",
    "คำขอนี้ได้รับการดำเนินการแล้ว", "บริการไม่พร้อมใช้งานชั่วคราว โปรดลองอีกครั้ง",
    "ไม่สามารถดำเนินการให้เสร็จได้ โปรดลองอีกครั้ง", "ข้อมูลที่ระบุไม่ถูกต้อง", "คำเชิญนี้หมดอายุแล้ว",
    "อัปเดตรหัสผ่านแล้ว", "ส่งคำแนะนำการรีเซ็ตรหัสผ่านแล้ว", "รีเซ็ตรหัสผ่านแล้ว คุณเข้าสู่ระบบได้ทันที",
    "ส่งรหัสยืนยันไปยังอีเมลของคุณแล้ว", "ยืนยันอีเมลแล้ว", "นำอุปกรณ์ที่เลือกออกจากระบบแล้ว",
    "นำทุกอุปกรณ์ออกจากระบบแล้ว", "ลบบัญชีของคุณแล้ว", "{player} ต้องการเป็นเพื่อนกับคุณ",
    "{player} เชิญคุณเข้าห้อง {room}", "{title}: {description}", "คุณปลดล็อก {item} แล้ว",
    "{mission} • รับ {reward}", "สร้างทัวร์นาเมนต์ส่วนตัวสำหรับ {players} คนแล้ว", "ส่งคำเชิญทัวร์นาเมนต์แล้ว",
    "ปฏิเสธคำเชิญทัวร์นาเมนต์แล้ว", "เพื่อนปฏิเสธคำเชิญทัวร์นาเมนต์", "เข้าร่วม {tournament} แล้ว",
    "โฮสต์ยกเลิกทัวร์นาเมนต์", "คุณออกจากทัวร์นาเมนต์แล้ว", "ส่งคำขอเป็นเพื่อนแล้ว",
    "ยกเลิกคำขอเป็นเพื่อนแล้ว", "ยอมรับคำขอเป็นเพื่อนแล้ว", "ปฏิเสธคำขอเป็นเพื่อนแล้ว", "ลบเพื่อนแล้ว",
    "บล็อกผู้เล่นแล้ว", "เลิกบล็อกผู้เล่นแล้ว", "ปฏิเสธคำเชิญเข้าห้องแล้ว", "เพื่อนของคุณปฏิเสธคำเชิญเข้าห้อง",
    "โฮสต์นำคุณออกจากห้อง", "คุณออกจากหน้าผลการแข่งขันแล้ว", "โฮสต์ออกจากห้องแล้ว",
    "{player} ออกจากห้องแล้ว", "ผู้เล่นขาดการเชื่อมต่อนานเกินไป", "สร้างแคลนแล้ว",
    "ส่งคำขอแล้ว โปรดรอหัวหน้าแคลนอนุมัติ", "อนุมัติ {player} แล้ว", "ปฏิเสธ {player} แล้ว",
    "คำขอเข้าร่วม {clan} ของคุณได้รับการอนุมัติ", "คำขอเข้าร่วม {clan} ของคุณถูกปฏิเสธ",
    "คุณออกจากแคลนแล้ว", "ซีซัน {season}", "Gold และ Gem ตามแรงก์สูงสุดของคุณ", "ชัยชนะแรก", "ชนะการแข่งขันครั้งแรก",
    "{player} ต้องการเข้าร่วม {clan}", "อนุมัติคำขอเข้าแคลนแล้ว", "ปฏิเสธคำขอเข้าแคลนแล้ว", "{player} เชิญคุณเข้าร่วม {clan}",
    "ซีซันเริ่มต้น"
)

internal val russianProtocolMessageTexts = protocolMessageTranslations(
    "Войдите, чтобы продолжить.", "Слишком много запросов. Повторите попытку через {seconds} сек.",
    "Недопустимый запрос. Повторите попытку.", "Срок действия сеанса истёк. Войдите снова.",
    "Эта версия приложения больше не поддерживается. Обновите приложение.", "Подтвердите адрес электронной почты, чтобы продолжить.",
    "Эта комната больше недоступна.", "Неверный пароль комнаты.", "Комната заполнена или матч уже начался.",
    "Вы не находитесь в этой комнате.", "Только владелец может выполнить это действие.", "Эта функция пока заблокирована.",
    "Недостаточно Золота.", "Игрок занят в другой комнате или турнире.", "Запрошенный объект не найден.",
    "Этот запрос уже обработан.", "Сервис временно недоступен. Повторите попытку.",
    "Не удалось выполнить действие. Повторите попытку.", "Введённые данные недействительны.", "Срок действия приглашения истёк.",
    "Пароль обновлён.", "Инструкции по сбросу пароля отправлены.", "Пароль сброшен. Теперь можно войти.",
    "Код подтверждения отправлен на вашу почту.", "Адрес электронной почты подтверждён.",
    "На выбранном устройстве выполнен выход.", "На всех устройствах выполнен выход.", "Ваша учётная запись удалена.",
    "{player} хочет добавить вас в друзья.", "{player} приглашает вас в {room}.", "{title}: {description}",
    "Вы открыли {item}.", "{mission} • Получите {reward}.", "Создан закрытый турнир на {players} игроков.",
    "Приглашение на турнир отправлено.", "Приглашение на турнир отклонено.", "Друг отклонил приглашение на турнир.",
    "Вы присоединились к {tournament}.", "Организатор отменил турнир.", "Вы покинули турнир.",
    "Запрос в друзья отправлен.", "Запрос в друзья отменён.", "Запрос в друзья принят.", "Запрос в друзья отклонён.",
    "Друг удалён.", "Игрок заблокирован.", "Игрок разблокирован.", "Приглашение в комнату отклонено.",
    "Ваш друг отклонил приглашение в комнату.", "Организатор удалил вас из комнаты.", "Вы покинули экран результатов.",
    "Организатор покинул комнату.", "{player} покинул комнату.", "Игрок слишком долго был отключён.",
    "Клан создан.", "Запрос отправлен. Ожидайте решения главы клана.", "Игрок {player} принят.", "Игрок {player} отклонён.",
    "Ваш запрос на вступление в {clan} принят.", "Ваш запрос на вступление в {clan} отклонён.",
    "Вы покинули клан.", "Сезон {season}", "Золото и Gem в зависимости от наивысшего ранга", "Первая победа", "Одержите первую победу",
    "{player} хочет вступить в {clan}.", "Заявка в клан принята", "Заявка в клан отклонена", "{player} приглашает вас вступить в {clan}.",
    "Стартовый сезон"
)
