package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.AppLanguage
import com.hienthai.fastowin.localization.TextKey

/** Copy discovered by the final hard-coded-text migration. English is the reviewed fallback. */
internal fun residualTexts(language: AppLanguage): Map<TextKey, String> =
    if (language == AppLanguage.VIETNAMESE) vietnameseResidualTexts else englishResidualTexts

private val englishResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Install Fast To Win",
    TextKey.SettingsInstallSubtitle to "Open the game quickly like a standalone app on this device.",
    TextKey.SettingsInstallRetry to "TRY OPENING INSTALLER",
    TextKey.SettingsInstallAction to "INSTALL FAST TO WIN",
    TextKey.SettingsInstallOpening to "OPENING INSTALLER",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: open the browser menu and choose Install app. Safari on iPhone/iPad: choose Share → Add to Home Screen.",
    TextKey.SettingsNotificationsTitle to "Notifications",
    TextKey.SettingsNotificationsSubtitle to "Choose exactly which updates you want to receive.",
    TextKey.SettingsDeviceNotifications to "Device notifications",
    TextKey.SettingsRoomInvitationsTitle to "Room invitations",
    TextKey.SettingsRoomInvitationsSubtitle to "When a friend invites you to a game room",
    TextKey.SettingsTournamentInvitationsTitle to "Tournament invitations",
    TextKey.SettingsTournamentInvitationsSubtitle to "When a friend invites you to a tournament",
    TextKey.SettingsMissionRewardsTitle to "Missions and rewards",
    TextKey.SettingsMissionRewardsSubtitle to "When you complete a mission",
    TextKey.SettingsDailyCheckInTitle to "Check-in reminder",
    TextKey.SettingsDailyCheckInSubtitle to "Once a day if you have not claimed the reward",
    TextKey.SettingsFeedbackTitle to "Gameplay feedback",
    TextKey.SettingsFeedbackSubtitle to "Applies immediately when you tap the number board.",
    TextKey.SettingsSoundTitle to "Sound effects",
    TextKey.SettingsSoundSubtitle to "Feedback for correct, wrong and match completion",
    TextKey.SettingsVibrationTitle to "Haptic feedback",
    TextKey.SettingsVibrationSubtitle to "A light vibration when you tap a number",
    TextKey.SettingsVisualEffectsTitle to "Visual effects",
    TextKey.SettingsVisualEffectsSubtitle to "Combos and close-score alerts",
    TextKey.SettingsPreviewSound to "Preview sound",
    TextKey.SettingsThemeTitle to "App theme",
    TextKey.ThemeSystem to "System",
    TextKey.ThemeLight to "Light",
    TextKey.ThemeDark to "Dark",
    TextKey.SettingsBoardStyleTitle to "Number board color",
    TextKey.BoardClassic to "Classic",
    TextKey.BoardOcean to "Ocean",
    TextKey.BoardHighContrast to "High contrast",
    TextKey.SettingsFontSizeTitle to "Text size",
    TextKey.FontCompact to "Small",
    TextKey.FontStandard to "Standard",
    TextKey.FontLarge to "Large",
    TextKey.SettingsOpenTutorial to "View tutorial again",
    TextKey.SettingsResetDefaults to "Restore default settings",
    TextKey.SettingsHeroEyebrow to "PREFERENCES",
    TextKey.SettingsHeroTitle to "Play your way",
    TextKey.SettingsHeroSubtitle to "Sound, haptics and appearance are saved on this device.",
    TextKey.InstallAvailableTitle to "Ready to install",
    TextKey.InstallAvailableSubtitle to "No download file needed; updates are automatic.",
    TextKey.InstallInstallingTitle to "Waiting for confirmation",
    TextKey.InstallInstallingSubtitle to "Finish in the browser window.",
    TextKey.InstallInstalledTitle to "Installed on this device",
    TextKey.InstallInstalledSubtitle to "You can open the game from the home screen.",
    TextKey.InstallManualTitle to "Install from the browser menu",
    TextKey.InstallManualSubtitle to "This browser requires manual installation.",
    TextKey.InstallErrorTitle to "Could not open the installer",
    TextKey.InstallErrorSubtitle to "Try again or install from the browser menu.",
    TextKey.InstallUnsupportedTitle to "Installation unsupported",
    TextKey.InstallUnsupportedSubtitle to "Continue playing directly in the browser.",
    TextKey.PushPromptDescription to "Receive room and tournament invitations and reward reminders",
    TextKey.PushRequestingDescription to "Waiting for notification permission…",
    TextKey.PushEnabledDescription to "Invitations, missions and check-in reminders are enabled",
    TextKey.PushDisabledDescription to "Disabled on this device",
    TextKey.PushDeniedDescription to "Blocked — allow notifications in device settings",
    TextKey.PushErrorDescription to "Could not enable notifications; please try again",
    TextKey.PushUnsupportedDescription to "This device does not support notifications",
    TextKey.PushUnconfiguredDescription to "Notifications are not configured",
    TextKey.GuestSessionMissing to "No guest session is available to save. Open the room list and try again.",
    TextKey.OpenRoomLinkBlocked to "Leave the current room before opening another room link.",
    TextKey.InvalidProfileName to "Nickname must contain 1 to {maximum} characters.",
    TextKey.InvalidAvatar to "The selected avatar is invalid.",
    TextKey.RoomNameRequired to "Enter a room name.",
    TextKey.RoomUnavailable to "This room is no longer available.",
    TextKey.RematchAccepting to "Accepting the rematch invitation…",
    TextKey.RematchSent to "Rematch invitation sent.",
    TextKey.PlayerBlockedAndLeft to "Player blocked and room left.",
    TextKey.ProfileSaved to "Profile saved.",
    TextKey.RematchRequestedByYou to "You requested a rematch.",
    TextKey.RematchRequestedByOpponent to "Your opponent wants a rematch.",
    TextKey.RematchCancelledByYou to "You cancelled the rematch request.",
    TextKey.RematchCancelledByOpponent to "Your opponent cancelled the rematch request.",
    TextKey.RematchDeclinedByYou to "You declined the rematch.",
    TextKey.RematchDeclinedByOpponent to "Your opponent declined the rematch.",
    TextKey.RematchExpired to "The rematch request expired.",
    TextKey.Spectator to "Spectator",
    TextKey.WaitingForServerResult to "Waiting for the server result…",
    TextKey.ReconnectingMatch to "Connection lost. Restoring the match; the room is held for up to 30 seconds…",
    TextKey.RewardReceivedSummary to "Received {rewards}."
)

private val vietnameseResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Cài Fast To Win",
    TextKey.SettingsInstallSubtitle to "Mở game nhanh như một ứng dụng độc lập trên thiết bị này.",
    TextKey.SettingsInstallRetry to "THỬ MỞ TRÌNH CÀI ĐẶT",
    TextKey.SettingsInstallAction to "CÀI FAST TO WIN",
    TextKey.SettingsInstallOpening to "ĐANG MỞ TRÌNH CÀI ĐẶT",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: mở menu trình duyệt và chọn Cài đặt ứng dụng. Safari trên iPhone/iPad: chọn Chia sẻ → Thêm vào Màn hình chính.",
    TextKey.SettingsNotificationsTitle to "Thông báo",
    TextKey.SettingsNotificationsSubtitle to "Chọn chính xác những cập nhật bạn muốn nhận.",
    TextKey.SettingsDeviceNotifications to "Thông báo trên thiết bị",
    TextKey.SettingsRoomInvitationsTitle to "Lời mời phòng",
    TextKey.SettingsRoomInvitationsSubtitle to "Khi bạn bè mời vào phòng chơi",
    TextKey.SettingsTournamentInvitationsTitle to "Lời mời giải đấu",
    TextKey.SettingsTournamentInvitationsSubtitle to "Khi bạn bè mời tham gia giải",
    TextKey.SettingsMissionRewardsTitle to "Nhiệm vụ và phần thưởng",
    TextKey.SettingsMissionRewardsSubtitle to "Khi vừa hoàn thành một nhiệm vụ",
    TextKey.SettingsDailyCheckInTitle to "Nhắc điểm danh",
    TextKey.SettingsDailyCheckInSubtitle to "Một lần mỗi ngày nếu bạn chưa nhận quà",
    TextKey.SettingsFeedbackTitle to "Phản hồi khi chơi",
    TextKey.SettingsFeedbackSubtitle to "Áp dụng ngay khi bạn chạm vào bàn số.",
    TextKey.SettingsSoundTitle to "Âm thanh hiệu ứng",
    TextKey.SettingsSoundSubtitle to "Báo đúng, sai và kết thúc trận",
    TextKey.SettingsVibrationTitle to "Rung phản hồi",
    TextKey.SettingsVibrationSubtitle to "Rung nhẹ khi chạm số",
    TextKey.SettingsVisualEffectsTitle to "Hiệu ứng hình ảnh",
    TextKey.SettingsVisualEffectsSubtitle to "Combo và cảnh báo bám đuổi",
    TextKey.SettingsPreviewSound to "Nghe thử âm thanh",
    TextKey.SettingsThemeTitle to "Chủ đề ứng dụng",
    TextKey.ThemeSystem to "Hệ thống",
    TextKey.ThemeLight to "Sáng",
    TextKey.ThemeDark to "Tối",
    TextKey.SettingsBoardStyleTitle to "Màu bàn số",
    TextKey.BoardClassic to "Cổ điển",
    TextKey.BoardOcean to "Đại dương",
    TextKey.BoardHighContrast to "Tương phản",
    TextKey.SettingsFontSizeTitle to "Kích thước chữ",
    TextKey.FontCompact to "Nhỏ",
    TextKey.FontStandard to "Chuẩn",
    TextKey.FontLarge to "Lớn",
    TextKey.SettingsOpenTutorial to "Xem lại hướng dẫn chơi",
    TextKey.SettingsResetDefaults to "Khôi phục cài đặt mặc định",
    TextKey.SettingsHeroEyebrow to "TÙY CHỌN",
    TextKey.SettingsHeroTitle to "Chơi theo cách của bạn",
    TextKey.SettingsHeroSubtitle to "Âm thanh, rung và giao diện được lưu riêng trên thiết bị.",
    TextKey.InstallAvailableTitle to "Sẵn sàng cài đặt",
    TextKey.InstallAvailableSubtitle to "Không cần tải file, cập nhật tự động.",
    TextKey.InstallInstallingTitle to "Đang chờ xác nhận",
    TextKey.InstallInstallingSubtitle to "Hoàn tất trong cửa sổ của trình duyệt.",
    TextKey.InstallInstalledTitle to "Đã cài trên thiết bị",
    TextKey.InstallInstalledSubtitle to "Bạn có thể mở game từ màn hình chính.",
    TextKey.InstallManualTitle to "Cài từ menu trình duyệt",
    TextKey.InstallManualSubtitle to "Trình duyệt này cần thao tác cài đặt thủ công.",
    TextKey.InstallErrorTitle to "Chưa mở được trình cài đặt",
    TextKey.InstallErrorSubtitle to "Bạn có thể thử lại hoặc cài từ menu trình duyệt.",
    TextKey.InstallUnsupportedTitle to "Không hỗ trợ cài đặt",
    TextKey.InstallUnsupportedSubtitle to "Hãy tiếp tục chơi trực tiếp trên trình duyệt.",
    TextKey.PushPromptDescription to "Nhận lời mời phòng, giải đấu và nhắc phần thưởng",
    TextKey.PushRequestingDescription to "Đang chờ bạn cấp quyền thông báo…",
    TextKey.PushEnabledDescription to "Đã bật lời mời, nhiệm vụ và nhắc điểm danh",
    TextKey.PushDisabledDescription to "Đang tắt trên thiết bị này",
    TextKey.PushDeniedDescription to "Đã bị chặn — hãy cho phép trong cài đặt thiết bị",
    TextKey.PushErrorDescription to "Chưa thể bật thông báo, vui lòng thử lại",
    TextKey.PushUnsupportedDescription to "Thiết bị không hỗ trợ thông báo",
    TextKey.PushUnconfiguredDescription to "Thông báo chưa được cấu hình",
    TextKey.GuestSessionMissing to "Chưa có phiên khách để lưu. Hãy vào danh sách phòng rồi thử lại.",
    TextKey.OpenRoomLinkBlocked to "Hãy rời phòng hiện tại trước khi mở liên kết phòng khác.",
    TextKey.InvalidProfileName to "Biệt danh phải có từ 1 đến {maximum} ký tự.",
    TextKey.InvalidAvatar to "Ảnh đại diện không hợp lệ.",
    TextKey.RoomNameRequired to "Vui lòng nhập tên phòng.",
    TextKey.RoomUnavailable to "Phòng không còn khả dụng.",
    TextKey.RematchAccepting to "Đang chấp nhận lời mời đấu lại…",
    TextKey.RematchSent to "Đã gửi lời mời đấu lại.",
    TextKey.PlayerBlockedAndLeft to "Đã chặn người chơi và rời phòng.",
    TextKey.ProfileSaved to "Đã lưu hồ sơ.",
    TextKey.RematchRequestedByYou to "Đã gửi yêu cầu đấu lại.",
    TextKey.RematchRequestedByOpponent to "Đối thủ muốn đấu lại với bạn.",
    TextKey.RematchCancelledByYou to "Bạn đã hủy yêu cầu đấu lại.",
    TextKey.RematchCancelledByOpponent to "Đối thủ đã hủy yêu cầu đấu lại.",
    TextKey.RematchDeclinedByYou to "Bạn đã từ chối đấu lại.",
    TextKey.RematchDeclinedByOpponent to "Đối thủ đã từ chối đấu lại.",
    TextKey.RematchExpired to "Yêu cầu đấu lại đã hết thời gian.",
    TextKey.Spectator to "Khán giả",
    TextKey.WaitingForServerResult to "Đang chờ kết quả từ máy chủ…",
    TextKey.ReconnectingMatch to "Mất kết nối. Đang khôi phục trận, phòng được giữ tối đa 30 giây…",
    TextKey.RewardReceivedSummary to "Đã nhận {rewards}."
)
