package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.AppLanguage
import com.hienthai.fastowin.localization.TextKey

/** Copy discovered by the final hard-coded-text migration, translated for every shipped catalog. */
internal fun residualTexts(language: AppLanguage): Map<TextKey, String> = when (language) {
    AppLanguage.VIETNAMESE -> vietnameseResidualTexts
    AppLanguage.ENGLISH -> englishResidualTexts
    AppLanguage.SIMPLIFIED_CHINESE -> simplifiedChineseResidualTexts
    AppLanguage.JAPANESE -> japaneseResidualTexts
    AppLanguage.KOREAN -> koreanResidualTexts
    AppLanguage.SPANISH -> spanishResidualTexts
    AppLanguage.BRAZILIAN_PORTUGUESE -> brazilianPortugueseResidualTexts
    AppLanguage.FRENCH -> frenchResidualTexts
    AppLanguage.GERMAN -> germanResidualTexts
    AppLanguage.INDONESIAN -> indonesianResidualTexts
    AppLanguage.THAI -> thaiResidualTexts
    AppLanguage.RUSSIAN -> russianResidualTexts
}

private val englishResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Install Fast To Win",
    TextKey.SettingsInstallSubtitle to "Open the game quickly like a standalone app on this device.",
    TextKey.SettingsInstallRetry to "TRY OPENING INSTALLER",
    TextKey.SettingsInstallAction to "INSTALL FAST TO WIN",
    TextKey.SettingsInstallOpening to "OPENING INSTALLER",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: open the browser menu and choose Install app. Safari on iPhone/iPad: choose Share → Add to Home Screen.",
    TextKey.SettingsNotificationsTitle to "Notifications",
    TextKey.SettingsNotificationsSubtitle to "Choose exactly which updates you want to receive.",
    TextKey.SettingsDeviceNotifications to "Device notifications",
    TextKey.SettingsRoomInvitationsTitle to "Room invitations",
    TextKey.SettingsRoomInvitationsSubtitle to "When a friend invites you to a game room",
    TextKey.SettingsTournamentInvitationsTitle to "Tournament invitations",
    TextKey.SettingsTournamentInvitationsSubtitle to "When a friend invites you to a tournament",
    TextKey.SettingsMissionRewardsTitle to "Missions and rewards",
    TextKey.SettingsMissionRewardsSubtitle to "When you complete a mission",
    TextKey.SettingsDailyCheckInTitle to "Check-in reminder",
    TextKey.SettingsDailyCheckInSubtitle to "Once a day if you have not claimed the reward",
    TextKey.SettingsFeedbackTitle to "Gameplay feedback",
    TextKey.SettingsFeedbackSubtitle to "Applies immediately when you tap the number board.",
    TextKey.SettingsSoundTitle to "Sound effects",
    TextKey.SettingsSoundSubtitle to "Feedback for correct, wrong and match completion",
    TextKey.SettingsVibrationTitle to "Haptic feedback",
    TextKey.SettingsVibrationSubtitle to "A light vibration when you tap a number",
    TextKey.SettingsVisualEffectsTitle to "Visual effects",
    TextKey.SettingsVisualEffectsSubtitle to "Combos and close-score alerts",
    TextKey.SettingsPreviewSound to "Preview sound",
    TextKey.SettingsThemeTitle to "App theme",
    TextKey.ThemeSystem to "System",
    TextKey.ThemeLight to "Light",
    TextKey.ThemeDark to "Dark",
    TextKey.SettingsBoardStyleTitle to "Number board color",
    TextKey.BoardClassic to "Classic",
    TextKey.BoardOcean to "Ocean",
    TextKey.BoardHighContrast to "High contrast",
    TextKey.SettingsFontSizeTitle to "Text size",
    TextKey.FontCompact to "Small",
    TextKey.FontStandard to "Standard",
    TextKey.FontLarge to "Large",
    TextKey.SettingsOpenTutorial to "View tutorial again",
    TextKey.SettingsResetDefaults to "Restore default settings",
    TextKey.SettingsHeroEyebrow to "PREFERENCES",
    TextKey.SettingsHeroTitle to "Play your way",
    TextKey.SettingsHeroSubtitle to "Sound, haptics and appearance are saved on this device.",
    TextKey.InstallAvailableTitle to "Ready to install",
    TextKey.InstallAvailableSubtitle to "No download file needed; updates are automatic.",
    TextKey.InstallInstallingTitle to "Waiting for confirmation",
    TextKey.InstallInstallingSubtitle to "Finish in the browser window.",
    TextKey.InstallInstalledTitle to "Installed on this device",
    TextKey.InstallInstalledSubtitle to "You can open the game from the home screen.",
    TextKey.InstallManualTitle to "Install from the browser menu",
    TextKey.InstallManualSubtitle to "This browser requires manual installation.",
    TextKey.InstallErrorTitle to "Could not open the installer",
    TextKey.InstallErrorSubtitle to "Try again or install from the browser menu.",
    TextKey.InstallUnsupportedTitle to "Installation unsupported",
    TextKey.InstallUnsupportedSubtitle to "Continue playing directly in the browser.",
    TextKey.PushPromptDescription to "Receive room and tournament invitations and reward reminders",
    TextKey.PushRequestingDescription to "Waiting for notification permission…",
    TextKey.PushEnabledDescription to "Invitations, missions and check-in reminders are enabled",
    TextKey.PushDisabledDescription to "Disabled on this device",
    TextKey.PushDeniedDescription to "Blocked — allow notifications in device settings",
    TextKey.PushErrorDescription to "Could not enable notifications; please try again",
    TextKey.PushUnsupportedDescription to "This device does not support notifications",
    TextKey.PushUnconfiguredDescription to "Notifications are not configured",
    TextKey.GuestSessionMissing to "No guest session is available to save. Open the room list and try again.",
    TextKey.OpenRoomLinkBlocked to "Leave the current room before opening another room link.",
    TextKey.InvalidProfileName to "Nickname must contain 1 to {maximum} characters.",
    TextKey.InvalidAvatar to "The selected avatar is invalid.",
    TextKey.RoomNameRequired to "Enter a room name.",
    TextKey.RoomUnavailable to "This room is no longer available.",
    TextKey.RematchAccepting to "Accepting the rematch invitation…",
    TextKey.RematchSent to "Rematch invitation sent.",
    TextKey.PlayerBlockedAndLeft to "Player blocked and room left.",
    TextKey.ProfileSaved to "Profile saved.",
    TextKey.RematchRequestedByYou to "You requested a rematch.",
    TextKey.RematchRequestedByOpponent to "Your opponent wants a rematch.",
    TextKey.RematchCancelledByYou to "You cancelled the rematch request.",
    TextKey.RematchCancelledByOpponent to "Your opponent cancelled the rematch request.",
    TextKey.RematchDeclinedByYou to "You declined the rematch.",
    TextKey.RematchDeclinedByOpponent to "Your opponent declined the rematch.",
    TextKey.RematchExpired to "The rematch request expired.",
    TextKey.Spectator to "Spectator",
    TextKey.WaitingForServerResult to "Waiting for the server result…",
    TextKey.ReconnectingMatch to "Connection lost. Restoring the match; the room is held for up to 30 seconds…",
    TextKey.ReconnectAction to "RETRY NOW",
    TextKey.ReconnectBlockingHint to "The board is locked until the server restores the match.",
    TextKey.MatchExpiredOfficialLoss to "The room expired while you were disconnected. This match is an official loss.",
    TextKey.RewardReceivedSummary to "Received {rewards}."
)

private val vietnameseResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Cài Fast To Win",
    TextKey.SettingsInstallSubtitle to "Mở game nhanh như một ứng dụng độc lập trên thiết bị này.",
    TextKey.SettingsInstallRetry to "THỬ MỞ TRÌNH CÀI ĐẶT",
    TextKey.SettingsInstallAction to "CÀI FAST TO WIN",
    TextKey.SettingsInstallOpening to "ĐANG MỞ TRÌNH CÀI ĐẶT",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: mở menu trình duyệt và chọn Cài đặt ứng dụng. Safari trên iPhone/iPad: chọn Chia sẻ → Thêm vào Màn hình chính.",
    TextKey.SettingsNotificationsTitle to "Thông báo",
    TextKey.SettingsNotificationsSubtitle to "Chọn chính xác những cập nhật bạn muốn nhận.",
    TextKey.SettingsDeviceNotifications to "Thông báo trên thiết bị",
    TextKey.SettingsRoomInvitationsTitle to "Lời mời phòng",
    TextKey.SettingsRoomInvitationsSubtitle to "Khi bạn bè mời vào phòng chơi",
    TextKey.SettingsTournamentInvitationsTitle to "Lời mời giải đấu",
    TextKey.SettingsTournamentInvitationsSubtitle to "Khi bạn bè mời tham gia giải",
    TextKey.SettingsMissionRewardsTitle to "Nhiệm vụ và phần thưởng",
    TextKey.SettingsMissionRewardsSubtitle to "Khi vừa hoàn thành một nhiệm vụ",
    TextKey.SettingsDailyCheckInTitle to "Nhắc điểm danh",
    TextKey.SettingsDailyCheckInSubtitle to "Một lần mỗi ngày nếu bạn chưa nhận quà",
    TextKey.SettingsFeedbackTitle to "Phản hồi khi chơi",
    TextKey.SettingsFeedbackSubtitle to "Áp dụng ngay khi bạn chạm vào bàn số.",
    TextKey.SettingsSoundTitle to "Âm thanh hiệu ứng",
    TextKey.SettingsSoundSubtitle to "Báo đúng, sai và kết thúc trận",
    TextKey.SettingsVibrationTitle to "Rung phản hồi",
    TextKey.SettingsVibrationSubtitle to "Rung nhẹ khi chạm số",
    TextKey.SettingsVisualEffectsTitle to "Hiệu ứng hình ảnh",
    TextKey.SettingsVisualEffectsSubtitle to "Combo và cảnh báo bám đuổi",
    TextKey.SettingsPreviewSound to "Nghe thử âm thanh",
    TextKey.SettingsThemeTitle to "Chủ đề ứng dụng",
    TextKey.ThemeSystem to "Hệ thống",
    TextKey.ThemeLight to "Sáng",
    TextKey.ThemeDark to "Tối",
    TextKey.SettingsBoardStyleTitle to "Màu bàn số",
    TextKey.BoardClassic to "Cổ điển",
    TextKey.BoardOcean to "Đại dương",
    TextKey.BoardHighContrast to "Tương phản",
    TextKey.SettingsFontSizeTitle to "Kích thước chữ",
    TextKey.FontCompact to "Nhỏ",
    TextKey.FontStandard to "Chuẩn",
    TextKey.FontLarge to "Lớn",
    TextKey.SettingsOpenTutorial to "Xem lại hướng dẫn chơi",
    TextKey.SettingsResetDefaults to "Khôi phục cài đặt mặc định",
    TextKey.SettingsHeroEyebrow to "TÙY CHỌN",
    TextKey.SettingsHeroTitle to "Chơi theo cách của bạn",
    TextKey.SettingsHeroSubtitle to "Âm thanh, rung và giao diện được lưu riêng trên thiết bị.",
    TextKey.InstallAvailableTitle to "Sẵn sàng cài đặt",
    TextKey.InstallAvailableSubtitle to "Không cần tải file, cập nhật tự động.",
    TextKey.InstallInstallingTitle to "Đang chờ xác nhận",
    TextKey.InstallInstallingSubtitle to "Hoàn tất trong cửa sổ của trình duyệt.",
    TextKey.InstallInstalledTitle to "Đã cài trên thiết bị",
    TextKey.InstallInstalledSubtitle to "Bạn có thể mở game từ màn hình chính.",
    TextKey.InstallManualTitle to "Cài từ menu trình duyệt",
    TextKey.InstallManualSubtitle to "Trình duyệt này cần thao tác cài đặt thủ công.",
    TextKey.InstallErrorTitle to "Chưa mở được trình cài đặt",
    TextKey.InstallErrorSubtitle to "Bạn có thể thử lại hoặc cài từ menu trình duyệt.",
    TextKey.InstallUnsupportedTitle to "Không hỗ trợ cài đặt",
    TextKey.InstallUnsupportedSubtitle to "Hãy tiếp tục chơi trực tiếp trên trình duyệt.",
    TextKey.PushPromptDescription to "Nhận lời mời phòng, giải đấu và nhắc phần thưởng",
    TextKey.PushRequestingDescription to "Đang chờ bạn cấp quyền thông báo…",
    TextKey.PushEnabledDescription to "Đã bật lời mời, nhiệm vụ và nhắc điểm danh",
    TextKey.PushDisabledDescription to "Đang tắt trên thiết bị này",
    TextKey.PushDeniedDescription to "Đã bị chặn — hãy cho phép trong cài đặt thiết bị",
    TextKey.PushErrorDescription to "Chưa thể bật thông báo, vui lòng thử lại",
    TextKey.PushUnsupportedDescription to "Thiết bị không hỗ trợ thông báo",
    TextKey.PushUnconfiguredDescription to "Thông báo chưa được cấu hình",
    TextKey.GuestSessionMissing to "Chưa có phiên khách để lưu. Hãy vào danh sách phòng rồi thử lại.",
    TextKey.OpenRoomLinkBlocked to "Hãy rời phòng hiện tại trước khi mở liên kết phòng khác.",
    TextKey.InvalidProfileName to "Biệt danh phải có từ 1 đến {maximum} ký tự.",
    TextKey.InvalidAvatar to "Ảnh đại diện không hợp lệ.",
    TextKey.RoomNameRequired to "Vui lòng nhập tên phòng.",
    TextKey.RoomUnavailable to "Phòng không còn khả dụng.",
    TextKey.RematchAccepting to "Đang chấp nhận lời mời đấu lại…",
    TextKey.RematchSent to "Đã gửi lời mời đấu lại.",
    TextKey.PlayerBlockedAndLeft to "Đã chặn người chơi và rời phòng.",
    TextKey.ProfileSaved to "Đã lưu hồ sơ.",
    TextKey.RematchRequestedByYou to "Đã gửi yêu cầu đấu lại.",
    TextKey.RematchRequestedByOpponent to "Đối thủ muốn đấu lại với bạn.",
    TextKey.RematchCancelledByYou to "Bạn đã hủy yêu cầu đấu lại.",
    TextKey.RematchCancelledByOpponent to "Đối thủ đã hủy yêu cầu đấu lại.",
    TextKey.RematchDeclinedByYou to "Bạn đã từ chối đấu lại.",
    TextKey.RematchDeclinedByOpponent to "Đối thủ đã từ chối đấu lại.",
    TextKey.RematchExpired to "Yêu cầu đấu lại đã hết thời gian.",
    TextKey.Spectator to "Khán giả",
    TextKey.WaitingForServerResult to "Đang chờ kết quả từ máy chủ…",
    TextKey.ReconnectingMatch to "Mất kết nối. Đang khôi phục trận, phòng được giữ tối đa 30 giây…",
    TextKey.ReconnectAction to "THỬ LẠI NGAY",
    TextKey.ReconnectBlockingHint to "Bàn số bị khóa cho đến khi máy chủ khôi phục trận.",
    TextKey.MatchExpiredOfficialLoss to "Phòng đã hết hạn khi bạn mất kết nối. Trận này được tính là thua chính thức.",
    TextKey.RewardReceivedSummary to "Đã nhận {rewards}."
)

private val japaneseResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Fast To Winをインストール",
    TextKey.SettingsInstallSubtitle to "この端末で単体アプリのようにゲームをすぐ開けます。",
    TextKey.SettingsInstallRetry to "インストーラーを再度開く",
    TextKey.SettingsInstallAction to "FAST TO WINをインストール",
    TextKey.SettingsInstallOpening to "インストーラーを開いています",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge：ブラウザのメニューから「アプリをインストール」を選択します。iPhone/iPadのSafari：「共有」→「ホーム画面に追加」を選択します。",
    TextKey.SettingsNotificationsTitle to "通知",
    TextKey.SettingsNotificationsSubtitle to "受け取りたい更新を個別に選択できます。",
    TextKey.SettingsDeviceNotifications to "端末の通知",
    TextKey.SettingsRoomInvitationsTitle to "ルーム招待",
    TextKey.SettingsRoomInvitationsSubtitle to "フレンドがゲームルームに招待したとき",
    TextKey.SettingsTournamentInvitationsTitle to "大会招待",
    TextKey.SettingsTournamentInvitationsSubtitle to "フレンドが大会に招待したとき",
    TextKey.SettingsMissionRewardsTitle to "ミッションと報酬",
    TextKey.SettingsMissionRewardsSubtitle to "ミッションを達成したとき",
    TextKey.SettingsDailyCheckInTitle to "チェックイン通知",
    TextKey.SettingsDailyCheckInSubtitle to "報酬を受け取っていない日に1回通知します",
    TextKey.SettingsFeedbackTitle to "プレイ中のフィードバック",
    TextKey.SettingsFeedbackSubtitle to "数字ボードをタップするとすぐに反映されます。",
    TextKey.SettingsSoundTitle to "効果音",
    TextKey.SettingsSoundSubtitle to "正解、不正解、対戦終了時のフィードバック",
    TextKey.SettingsVibrationTitle to "触覚フィードバック",
    TextKey.SettingsVibrationSubtitle to "数字をタップしたときに軽く振動します",
    TextKey.SettingsVisualEffectsTitle to "視覚効果",
    TextKey.SettingsVisualEffectsSubtitle to "コンボと接戦アラート",
    TextKey.SettingsPreviewSound to "効果音を試聴",
    TextKey.SettingsThemeTitle to "アプリのテーマ",
    TextKey.ThemeSystem to "システム",
    TextKey.ThemeLight to "ライト",
    TextKey.ThemeDark to "ダーク",
    TextKey.SettingsBoardStyleTitle to "数字ボードの色",
    TextKey.BoardClassic to "クラシック",
    TextKey.BoardOcean to "オーシャン",
    TextKey.BoardHighContrast to "ハイコントラスト",
    TextKey.SettingsFontSizeTitle to "文字サイズ",
    TextKey.FontCompact to "小",
    TextKey.FontStandard to "標準",
    TextKey.FontLarge to "大",
    TextKey.SettingsOpenTutorial to "チュートリアルをもう一度見る",
    TextKey.SettingsResetDefaults to "初期設定に戻す",
    TextKey.SettingsHeroEyebrow to "設定",
    TextKey.SettingsHeroTitle to "自分らしくプレイ",
    TextKey.SettingsHeroSubtitle to "サウンド、振動、表示設定はこの端末に保存されます。",
    TextKey.InstallAvailableTitle to "インストールできます",
    TextKey.InstallAvailableSubtitle to "ファイルのダウンロードは不要で、更新は自動です。",
    TextKey.InstallInstallingTitle to "確認待ち",
    TextKey.InstallInstallingSubtitle to "ブラウザの画面で完了してください。",
    TextKey.InstallInstalledTitle to "この端末にインストール済み",
    TextKey.InstallInstalledSubtitle to "ホーム画面からゲームを開けます。",
    TextKey.InstallManualTitle to "ブラウザメニューからインストール",
    TextKey.InstallManualSubtitle to "このブラウザでは手動でのインストールが必要です。",
    TextKey.InstallErrorTitle to "インストーラーを開けませんでした",
    TextKey.InstallErrorSubtitle to "もう一度試すか、ブラウザメニューからインストールしてください。",
    TextKey.InstallUnsupportedTitle to "インストール非対応",
    TextKey.InstallUnsupportedSubtitle to "ブラウザでそのままプレイできます。",
    TextKey.PushPromptDescription to "ルームや大会の招待、報酬のお知らせを受け取る",
    TextKey.PushRequestingDescription to "通知の許可を待っています…",
    TextKey.PushEnabledDescription to "招待、ミッション、チェックイン通知が有効です",
    TextKey.PushDisabledDescription to "この端末では無効です",
    TextKey.PushDeniedDescription to "ブロックされています — 端末の設定で通知を許可してください",
    TextKey.PushErrorDescription to "通知を有効にできませんでした。もう一度お試しください",
    TextKey.PushUnsupportedDescription to "この端末は通知に対応していません",
    TextKey.PushUnconfiguredDescription to "通知が設定されていません",
    TextKey.GuestSessionMissing to "保存できるゲストセッションがありません。ルーム一覧を開いてもう一度お試しください。",
    TextKey.OpenRoomLinkBlocked to "別のルームリンクを開く前に、現在のルームから退出してください。",
    TextKey.InvalidProfileName to "ニックネームは1〜{maximum}文字で入力してください。",
    TextKey.InvalidAvatar to "選択したアバターは無効です。",
    TextKey.RoomNameRequired to "ルーム名を入力してください。",
    TextKey.RoomUnavailable to "このルームは利用できません。",
    TextKey.RematchAccepting to "再戦の招待を承認しています…",
    TextKey.RematchSent to "再戦の招待を送信しました。",
    TextKey.PlayerBlockedAndLeft to "プレイヤーをブロックしてルームから退出しました。",
    TextKey.ProfileSaved to "プロフィールを保存しました。",
    TextKey.RematchRequestedByYou to "再戦をリクエストしました。",
    TextKey.RematchRequestedByOpponent to "対戦相手が再戦を希望しています。",
    TextKey.RematchCancelledByYou to "再戦リクエストをキャンセルしました。",
    TextKey.RematchCancelledByOpponent to "対戦相手が再戦リクエストをキャンセルしました。",
    TextKey.RematchDeclinedByYou to "再戦を辞退しました。",
    TextKey.RematchDeclinedByOpponent to "対戦相手が再戦を辞退しました。",
    TextKey.RematchExpired to "再戦リクエストの期限が切れました。",
    TextKey.Spectator to "観戦者",
    TextKey.WaitingForServerResult to "サーバーの結果を待っています…",
    TextKey.ReconnectingMatch to "接続が切れました。対戦を復元しています。ルームは最大30秒間保持されます…",
    TextKey.ReconnectAction to "今すぐ再試行",
    TextKey.ReconnectBlockingHint to "サーバーが対戦を復元するまでボードはロックされています。",
    TextKey.MatchExpiredOfficialLoss to "切断中にルームの期限が切れました。この対戦は公式の敗北として記録されます。",
    TextKey.RewardReceivedSummary to "{rewards}を受け取りました。"
)

private val koreanResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Fast To Win 설치",
    TextKey.SettingsInstallSubtitle to "이 기기에서 독립 실행형 앱처럼 게임을 빠르게 여세요.",
    TextKey.SettingsInstallRetry to "설치 프로그램 다시 열기",
    TextKey.SettingsInstallAction to "FAST TO WIN 설치",
    TextKey.SettingsInstallOpening to "설치 프로그램 여는 중",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: 브라우저 메뉴에서 앱 설치를 선택하세요. iPhone/iPad의 Safari: 공유 → 홈 화면에 추가를 선택하세요.",
    TextKey.SettingsNotificationsTitle to "알림",
    TextKey.SettingsNotificationsSubtitle to "받고 싶은 업데이트를 정확히 선택하세요.",
    TextKey.SettingsDeviceNotifications to "기기 알림",
    TextKey.SettingsRoomInvitationsTitle to "방 초대",
    TextKey.SettingsRoomInvitationsSubtitle to "친구가 게임 방에 초대할 때",
    TextKey.SettingsTournamentInvitationsTitle to "토너먼트 초대",
    TextKey.SettingsTournamentInvitationsSubtitle to "친구가 토너먼트에 초대할 때",
    TextKey.SettingsMissionRewardsTitle to "미션과 보상",
    TextKey.SettingsMissionRewardsSubtitle to "미션을 완료할 때",
    TextKey.SettingsDailyCheckInTitle to "출석 알림",
    TextKey.SettingsDailyCheckInSubtitle to "보상을 받지 않은 경우 하루에 한 번",
    TextKey.SettingsFeedbackTitle to "게임 피드백",
    TextKey.SettingsFeedbackSubtitle to "숫자판을 누르면 즉시 적용됩니다.",
    TextKey.SettingsSoundTitle to "효과음",
    TextKey.SettingsSoundSubtitle to "정답, 오답 및 경기 종료 피드백",
    TextKey.SettingsVibrationTitle to "햅틱 피드백",
    TextKey.SettingsVibrationSubtitle to "숫자를 누를 때 가볍게 진동합니다",
    TextKey.SettingsVisualEffectsTitle to "시각 효과",
    TextKey.SettingsVisualEffectsSubtitle to "콤보 및 접전 알림",
    TextKey.SettingsPreviewSound to "효과음 미리 듣기",
    TextKey.SettingsThemeTitle to "앱 테마",
    TextKey.ThemeSystem to "시스템",
    TextKey.ThemeLight to "라이트",
    TextKey.ThemeDark to "다크",
    TextKey.SettingsBoardStyleTitle to "숫자판 색상",
    TextKey.BoardClassic to "클래식",
    TextKey.BoardOcean to "오션",
    TextKey.BoardHighContrast to "고대비",
    TextKey.SettingsFontSizeTitle to "글자 크기",
    TextKey.FontCompact to "작게",
    TextKey.FontStandard to "표준",
    TextKey.FontLarge to "크게",
    TextKey.SettingsOpenTutorial to "튜토리얼 다시 보기",
    TextKey.SettingsResetDefaults to "기본 설정 복원",
    TextKey.SettingsHeroEyebrow to "환경설정",
    TextKey.SettingsHeroTitle to "나만의 방식으로 플레이",
    TextKey.SettingsHeroSubtitle to "소리, 진동 및 화면 설정은 이 기기에 저장됩니다.",
    TextKey.InstallAvailableTitle to "설치 준비 완료",
    TextKey.InstallAvailableSubtitle to "파일을 다운로드할 필요가 없으며 업데이트는 자동입니다.",
    TextKey.InstallInstallingTitle to "확인 대기 중",
    TextKey.InstallInstallingSubtitle to "브라우저 창에서 완료하세요.",
    TextKey.InstallInstalledTitle to "이 기기에 설치됨",
    TextKey.InstallInstalledSubtitle to "홈 화면에서 게임을 열 수 있습니다.",
    TextKey.InstallManualTitle to "브라우저 메뉴에서 설치",
    TextKey.InstallManualSubtitle to "이 브라우저는 수동 설치가 필요합니다.",
    TextKey.InstallErrorTitle to "설치 프로그램을 열 수 없음",
    TextKey.InstallErrorSubtitle to "다시 시도하거나 브라우저 메뉴에서 설치하세요.",
    TextKey.InstallUnsupportedTitle to "설치가 지원되지 않음",
    TextKey.InstallUnsupportedSubtitle to "브라우저에서 바로 계속 플레이하세요.",
    TextKey.PushPromptDescription to "방 및 토너먼트 초대와 보상 알림 받기",
    TextKey.PushRequestingDescription to "알림 권한을 기다리는 중…",
    TextKey.PushEnabledDescription to "초대, 미션 및 출석 알림이 활성화되었습니다",
    TextKey.PushDisabledDescription to "이 기기에서 비활성화됨",
    TextKey.PushDeniedDescription to "차단됨 — 기기 설정에서 알림을 허용하세요",
    TextKey.PushErrorDescription to "알림을 활성화할 수 없습니다. 다시 시도하세요",
    TextKey.PushUnsupportedDescription to "이 기기는 알림을 지원하지 않습니다",
    TextKey.PushUnconfiguredDescription to "알림이 설정되지 않았습니다",
    TextKey.GuestSessionMissing to "저장할 게스트 세션이 없습니다. 방 목록을 열고 다시 시도하세요.",
    TextKey.OpenRoomLinkBlocked to "다른 방 링크를 열기 전에 현재 방에서 나가세요.",
    TextKey.InvalidProfileName to "닉네임은 1~{maximum}자여야 합니다.",
    TextKey.InvalidAvatar to "선택한 아바타가 올바르지 않습니다.",
    TextKey.RoomNameRequired to "방 이름을 입력하세요.",
    TextKey.RoomUnavailable to "이 방은 더 이상 이용할 수 없습니다.",
    TextKey.RematchAccepting to "재대결 초대를 수락하는 중…",
    TextKey.RematchSent to "재대결 초대를 보냈습니다.",
    TextKey.PlayerBlockedAndLeft to "플레이어를 차단하고 방에서 나갔습니다.",
    TextKey.ProfileSaved to "프로필을 저장했습니다.",
    TextKey.RematchRequestedByYou to "재대결을 요청했습니다.",
    TextKey.RematchRequestedByOpponent to "상대가 재대결을 원합니다.",
    TextKey.RematchCancelledByYou to "재대결 요청을 취소했습니다.",
    TextKey.RematchCancelledByOpponent to "상대가 재대결 요청을 취소했습니다.",
    TextKey.RematchDeclinedByYou to "재대결을 거절했습니다.",
    TextKey.RematchDeclinedByOpponent to "상대가 재대결을 거절했습니다.",
    TextKey.RematchExpired to "재대결 요청이 만료되었습니다.",
    TextKey.Spectator to "관전자",
    TextKey.WaitingForServerResult to "서버 결과를 기다리는 중…",
    TextKey.ReconnectingMatch to "연결이 끊겼습니다. 경기를 복원 중이며 방은 최대 30초 동안 유지됩니다…",
    TextKey.ReconnectAction to "지금 재시도",
    TextKey.ReconnectBlockingHint to "서버가 경기를 복원할 때까지 보드가 잠깁니다.",
    TextKey.MatchExpiredOfficialLoss to "연결이 끊긴 동안 방이 만료되었습니다. 이 경기는 공식 패배로 기록됩니다.",
    TextKey.RewardReceivedSummary to "{rewards}을(를) 받았습니다."
)

private val simplifiedChineseResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "安装 Fast To Win",
    TextKey.SettingsInstallSubtitle to "在此设备上像独立应用一样快速打开游戏。",
    TextKey.SettingsInstallRetry to "再次打开安装程序",
    TextKey.SettingsInstallAction to "安装 FAST TO WIN",
    TextKey.SettingsInstallOpening to "正在打开安装程序",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge：打开浏览器菜单并选择“安装应用”。iPhone/iPad 上的 Safari：选择“共享”→“添加到主屏幕”。",
    TextKey.SettingsNotificationsTitle to "通知",
    TextKey.SettingsNotificationsSubtitle to "准确选择你想接收的更新。",
    TextKey.SettingsDeviceNotifications to "设备通知",
    TextKey.SettingsRoomInvitationsTitle to "房间邀请",
    TextKey.SettingsRoomInvitationsSubtitle to "好友邀请你加入游戏房间时",
    TextKey.SettingsTournamentInvitationsTitle to "锦标赛邀请",
    TextKey.SettingsTournamentInvitationsSubtitle to "好友邀请你参加锦标赛时",
    TextKey.SettingsMissionRewardsTitle to "任务与奖励",
    TextKey.SettingsMissionRewardsSubtitle to "完成任务时",
    TextKey.SettingsDailyCheckInTitle to "签到提醒",
    TextKey.SettingsDailyCheckInSubtitle to "尚未领取奖励时每天提醒一次",
    TextKey.SettingsFeedbackTitle to "游戏反馈",
    TextKey.SettingsFeedbackSubtitle to "点击数字棋盘后立即生效。",
    TextKey.SettingsSoundTitle to "音效",
    TextKey.SettingsSoundSubtitle to "答对、答错和比赛结束时的反馈",
    TextKey.SettingsVibrationTitle to "触觉反馈",
    TextKey.SettingsVibrationSubtitle to "点击数字时轻微振动",
    TextKey.SettingsVisualEffectsTitle to "视觉效果",
    TextKey.SettingsVisualEffectsSubtitle to "连击和比分接近提醒",
    TextKey.SettingsPreviewSound to "试听音效",
    TextKey.SettingsThemeTitle to "应用主题",
    TextKey.ThemeSystem to "跟随系统",
    TextKey.ThemeLight to "浅色",
    TextKey.ThemeDark to "深色",
    TextKey.SettingsBoardStyleTitle to "数字棋盘颜色",
    TextKey.BoardClassic to "经典",
    TextKey.BoardOcean to "海洋",
    TextKey.BoardHighContrast to "高对比度",
    TextKey.SettingsFontSizeTitle to "文字大小",
    TextKey.FontCompact to "小",
    TextKey.FontStandard to "标准",
    TextKey.FontLarge to "大",
    TextKey.SettingsOpenTutorial to "再次查看教程",
    TextKey.SettingsResetDefaults to "恢复默认设置",
    TextKey.SettingsHeroEyebrow to "偏好设置",
    TextKey.SettingsHeroTitle to "按你的方式游戏",
    TextKey.SettingsHeroSubtitle to "声音、触觉和外观设置保存在此设备上。",
    TextKey.InstallAvailableTitle to "可以安装",
    TextKey.InstallAvailableSubtitle to "无需下载文件，更新会自动完成。",
    TextKey.InstallInstallingTitle to "等待确认",
    TextKey.InstallInstallingSubtitle to "请在浏览器窗口中完成。",
    TextKey.InstallInstalledTitle to "已安装到此设备",
    TextKey.InstallInstalledSubtitle to "你可以从主屏幕打开游戏。",
    TextKey.InstallManualTitle to "从浏览器菜单安装",
    TextKey.InstallManualSubtitle to "此浏览器需要手动安装。",
    TextKey.InstallErrorTitle to "无法打开安装程序",
    TextKey.InstallErrorSubtitle to "请重试或从浏览器菜单安装。",
    TextKey.InstallUnsupportedTitle to "不支持安装",
    TextKey.InstallUnsupportedSubtitle to "请继续在浏览器中直接游戏。",
    TextKey.PushPromptDescription to "接收房间和锦标赛邀请以及奖励提醒",
    TextKey.PushRequestingDescription to "正在等待通知权限…",
    TextKey.PushEnabledDescription to "邀请、任务和签到提醒已启用",
    TextKey.PushDisabledDescription to "已在此设备上停用",
    TextKey.PushDeniedDescription to "已阻止 — 请在设备设置中允许通知",
    TextKey.PushErrorDescription to "无法启用通知，请重试",
    TextKey.PushUnsupportedDescription to "此设备不支持通知",
    TextKey.PushUnconfiguredDescription to "通知尚未配置",
    TextKey.GuestSessionMissing to "没有可保存的访客会话。请打开房间列表后重试。",
    TextKey.OpenRoomLinkBlocked to "打开其他房间链接前，请先离开当前房间。",
    TextKey.InvalidProfileName to "昵称必须为 1 到 {maximum} 个字符。",
    TextKey.InvalidAvatar to "所选头像无效。",
    TextKey.RoomNameRequired to "请输入房间名称。",
    TextKey.RoomUnavailable to "此房间已不可用。",
    TextKey.RematchAccepting to "正在接受再战邀请…",
    TextKey.RematchSent to "再战邀请已发送。",
    TextKey.PlayerBlockedAndLeft to "已屏蔽玩家并离开房间。",
    TextKey.ProfileSaved to "个人资料已保存。",
    TextKey.RematchRequestedByYou to "你已请求再战。",
    TextKey.RematchRequestedByOpponent to "对手想要再战。",
    TextKey.RematchCancelledByYou to "你已取消再战请求。",
    TextKey.RematchCancelledByOpponent to "对手已取消再战请求。",
    TextKey.RematchDeclinedByYou to "你已拒绝再战。",
    TextKey.RematchDeclinedByOpponent to "对手已拒绝再战。",
    TextKey.RematchExpired to "再战请求已过期。",
    TextKey.Spectator to "观战者",
    TextKey.WaitingForServerResult to "正在等待服务器结果…",
    TextKey.ReconnectingMatch to "连接已断开。正在恢复比赛，房间最多保留 30 秒…",
    TextKey.ReconnectAction to "立即重试",
    TextKey.ReconnectBlockingHint to "服务器恢复比赛前，数字面板已锁定。",
    TextKey.MatchExpiredOfficialLoss to "断线期间房间已过期。本场比赛将记为正式失利。",
    TextKey.RewardReceivedSummary to "已收到 {rewards}。"
)

private val spanishResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Instalar Fast To Win",
    TextKey.SettingsInstallSubtitle to "Abre el juego rápidamente como una aplicación independiente en este dispositivo.",
    TextKey.SettingsInstallRetry to "INTENTAR ABRIR EL INSTALADOR",
    TextKey.SettingsInstallAction to "INSTALAR FAST TO WIN",
    TextKey.SettingsInstallOpening to "ABRIENDO EL INSTALADOR",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: abre el menú del navegador y elige Instalar aplicación. Safari en iPhone/iPad: elige Compartir → Añadir a pantalla de inicio.",
    TextKey.SettingsNotificationsTitle to "Notificaciones",
    TextKey.SettingsNotificationsSubtitle to "Elige exactamente qué novedades quieres recibir.",
    TextKey.SettingsDeviceNotifications to "Notificaciones del dispositivo",
    TextKey.SettingsRoomInvitationsTitle to "Invitaciones a salas",
    TextKey.SettingsRoomInvitationsSubtitle to "Cuando un amigo te invite a una sala de juego",
    TextKey.SettingsTournamentInvitationsTitle to "Invitaciones a torneos",
    TextKey.SettingsTournamentInvitationsSubtitle to "Cuando un amigo te invite a un torneo",
    TextKey.SettingsMissionRewardsTitle to "Misiones y recompensas",
    TextKey.SettingsMissionRewardsSubtitle to "Cuando completes una misión",
    TextKey.SettingsDailyCheckInTitle to "Recordatorio de registro",
    TextKey.SettingsDailyCheckInSubtitle to "Una vez al día si no has reclamado la recompensa",
    TextKey.SettingsFeedbackTitle to "Respuesta del juego",
    TextKey.SettingsFeedbackSubtitle to "Se aplica inmediatamente al tocar el tablero de números.",
    TextKey.SettingsSoundTitle to "Efectos de sonido",
    TextKey.SettingsSoundSubtitle to "Respuesta para aciertos, errores y final de partida",
    TextKey.SettingsVibrationTitle to "Respuesta háptica",
    TextKey.SettingsVibrationSubtitle to "Una vibración suave al tocar un número",
    TextKey.SettingsVisualEffectsTitle to "Efectos visuales",
    TextKey.SettingsVisualEffectsSubtitle to "Combos y alertas de marcador ajustado",
    TextKey.SettingsPreviewSound to "Probar sonido",
    TextKey.SettingsThemeTitle to "Tema de la aplicación",
    TextKey.ThemeSystem to "Sistema",
    TextKey.ThemeLight to "Claro",
    TextKey.ThemeDark to "Oscuro",
    TextKey.SettingsBoardStyleTitle to "Color del tablero de números",
    TextKey.BoardClassic to "Clásico",
    TextKey.BoardOcean to "Océano",
    TextKey.BoardHighContrast to "Alto contraste",
    TextKey.SettingsFontSizeTitle to "Tamaño del texto",
    TextKey.FontCompact to "Pequeño",
    TextKey.FontStandard to "Estándar",
    TextKey.FontLarge to "Grande",
    TextKey.SettingsOpenTutorial to "Ver el tutorial de nuevo",
    TextKey.SettingsResetDefaults to "Restaurar ajustes predeterminados",
    TextKey.SettingsHeroEyebrow to "PREFERENCIAS",
    TextKey.SettingsHeroTitle to "Juega a tu manera",
    TextKey.SettingsHeroSubtitle to "El sonido, la vibración y la apariencia se guardan en este dispositivo.",
    TextKey.InstallAvailableTitle to "Listo para instalar",
    TextKey.InstallAvailableSubtitle to "No necesitas descargar archivos; las actualizaciones son automáticas.",
    TextKey.InstallInstallingTitle to "Esperando confirmación",
    TextKey.InstallInstallingSubtitle to "Termina en la ventana del navegador.",
    TextKey.InstallInstalledTitle to "Instalado en este dispositivo",
    TextKey.InstallInstalledSubtitle to "Puedes abrir el juego desde la pantalla de inicio.",
    TextKey.InstallManualTitle to "Instalar desde el menú del navegador",
    TextKey.InstallManualSubtitle to "Este navegador requiere instalación manual.",
    TextKey.InstallErrorTitle to "No se pudo abrir el instalador",
    TextKey.InstallErrorSubtitle to "Inténtalo de nuevo o instala desde el menú del navegador.",
    TextKey.InstallUnsupportedTitle to "Instalación no compatible",
    TextKey.InstallUnsupportedSubtitle to "Continúa jugando directamente en el navegador.",
    TextKey.PushPromptDescription to "Recibe invitaciones a salas y torneos y recordatorios de recompensas",
    TextKey.PushRequestingDescription to "Esperando permiso para enviar notificaciones…",
    TextKey.PushEnabledDescription to "Las invitaciones, misiones y recordatorios de registro están activados",
    TextKey.PushDisabledDescription to "Desactivadas en este dispositivo",
    TextKey.PushDeniedDescription to "Bloqueadas — permite las notificaciones en los ajustes del dispositivo",
    TextKey.PushErrorDescription to "No se pudieron activar las notificaciones; inténtalo de nuevo",
    TextKey.PushUnsupportedDescription to "Este dispositivo no admite notificaciones",
    TextKey.PushUnconfiguredDescription to "Las notificaciones no están configuradas",
    TextKey.GuestSessionMissing to "No hay ninguna sesión de invitado disponible para guardar. Abre la lista de salas e inténtalo de nuevo.",
    TextKey.OpenRoomLinkBlocked to "Sal de la sala actual antes de abrir otro enlace de sala.",
    TextKey.InvalidProfileName to "El apodo debe tener entre 1 y {maximum} caracteres.",
    TextKey.InvalidAvatar to "El avatar seleccionado no es válido.",
    TextKey.RoomNameRequired to "Introduce un nombre para la sala.",
    TextKey.RoomUnavailable to "Esta sala ya no está disponible.",
    TextKey.RematchAccepting to "Aceptando la invitación a la revancha…",
    TextKey.RematchSent to "Invitación a la revancha enviada.",
    TextKey.PlayerBlockedAndLeft to "Jugador bloqueado y sala abandonada.",
    TextKey.ProfileSaved to "Perfil guardado.",
    TextKey.RematchRequestedByYou to "Has solicitado una revancha.",
    TextKey.RematchRequestedByOpponent to "Tu rival quiere una revancha.",
    TextKey.RematchCancelledByYou to "Has cancelado la solicitud de revancha.",
    TextKey.RematchCancelledByOpponent to "Tu rival ha cancelado la solicitud de revancha.",
    TextKey.RematchDeclinedByYou to "Has rechazado la revancha.",
    TextKey.RematchDeclinedByOpponent to "Tu rival ha rechazado la revancha.",
    TextKey.RematchExpired to "La solicitud de revancha ha caducado.",
    TextKey.Spectator to "Espectador",
    TextKey.WaitingForServerResult to "Esperando el resultado del servidor…",
    TextKey.ReconnectingMatch to "Se perdió la conexión. Restaurando la partida; la sala se conserva hasta 30 segundos…",
    TextKey.ReconnectAction to "REINTENTAR AHORA",
    TextKey.ReconnectBlockingHint to "El tablero está bloqueado hasta que el servidor restaure la partida.",
    TextKey.MatchExpiredOfficialLoss to "La sala expiró mientras estabas desconectado. Esta partida cuenta como derrota oficial.",
    TextKey.RewardReceivedSummary to "Has recibido {rewards}."
)

private val brazilianPortugueseResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Instalar o Fast To Win",
    TextKey.SettingsInstallSubtitle to "Abra o jogo rapidamente como um app independente neste dispositivo.",
    TextKey.SettingsInstallRetry to "TENTAR ABRIR O INSTALADOR",
    TextKey.SettingsInstallAction to "INSTALAR O FAST TO WIN",
    TextKey.SettingsInstallOpening to "ABRINDO O INSTALADOR",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: abra o menu do navegador e escolha Instalar app. Safari no iPhone/iPad: escolha Compartilhar → Adicionar à Tela de Início.",
    TextKey.SettingsNotificationsTitle to "Notificações",
    TextKey.SettingsNotificationsSubtitle to "Escolha exatamente quais novidades deseja receber.",
    TextKey.SettingsDeviceNotifications to "Notificações do dispositivo",
    TextKey.SettingsRoomInvitationsTitle to "Convites para salas",
    TextKey.SettingsRoomInvitationsSubtitle to "Quando um amigo convidar você para uma sala de jogo",
    TextKey.SettingsTournamentInvitationsTitle to "Convites para torneios",
    TextKey.SettingsTournamentInvitationsSubtitle to "Quando um amigo convidar você para um torneio",
    TextKey.SettingsMissionRewardsTitle to "Missões e recompensas",
    TextKey.SettingsMissionRewardsSubtitle to "Quando você concluir uma missão",
    TextKey.SettingsDailyCheckInTitle to "Lembrete de check-in",
    TextKey.SettingsDailyCheckInSubtitle to "Uma vez por dia se você ainda não resgatou a recompensa",
    TextKey.SettingsFeedbackTitle to "Feedback de jogo",
    TextKey.SettingsFeedbackSubtitle to "Aplicado imediatamente ao tocar no tabuleiro de números.",
    TextKey.SettingsSoundTitle to "Efeitos sonoros",
    TextKey.SettingsSoundSubtitle to "Feedback para acertos, erros e fim da partida",
    TextKey.SettingsVibrationTitle to "Feedback tátil",
    TextKey.SettingsVibrationSubtitle to "Uma vibração leve ao tocar em um número",
    TextKey.SettingsVisualEffectsTitle to "Efeitos visuais",
    TextKey.SettingsVisualEffectsSubtitle to "Combos e alertas de placar acirrado",
    TextKey.SettingsPreviewSound to "Ouvir som",
    TextKey.SettingsThemeTitle to "Tema do app",
    TextKey.ThemeSystem to "Sistema",
    TextKey.ThemeLight to "Claro",
    TextKey.ThemeDark to "Escuro",
    TextKey.SettingsBoardStyleTitle to "Cor do tabuleiro de números",
    TextKey.BoardClassic to "Clássico",
    TextKey.BoardOcean to "Oceano",
    TextKey.BoardHighContrast to "Alto contraste",
    TextKey.SettingsFontSizeTitle to "Tamanho do texto",
    TextKey.FontCompact to "Pequeno",
    TextKey.FontStandard to "Padrão",
    TextKey.FontLarge to "Grande",
    TextKey.SettingsOpenTutorial to "Ver o tutorial novamente",
    TextKey.SettingsResetDefaults to "Restaurar configurações padrão",
    TextKey.SettingsHeroEyebrow to "PREFERÊNCIAS",
    TextKey.SettingsHeroTitle to "Jogue do seu jeito",
    TextKey.SettingsHeroSubtitle to "Som, vibração e aparência ficam salvos neste dispositivo.",
    TextKey.InstallAvailableTitle to "Pronto para instalar",
    TextKey.InstallAvailableSubtitle to "Não é preciso baixar arquivos; as atualizações são automáticas.",
    TextKey.InstallInstallingTitle to "Aguardando confirmação",
    TextKey.InstallInstallingSubtitle to "Conclua na janela do navegador.",
    TextKey.InstallInstalledTitle to "Instalado neste dispositivo",
    TextKey.InstallInstalledSubtitle to "Você pode abrir o jogo pela tela inicial.",
    TextKey.InstallManualTitle to "Instalar pelo menu do navegador",
    TextKey.InstallManualSubtitle to "Este navegador exige instalação manual.",
    TextKey.InstallErrorTitle to "Não foi possível abrir o instalador",
    TextKey.InstallErrorSubtitle to "Tente novamente ou instale pelo menu do navegador.",
    TextKey.InstallUnsupportedTitle to "Instalação não compatível",
    TextKey.InstallUnsupportedSubtitle to "Continue jogando diretamente no navegador.",
    TextKey.PushPromptDescription to "Receba convites para salas e torneios e lembretes de recompensas",
    TextKey.PushRequestingDescription to "Aguardando permissão para notificações…",
    TextKey.PushEnabledDescription to "Convites, missões e lembretes de check-in estão ativados",
    TextKey.PushDisabledDescription to "Desativadas neste dispositivo",
    TextKey.PushDeniedDescription to "Bloqueadas — permita notificações nas configurações do dispositivo",
    TextKey.PushErrorDescription to "Não foi possível ativar as notificações; tente novamente",
    TextKey.PushUnsupportedDescription to "Este dispositivo não oferece suporte a notificações",
    TextKey.PushUnconfiguredDescription to "As notificações não estão configuradas",
    TextKey.GuestSessionMissing to "Não há uma sessão de convidado disponível para salvar. Abra a lista de salas e tente novamente.",
    TextKey.OpenRoomLinkBlocked to "Saia da sala atual antes de abrir outro link de sala.",
    TextKey.InvalidProfileName to "O apelido deve ter entre 1 e {maximum} caracteres.",
    TextKey.InvalidAvatar to "O avatar selecionado é inválido.",
    TextKey.RoomNameRequired to "Digite um nome para a sala.",
    TextKey.RoomUnavailable to "Esta sala não está mais disponível.",
    TextKey.RematchAccepting to "Aceitando o convite para revanche…",
    TextKey.RematchSent to "Convite para revanche enviado.",
    TextKey.PlayerBlockedAndLeft to "Jogador bloqueado e sala abandonada.",
    TextKey.ProfileSaved to "Perfil salvo.",
    TextKey.RematchRequestedByYou to "Você solicitou uma revanche.",
    TextKey.RematchRequestedByOpponent to "Seu adversário quer uma revanche.",
    TextKey.RematchCancelledByYou to "Você cancelou a solicitação de revanche.",
    TextKey.RematchCancelledByOpponent to "Seu adversário cancelou a solicitação de revanche.",
    TextKey.RematchDeclinedByYou to "Você recusou a revanche.",
    TextKey.RematchDeclinedByOpponent to "Seu adversário recusou a revanche.",
    TextKey.RematchExpired to "A solicitação de revanche expirou.",
    TextKey.Spectator to "Espectador",
    TextKey.WaitingForServerResult to "Aguardando o resultado do servidor…",
    TextKey.ReconnectingMatch to "A conexão foi perdida. Restaurando a partida; a sala fica reservada por até 30 segundos…",
    TextKey.ReconnectAction to "TENTAR NOVAMENTE",
    TextKey.ReconnectBlockingHint to "O tabuleiro fica bloqueado até o servidor restaurar a partida.",
    TextKey.MatchExpiredOfficialLoss to "A sala expirou enquanto você estava desconectado. Esta partida conta como derrota oficial.",
    TextKey.RewardReceivedSummary to "Você recebeu {rewards}."
)

private val frenchResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Installer Fast To Win",
    TextKey.SettingsInstallSubtitle to "Ouvrez rapidement le jeu comme une application autonome sur cet appareil.",
    TextKey.SettingsInstallRetry to "RÉESSAYER D’OUVRIR L’INSTALLATEUR",
    TextKey.SettingsInstallAction to "INSTALLER FAST TO WIN",
    TextKey.SettingsInstallOpening to "OUVERTURE DE L’INSTALLATEUR",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge : ouvrez le menu du navigateur et choisissez Installer l’application. Safari sur iPhone/iPad : choisissez Partager → Sur l’écran d’accueil.",
    TextKey.SettingsNotificationsTitle to "Notifications",
    TextKey.SettingsNotificationsSubtitle to "Choisissez précisément les actualités que vous souhaitez recevoir.",
    TextKey.SettingsDeviceNotifications to "Notifications de l’appareil",
    TextKey.SettingsRoomInvitationsTitle to "Invitations aux salles",
    TextKey.SettingsRoomInvitationsSubtitle to "Lorsqu’un ami vous invite dans une salle de jeu",
    TextKey.SettingsTournamentInvitationsTitle to "Invitations aux tournois",
    TextKey.SettingsTournamentInvitationsSubtitle to "Lorsqu’un ami vous invite à un tournoi",
    TextKey.SettingsMissionRewardsTitle to "Missions et récompenses",
    TextKey.SettingsMissionRewardsSubtitle to "Lorsque vous terminez une mission",
    TextKey.SettingsDailyCheckInTitle to "Rappel de pointage",
    TextKey.SettingsDailyCheckInSubtitle to "Une fois par jour si vous n’avez pas récupéré la récompense",
    TextKey.SettingsFeedbackTitle to "Retour de jeu",
    TextKey.SettingsFeedbackSubtitle to "S’applique immédiatement lorsque vous touchez la grille de nombres.",
    TextKey.SettingsSoundTitle to "Effets sonores",
    TextKey.SettingsSoundSubtitle to "Retour pour les bonnes réponses, les erreurs et la fin du match",
    TextKey.SettingsVibrationTitle to "Retour haptique",
    TextKey.SettingsVibrationSubtitle to "Une légère vibration lorsque vous touchez un nombre",
    TextKey.SettingsVisualEffectsTitle to "Effets visuels",
    TextKey.SettingsVisualEffectsSubtitle to "Combos et alertes de score serré",
    TextKey.SettingsPreviewSound to "Écouter le son",
    TextKey.SettingsThemeTitle to "Thème de l’application",
    TextKey.ThemeSystem to "Système",
    TextKey.ThemeLight to "Clair",
    TextKey.ThemeDark to "Sombre",
    TextKey.SettingsBoardStyleTitle to "Couleur de la grille de nombres",
    TextKey.BoardClassic to "Classique",
    TextKey.BoardOcean to "Océan",
    TextKey.BoardHighContrast to "Contraste élevé",
    TextKey.SettingsFontSizeTitle to "Taille du texte",
    TextKey.FontCompact to "Petite",
    TextKey.FontStandard to "Standard",
    TextKey.FontLarge to "Grande",
    TextKey.SettingsOpenTutorial to "Revoir le tutoriel",
    TextKey.SettingsResetDefaults to "Restaurer les paramètres par défaut",
    TextKey.SettingsHeroEyebrow to "PRÉFÉRENCES",
    TextKey.SettingsHeroTitle to "Jouez à votre façon",
    TextKey.SettingsHeroSubtitle to "Le son, les vibrations et l’apparence sont enregistrés sur cet appareil.",
    TextKey.InstallAvailableTitle to "Prêt à installer",
    TextKey.InstallAvailableSubtitle to "Aucun fichier à télécharger ; les mises à jour sont automatiques.",
    TextKey.InstallInstallingTitle to "En attente de confirmation",
    TextKey.InstallInstallingSubtitle to "Terminez dans la fenêtre du navigateur.",
    TextKey.InstallInstalledTitle to "Installé sur cet appareil",
    TextKey.InstallInstalledSubtitle to "Vous pouvez ouvrir le jeu depuis l’écran d’accueil.",
    TextKey.InstallManualTitle to "Installer depuis le menu du navigateur",
    TextKey.InstallManualSubtitle to "Ce navigateur nécessite une installation manuelle.",
    TextKey.InstallErrorTitle to "Impossible d’ouvrir l’installateur",
    TextKey.InstallErrorSubtitle to "Réessayez ou installez depuis le menu du navigateur.",
    TextKey.InstallUnsupportedTitle to "Installation non prise en charge",
    TextKey.InstallUnsupportedSubtitle to "Continuez à jouer directement dans le navigateur.",
    TextKey.PushPromptDescription to "Recevez les invitations aux salles et tournois ainsi que les rappels de récompenses",
    TextKey.PushRequestingDescription to "En attente de l’autorisation des notifications…",
    TextKey.PushEnabledDescription to "Les invitations, missions et rappels de pointage sont activés",
    TextKey.PushDisabledDescription to "Désactivées sur cet appareil",
    TextKey.PushDeniedDescription to "Bloquées — autorisez les notifications dans les réglages de l’appareil",
    TextKey.PushErrorDescription to "Impossible d’activer les notifications ; veuillez réessayer",
    TextKey.PushUnsupportedDescription to "Cet appareil ne prend pas en charge les notifications",
    TextKey.PushUnconfiguredDescription to "Les notifications ne sont pas configurées",
    TextKey.GuestSessionMissing to "Aucune session invité ne peut être enregistrée. Ouvrez la liste des salles et réessayez.",
    TextKey.OpenRoomLinkBlocked to "Quittez la salle actuelle avant d’ouvrir un autre lien de salle.",
    TextKey.InvalidProfileName to "Le pseudonyme doit comporter entre 1 et {maximum} caractères.",
    TextKey.InvalidAvatar to "L’avatar sélectionné n’est pas valide.",
    TextKey.RoomNameRequired to "Saisissez un nom de salle.",
    TextKey.RoomUnavailable to "Cette salle n’est plus disponible.",
    TextKey.RematchAccepting to "Acceptation de l’invitation à rejouer…",
    TextKey.RematchSent to "Invitation à rejouer envoyée.",
    TextKey.PlayerBlockedAndLeft to "Joueur bloqué et salle quittée.",
    TextKey.ProfileSaved to "Profil enregistré.",
    TextKey.RematchRequestedByYou to "Vous avez demandé à rejouer.",
    TextKey.RematchRequestedByOpponent to "Votre adversaire souhaite rejouer.",
    TextKey.RematchCancelledByYou to "Vous avez annulé la demande de revanche.",
    TextKey.RematchCancelledByOpponent to "Votre adversaire a annulé la demande de revanche.",
    TextKey.RematchDeclinedByYou to "Vous avez refusé la revanche.",
    TextKey.RematchDeclinedByOpponent to "Votre adversaire a refusé la revanche.",
    TextKey.RematchExpired to "La demande de revanche a expiré.",
    TextKey.Spectator to "Spectateur",
    TextKey.WaitingForServerResult to "En attente du résultat du serveur…",
    TextKey.ReconnectingMatch to "Connexion perdue. Restauration du match ; la salle est conservée jusqu’à 30 secondes…",
    TextKey.ReconnectAction to "RÉESSAYER",
    TextKey.ReconnectBlockingHint to "Le plateau est verrouillé jusqu’à ce que le serveur restaure le match.",
    TextKey.MatchExpiredOfficialLoss to "La salle a expiré pendant votre déconnexion. Ce match compte comme une défaite officielle.",
    TextKey.RewardReceivedSummary to "Vous avez reçu {rewards}."
)

private val germanResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Fast To Win installieren",
    TextKey.SettingsInstallSubtitle to "Öffne das Spiel auf diesem Gerät schnell wie eine eigenständige App.",
    TextKey.SettingsInstallRetry to "INSTALLATION ERNEUT ÖFFNEN",
    TextKey.SettingsInstallAction to "FAST TO WIN INSTALLIEREN",
    TextKey.SettingsInstallOpening to "INSTALLATION WIRD GEÖFFNET",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: Öffne das Browsermenü und wähle App installieren. Safari auf iPhone/iPad: Wähle Teilen → Zum Home-Bildschirm.",
    TextKey.SettingsNotificationsTitle to "Benachrichtigungen",
    TextKey.SettingsNotificationsSubtitle to "Wähle genau aus, welche Neuigkeiten du erhalten möchtest.",
    TextKey.SettingsDeviceNotifications to "Gerätebenachrichtigungen",
    TextKey.SettingsRoomInvitationsTitle to "Raumeinladungen",
    TextKey.SettingsRoomInvitationsSubtitle to "Wenn dich ein Freund in einen Spielraum einlädt",
    TextKey.SettingsTournamentInvitationsTitle to "Turniereinladungen",
    TextKey.SettingsTournamentInvitationsSubtitle to "Wenn dich ein Freund zu einem Turnier einlädt",
    TextKey.SettingsMissionRewardsTitle to "Missionen und Belohnungen",
    TextKey.SettingsMissionRewardsSubtitle to "Wenn du eine Mission abschließt",
    TextKey.SettingsDailyCheckInTitle to "Check-in-Erinnerung",
    TextKey.SettingsDailyCheckInSubtitle to "Einmal täglich, falls du die Belohnung noch nicht abgeholt hast",
    TextKey.SettingsFeedbackTitle to "Spiel-Feedback",
    TextKey.SettingsFeedbackSubtitle to "Wird sofort angewendet, wenn du das Zahlenfeld antippst.",
    TextKey.SettingsSoundTitle to "Soundeffekte",
    TextKey.SettingsSoundSubtitle to "Feedback für richtige und falsche Eingaben sowie das Matchende",
    TextKey.SettingsVibrationTitle to "Haptisches Feedback",
    TextKey.SettingsVibrationSubtitle to "Eine leichte Vibration beim Antippen einer Zahl",
    TextKey.SettingsVisualEffectsTitle to "Visuelle Effekte",
    TextKey.SettingsVisualEffectsSubtitle to "Combos und Hinweise bei knappem Spielstand",
    TextKey.SettingsPreviewSound to "Sound anhören",
    TextKey.SettingsThemeTitle to "App-Design",
    TextKey.ThemeSystem to "System",
    TextKey.ThemeLight to "Hell",
    TextKey.ThemeDark to "Dunkel",
    TextKey.SettingsBoardStyleTitle to "Farbe des Zahlenfelds",
    TextKey.BoardClassic to "Klassisch",
    TextKey.BoardOcean to "Ozean",
    TextKey.BoardHighContrast to "Hoher Kontrast",
    TextKey.SettingsFontSizeTitle to "Textgröße",
    TextKey.FontCompact to "Klein",
    TextKey.FontStandard to "Standard",
    TextKey.FontLarge to "Groß",
    TextKey.SettingsOpenTutorial to "Tutorial erneut ansehen",
    TextKey.SettingsResetDefaults to "Standardeinstellungen wiederherstellen",
    TextKey.SettingsHeroEyebrow to "EINSTELLUNGEN",
    TextKey.SettingsHeroTitle to "Spiele auf deine Art",
    TextKey.SettingsHeroSubtitle to "Sound, Haptik und Darstellung werden auf diesem Gerät gespeichert.",
    TextKey.InstallAvailableTitle to "Bereit zur Installation",
    TextKey.InstallAvailableSubtitle to "Keine Datei nötig; Updates erfolgen automatisch.",
    TextKey.InstallInstallingTitle to "Bestätigung ausstehend",
    TextKey.InstallInstallingSubtitle to "Schließe den Vorgang im Browserfenster ab.",
    TextKey.InstallInstalledTitle to "Auf diesem Gerät installiert",
    TextKey.InstallInstalledSubtitle to "Du kannst das Spiel vom Home-Bildschirm öffnen.",
    TextKey.InstallManualTitle to "Über das Browsermenü installieren",
    TextKey.InstallManualSubtitle to "Dieser Browser erfordert eine manuelle Installation.",
    TextKey.InstallErrorTitle to "Installation konnte nicht geöffnet werden",
    TextKey.InstallErrorSubtitle to "Versuche es erneut oder installiere über das Browsermenü.",
    TextKey.InstallUnsupportedTitle to "Installation nicht unterstützt",
    TextKey.InstallUnsupportedSubtitle to "Spiele direkt im Browser weiter.",
    TextKey.PushPromptDescription to "Erhalte Raum- und Turniereinladungen sowie Belohnungserinnerungen",
    TextKey.PushRequestingDescription to "Warten auf die Benachrichtigungsberechtigung…",
    TextKey.PushEnabledDescription to "Einladungen, Missionen und Check-in-Erinnerungen sind aktiviert",
    TextKey.PushDisabledDescription to "Auf diesem Gerät deaktiviert",
    TextKey.PushDeniedDescription to "Blockiert — erlaube Benachrichtigungen in den Geräteeinstellungen",
    TextKey.PushErrorDescription to "Benachrichtigungen konnten nicht aktiviert werden; versuche es erneut",
    TextKey.PushUnsupportedDescription to "Dieses Gerät unterstützt keine Benachrichtigungen",
    TextKey.PushUnconfiguredDescription to "Benachrichtigungen sind nicht eingerichtet",
    TextKey.GuestSessionMissing to "Es ist keine Gastsitzung zum Speichern verfügbar. Öffne die Raumliste und versuche es erneut.",
    TextKey.OpenRoomLinkBlocked to "Verlasse den aktuellen Raum, bevor du einen anderen Raumlink öffnest.",
    TextKey.InvalidProfileName to "Der Spitzname muss 1 bis {maximum} Zeichen lang sein.",
    TextKey.InvalidAvatar to "Der ausgewählte Avatar ist ungültig.",
    TextKey.RoomNameRequired to "Gib einen Raumnamen ein.",
    TextKey.RoomUnavailable to "Dieser Raum ist nicht mehr verfügbar.",
    TextKey.RematchAccepting to "Einladung zur Revanche wird angenommen…",
    TextKey.RematchSent to "Einladung zur Revanche gesendet.",
    TextKey.PlayerBlockedAndLeft to "Spieler blockiert und Raum verlassen.",
    TextKey.ProfileSaved to "Profil gespeichert.",
    TextKey.RematchRequestedByYou to "Du hast eine Revanche angefordert.",
    TextKey.RematchRequestedByOpponent to "Dein Gegner möchte eine Revanche.",
    TextKey.RematchCancelledByYou to "Du hast die Revanche-Anfrage abgebrochen.",
    TextKey.RematchCancelledByOpponent to "Dein Gegner hat die Revanche-Anfrage abgebrochen.",
    TextKey.RematchDeclinedByYou to "Du hast die Revanche abgelehnt.",
    TextKey.RematchDeclinedByOpponent to "Dein Gegner hat die Revanche abgelehnt.",
    TextKey.RematchExpired to "Die Revanche-Anfrage ist abgelaufen.",
    TextKey.Spectator to "Zuschauer",
    TextKey.WaitingForServerResult to "Warten auf das Serverergebnis…",
    TextKey.ReconnectingMatch to "Verbindung verloren. Das Match wird wiederhergestellt; der Raum bleibt bis zu 30 Sekunden reserviert…",
    TextKey.ReconnectAction to "JETZT ERNEUT VERSUCHEN",
    TextKey.ReconnectBlockingHint to "Das Spielfeld ist gesperrt, bis der Server das Match wiederhergestellt hat.",
    TextKey.MatchExpiredOfficialLoss to "Der Raum ist während deiner Trennung abgelaufen. Dieses Match zählt als offizielle Niederlage.",
    TextKey.RewardReceivedSummary to "{rewards} erhalten."
)

private val indonesianResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Instal Fast To Win",
    TextKey.SettingsInstallSubtitle to "Buka game dengan cepat seperti aplikasi mandiri di perangkat ini.",
    TextKey.SettingsInstallRetry to "COBA BUKA PENGINSTAL",
    TextKey.SettingsInstallAction to "INSTAL FAST TO WIN",
    TextKey.SettingsInstallOpening to "MEMBUKA PENGINSTAL",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: buka menu browser dan pilih Instal aplikasi. Safari di iPhone/iPad: pilih Bagikan → Tambahkan ke Layar Utama.",
    TextKey.SettingsNotificationsTitle to "Notifikasi",
    TextKey.SettingsNotificationsSubtitle to "Pilih dengan tepat pembaruan yang ingin Anda terima.",
    TextKey.SettingsDeviceNotifications to "Notifikasi perangkat",
    TextKey.SettingsRoomInvitationsTitle to "Undangan room",
    TextKey.SettingsRoomInvitationsSubtitle to "Saat teman mengundang Anda ke room game",
    TextKey.SettingsTournamentInvitationsTitle to "Undangan turnamen",
    TextKey.SettingsTournamentInvitationsSubtitle to "Saat teman mengundang Anda ke turnamen",
    TextKey.SettingsMissionRewardsTitle to "Misi dan hadiah",
    TextKey.SettingsMissionRewardsSubtitle to "Saat Anda menyelesaikan misi",
    TextKey.SettingsDailyCheckInTitle to "Pengingat check-in",
    TextKey.SettingsDailyCheckInSubtitle to "Sekali sehari jika hadiah belum diklaim",
    TextKey.SettingsFeedbackTitle to "Umpan balik permainan",
    TextKey.SettingsFeedbackSubtitle to "Langsung diterapkan saat Anda mengetuk papan angka.",
    TextKey.SettingsSoundTitle to "Efek suara",
    TextKey.SettingsSoundSubtitle to "Umpan balik untuk jawaban benar, salah, dan akhir pertandingan",
    TextKey.SettingsVibrationTitle to "Umpan balik haptik",
    TextKey.SettingsVibrationSubtitle to "Getaran ringan saat Anda mengetuk angka",
    TextKey.SettingsVisualEffectsTitle to "Efek visual",
    TextKey.SettingsVisualEffectsSubtitle to "Combo dan peringatan skor ketat",
    TextKey.SettingsPreviewSound to "Pratinjau suara",
    TextKey.SettingsThemeTitle to "Tema aplikasi",
    TextKey.ThemeSystem to "Sistem",
    TextKey.ThemeLight to "Terang",
    TextKey.ThemeDark to "Gelap",
    TextKey.SettingsBoardStyleTitle to "Warna papan angka",
    TextKey.BoardClassic to "Klasik",
    TextKey.BoardOcean to "Lautan",
    TextKey.BoardHighContrast to "Kontras tinggi",
    TextKey.SettingsFontSizeTitle to "Ukuran teks",
    TextKey.FontCompact to "Kecil",
    TextKey.FontStandard to "Standar",
    TextKey.FontLarge to "Besar",
    TextKey.SettingsOpenTutorial to "Lihat tutorial lagi",
    TextKey.SettingsResetDefaults to "Pulihkan pengaturan bawaan",
    TextKey.SettingsHeroEyebrow to "PREFERENSI",
    TextKey.SettingsHeroTitle to "Main dengan cara Anda",
    TextKey.SettingsHeroSubtitle to "Suara, haptik, dan tampilan disimpan di perangkat ini.",
    TextKey.InstallAvailableTitle to "Siap diinstal",
    TextKey.InstallAvailableSubtitle to "Tidak perlu mengunduh berkas; pembaruan berlangsung otomatis.",
    TextKey.InstallInstallingTitle to "Menunggu konfirmasi",
    TextKey.InstallInstallingSubtitle to "Selesaikan di jendela browser.",
    TextKey.InstallInstalledTitle to "Terinstal di perangkat ini",
    TextKey.InstallInstalledSubtitle to "Anda dapat membuka game dari layar utama.",
    TextKey.InstallManualTitle to "Instal dari menu browser",
    TextKey.InstallManualSubtitle to "Browser ini memerlukan instalasi manual.",
    TextKey.InstallErrorTitle to "Penginstal tidak dapat dibuka",
    TextKey.InstallErrorSubtitle to "Coba lagi atau instal dari menu browser.",
    TextKey.InstallUnsupportedTitle to "Instalasi tidak didukung",
    TextKey.InstallUnsupportedSubtitle to "Lanjutkan bermain langsung di browser.",
    TextKey.PushPromptDescription to "Terima undangan room dan turnamen serta pengingat hadiah",
    TextKey.PushRequestingDescription to "Menunggu izin notifikasi…",
    TextKey.PushEnabledDescription to "Undangan, misi, dan pengingat check-in telah aktif",
    TextKey.PushDisabledDescription to "Dinonaktifkan di perangkat ini",
    TextKey.PushDeniedDescription to "Diblokir — izinkan notifikasi di pengaturan perangkat",
    TextKey.PushErrorDescription to "Notifikasi tidak dapat diaktifkan; silakan coba lagi",
    TextKey.PushUnsupportedDescription to "Perangkat ini tidak mendukung notifikasi",
    TextKey.PushUnconfiguredDescription to "Notifikasi belum dikonfigurasi",
    TextKey.GuestSessionMissing to "Tidak ada sesi tamu yang dapat disimpan. Buka daftar room dan coba lagi.",
    TextKey.OpenRoomLinkBlocked to "Keluar dari room saat ini sebelum membuka tautan room lain.",
    TextKey.InvalidProfileName to "Nama panggilan harus berisi 1 hingga {maximum} karakter.",
    TextKey.InvalidAvatar to "Avatar yang dipilih tidak valid.",
    TextKey.RoomNameRequired to "Masukkan nama room.",
    TextKey.RoomUnavailable to "Room ini tidak lagi tersedia.",
    TextKey.RematchAccepting to "Menerima undangan tanding ulang…",
    TextKey.RematchSent to "Undangan tanding ulang dikirim.",
    TextKey.PlayerBlockedAndLeft to "Pemain diblokir dan room ditinggalkan.",
    TextKey.ProfileSaved to "Profil disimpan.",
    TextKey.RematchRequestedByYou to "Anda meminta tanding ulang.",
    TextKey.RematchRequestedByOpponent to "Lawan Anda ingin tanding ulang.",
    TextKey.RematchCancelledByYou to "Anda membatalkan permintaan tanding ulang.",
    TextKey.RematchCancelledByOpponent to "Lawan membatalkan permintaan tanding ulang.",
    TextKey.RematchDeclinedByYou to "Anda menolak tanding ulang.",
    TextKey.RematchDeclinedByOpponent to "Lawan menolak tanding ulang.",
    TextKey.RematchExpired to "Permintaan tanding ulang telah kedaluwarsa.",
    TextKey.Spectator to "Penonton",
    TextKey.WaitingForServerResult to "Menunggu hasil dari server…",
    TextKey.ReconnectingMatch to "Koneksi terputus. Memulihkan pertandingan; room dipertahankan hingga 30 detik…",
    TextKey.ReconnectAction to "COBA LAGI SEKARANG",
    TextKey.ReconnectBlockingHint to "Papan terkunci sampai server memulihkan pertandingan.",
    TextKey.MatchExpiredOfficialLoss to "Room berakhir saat Anda terputus. Pertandingan ini dihitung sebagai kekalahan resmi.",
    TextKey.RewardReceivedSummary to "Menerima {rewards}."
)

private val thaiResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "ติดตั้ง Fast To Win",
    TextKey.SettingsInstallSubtitle to "เปิดเกมได้อย่างรวดเร็วเหมือนแอปแบบสแตนด์อโลนบนอุปกรณ์นี้",
    TextKey.SettingsInstallRetry to "ลองเปิดตัวติดตั้งอีกครั้ง",
    TextKey.SettingsInstallAction to "ติดตั้ง FAST TO WIN",
    TextKey.SettingsInstallOpening to "กำลังเปิดตัวติดตั้ง",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: เปิดเมนูเบราว์เซอร์แล้วเลือกติดตั้งแอป Safari บน iPhone/iPad: เลือกแชร์ → เพิ่มไปยังหน้าจอโฮม",
    TextKey.SettingsNotificationsTitle to "การแจ้งเตือน",
    TextKey.SettingsNotificationsSubtitle to "เลือกข่าวสารที่คุณต้องการรับอย่างละเอียด",
    TextKey.SettingsDeviceNotifications to "การแจ้งเตือนของอุปกรณ์",
    TextKey.SettingsRoomInvitationsTitle to "คำเชิญเข้าห้อง",
    TextKey.SettingsRoomInvitationsSubtitle to "เมื่อเพื่อนเชิญคุณเข้าห้องเกม",
    TextKey.SettingsTournamentInvitationsTitle to "คำเชิญทัวร์นาเมนต์",
    TextKey.SettingsTournamentInvitationsSubtitle to "เมื่อเพื่อนเชิญคุณเข้าร่วมทัวร์นาเมนต์",
    TextKey.SettingsMissionRewardsTitle to "ภารกิจและรางวัล",
    TextKey.SettingsMissionRewardsSubtitle to "เมื่อคุณทำภารกิจสำเร็จ",
    TextKey.SettingsDailyCheckInTitle to "เตือนเช็กอิน",
    TextKey.SettingsDailyCheckInSubtitle to "วันละครั้งหากคุณยังไม่ได้รับรางวัล",
    TextKey.SettingsFeedbackTitle to "การตอบสนองขณะเล่น",
    TextKey.SettingsFeedbackSubtitle to "มีผลทันทีเมื่อคุณแตะกระดานตัวเลข",
    TextKey.SettingsSoundTitle to "เอฟเฟกต์เสียง",
    TextKey.SettingsSoundSubtitle to "เสียงตอบสนองเมื่อถูก ผิด และจบการแข่งขัน",
    TextKey.SettingsVibrationTitle to "การตอบสนองแบบสั่น",
    TextKey.SettingsVibrationSubtitle to "สั่นเบา ๆ เมื่อคุณแตะตัวเลข",
    TextKey.SettingsVisualEffectsTitle to "เอฟเฟกต์ภาพ",
    TextKey.SettingsVisualEffectsSubtitle to "คอมโบและการแจ้งเตือนคะแนนสูสี",
    TextKey.SettingsPreviewSound to "ฟังตัวอย่างเสียง",
    TextKey.SettingsThemeTitle to "ธีมแอป",
    TextKey.ThemeSystem to "ระบบ",
    TextKey.ThemeLight to "สว่าง",
    TextKey.ThemeDark to "มืด",
    TextKey.SettingsBoardStyleTitle to "สีกระดานตัวเลข",
    TextKey.BoardClassic to "คลาสสิก",
    TextKey.BoardOcean to "มหาสมุทร",
    TextKey.BoardHighContrast to "คอนทราสต์สูง",
    TextKey.SettingsFontSizeTitle to "ขนาดข้อความ",
    TextKey.FontCompact to "เล็ก",
    TextKey.FontStandard to "มาตรฐาน",
    TextKey.FontLarge to "ใหญ่",
    TextKey.SettingsOpenTutorial to "ดูบทแนะนำอีกครั้ง",
    TextKey.SettingsResetDefaults to "คืนค่าการตั้งค่าเริ่มต้น",
    TextKey.SettingsHeroEyebrow to "การตั้งค่า",
    TextKey.SettingsHeroTitle to "เล่นในแบบของคุณ",
    TextKey.SettingsHeroSubtitle to "เสียง การสั่น และรูปลักษณ์จะถูกบันทึกไว้ในอุปกรณ์นี้",
    TextKey.InstallAvailableTitle to "พร้อมติดตั้ง",
    TextKey.InstallAvailableSubtitle to "ไม่ต้องดาวน์โหลดไฟล์ การอัปเดตเป็นอัตโนมัติ",
    TextKey.InstallInstallingTitle to "รอการยืนยัน",
    TextKey.InstallInstallingSubtitle to "ดำเนินการให้เสร็จในหน้าต่างเบราว์เซอร์",
    TextKey.InstallInstalledTitle to "ติดตั้งบนอุปกรณ์นี้แล้ว",
    TextKey.InstallInstalledSubtitle to "คุณเปิดเกมได้จากหน้าจอโฮม",
    TextKey.InstallManualTitle to "ติดตั้งจากเมนูเบราว์เซอร์",
    TextKey.InstallManualSubtitle to "เบราว์เซอร์นี้ต้องติดตั้งด้วยตนเอง",
    TextKey.InstallErrorTitle to "เปิดตัวติดตั้งไม่ได้",
    TextKey.InstallErrorSubtitle to "ลองอีกครั้งหรือติดตั้งจากเมนูเบราว์เซอร์",
    TextKey.InstallUnsupportedTitle to "ไม่รองรับการติดตั้ง",
    TextKey.InstallUnsupportedSubtitle to "เล่นต่อได้โดยตรงในเบราว์เซอร์",
    TextKey.PushPromptDescription to "รับคำเชิญเข้าห้องและทัวร์นาเมนต์พร้อมการเตือนรางวัล",
    TextKey.PushRequestingDescription to "กำลังรอสิทธิ์การแจ้งเตือน…",
    TextKey.PushEnabledDescription to "เปิดใช้คำเชิญ ภารกิจ และการเตือนเช็กอินแล้ว",
    TextKey.PushDisabledDescription to "ปิดใช้งานบนอุปกรณ์นี้",
    TextKey.PushDeniedDescription to "ถูกบล็อก — อนุญาตการแจ้งเตือนในการตั้งค่าอุปกรณ์",
    TextKey.PushErrorDescription to "เปิดการแจ้งเตือนไม่ได้ โปรดลองอีกครั้ง",
    TextKey.PushUnsupportedDescription to "อุปกรณ์นี้ไม่รองรับการแจ้งเตือน",
    TextKey.PushUnconfiguredDescription to "ยังไม่ได้ตั้งค่าการแจ้งเตือน",
    TextKey.GuestSessionMissing to "ไม่มีเซสชันผู้เยี่ยมชมให้บันทึก เปิดรายการห้องแล้วลองอีกครั้ง",
    TextKey.OpenRoomLinkBlocked to "ออกจากห้องปัจจุบันก่อนเปิดลิงก์ห้องอื่น",
    TextKey.InvalidProfileName to "ชื่อเล่นต้องมีความยาว 1 ถึง {maximum} ตัวอักษร",
    TextKey.InvalidAvatar to "อวาตาร์ที่เลือกไม่ถูกต้อง",
    TextKey.RoomNameRequired to "ป้อนชื่อห้อง",
    TextKey.RoomUnavailable to "ห้องนี้ไม่พร้อมใช้งานแล้ว",
    TextKey.RematchAccepting to "กำลังยอมรับคำเชิญแข่งใหม่…",
    TextKey.RematchSent to "ส่งคำเชิญแข่งใหม่แล้ว",
    TextKey.PlayerBlockedAndLeft to "บล็อกผู้เล่นและออกจากห้องแล้ว",
    TextKey.ProfileSaved to "บันทึกโปรไฟล์แล้ว",
    TextKey.RematchRequestedByYou to "คุณขอแข่งใหม่แล้ว",
    TextKey.RematchRequestedByOpponent to "คู่แข่งต้องการแข่งใหม่",
    TextKey.RematchCancelledByYou to "คุณยกเลิกคำขอแข่งใหม่แล้ว",
    TextKey.RematchCancelledByOpponent to "คู่แข่งยกเลิกคำขอแข่งใหม่แล้ว",
    TextKey.RematchDeclinedByYou to "คุณปฏิเสธการแข่งใหม่แล้ว",
    TextKey.RematchDeclinedByOpponent to "คู่แข่งปฏิเสธการแข่งใหม่แล้ว",
    TextKey.RematchExpired to "คำขอแข่งใหม่หมดอายุแล้ว",
    TextKey.Spectator to "ผู้ชม",
    TextKey.WaitingForServerResult to "กำลังรอผลจากเซิร์ฟเวอร์…",
    TextKey.ReconnectingMatch to "การเชื่อมต่อขาดหาย กำลังกู้คืนการแข่งขัน ห้องจะถูกเก็บไว้นานสูงสุด 30 วินาที…",
    TextKey.ReconnectAction to "ลองใหม่ทันที",
    TextKey.ReconnectBlockingHint to "กระดานถูกล็อกจนกว่าเซิร์ฟเวอร์จะกู้คืนการแข่งขัน",
    TextKey.MatchExpiredOfficialLoss to "ห้องหมดอายุขณะที่คุณขาดการเชื่อมต่อ การแข่งนี้นับเป็นการแพ้อย่างเป็นทางการ",
    TextKey.RewardReceivedSummary to "ได้รับ {rewards} แล้ว"
)

private val russianResidualTexts = mapOf(
    TextKey.SettingsInstallTitle to "Установить Fast To Win",
    TextKey.SettingsInstallSubtitle to "Быстро открывайте игру как отдельное приложение на этом устройстве.",
    TextKey.SettingsInstallRetry to "СНОВА ОТКРЫТЬ УСТАНОВЩИК",
    TextKey.SettingsInstallAction to "УСТАНОВИТЬ FAST TO WIN",
    TextKey.SettingsInstallOpening to "ОТКРЫВАЕМ УСТАНОВЩИК",
    TextKey.SettingsInstallManualInstructions to "Chrome/Edge: откройте меню браузера и выберите «Установить приложение». Safari на iPhone/iPad: выберите «Поделиться» → «На экран Домой».",
    TextKey.SettingsNotificationsTitle to "Уведомления",
    TextKey.SettingsNotificationsSubtitle to "Выберите, какие именно новости вы хотите получать.",
    TextKey.SettingsDeviceNotifications to "Уведомления устройства",
    TextKey.SettingsRoomInvitationsTitle to "Приглашения в комнаты",
    TextKey.SettingsRoomInvitationsSubtitle to "Когда друг приглашает вас в игровую комнату",
    TextKey.SettingsTournamentInvitationsTitle to "Приглашения на турниры",
    TextKey.SettingsTournamentInvitationsSubtitle to "Когда друг приглашает вас на турнир",
    TextKey.SettingsMissionRewardsTitle to "Миссии и награды",
    TextKey.SettingsMissionRewardsSubtitle to "Когда вы выполняете миссию",
    TextKey.SettingsDailyCheckInTitle to "Напоминание о входе",
    TextKey.SettingsDailyCheckInSubtitle to "Раз в день, если вы ещё не забрали награду",
    TextKey.SettingsFeedbackTitle to "Отклик во время игры",
    TextKey.SettingsFeedbackSubtitle to "Применяется сразу при нажатии на числовое поле.",
    TextKey.SettingsSoundTitle to "Звуковые эффекты",
    TextKey.SettingsSoundSubtitle to "Отклик на правильный и неверный выбор, а также завершение матча",
    TextKey.SettingsVibrationTitle to "Тактильный отклик",
    TextKey.SettingsVibrationSubtitle to "Лёгкая вибрация при нажатии на число",
    TextKey.SettingsVisualEffectsTitle to "Визуальные эффекты",
    TextKey.SettingsVisualEffectsSubtitle to "Комбо и предупреждения о близком счёте",
    TextKey.SettingsPreviewSound to "Прослушать звук",
    TextKey.SettingsThemeTitle to "Тема приложения",
    TextKey.ThemeSystem to "Системная",
    TextKey.ThemeLight to "Светлая",
    TextKey.ThemeDark to "Тёмная",
    TextKey.SettingsBoardStyleTitle to "Цвет числового поля",
    TextKey.BoardClassic to "Классический",
    TextKey.BoardOcean to "Океан",
    TextKey.BoardHighContrast to "Высокая контрастность",
    TextKey.SettingsFontSizeTitle to "Размер текста",
    TextKey.FontCompact to "Маленький",
    TextKey.FontStandard to "Стандартный",
    TextKey.FontLarge to "Большой",
    TextKey.SettingsOpenTutorial to "Снова открыть обучение",
    TextKey.SettingsResetDefaults to "Восстановить настройки по умолчанию",
    TextKey.SettingsHeroEyebrow to "НАСТРОЙКИ",
    TextKey.SettingsHeroTitle to "Играйте по-своему",
    TextKey.SettingsHeroSubtitle to "Звук, вибрация и оформление сохраняются на этом устройстве.",
    TextKey.InstallAvailableTitle to "Готово к установке",
    TextKey.InstallAvailableSubtitle to "Файл скачивать не нужно; обновления устанавливаются автоматически.",
    TextKey.InstallInstallingTitle to "Ожидание подтверждения",
    TextKey.InstallInstallingSubtitle to "Завершите установку в окне браузера.",
    TextKey.InstallInstalledTitle to "Установлено на этом устройстве",
    TextKey.InstallInstalledSubtitle to "Игру можно открыть с главного экрана.",
    TextKey.InstallManualTitle to "Установить через меню браузера",
    TextKey.InstallManualSubtitle to "В этом браузере требуется ручная установка.",
    TextKey.InstallErrorTitle to "Не удалось открыть установщик",
    TextKey.InstallErrorSubtitle to "Попробуйте ещё раз или установите через меню браузера.",
    TextKey.InstallUnsupportedTitle to "Установка не поддерживается",
    TextKey.InstallUnsupportedSubtitle to "Продолжайте играть прямо в браузере.",
    TextKey.PushPromptDescription to "Получайте приглашения в комнаты и на турниры, а также напоминания о наградах",
    TextKey.PushRequestingDescription to "Ожидание разрешения на уведомления…",
    TextKey.PushEnabledDescription to "Приглашения, миссии и напоминания о входе включены",
    TextKey.PushDisabledDescription to "Отключено на этом устройстве",
    TextKey.PushDeniedDescription to "Заблокировано — разрешите уведомления в настройках устройства",
    TextKey.PushErrorDescription to "Не удалось включить уведомления; попробуйте ещё раз",
    TextKey.PushUnsupportedDescription to "Это устройство не поддерживает уведомления",
    TextKey.PushUnconfiguredDescription to "Уведомления не настроены",
    TextKey.GuestSessionMissing to "Нет гостевой сессии для сохранения. Откройте список комнат и попробуйте ещё раз.",
    TextKey.OpenRoomLinkBlocked to "Покиньте текущую комнату, прежде чем открывать другую ссылку на комнату.",
    TextKey.InvalidProfileName to "Псевдоним должен содержать от 1 до {maximum} символов.",
    TextKey.InvalidAvatar to "Выбранный аватар недействителен.",
    TextKey.RoomNameRequired to "Введите название комнаты.",
    TextKey.RoomUnavailable to "Эта комната больше недоступна.",
    TextKey.RematchAccepting to "Принимаем приглашение на реванш…",
    TextKey.RematchSent to "Приглашение на реванш отправлено.",
    TextKey.PlayerBlockedAndLeft to "Игрок заблокирован, комната покинута.",
    TextKey.ProfileSaved to "Профиль сохранён.",
    TextKey.RematchRequestedByYou to "Вы запросили реванш.",
    TextKey.RematchRequestedByOpponent to "Соперник хочет сыграть реванш.",
    TextKey.RematchCancelledByYou to "Вы отменили запрос на реванш.",
    TextKey.RematchCancelledByOpponent to "Соперник отменил запрос на реванш.",
    TextKey.RematchDeclinedByYou to "Вы отклонили реванш.",
    TextKey.RematchDeclinedByOpponent to "Соперник отклонил реванш.",
    TextKey.RematchExpired to "Срок запроса на реванш истёк.",
    TextKey.Spectator to "Зритель",
    TextKey.WaitingForServerResult to "Ожидание результата сервера…",
    TextKey.ReconnectingMatch to "Соединение потеряно. Матч восстанавливается; комната сохраняется до 30 секунд…",
    TextKey.ReconnectAction to "ПОВТОРИТЬ СЕЙЧАС",
    TextKey.ReconnectBlockingHint to "Поле заблокировано, пока сервер восстанавливает матч.",
    TextKey.MatchExpiredOfficialLoss to "Комната истекла, пока вы были отключены. Этот матч засчитан как официальное поражение.",
    TextKey.RewardReceivedSummary to "Получено: {rewards}."
)
