package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey

internal val englishShellAuthTexts = mapOf(
    TextKey.Gold to "Gold",
    TextKey.Gems to "Gems",
    TextKey.Notifications to "Notifications",
    TextKey.ViewMoreCount to "VIEW MORE ({count})",
    TextKey.UpdateGameTitle to "GAME UPDATE",
    TextKey.UpdateAvailableSubtitle to "A new version is ready",
    TextKey.UpdateHeroTitle to "READY TO SPEED UP?",
    TextKey.UpdateDescription to "Get the latest fixes and improvements.",
    TextKey.UpdateAutoReload to "Quick update, automatic reload",
    TextKey.UpdateProgressPreserved to "Your account and progress stay safe.",
    TextKey.UpdateNow to "UPDATE NOW",
    TextKey.Later to "LATER",
    TextKey.MaintenanceBadge to "MAINTENANCE",
    TextKey.MaintenanceTitle to "SERVER TAKING\nA TIMEOUT",
    TextKey.MaintenanceDefaultMessage to "The team is upgrading the arena. This may take a few hours.",
    TextKey.MaintenanceAutoResume to "The game will reopen automatically when ready",
    TextKey.MaintenanceNoAction to "No need to sign out or reinstall the app.",
    TextKey.OfflineBadge to "OFFLINE",
    TextKey.OfflineTitle to "CONNECTION\nLOST",
    TextKey.OfflineDescription to "Online matches are paused. The game will reconnect when your network is stable.",
    TextKey.OfflineCheckNetwork to "Check Wi-Fi or mobile data",
    TextKey.OfflineNotMaintenance to "This is a connection issue, not server maintenance.",
    TextKey.RetryConnection to "RECONNECT",
    TextKey.OfflinePractice to "OFFLINE PRACTICE",
    TextKey.NoNetwork to "No network connection",
    TextKey.TutorialTitle to "HOW TO PLAY",
    TextKey.Skip to "Skip",
    TextKey.TutorialStep to "STEP {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Find numbers fast",
    TextKey.TutorialFindNumbersDescription to "Tap from 1 to 50 in order. The target always stands out above the board.",
    TextKey.TutorialFindNumbersHint to "Wrong taps count toward your accuracy stats.",
    TextKey.TutorialSharedTargetTitle to "One shared target",
    TextKey.TutorialSharedTargetDescription to "Both players see the same number. The faster player scores and locks it on both boards.",
    TextKey.TutorialSharedTargetHint to "Each correct turn earns 10 points.",
    TextKey.TutorialChooseModeTitle to "Choose how to play",
    TextKey.TutorialChooseModeDescription to "Practice offline, play casual, or enter ranked matches that affect Elo.",
    TextKey.TutorialChooseModeHint to "You can reopen this guide from Settings.",
    TextKey.StartPlaying to "START PLAYING",
    TextKey.Continue to "CONTINUE",
    TextKey.VerifyEmailTitle to "Verify email",
    TextKey.VerifyEmailDescription to "Enter the 6-digit code sent to the email address below. It expires in 15 minutes.",
    TextKey.DevVerificationCode to "Dev mode — code filled automatically:",
    TextKey.VerificationCode to "Verification code",
    TextKey.Verifying to "VERIFYING…",
    TextKey.Verify to "VERIFY",
    TextKey.ResendCode to "RESEND CODE",
    TextKey.Logout to "Log out",
    TextKey.AuthWelcomeDescription to "Sign in to sync Elo, history, and achievements across devices.",
    TextKey.AuthLoginTitle to "Login",
    TextKey.Login to "LOGIN",
    TextKey.LoggingIn to "LOGGING IN…",
    TextKey.CreateAccount to "CREATE ACCOUNT",
    TextKey.PlayAsGuest to "Play as guest",
    TextKey.Password to "Password",
    TextKey.ForgotPassword to "Forgot password?",
    TextKey.ResetPasswordTitle to "Reset password",
    TextKey.ResetPasswordDescription to "Enter your email to receive a reset code valid for 15 minutes.",
    TextKey.Sending to "SENDING…",
    TextKey.SendResetCode to "SEND RESET CODE",
    TextKey.DevResetCode to "Dev mode — code filled automatically:",
    TextKey.ResetCode to "Reset code",
    TextKey.NewPassword to "New password (at least {minimum} characters)",
    TextKey.ConfirmNewPassword to "Confirm new password",
    TextKey.Updating to "UPDATING…",
    TextKey.ResetPasswordAction to "RESET PASSWORD",
    TextKey.UseDifferentEmail to "Use another email",
    TextKey.DisplayName to "Nickname",
    TextKey.GenderDefaultAvatar to "GENDER · DEFAULT AVATAR",
    TextKey.Male to "Male",
    TextKey.Female to "Female",
    TextKey.Player to "Player",
    TextKey.PasswordWithMinimum to "Password (at least {minimum} characters)",
    TextKey.ConfirmPassword to "Confirm password",
    TextKey.Creating to "CREATING…",
    TextKey.SaveGuestAccountTitle to "Save guest account",
    TextKey.SaveGuestAccountDescription to "Your current Elo, history, stats, and achievements will be preserved.",
    TextKey.Saving to "SAVING…",
    TextKey.SaveAndCreateAccount to "SAVE & CREATE ACCOUNT",
    TextKey.Email to "Email",
    TextKey.HidePassword to "Hide password",
    TextKey.ShowPassword to "Show password",
    TextKey.PasswordTooShort to "Password must contain at least {minimum} characters.",
    TextKey.PasswordTooLong to "Password cannot exceed {maximum} characters.",
    TextKey.PasswordMismatch to "Passwords do not match.",
    TextKey.Rooms to "Rooms",
    TextKey.Leaderboard to "Leaderboard",
    TextKey.Clan to "Clan",
    TextKey.Account to "Account",
    TextKey.FinishCurrentMatchBeforeChallenge to "Finish or leave your current match before opening a challenge.",
    TextKey.ModeUnlockLevel to "{mode} unlocks at level {level}.",
    TextKey.CannotOpenChallenge to "Cannot open challenge",
    TextKey.Understood to "Got it",
    TextKey.ChoosePracticeMode to "Choose practice mode",
    TextKey.ShareRoom to "Share room"
)

internal val vietnameseShellAuthTexts = mapOf(
    TextKey.Gold to "Vàng",
    TextKey.Gems to "Gem",
    TextKey.Notifications to "Thông báo",
    TextKey.ViewMoreCount to "XEM THÊM ({count})",
    TextKey.UpdateGameTitle to "CẬP NHẬT GAME",
    TextKey.UpdateAvailableSubtitle to "Phiên bản mới đã sẵn sàng",
    TextKey.UpdateHeroTitle to "SẴN SÀNG TĂNG TỐC?",
    TextKey.UpdateDescription to "Nhận bản sửa lỗi và cải tiến mới nhất.",
    TextKey.UpdateAutoReload to "Cập nhật nhanh, tự tải lại",
    TextKey.UpdateProgressPreserved to "Tài khoản và tiến trình của bạn vẫn được giữ nguyên.",
    TextKey.UpdateNow to "CẬP NHẬT NGAY",
    TextKey.Later to "ĐỂ SAU",
    TextKey.MaintenanceBadge to "ĐANG BẢO TRÌ",
    TextKey.MaintenanceTitle to "MÁY CHỦ ĐANG\nNGHỈ GIỮA HIỆP",
    TextKey.MaintenanceDefaultMessage to "Đội kỹ thuật đang nâng cấp đấu trường. Quá trình này có thể kéo dài vài giờ.",
    TextKey.MaintenanceAutoResume to "Hệ thống sẽ tự mở lại khi hoàn tất",
    TextKey.MaintenanceNoAction to "Bạn không cần thao tác, đăng xuất hoặc cài lại ứng dụng.",
    TextKey.OfflineBadge to "OFFLINE",
    TextKey.OfflineTitle to "TẠM MẤT\nKẾT NỐI",
    TextKey.OfflineDescription to "Các trận online đang tạm dừng. Game sẽ tự kết nối lại khi mạng ổn định.",
    TextKey.OfflineCheckNetwork to "Kiểm tra Wi-Fi hoặc dữ liệu di động",
    TextKey.OfflineNotMaintenance to "Đây là lỗi kết nối, không phải máy chủ đang bảo trì.",
    TextKey.RetryConnection to "THỬ KẾT NỐI LẠI",
    TextKey.OfflinePractice to "LUYỆN TẬP OFFLINE",
    TextKey.NoNetwork to "Không có kết nối mạng",
    TextKey.TutorialTitle to "HƯỚNG DẪN",
    TextKey.Skip to "Bỏ qua",
    TextKey.TutorialStep to "BƯỚC {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Tìm số thật nhanh",
    TextKey.TutorialFindNumbersDescription to "Chạm lần lượt từ 1 đến 50. Mục tiêu luôn nổi bật phía trên bàn.",
    TextKey.TutorialFindNumbersHint to "Chạm sai được ghi vào thống kê độ chính xác.",
    TextKey.TutorialSharedTargetTitle to "Cùng một mục tiêu",
    TextKey.TutorialSharedTargetDescription to "Hai người cùng nhìn một số. Người nhanh hơn ghi điểm và số bị khóa cả hai bên.",
    TextKey.TutorialSharedTargetHint to "Mỗi lượt đúng nhận 10 điểm.",
    TextKey.TutorialChooseModeTitle to "Chọn cách bạn muốn chơi",
    TextKey.TutorialChooseModeDescription to "Luyện tập offline, đấu thường hoặc xếp hạng ảnh hưởng Elo.",
    TextKey.TutorialChooseModeHint to "Có thể xem lại hướng dẫn trong Cài đặt.",
    TextKey.StartPlaying to "BẮT ĐẦU CHƠI",
    TextKey.Continue to "TIẾP TỤC",
    TextKey.VerifyEmailTitle to "Xác minh email",
    TextKey.VerifyEmailDescription to "Nhập mã 6 số được gửi tới địa chỉ email bên dưới. Mã có hiệu lực trong 15 phút.",
    TextKey.DevVerificationCode to "Môi trường dev – mã đã được tự điền:",
    TextKey.VerificationCode to "Mã xác minh",
    TextKey.Verifying to "ĐANG XÁC MINH…",
    TextKey.Verify to "XÁC MINH",
    TextKey.ResendCode to "GỬI LẠI MÃ",
    TextKey.Logout to "Đăng xuất",
    TextKey.AuthWelcomeDescription to "Đăng nhập để đồng bộ Elo, lịch sử và thành tích trên mọi thiết bị.",
    TextKey.AuthLoginTitle to "Đăng nhập",
    TextKey.Login to "ĐĂNG NHẬP",
    TextKey.LoggingIn to "ĐANG ĐĂNG NHẬP…",
    TextKey.CreateAccount to "TẠO TÀI KHOẢN",
    TextKey.PlayAsGuest to "Chơi với tư cách khách",
    TextKey.Password to "Mật khẩu",
    TextKey.ForgotPassword to "Quên mật khẩu?",
    TextKey.ResetPasswordTitle to "Khôi phục mật khẩu",
    TextKey.ResetPasswordDescription to "Nhập email để nhận mã khôi phục có hiệu lực trong 15 phút.",
    TextKey.Sending to "ĐANG GỬI…",
    TextKey.SendResetCode to "GỬI MÃ KHÔI PHỤC",
    TextKey.DevResetCode to "Môi trường dev – mã đã được tự điền:",
    TextKey.ResetCode to "Mã khôi phục",
    TextKey.NewPassword to "Mật khẩu mới (ít nhất {minimum} ký tự)",
    TextKey.ConfirmNewPassword to "Nhập lại mật khẩu mới",
    TextKey.Updating to "ĐANG CẬP NHẬT…",
    TextKey.ResetPasswordAction to "ĐẶT LẠI MẬT KHẨU",
    TextKey.UseDifferentEmail to "Dùng email khác",
    TextKey.DisplayName to "Biệt danh",
    TextKey.GenderDefaultAvatar to "GIỚI TÍNH · ẢNH ĐẠI DIỆN MẶC ĐỊNH",
    TextKey.Male to "Nam",
    TextKey.Female to "Nữ",
    TextKey.Player to "Người chơi",
    TextKey.PasswordWithMinimum to "Mật khẩu (ít nhất {minimum} ký tự)",
    TextKey.ConfirmPassword to "Nhập lại mật khẩu",
    TextKey.Creating to "ĐANG TẠO…",
    TextKey.SaveGuestAccountTitle to "Lưu tài khoản khách",
    TextKey.SaveGuestAccountDescription to "Elo, lịch sử, thống kê và thành tích hiện tại sẽ được giữ nguyên.",
    TextKey.Saving to "ĐANG LƯU…",
    TextKey.SaveAndCreateAccount to "LƯU VÀ TẠO TÀI KHOẢN",
    TextKey.Email to "Email",
    TextKey.HidePassword to "Ẩn mật khẩu",
    TextKey.ShowPassword to "Hiện mật khẩu",
    TextKey.PasswordTooShort to "Mật khẩu phải có ít nhất {minimum} ký tự.",
    TextKey.PasswordTooLong to "Mật khẩu không được vượt quá {maximum} ký tự.",
    TextKey.PasswordMismatch to "Mật khẩu nhập lại chưa khớp.",
    TextKey.Rooms to "Phòng",
    TextKey.Leaderboard to "Xếp hạng",
    TextKey.Clan to "Bang hội",
    TextKey.Account to "Tài khoản",
    TextKey.FinishCurrentMatchBeforeChallenge to "Hãy kết thúc hoặc rời trận hiện tại trước khi mở thử thách.",
    TextKey.ModeUnlockLevel to "Chế độ {mode} mở khóa ở cấp {level}.",
    TextKey.CannotOpenChallenge to "Không thể mở thử thách",
    TextKey.Understood to "Đã hiểu",
    TextKey.ChoosePracticeMode to "Chọn chế độ luyện tập",
    TextKey.ShareRoom to "Chia sẻ phòng"
)

internal val japaneseShellAuthTexts = mapOf(
    TextKey.Gold to "ゴールド",
    TextKey.Gems to "ジェム",
    TextKey.Notifications to "通知",
    TextKey.ViewMoreCount to "さらに表示（{count}）",
    TextKey.UpdateGameTitle to "ゲーム更新",
    TextKey.UpdateAvailableSubtitle to "新しいバージョンがあります",
    TextKey.UpdateHeroTitle to "さらに速くなる準備は？",
    TextKey.UpdateDescription to "最新の修正と改善を入手しましょう。",
    TextKey.UpdateAutoReload to "すばやく更新して自動再読み込み",
    TextKey.UpdateProgressPreserved to "アカウントと進行状況は保持されます。",
    TextKey.UpdateNow to "今すぐ更新",
    TextKey.Later to "後で",
    TextKey.MaintenanceBadge to "メンテナンス中",
    TextKey.MaintenanceTitle to "サーバーは現在\nメンテナンス中",
    TextKey.MaintenanceDefaultMessage to "アリーナをアップグレードしています。数時間かかる場合があります。",
    TextKey.MaintenanceAutoResume to "完了するとゲームは自動的に再開します",
    TextKey.MaintenanceNoAction to "ログアウトや再インストールは不要です。",
    TextKey.OfflineBadge to "オフライン",
    TextKey.OfflineTitle to "接続が\n切れました",
    TextKey.OfflineDescription to "オンライン対戦は一時停止中です。通信が安定すると自動で再接続します。",
    TextKey.OfflineCheckNetwork to "Wi-Fiまたはモバイル通信を確認",
    TextKey.OfflineNotMaintenance to "接続の問題であり、サーバーメンテナンスではありません。",
    TextKey.RetryConnection to "再接続",
    TextKey.OfflinePractice to "オフライン練習",
    TextKey.NoNetwork to "ネットワーク接続がありません",
    TextKey.TutorialTitle to "遊び方",
    TextKey.Skip to "スキップ",
    TextKey.TutorialStep to "ステップ {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "数字をすばやく探そう",
    TextKey.TutorialFindNumbersDescription to "1から50まで順番にタップします。次の数字はボード上部に表示されます。",
    TextKey.TutorialFindNumbersHint to "ミスタップは正確性の統計に記録されます。",
    TextKey.TutorialSharedTargetTitle to "同じターゲット",
    TextKey.TutorialSharedTargetDescription to "両方のプレイヤーに同じ数字が表示されます。速い方が得点し、両方の盤で数字がロックされます。",
    TextKey.TutorialSharedTargetHint to "正解するたびに10ポイント獲得します。",
    TextKey.TutorialChooseModeTitle to "プレイ方法を選ぼう",
    TextKey.TutorialChooseModeDescription to "オフライン練習、カジュアル対戦、Eloが変動するランク戦から選べます。",
    TextKey.TutorialChooseModeHint to "設定からいつでも遊び方を確認できます。",
    TextKey.StartPlaying to "ゲーム開始",
    TextKey.Continue to "次へ",
    TextKey.VerifyEmailTitle to "メールを確認",
    TextKey.VerifyEmailDescription to "以下のメールアドレスに送信された6桁のコードを入力してください。有効期限は15分です。",
    TextKey.DevVerificationCode to "開発モード — コードを自動入力しました：",
    TextKey.VerificationCode to "確認コード",
    TextKey.Verifying to "確認中…",
    TextKey.Verify to "確認",
    TextKey.ResendCode to "コードを再送信",
    TextKey.Logout to "ログアウト",
    TextKey.AuthWelcomeDescription to "ログインすると、Elo・履歴・実績をすべての端末で同期できます。",
    TextKey.AuthLoginTitle to "ログイン",
    TextKey.Login to "ログイン",
    TextKey.LoggingIn to "ログイン中…",
    TextKey.CreateAccount to "アカウント作成",
    TextKey.PlayAsGuest to "ゲストとしてプレイ",
    TextKey.Password to "パスワード",
    TextKey.ForgotPassword to "パスワードを忘れた場合",
    TextKey.ResetPasswordTitle to "パスワードを再設定",
    TextKey.ResetPasswordDescription to "メールアドレスを入力すると、15分間有効な再設定コードが届きます。",
    TextKey.Sending to "送信中…",
    TextKey.SendResetCode to "再設定コードを送信",
    TextKey.DevResetCode to "開発モード — コードを自動入力しました：",
    TextKey.ResetCode to "再設定コード",
    TextKey.NewPassword to "新しいパスワード（{minimum}文字以上）",
    TextKey.ConfirmNewPassword to "新しいパスワードを再入力",
    TextKey.Updating to "更新中…",
    TextKey.ResetPasswordAction to "パスワードを再設定",
    TextKey.UseDifferentEmail to "別のメールを使う",
    TextKey.DisplayName to "ニックネーム",
    TextKey.GenderDefaultAvatar to "性別・デフォルトアバター",
    TextKey.Male to "男性",
    TextKey.Female to "女性",
    TextKey.Player to "プレイヤー",
    TextKey.PasswordWithMinimum to "パスワード（{minimum}文字以上）",
    TextKey.ConfirmPassword to "パスワードを再入力",
    TextKey.Creating to "作成中…",
    TextKey.SaveGuestAccountTitle to "ゲストアカウントを保存",
    TextKey.SaveGuestAccountDescription to "現在のElo・履歴・統計・実績は保持されます。",
    TextKey.Saving to "保存中…",
    TextKey.SaveAndCreateAccount to "保存してアカウント作成",
    TextKey.Email to "メール",
    TextKey.HidePassword to "パスワードを隠す",
    TextKey.ShowPassword to "パスワードを表示",
    TextKey.PasswordTooShort to "パスワードは{minimum}文字以上で入力してください。",
    TextKey.PasswordTooLong to "パスワードは{maximum}文字以内で入力してください。",
    TextKey.PasswordMismatch to "パスワードが一致しません。",
    TextKey.Rooms to "ルーム",
    TextKey.Leaderboard to "ランキング",
    TextKey.Clan to "クラン",
    TextKey.Account to "アカウント",
    TextKey.FinishCurrentMatchBeforeChallenge to "チャレンジを開く前に現在の対戦を終了するか退出してください。",
    TextKey.ModeUnlockLevel to "{mode}はレベル{level}で解放されます。",
    TextKey.CannotOpenChallenge to "チャレンジを開けません",
    TextKey.Understood to "了解",
    TextKey.ChoosePracticeMode to "練習モードを選択",
    TextKey.ShareRoom to "ルームを共有"
)

internal val simplifiedChineseShellAuthTexts = mapOf(
    TextKey.Gold to "金币", TextKey.Gems to "宝石", TextKey.Notifications to "通知",
    TextKey.ViewMoreCount to "查看更多（{count}）",
    TextKey.UpdateGameTitle to "更新游戏", TextKey.UpdateAvailableSubtitle to "新版本已准备好",
    TextKey.UpdateHeroTitle to "准备加速了吗？", TextKey.UpdateDescription to "获取最新修复与改进。",
    TextKey.UpdateAutoReload to "快速更新，自动重载", TextKey.UpdateProgressPreserved to "账号和进度都会保留。",
    TextKey.UpdateNow to "立即更新", TextKey.Later to "稍后",
    TextKey.MaintenanceBadge to "维护中", TextKey.MaintenanceTitle to "服务器正在\n中场休息",
    TextKey.MaintenanceDefaultMessage to "团队正在升级竞技场，可能需要数小时。",
    TextKey.MaintenanceAutoResume to "完成后游戏将自动开放", TextKey.MaintenanceNoAction to "无需退出账号或重新安装应用。",
    TextKey.OfflineBadge to "离线", TextKey.OfflineTitle to "连接\n已断开",
    TextKey.OfflineDescription to "在线对战已暂停，网络稳定后游戏会自动重连。",
    TextKey.OfflineCheckNetwork to "检查 Wi-Fi 或移动数据", TextKey.OfflineNotMaintenance to "这是网络连接问题，并非服务器维护。",
    TextKey.RetryConnection to "重新连接", TextKey.OfflinePractice to "离线练习", TextKey.NoNetwork to "无网络连接",
    TextKey.TutorialTitle to "玩法说明", TextKey.Skip to "跳过", TextKey.TutorialStep to "第 {current} / {total} 步",
    TextKey.TutorialFindNumbersTitle to "快速找数字",
    TextKey.TutorialFindNumbersDescription to "按顺序点击 1 到 50，目标数字会突出显示在棋盘上方。",
    TextKey.TutorialFindNumbersHint to "点错会计入准确率统计。",
    TextKey.TutorialSharedTargetTitle to "共享同一目标",
    TextKey.TutorialSharedTargetDescription to "双方看到相同数字，更快的一方得分，并在两边棋盘锁定该数字。",
    TextKey.TutorialSharedTargetHint to "每次正确点击获得 10 分。",
    TextKey.TutorialChooseModeTitle to "选择玩法",
    TextKey.TutorialChooseModeDescription to "可选择离线练习、休闲对战或影响 Elo 的排位赛。",
    TextKey.TutorialChooseModeHint to "可随时在设置中重新查看玩法说明。",
    TextKey.StartPlaying to "开始游戏", TextKey.Continue to "继续",
    TextKey.VerifyEmailTitle to "验证邮箱",
    TextKey.VerifyEmailDescription to "输入发送至下方邮箱地址的 6 位验证码，有效期为 15 分钟。",
    TextKey.DevVerificationCode to "开发模式 — 已自动填入验证码：", TextKey.VerificationCode to "验证码",
    TextKey.Verifying to "验证中…", TextKey.Verify to "验证", TextKey.ResendCode to "重新发送", TextKey.Logout to "退出登录",
    TextKey.AuthWelcomeDescription to "登录后可在所有设备间同步 Elo、战绩和成就。",
    TextKey.AuthLoginTitle to "登录",
    TextKey.Login to "登录", TextKey.LoggingIn to "登录中…", TextKey.CreateAccount to "创建账号",
    TextKey.PlayAsGuest to "游客模式", TextKey.Password to "密码", TextKey.ForgotPassword to "忘记密码？",
    TextKey.ResetPasswordTitle to "重置密码", TextKey.ResetPasswordDescription to "输入邮箱以获取有效期 15 分钟的重置码。",
    TextKey.Sending to "发送中…", TextKey.SendResetCode to "发送重置码",
    TextKey.DevResetCode to "开发模式 — 已自动填入重置码：", TextKey.ResetCode to "重置码",
    TextKey.NewPassword to "新密码（至少 {minimum} 个字符）", TextKey.ConfirmNewPassword to "再次输入新密码",
    TextKey.Updating to "更新中…", TextKey.ResetPasswordAction to "重置密码", TextKey.UseDifferentEmail to "使用其他邮箱",
    TextKey.DisplayName to "昵称", TextKey.GenderDefaultAvatar to "性别 · 默认头像", TextKey.Male to "男", TextKey.Female to "女",
    TextKey.Player to "玩家", TextKey.PasswordWithMinimum to "密码（至少 {minimum} 个字符）",
    TextKey.ConfirmPassword to "确认密码", TextKey.Creating to "创建中…",
    TextKey.SaveGuestAccountTitle to "保存游客账号", TextKey.SaveGuestAccountDescription to "当前 Elo、战绩、统计和成就都会保留。",
    TextKey.Saving to "保存中…", TextKey.SaveAndCreateAccount to "保存并创建账号", TextKey.Email to "邮箱",
    TextKey.HidePassword to "隐藏密码", TextKey.ShowPassword to "显示密码",
    TextKey.PasswordTooShort to "密码至少需要 {minimum} 个字符。", TextKey.PasswordTooLong to "密码不能超过 {maximum} 个字符。",
    TextKey.PasswordMismatch to "两次密码不一致。", TextKey.Rooms to "房间", TextKey.Leaderboard to "排行榜",
    TextKey.Clan to "战队", TextKey.Account to "账号",
    TextKey.FinishCurrentMatchBeforeChallenge to "打开挑战前，请先结束或退出当前对战。",
    TextKey.ModeUnlockLevel to "{mode} 将在 {level} 级解锁。", TextKey.CannotOpenChallenge to "无法打开挑战",
    TextKey.Understood to "知道了", TextKey.ChoosePracticeMode to "选择练习模式", TextKey.ShareRoom to "分享房间"
)

internal val koreanShellAuthTexts = mapOf(
    TextKey.Gold to "골드", TextKey.Gems to "젬", TextKey.Notifications to "알림",
    TextKey.ViewMoreCount to "더 보기 ({count})",
    TextKey.UpdateGameTitle to "게임 업데이트", TextKey.UpdateAvailableSubtitle to "새 버전이 준비되었습니다",
    TextKey.UpdateHeroTitle to "더 빨라질 준비됐나요?", TextKey.UpdateDescription to "최신 수정 및 개선 사항을 받아보세요.",
    TextKey.UpdateAutoReload to "빠른 업데이트 후 자동 새로고침", TextKey.UpdateProgressPreserved to "계정과 진행 상황은 그대로 유지됩니다.",
    TextKey.UpdateNow to "지금 업데이트", TextKey.Later to "나중에",
    TextKey.MaintenanceBadge to "점검 중", TextKey.MaintenanceTitle to "서버가 잠시\n쉬고 있어요",
    TextKey.MaintenanceDefaultMessage to "경기장을 업그레이드하고 있습니다. 몇 시간이 걸릴 수 있습니다.",
    TextKey.MaintenanceAutoResume to "완료되면 게임이 자동으로 다시 열립니다", TextKey.MaintenanceNoAction to "로그아웃하거나 앱을 다시 설치할 필요가 없습니다.",
    TextKey.OfflineBadge to "오프라인", TextKey.OfflineTitle to "연결이\n끊겼습니다",
    TextKey.OfflineDescription to "온라인 경기가 일시 중지되었습니다. 네트워크가 안정되면 자동으로 다시 연결됩니다.",
    TextKey.OfflineCheckNetwork to "Wi-Fi 또는 모바일 데이터를 확인하세요", TextKey.OfflineNotMaintenance to "서버 점검이 아닌 연결 문제입니다.",
    TextKey.RetryConnection to "다시 연결", TextKey.OfflinePractice to "오프라인 연습", TextKey.NoNetwork to "네트워크 연결 없음",
    TextKey.TutorialTitle to "게임 방법", TextKey.Skip to "건너뛰기", TextKey.TutorialStep to "단계 {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "숫자를 빠르게 찾으세요",
    TextKey.TutorialFindNumbersDescription to "1부터 50까지 순서대로 누르세요. 목표 숫자는 보드 위에 강조됩니다.",
    TextKey.TutorialFindNumbersHint to "잘못 누른 횟수는 정확도 통계에 기록됩니다.",
    TextKey.TutorialSharedTargetTitle to "같은 목표",
    TextKey.TutorialSharedTargetDescription to "두 플레이어가 같은 숫자를 봅니다. 더 빠른 플레이어가 점수를 얻고 양쪽 보드에서 숫자가 잠깁니다.",
    TextKey.TutorialSharedTargetHint to "정답마다 10점을 얻습니다.",
    TextKey.TutorialChooseModeTitle to "플레이 방식 선택",
    TextKey.TutorialChooseModeDescription to "오프라인 연습, 일반전 또는 Elo가 변하는 랭크전을 선택하세요.",
    TextKey.TutorialChooseModeHint to "설정에서 언제든 다시 볼 수 있습니다.",
    TextKey.StartPlaying to "게임 시작", TextKey.Continue to "계속",
    TextKey.VerifyEmailTitle to "이메일 인증",
    TextKey.VerifyEmailDescription to "아래 이메일 주소로 전송된 6자리 코드를 입력하세요. 15분 동안 유효합니다.",
    TextKey.DevVerificationCode to "개발 모드 — 코드 자동 입력:", TextKey.VerificationCode to "인증 코드",
    TextKey.Verifying to "인증 중…", TextKey.Verify to "인증", TextKey.ResendCode to "코드 다시 보내기", TextKey.Logout to "로그아웃",
    TextKey.AuthWelcomeDescription to "로그인하면 모든 기기에서 Elo, 기록, 업적을 동기화할 수 있습니다.",
    TextKey.AuthLoginTitle to "로그인",
    TextKey.Login to "로그인", TextKey.LoggingIn to "로그인 중…", TextKey.CreateAccount to "계정 만들기",
    TextKey.PlayAsGuest to "게스트로 플레이", TextKey.Password to "비밀번호", TextKey.ForgotPassword to "비밀번호를 잊으셨나요?",
    TextKey.ResetPasswordTitle to "비밀번호 재설정", TextKey.ResetPasswordDescription to "이메일을 입력하면 15분 동안 유효한 재설정 코드를 보내드립니다.",
    TextKey.Sending to "보내는 중…", TextKey.SendResetCode to "재설정 코드 보내기",
    TextKey.DevResetCode to "개발 모드 — 코드 자동 입력:", TextKey.ResetCode to "재설정 코드",
    TextKey.NewPassword to "새 비밀번호 ({minimum}자 이상)", TextKey.ConfirmNewPassword to "새 비밀번호 확인",
    TextKey.Updating to "업데이트 중…", TextKey.ResetPasswordAction to "비밀번호 재설정", TextKey.UseDifferentEmail to "다른 이메일 사용",
    TextKey.DisplayName to "닉네임", TextKey.GenderDefaultAvatar to "성별 · 기본 아바타", TextKey.Male to "남성", TextKey.Female to "여성",
    TextKey.Player to "플레이어", TextKey.PasswordWithMinimum to "비밀번호 ({minimum}자 이상)", TextKey.ConfirmPassword to "비밀번호 확인",
    TextKey.Creating to "만드는 중…", TextKey.SaveGuestAccountTitle to "게스트 계정 저장",
    TextKey.SaveGuestAccountDescription to "현재 Elo, 기록, 통계, 업적이 그대로 유지됩니다.",
    TextKey.Saving to "저장 중…", TextKey.SaveAndCreateAccount to "저장하고 계정 만들기", TextKey.Email to "이메일",
    TextKey.HidePassword to "비밀번호 숨기기", TextKey.ShowPassword to "비밀번호 표시",
    TextKey.PasswordTooShort to "비밀번호는 {minimum}자 이상이어야 합니다.", TextKey.PasswordTooLong to "비밀번호는 {maximum}자를 넘을 수 없습니다.",
    TextKey.PasswordMismatch to "비밀번호가 일치하지 않습니다.", TextKey.Rooms to "방", TextKey.Leaderboard to "랭킹",
    TextKey.Clan to "클랜", TextKey.Account to "계정",
    TextKey.FinishCurrentMatchBeforeChallenge to "도전을 열기 전에 현재 경기를 끝내거나 나가세요.",
    TextKey.ModeUnlockLevel to "{mode} 모드는 레벨 {level}에서 해제됩니다.", TextKey.CannotOpenChallenge to "도전을 열 수 없습니다",
    TextKey.Understood to "확인", TextKey.ChoosePracticeMode to "연습 모드 선택", TextKey.ShareRoom to "방 공유"
)

internal val spanishShellAuthTexts = mapOf(
    TextKey.Gold to "Oro", TextKey.Gems to "Gemas", TextKey.Notifications to "Notificaciones",
    TextKey.ViewMoreCount to "VER MÁS ({count})",
    TextKey.UpdateGameTitle to "ACTUALIZAR JUEGO", TextKey.UpdateAvailableSubtitle to "Hay una nueva versión lista",
    TextKey.UpdateHeroTitle to "¿LISTO PARA ACELERAR?", TextKey.UpdateDescription to "Obtén las últimas correcciones y mejoras.",
    TextKey.UpdateAutoReload to "Actualización rápida y recarga automática", TextKey.UpdateProgressPreserved to "Tu cuenta y progreso se conservarán.",
    TextKey.UpdateNow to "ACTUALIZAR AHORA", TextKey.Later to "MÁS TARDE",
    TextKey.MaintenanceBadge to "MANTENIMIENTO", TextKey.MaintenanceTitle to "EL SERVIDOR ESTÁ\nEN DESCANSO",
    TextKey.MaintenanceDefaultMessage to "El equipo está mejorando la arena. Puede tardar unas horas.",
    TextKey.MaintenanceAutoResume to "El juego volverá a abrirse automáticamente", TextKey.MaintenanceNoAction to "No necesitas cerrar sesión ni reinstalar la app.",
    TextKey.OfflineBadge to "SIN CONEXIÓN", TextKey.OfflineTitle to "CONEXIÓN\nPERDIDA",
    TextKey.OfflineDescription to "Las partidas online están pausadas. El juego se reconectará cuando la red sea estable.",
    TextKey.OfflineCheckNetwork to "Comprueba el Wi-Fi o los datos móviles", TextKey.OfflineNotMaintenance to "Es un problema de conexión, no mantenimiento del servidor.",
    TextKey.RetryConnection to "RECONECTAR", TextKey.OfflinePractice to "PRÁCTICA OFFLINE", TextKey.NoNetwork to "Sin conexión de red",
    TextKey.TutorialTitle to "CÓMO JUGAR", TextKey.Skip to "Saltar", TextKey.TutorialStep to "PASO {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Encuentra números rápido",
    TextKey.TutorialFindNumbersDescription to "Toca del 1 al 50 en orden. El objetivo siempre destaca sobre el tablero.",
    TextKey.TutorialFindNumbersHint to "Los toques incorrectos cuentan en tus estadísticas de precisión.",
    TextKey.TutorialSharedTargetTitle to "Un objetivo compartido",
    TextKey.TutorialSharedTargetDescription to "Ambos jugadores ven el mismo número. El más rápido puntúa y lo bloquea en ambos tableros.",
    TextKey.TutorialSharedTargetHint to "Cada acierto da 10 puntos.",
    TextKey.TutorialChooseModeTitle to "Elige cómo jugar",
    TextKey.TutorialChooseModeDescription to "Practica offline, juega casual o compite en clasificatorias que afectan al Elo.",
    TextKey.TutorialChooseModeHint to "Puedes volver a ver esta guía desde Ajustes.",
    TextKey.StartPlaying to "EMPEZAR", TextKey.Continue to "CONTINUAR",
    TextKey.VerifyEmailTitle to "Verificar email", TextKey.VerifyEmailDescription to "Introduce el código de 6 dígitos enviado a la dirección de correo de abajo. Caduca en 15 minutos.",
    TextKey.DevVerificationCode to "Modo dev — código rellenado automáticamente:", TextKey.VerificationCode to "Código de verificación",
    TextKey.Verifying to "VERIFICANDO…", TextKey.Verify to "VERIFICAR", TextKey.ResendCode to "REENVIAR CÓDIGO", TextKey.Logout to "Cerrar sesión",
    TextKey.AuthWelcomeDescription to "Inicia sesión para sincronizar Elo, historial y logros entre dispositivos.",
    TextKey.AuthLoginTitle to "Iniciar sesión",
    TextKey.Login to "INICIAR SESIÓN", TextKey.LoggingIn to "INICIANDO SESIÓN…", TextKey.CreateAccount to "CREAR CUENTA",
    TextKey.PlayAsGuest to "Jugar como invitado", TextKey.Password to "Contraseña", TextKey.ForgotPassword to "¿Olvidaste la contraseña?",
    TextKey.ResetPasswordTitle to "Restablecer contraseña", TextKey.ResetPasswordDescription to "Introduce tu email para recibir un código válido durante 15 minutos.",
    TextKey.Sending to "ENVIANDO…", TextKey.SendResetCode to "ENVIAR CÓDIGO",
    TextKey.DevResetCode to "Modo dev — código rellenado automáticamente:", TextKey.ResetCode to "Código de recuperación",
    TextKey.NewPassword to "Nueva contraseña (mínimo {minimum} caracteres)", TextKey.ConfirmNewPassword to "Confirmar nueva contraseña",
    TextKey.Updating to "ACTUALIZANDO…", TextKey.ResetPasswordAction to "RESTABLECER CONTRASEÑA", TextKey.UseDifferentEmail to "Usar otro email",
    TextKey.DisplayName to "Apodo", TextKey.GenderDefaultAvatar to "GÉNERO · AVATAR PREDETERMINADO", TextKey.Male to "Hombre", TextKey.Female to "Mujer",
    TextKey.Player to "Jugador", TextKey.PasswordWithMinimum to "Contraseña (mínimo {minimum} caracteres)", TextKey.ConfirmPassword to "Confirmar contraseña",
    TextKey.Creating to "CREANDO…", TextKey.SaveGuestAccountTitle to "Guardar cuenta de invitado",
    TextKey.SaveGuestAccountDescription to "Se conservarán tu Elo, historial, estadísticas y logros actuales.",
    TextKey.Saving to "GUARDANDO…", TextKey.SaveAndCreateAccount to "GUARDAR Y CREAR CUENTA", TextKey.Email to "Email",
    TextKey.HidePassword to "Ocultar contraseña", TextKey.ShowPassword to "Mostrar contraseña",
    TextKey.PasswordTooShort to "La contraseña debe tener al menos {minimum} caracteres.", TextKey.PasswordTooLong to "La contraseña no puede superar {maximum} caracteres.",
    TextKey.PasswordMismatch to "Las contraseñas no coinciden.", TextKey.Rooms to "Salas", TextKey.Leaderboard to "Clasificación",
    TextKey.Clan to "Clan", TextKey.Account to "Cuenta",
    TextKey.FinishCurrentMatchBeforeChallenge to "Termina o abandona la partida actual antes de abrir un desafío.",
    TextKey.ModeUnlockLevel to "{mode} se desbloquea en el nivel {level}.", TextKey.CannotOpenChallenge to "No se puede abrir el desafío",
    TextKey.Understood to "Entendido", TextKey.ChoosePracticeMode to "Elegir modo de práctica", TextKey.ShareRoom to "Compartir sala"
)

internal val brazilianPortugueseShellAuthTexts = mapOf(
    TextKey.Gold to "Ouro", TextKey.Gems to "Gemas", TextKey.Notifications to "Notificações", TextKey.ViewMoreCount to "VER MAIS ({count})",
    TextKey.UpdateGameTitle to "ATUALIZAR JOGO", TextKey.UpdateAvailableSubtitle to "Uma nova versão está pronta",
    TextKey.UpdateHeroTitle to "PRONTO PARA ACELERAR?", TextKey.UpdateDescription to "Receba as correções e melhorias mais recentes.",
    TextKey.UpdateAutoReload to "Atualização rápida e recarga automática", TextKey.UpdateProgressPreserved to "Sua conta e seu progresso serão mantidos.",
    TextKey.UpdateNow to "ATUALIZAR AGORA", TextKey.Later to "MAIS TARDE",
    TextKey.MaintenanceBadge to "MANUTENÇÃO", TextKey.MaintenanceTitle to "SERVIDOR EM\nINTERVALO",
    TextKey.MaintenanceDefaultMessage to "A equipe está melhorando a arena. Isso pode levar algumas horas.",
    TextKey.MaintenanceAutoResume to "O jogo reabrirá automaticamente quando estiver pronto", TextKey.MaintenanceNoAction to "Não é preciso sair nem reinstalar o app.",
    TextKey.OfflineBadge to "OFFLINE", TextKey.OfflineTitle to "CONEXÃO\nPERDIDA",
    TextKey.OfflineDescription to "As partidas online estão pausadas. O jogo reconectará quando a rede estabilizar.",
    TextKey.OfflineCheckNetwork to "Confira o Wi-Fi ou os dados móveis", TextKey.OfflineNotMaintenance to "É um problema de conexão, não manutenção do servidor.",
    TextKey.RetryConnection to "RECONECTAR", TextKey.OfflinePractice to "TREINO OFFLINE", TextKey.NoNetwork to "Sem conexão de rede",
    TextKey.TutorialTitle to "COMO JOGAR", TextKey.Skip to "Pular", TextKey.TutorialStep to "PASSO {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Encontre números rápido", TextKey.TutorialFindNumbersDescription to "Toque de 1 a 50 em ordem. O alvo fica destacado acima do tabuleiro.",
    TextKey.TutorialFindNumbersHint to "Toques errados entram nas estatísticas de precisão.", TextKey.TutorialSharedTargetTitle to "Um alvo compartilhado",
    TextKey.TutorialSharedTargetDescription to "Os dois jogadores veem o mesmo número. O mais rápido pontua e bloqueia o número nos dois tabuleiros.",
    TextKey.TutorialSharedTargetHint to "Cada acerto vale 10 pontos.", TextKey.TutorialChooseModeTitle to "Escolha como jogar",
    TextKey.TutorialChooseModeDescription to "Treine offline, jogue casual ou entre em partidas ranqueadas que afetam o Elo.",
    TextKey.TutorialChooseModeHint to "Você pode rever este guia em Configurações.", TextKey.StartPlaying to "COMEÇAR", TextKey.Continue to "CONTINUAR",
    TextKey.VerifyEmailTitle to "Verificar email", TextKey.VerifyEmailDescription to "Digite o código de 6 dígitos enviado para o endereço de e-mail abaixo. Ele expira em 15 minutos.",
    TextKey.DevVerificationCode to "Modo dev — código preenchido automaticamente:", TextKey.VerificationCode to "Código de verificação",
    TextKey.Verifying to "VERIFICANDO…", TextKey.Verify to "VERIFICAR", TextKey.ResendCode to "REENVIAR CÓDIGO", TextKey.Logout to "Sair",
    TextKey.AuthWelcomeDescription to "Entre para sincronizar Elo, histórico e conquistas entre dispositivos.", TextKey.Login to "ENTRAR",
    TextKey.AuthLoginTitle to "Entrar",
    TextKey.LoggingIn to "ENTRANDO…", TextKey.CreateAccount to "CRIAR CONTA", TextKey.PlayAsGuest to "Jogar como convidado",
    TextKey.Password to "Senha", TextKey.ForgotPassword to "Esqueceu a senha?", TextKey.ResetPasswordTitle to "Redefinir senha",
    TextKey.ResetPasswordDescription to "Digite seu email para receber um código válido por 15 minutos.", TextKey.Sending to "ENVIANDO…",
    TextKey.SendResetCode to "ENVIAR CÓDIGO", TextKey.DevResetCode to "Modo dev — código preenchido automaticamente:",
    TextKey.ResetCode to "Código de redefinição", TextKey.NewPassword to "Nova senha (mínimo de {minimum} caracteres)",
    TextKey.ConfirmNewPassword to "Confirmar nova senha", TextKey.Updating to "ATUALIZANDO…", TextKey.ResetPasswordAction to "REDEFINIR SENHA",
    TextKey.UseDifferentEmail to "Usar outro email", TextKey.DisplayName to "Apelido", TextKey.GenderDefaultAvatar to "GÊNERO · AVATAR PADRÃO",
    TextKey.Male to "Masculino", TextKey.Female to "Feminino", TextKey.Player to "Jogador",
    TextKey.PasswordWithMinimum to "Senha (mínimo de {minimum} caracteres)", TextKey.ConfirmPassword to "Confirmar senha", TextKey.Creating to "CRIANDO…",
    TextKey.SaveGuestAccountTitle to "Salvar conta de convidado", TextKey.SaveGuestAccountDescription to "Seu Elo, histórico, estatísticas e conquistas serão mantidos.",
    TextKey.Saving to "SALVANDO…", TextKey.SaveAndCreateAccount to "SALVAR E CRIAR CONTA", TextKey.Email to "Email",
    TextKey.HidePassword to "Ocultar senha", TextKey.ShowPassword to "Mostrar senha",
    TextKey.PasswordTooShort to "A senha deve ter pelo menos {minimum} caracteres.", TextKey.PasswordTooLong to "A senha não pode exceder {maximum} caracteres.",
    TextKey.PasswordMismatch to "As senhas não coincidem.", TextKey.Rooms to "Salas", TextKey.Leaderboard to "Ranking", TextKey.Clan to "Clã", TextKey.Account to "Conta",
    TextKey.FinishCurrentMatchBeforeChallenge to "Termine ou saia da partida atual antes de abrir um desafio.",
    TextKey.ModeUnlockLevel to "{mode} é desbloqueado no nível {level}.", TextKey.CannotOpenChallenge to "Não foi possível abrir o desafio",
    TextKey.Understood to "Entendi", TextKey.ChoosePracticeMode to "Escolher modo de treino", TextKey.ShareRoom to "Compartilhar sala"
)

internal val frenchShellAuthTexts = mapOf(
    TextKey.Gold to "Or", TextKey.Gems to "Gemmes", TextKey.Notifications to "Notifications", TextKey.ViewMoreCount to "VOIR PLUS ({count})",
    TextKey.UpdateGameTitle to "MISE À JOUR DU JEU", TextKey.UpdateAvailableSubtitle to "Une nouvelle version est prête",
    TextKey.UpdateHeroTitle to "PRÊT À ACCÉLÉRER ?", TextKey.UpdateDescription to "Profitez des derniers correctifs et améliorations.",
    TextKey.UpdateAutoReload to "Mise à jour rapide et rechargement automatique", TextKey.UpdateProgressPreserved to "Votre compte et votre progression sont conservés.",
    TextKey.UpdateNow to "METTRE À JOUR", TextKey.Later to "PLUS TARD",
    TextKey.MaintenanceBadge to "MAINTENANCE", TextKey.MaintenanceTitle to "LE SERVEUR FAIT\nUNE PAUSE",
    TextKey.MaintenanceDefaultMessage to "L'équipe améliore l'arène. Cela peut prendre quelques heures.",
    TextKey.MaintenanceAutoResume to "Le jeu rouvrira automatiquement une fois prêt", TextKey.MaintenanceNoAction to "Inutile de vous déconnecter ou de réinstaller l'application.",
    TextKey.OfflineBadge to "HORS LIGNE", TextKey.OfflineTitle to "CONNEXION\nPERDUE",
    TextKey.OfflineDescription to "Les parties en ligne sont en pause. Le jeu se reconnectera quand le réseau sera stable.",
    TextKey.OfflineCheckNetwork to "Vérifiez le Wi-Fi ou les données mobiles", TextKey.OfflineNotMaintenance to "C'est un problème de connexion, pas une maintenance du serveur.",
    TextKey.RetryConnection to "SE RECONNECTER", TextKey.OfflinePractice to "ENTRAÎNEMENT HORS LIGNE", TextKey.NoNetwork to "Aucune connexion réseau",
    TextKey.TutorialTitle to "COMMENT JOUER", TextKey.Skip to "Passer", TextKey.TutorialStep to "ÉTAPE {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Trouvez vite les nombres", TextKey.TutorialFindNumbersDescription to "Touchez les nombres de 1 à 50 dans l'ordre. La cible est mise en évidence au-dessus du plateau.",
    TextKey.TutorialFindNumbersHint to "Les erreurs comptent dans vos statistiques de précision.", TextKey.TutorialSharedTargetTitle to "Une cible commune",
    TextKey.TutorialSharedTargetDescription to "Les deux joueurs voient le même nombre. Le plus rapide marque et le verrouille sur les deux plateaux.",
    TextKey.TutorialSharedTargetHint to "Chaque bonne réponse rapporte 10 points.", TextKey.TutorialChooseModeTitle to "Choisissez votre façon de jouer",
    TextKey.TutorialChooseModeDescription to "Entraînez-vous hors ligne, jouez en mode détente ou lancez une partie classée qui modifie l'Elo.",
    TextKey.TutorialChooseModeHint to "Vous pouvez revoir ce guide dans les Paramètres.", TextKey.StartPlaying to "COMMENCER", TextKey.Continue to "CONTINUER",
    TextKey.VerifyEmailTitle to "Vérifier l'e-mail", TextKey.VerifyEmailDescription to "Saisissez le code à 6 chiffres envoyé à l’adresse e-mail ci-dessous. Il expire dans 15 minutes.",
    TextKey.DevVerificationCode to "Mode dev — code rempli automatiquement :", TextKey.VerificationCode to "Code de vérification",
    TextKey.Verifying to "VÉRIFICATION…", TextKey.Verify to "VÉRIFIER", TextKey.ResendCode to "RENVOYER LE CODE", TextKey.Logout to "Se déconnecter",
    TextKey.AuthWelcomeDescription to "Connectez-vous pour synchroniser votre Elo, historique et vos succès entre appareils.",
    TextKey.AuthLoginTitle to "Connexion",
    TextKey.Login to "CONNEXION", TextKey.LoggingIn to "CONNEXION…", TextKey.CreateAccount to "CRÉER UN COMPTE",
    TextKey.PlayAsGuest to "Jouer en invité", TextKey.Password to "Mot de passe", TextKey.ForgotPassword to "Mot de passe oublié ?",
    TextKey.ResetPasswordTitle to "Réinitialiser le mot de passe", TextKey.ResetPasswordDescription to "Saisissez votre e-mail pour recevoir un code valable 15 minutes.",
    TextKey.Sending to "ENVOI…", TextKey.SendResetCode to "ENVOYER LE CODE",
    TextKey.DevResetCode to "Mode dev — code rempli automatiquement :", TextKey.ResetCode to "Code de réinitialisation",
    TextKey.NewPassword to "Nouveau mot de passe ({minimum} caractères minimum)", TextKey.ConfirmNewPassword to "Confirmer le nouveau mot de passe",
    TextKey.Updating to "MISE À JOUR…", TextKey.ResetPasswordAction to "RÉINITIALISER", TextKey.UseDifferentEmail to "Utiliser un autre e-mail",
    TextKey.DisplayName to "Pseudo", TextKey.GenderDefaultAvatar to "GENRE · AVATAR PAR DÉFAUT", TextKey.Male to "Homme", TextKey.Female to "Femme",
    TextKey.Player to "Joueur", TextKey.PasswordWithMinimum to "Mot de passe ({minimum} caractères minimum)", TextKey.ConfirmPassword to "Confirmer le mot de passe",
    TextKey.Creating to "CRÉATION…", TextKey.SaveGuestAccountTitle to "Enregistrer le compte invité",
    TextKey.SaveGuestAccountDescription to "Votre Elo, historique, vos statistiques et succès seront conservés.",
    TextKey.Saving to "ENREGISTREMENT…", TextKey.SaveAndCreateAccount to "ENREGISTRER ET CRÉER", TextKey.Email to "E-mail",
    TextKey.HidePassword to "Masquer le mot de passe", TextKey.ShowPassword to "Afficher le mot de passe",
    TextKey.PasswordTooShort to "Le mot de passe doit contenir au moins {minimum} caractères.", TextKey.PasswordTooLong to "Le mot de passe ne peut pas dépasser {maximum} caractères.",
    TextKey.PasswordMismatch to "Les mots de passe ne correspondent pas.", TextKey.Rooms to "Salles", TextKey.Leaderboard to "Classement", TextKey.Clan to "Clan", TextKey.Account to "Compte",
    TextKey.FinishCurrentMatchBeforeChallenge to "Terminez ou quittez la partie en cours avant d'ouvrir un défi.",
    TextKey.ModeUnlockLevel to "{mode} se débloque au niveau {level}.", TextKey.CannotOpenChallenge to "Impossible d'ouvrir le défi",
    TextKey.Understood to "Compris", TextKey.ChoosePracticeMode to "Choisir le mode entraînement", TextKey.ShareRoom to "Partager la salle"
)

internal val germanShellAuthTexts = mapOf(
    TextKey.Gold to "Gold", TextKey.Gems to "Juwelen", TextKey.Notifications to "Benachrichtigungen", TextKey.ViewMoreCount to "MEHR ANZEIGEN ({count})",
    TextKey.UpdateGameTitle to "SPIEL AKTUALISIEREN", TextKey.UpdateAvailableSubtitle to "Eine neue Version ist bereit",
    TextKey.UpdateHeroTitle to "BEREIT FÜR MEHR TEMPO?", TextKey.UpdateDescription to "Hol dir die neuesten Fehlerbehebungen und Verbesserungen.",
    TextKey.UpdateAutoReload to "Schnelles Update, automatisches Neuladen", TextKey.UpdateProgressPreserved to "Konto und Fortschritt bleiben erhalten.",
    TextKey.UpdateNow to "JETZT AKTUALISIEREN", TextKey.Later to "SPÄTER",
    TextKey.MaintenanceBadge to "WARTUNG", TextKey.MaintenanceTitle to "SERVER MACHT\nEINE PAUSE",
    TextKey.MaintenanceDefaultMessage to "Das Team verbessert die Arena. Dies kann einige Stunden dauern.",
    TextKey.MaintenanceAutoResume to "Das Spiel öffnet sich danach automatisch", TextKey.MaintenanceNoAction to "Abmelden oder Neuinstallieren ist nicht nötig.",
    TextKey.OfflineBadge to "OFFLINE", TextKey.OfflineTitle to "VERBINDUNG\nVERLOREN",
    TextKey.OfflineDescription to "Online-Partien sind pausiert. Das Spiel verbindet sich bei stabilem Netz erneut.",
    TextKey.OfflineCheckNetwork to "WLAN oder mobile Daten prüfen", TextKey.OfflineNotMaintenance to "Dies ist ein Verbindungsproblem, keine Serverwartung.",
    TextKey.RetryConnection to "NEU VERBINDEN", TextKey.OfflinePractice to "OFFLINE-TRAINING", TextKey.NoNetwork to "Keine Netzwerkverbindung",
    TextKey.TutorialTitle to "SO WIRD GESPIELT", TextKey.Skip to "Überspringen", TextKey.TutorialStep to "SCHRITT {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Zahlen schnell finden", TextKey.TutorialFindNumbersDescription to "Tippe der Reihe nach von 1 bis 50. Das Ziel wird über dem Feld hervorgehoben.",
    TextKey.TutorialFindNumbersHint to "Fehltipps fließen in deine Genauigkeitsstatistik ein.", TextKey.TutorialSharedTargetTitle to "Ein gemeinsames Ziel",
    TextKey.TutorialSharedTargetDescription to "Beide sehen dieselbe Zahl. Wer schneller ist, punktet und sperrt sie auf beiden Feldern.",
    TextKey.TutorialSharedTargetHint to "Jeder Treffer bringt 10 Punkte.", TextKey.TutorialChooseModeTitle to "Spielweise wählen",
    TextKey.TutorialChooseModeDescription to "Trainiere offline, spiele locker oder tritt in Ranglistenpartien mit Elo-Wertung an.",
    TextKey.TutorialChooseModeHint to "Du kannst diese Anleitung in den Einstellungen erneut öffnen.", TextKey.StartPlaying to "SPIEL STARTEN", TextKey.Continue to "WEITER",
    TextKey.VerifyEmailTitle to "E-Mail bestätigen", TextKey.VerifyEmailDescription to "Gib den 6-stelligen Code ein, der an die unten stehende E-Mail-Adresse gesendet wurde. Er gilt 15 Minuten.",
    TextKey.DevVerificationCode to "Dev-Modus — Code automatisch eingefügt:", TextKey.VerificationCode to "Bestätigungscode",
    TextKey.Verifying to "WIRD BESTÄTIGT…", TextKey.Verify to "BESTÄTIGEN", TextKey.ResendCode to "CODE ERNEUT SENDEN", TextKey.Logout to "Abmelden",
    TextKey.AuthWelcomeDescription to "Melde dich an, um Elo, Verlauf und Erfolge auf allen Geräten zu synchronisieren.",
    TextKey.AuthLoginTitle to "Anmelden",
    TextKey.Login to "ANMELDEN", TextKey.LoggingIn to "ANMELDUNG…", TextKey.CreateAccount to "KONTO ERSTELLEN",
    TextKey.PlayAsGuest to "Als Gast spielen", TextKey.Password to "Passwort", TextKey.ForgotPassword to "Passwort vergessen?",
    TextKey.ResetPasswordTitle to "Passwort zurücksetzen", TextKey.ResetPasswordDescription to "Gib deine E-Mail ein, um einen 15 Minuten gültigen Code zu erhalten.",
    TextKey.Sending to "WIRD GESENDET…", TextKey.SendResetCode to "CODE SENDEN", TextKey.DevResetCode to "Dev-Modus — Code automatisch eingefügt:",
    TextKey.ResetCode to "Rücksetzcode", TextKey.NewPassword to "Neues Passwort (mindestens {minimum} Zeichen)", TextKey.ConfirmNewPassword to "Neues Passwort bestätigen",
    TextKey.Updating to "WIRD AKTUALISIERT…", TextKey.ResetPasswordAction to "PASSWORT ZURÜCKSETZEN", TextKey.UseDifferentEmail to "Andere E-Mail verwenden",
    TextKey.DisplayName to "Spitzname", TextKey.GenderDefaultAvatar to "GESCHLECHT · STANDARD-AVATAR", TextKey.Male to "Männlich", TextKey.Female to "Weiblich",
    TextKey.Player to "Spieler", TextKey.PasswordWithMinimum to "Passwort (mindestens {minimum} Zeichen)", TextKey.ConfirmPassword to "Passwort bestätigen",
    TextKey.Creating to "WIRD ERSTELLT…", TextKey.SaveGuestAccountTitle to "Gastkonto speichern",
    TextKey.SaveGuestAccountDescription to "Deine aktuelle Elo, dein Verlauf, deine Statistiken und Erfolge bleiben erhalten.",
    TextKey.Saving to "WIRD GESPEICHERT…", TextKey.SaveAndCreateAccount to "SPEICHERN & KONTO ERSTELLEN", TextKey.Email to "E-Mail",
    TextKey.HidePassword to "Passwort ausblenden", TextKey.ShowPassword to "Passwort anzeigen",
    TextKey.PasswordTooShort to "Das Passwort muss mindestens {minimum} Zeichen lang sein.", TextKey.PasswordTooLong to "Das Passwort darf höchstens {maximum} Zeichen lang sein.",
    TextKey.PasswordMismatch to "Die Passwörter stimmen nicht überein.", TextKey.Rooms to "Räume", TextKey.Leaderboard to "Rangliste", TextKey.Clan to "Clan", TextKey.Account to "Konto",
    TextKey.FinishCurrentMatchBeforeChallenge to "Beende oder verlasse die aktuelle Partie, bevor du eine Herausforderung öffnest.",
    TextKey.ModeUnlockLevel to "{mode} wird auf Stufe {level} freigeschaltet.", TextKey.CannotOpenChallenge to "Herausforderung kann nicht geöffnet werden",
    TextKey.Understood to "Verstanden", TextKey.ChoosePracticeMode to "Trainingsmodus wählen", TextKey.ShareRoom to "Raum teilen"
)

internal val indonesianShellAuthTexts = mapOf(
    TextKey.Gold to "Emas", TextKey.Gems to "Gem", TextKey.Notifications to "Notifikasi", TextKey.ViewMoreCount to "LIHAT LAGI ({count})",
    TextKey.UpdateGameTitle to "PERBARUI GAME", TextKey.UpdateAvailableSubtitle to "Versi baru sudah siap",
    TextKey.UpdateHeroTitle to "SIAP MAKIN CEPAT?", TextKey.UpdateDescription to "Dapatkan perbaikan dan peningkatan terbaru.",
    TextKey.UpdateAutoReload to "Pembaruan cepat, muat ulang otomatis", TextKey.UpdateProgressPreserved to "Akun dan progresmu tetap tersimpan.",
    TextKey.UpdateNow to "PERBARUI SEKARANG", TextKey.Later to "NANTI",
    TextKey.MaintenanceBadge to "PEMELIHARAAN", TextKey.MaintenanceTitle to "SERVER SEDANG\nISTIRAHAT",
    TextKey.MaintenanceDefaultMessage to "Tim sedang meningkatkan arena. Proses ini dapat memakan waktu beberapa jam.",
    TextKey.MaintenanceAutoResume to "Game akan terbuka otomatis setelah selesai", TextKey.MaintenanceNoAction to "Tidak perlu keluar atau memasang ulang aplikasi.",
    TextKey.OfflineBadge to "OFFLINE", TextKey.OfflineTitle to "KONEKSI\nTERPUTUS",
    TextKey.OfflineDescription to "Pertandingan online dijeda. Game akan tersambung kembali saat jaringan stabil.",
    TextKey.OfflineCheckNetwork to "Periksa Wi-Fi atau data seluler", TextKey.OfflineNotMaintenance to "Ini masalah koneksi, bukan pemeliharaan server.",
    TextKey.RetryConnection to "SAMBUNGKAN LAGI", TextKey.OfflinePractice to "LATIHAN OFFLINE", TextKey.NoNetwork to "Tidak ada koneksi jaringan",
    TextKey.TutorialTitle to "CARA BERMAIN", TextKey.Skip to "Lewati", TextKey.TutorialStep to "LANGKAH {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Temukan angka dengan cepat", TextKey.TutorialFindNumbersDescription to "Ketuk 1 hingga 50 secara berurutan. Target selalu disorot di atas papan.",
    TextKey.TutorialFindNumbersHint to "Ketukan salah masuk ke statistik akurasi.", TextKey.TutorialSharedTargetTitle to "Satu target bersama",
    TextKey.TutorialSharedTargetDescription to "Kedua pemain melihat angka yang sama. Pemain tercepat mendapat poin dan mengunci angka di kedua papan.",
    TextKey.TutorialSharedTargetHint to "Setiap jawaban benar mendapat 10 poin.", TextKey.TutorialChooseModeTitle to "Pilih cara bermain",
    TextKey.TutorialChooseModeDescription to "Latihan offline, main santai, atau masuk pertandingan peringkat yang memengaruhi Elo.",
    TextKey.TutorialChooseModeHint to "Panduan ini dapat dibuka lagi dari Pengaturan.", TextKey.StartPlaying to "MULAI BERMAIN", TextKey.Continue to "LANJUT",
    TextKey.VerifyEmailTitle to "Verifikasi email", TextKey.VerifyEmailDescription to "Masukkan kode 6 digit yang dikirim ke alamat email di bawah. Berlaku selama 15 menit.",
    TextKey.DevVerificationCode to "Mode dev — kode terisi otomatis:", TextKey.VerificationCode to "Kode verifikasi",
    TextKey.Verifying to "MEMVERIFIKASI…", TextKey.Verify to "VERIFIKASI", TextKey.ResendCode to "KIRIM ULANG KODE", TextKey.Logout to "Keluar",
    TextKey.AuthWelcomeDescription to "Masuk untuk menyinkronkan Elo, riwayat, dan pencapaian di semua perangkat.",
    TextKey.AuthLoginTitle to "Masuk",
    TextKey.Login to "MASUK", TextKey.LoggingIn to "SEDANG MASUK…", TextKey.CreateAccount to "BUAT AKUN", TextKey.PlayAsGuest to "Main sebagai tamu",
    TextKey.Password to "Kata sandi", TextKey.ForgotPassword to "Lupa kata sandi?", TextKey.ResetPasswordTitle to "Atur ulang kata sandi",
    TextKey.ResetPasswordDescription to "Masukkan email untuk menerima kode yang berlaku 15 menit.", TextKey.Sending to "MENGIRIM…",
    TextKey.SendResetCode to "KIRIM KODE", TextKey.DevResetCode to "Mode dev — kode terisi otomatis:", TextKey.ResetCode to "Kode pemulihan",
    TextKey.NewPassword to "Kata sandi baru (minimal {minimum} karakter)", TextKey.ConfirmNewPassword to "Konfirmasi kata sandi baru",
    TextKey.Updating to "MEMPERBARUI…", TextKey.ResetPasswordAction to "ATUR ULANG KATA SANDI", TextKey.UseDifferentEmail to "Gunakan email lain",
    TextKey.DisplayName to "Nama panggilan", TextKey.GenderDefaultAvatar to "GENDER · AVATAR BAWAAN", TextKey.Male to "Pria", TextKey.Female to "Wanita",
    TextKey.Player to "Pemain", TextKey.PasswordWithMinimum to "Kata sandi (minimal {minimum} karakter)", TextKey.ConfirmPassword to "Konfirmasi kata sandi",
    TextKey.Creating to "MEMBUAT…", TextKey.SaveGuestAccountTitle to "Simpan akun tamu",
    TextKey.SaveGuestAccountDescription to "Elo, riwayat, statistik, dan pencapaianmu saat ini akan dipertahankan.",
    TextKey.Saving to "MENYIMPAN…", TextKey.SaveAndCreateAccount to "SIMPAN & BUAT AKUN", TextKey.Email to "Email",
    TextKey.HidePassword to "Sembunyikan kata sandi", TextKey.ShowPassword to "Tampilkan kata sandi",
    TextKey.PasswordTooShort to "Kata sandi minimal {minimum} karakter.", TextKey.PasswordTooLong to "Kata sandi tidak boleh lebih dari {maximum} karakter.",
    TextKey.PasswordMismatch to "Kata sandi tidak cocok.", TextKey.Rooms to "Ruang", TextKey.Leaderboard to "Peringkat", TextKey.Clan to "Klan", TextKey.Account to "Akun",
    TextKey.FinishCurrentMatchBeforeChallenge to "Selesaikan atau tinggalkan pertandingan saat ini sebelum membuka tantangan.",
    TextKey.ModeUnlockLevel to "{mode} terbuka di level {level}.", TextKey.CannotOpenChallenge to "Tantangan tidak dapat dibuka",
    TextKey.Understood to "Mengerti", TextKey.ChoosePracticeMode to "Pilih mode latihan", TextKey.ShareRoom to "Bagikan ruang"
)

internal val thaiShellAuthTexts = mapOf(
    TextKey.Gold to "ทอง", TextKey.Gems to "เจม", TextKey.Notifications to "การแจ้งเตือน", TextKey.ViewMoreCount to "ดูเพิ่ม ({count})",
    TextKey.UpdateGameTitle to "อัปเดตเกม", TextKey.UpdateAvailableSubtitle to "เวอร์ชันใหม่พร้อมแล้ว",
    TextKey.UpdateHeroTitle to "พร้อมเร่งความเร็วหรือยัง?", TextKey.UpdateDescription to "รับการแก้ไขและการปรับปรุงล่าสุด",
    TextKey.UpdateAutoReload to "อัปเดตรวดเร็วและโหลดใหม่อัตโนมัติ", TextKey.UpdateProgressPreserved to "บัญชีและความคืบหน้าของคุณยังคงอยู่",
    TextKey.UpdateNow to "อัปเดตตอนนี้", TextKey.Later to "ไว้ทีหลัง",
    TextKey.MaintenanceBadge to "กำลังบำรุงรักษา", TextKey.MaintenanceTitle to "เซิร์ฟเวอร์กำลัง\nพักครึ่ง",
    TextKey.MaintenanceDefaultMessage to "ทีมงานกำลังปรับปรุงสนาม อาจใช้เวลาหลายชั่วโมง",
    TextKey.MaintenanceAutoResume to "เกมจะเปิดอีกครั้งอัตโนมัติเมื่อพร้อม", TextKey.MaintenanceNoAction to "ไม่ต้องออกจากระบบหรือติดตั้งแอปใหม่",
    TextKey.OfflineBadge to "ออฟไลน์", TextKey.OfflineTitle to "ขาดการ\nเชื่อมต่อ",
    TextKey.OfflineDescription to "การแข่งขันออนไลน์หยุดชั่วคราว เกมจะเชื่อมต่อใหม่เมื่อเครือข่ายเสถียร",
    TextKey.OfflineCheckNetwork to "ตรวจสอบ Wi-Fi หรือข้อมูลมือถือ", TextKey.OfflineNotMaintenance to "นี่คือปัญหาการเชื่อมต่อ ไม่ใช่การบำรุงรักษาเซิร์ฟเวอร์",
    TextKey.RetryConnection to "เชื่อมต่อใหม่", TextKey.OfflinePractice to "ฝึกออฟไลน์", TextKey.NoNetwork to "ไม่มีการเชื่อมต่อเครือข่าย",
    TextKey.TutorialTitle to "วิธีเล่น", TextKey.Skip to "ข้าม", TextKey.TutorialStep to "ขั้นที่ {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "ค้นหาตัวเลขให้เร็ว", TextKey.TutorialFindNumbersDescription to "แตะเลข 1 ถึง 50 ตามลำดับ เป้าหมายจะแสดงเด่นเหนือกระดานเสมอ",
    TextKey.TutorialFindNumbersHint to "การแตะผิดจะถูกนับในสถิติความแม่นยำ", TextKey.TutorialSharedTargetTitle to "เป้าหมายเดียวกัน",
    TextKey.TutorialSharedTargetDescription to "ผู้เล่นทั้งสองเห็นเลขเดียวกัน คนที่เร็วกว่าจะได้คะแนนและล็อกเลขบนทั้งสองกระดาน",
    TextKey.TutorialSharedTargetHint to "ตอบถูกแต่ละครั้งได้ 10 คะแนน", TextKey.TutorialChooseModeTitle to "เลือกวิธีเล่น",
    TextKey.TutorialChooseModeDescription to "ฝึกออฟไลน์ เล่นทั่วไป หรือเล่นจัดอันดับที่มีผลต่อ Elo",
    TextKey.TutorialChooseModeHint to "เปิดดูคำแนะนำนี้อีกครั้งได้จากการตั้งค่า", TextKey.StartPlaying to "เริ่มเล่น", TextKey.Continue to "ต่อไป",
    TextKey.VerifyEmailTitle to "ยืนยันอีเมล", TextKey.VerifyEmailDescription to "กรอกรหัส 6 หลักที่ส่งไปยังอีเมลด้านล่าง รหัสหมดอายุใน 15 นาที",
    TextKey.DevVerificationCode to "โหมด dev — กรอกรหัสให้อัตโนมัติ:", TextKey.VerificationCode to "รหัสยืนยัน",
    TextKey.Verifying to "กำลังยืนยัน…", TextKey.Verify to "ยืนยัน", TextKey.ResendCode to "ส่งรหัสอีกครั้ง", TextKey.Logout to "ออกจากระบบ",
    TextKey.AuthWelcomeDescription to "เข้าสู่ระบบเพื่อซิงค์ Elo ประวัติ และความสำเร็จในทุกอุปกรณ์",
    TextKey.AuthLoginTitle to "เข้าสู่ระบบ",
    TextKey.Login to "เข้าสู่ระบบ", TextKey.LoggingIn to "กำลังเข้าสู่ระบบ…", TextKey.CreateAccount to "สร้างบัญชี", TextKey.PlayAsGuest to "เล่นแบบผู้เยี่ยมชม",
    TextKey.Password to "รหัสผ่าน", TextKey.ForgotPassword to "ลืมรหัสผ่าน?", TextKey.ResetPasswordTitle to "รีเซ็ตรหัสผ่าน",
    TextKey.ResetPasswordDescription to "กรอกอีเมลเพื่อรับรหัสรีเซ็ตที่ใช้ได้ 15 นาที", TextKey.Sending to "กำลังส่ง…",
    TextKey.SendResetCode to "ส่งรหัสรีเซ็ต", TextKey.DevResetCode to "โหมด dev — กรอกรหัสให้อัตโนมัติ:", TextKey.ResetCode to "รหัสรีเซ็ต",
    TextKey.NewPassword to "รหัสผ่านใหม่ (อย่างน้อย {minimum} ตัวอักษร)", TextKey.ConfirmNewPassword to "ยืนยันรหัสผ่านใหม่",
    TextKey.Updating to "กำลังอัปเดต…", TextKey.ResetPasswordAction to "รีเซ็ตรหัสผ่าน", TextKey.UseDifferentEmail to "ใช้อีเมลอื่น",
    TextKey.DisplayName to "ชื่อเล่น", TextKey.GenderDefaultAvatar to "เพศ · อวตารเริ่มต้น", TextKey.Male to "ชาย", TextKey.Female to "หญิง",
    TextKey.Player to "ผู้เล่น", TextKey.PasswordWithMinimum to "รหัสผ่าน (อย่างน้อย {minimum} ตัวอักษร)", TextKey.ConfirmPassword to "ยืนยันรหัสผ่าน",
    TextKey.Creating to "กำลังสร้าง…", TextKey.SaveGuestAccountTitle to "บันทึกบัญชีผู้เยี่ยมชม",
    TextKey.SaveGuestAccountDescription to "Elo ประวัติ สถิติ และความสำเร็จปัจจุบันจะยังคงอยู่",
    TextKey.Saving to "กำลังบันทึก…", TextKey.SaveAndCreateAccount to "บันทึกและสร้างบัญชี", TextKey.Email to "อีเมล",
    TextKey.HidePassword to "ซ่อนรหัสผ่าน", TextKey.ShowPassword to "แสดงรหัสผ่าน",
    TextKey.PasswordTooShort to "รหัสผ่านต้องมีอย่างน้อย {minimum} ตัวอักษร", TextKey.PasswordTooLong to "รหัสผ่านต้องไม่เกิน {maximum} ตัวอักษร",
    TextKey.PasswordMismatch to "รหัสผ่านไม่ตรงกัน", TextKey.Rooms to "ห้อง", TextKey.Leaderboard to "อันดับ", TextKey.Clan to "แคลน", TextKey.Account to "บัญชี",
    TextKey.FinishCurrentMatchBeforeChallenge to "จบหรือออกจากการแข่งขันปัจจุบันก่อนเปิดความท้าทาย",
    TextKey.ModeUnlockLevel to "{mode} ปลดล็อกที่เลเวล {level}", TextKey.CannotOpenChallenge to "เปิดความท้าทายไม่ได้",
    TextKey.Understood to "เข้าใจแล้ว", TextKey.ChoosePracticeMode to "เลือกโหมดฝึก", TextKey.ShareRoom to "แชร์ห้อง"
)

internal val russianShellAuthTexts = mapOf(
    TextKey.Gold to "Золото", TextKey.Gems to "Кристаллы", TextKey.Notifications to "Уведомления", TextKey.ViewMoreCount to "ПОКАЗАТЬ ЕЩЁ ({count})",
    TextKey.UpdateGameTitle to "ОБНОВЛЕНИЕ ИГРЫ", TextKey.UpdateAvailableSubtitle to "Новая версия готова",
    TextKey.UpdateHeroTitle to "ГОТОВЫ УСКОРИТЬСЯ?", TextKey.UpdateDescription to "Получите последние исправления и улучшения.",
    TextKey.UpdateAutoReload to "Быстрое обновление и автоперезапуск", TextKey.UpdateProgressPreserved to "Аккаунт и прогресс сохранятся.",
    TextKey.UpdateNow to "ОБНОВИТЬ СЕЙЧАС", TextKey.Later to "ПОЗЖЕ",
    TextKey.MaintenanceBadge to "ТЕХОБСЛУЖИВАНИЕ", TextKey.MaintenanceTitle to "СЕРВЕР ВЗЯЛ\nТАЙМ-АУТ",
    TextKey.MaintenanceDefaultMessage to "Команда улучшает арену. Это может занять несколько часов.",
    TextKey.MaintenanceAutoResume to "Игра откроется автоматически после завершения", TextKey.MaintenanceNoAction to "Не нужно выходить из аккаунта или переустанавливать приложение.",
    TextKey.OfflineBadge to "НЕ В СЕТИ", TextKey.OfflineTitle to "СОЕДИНЕНИЕ\nПОТЕРЯНО",
    TextKey.OfflineDescription to "Онлайн-матчи приостановлены. Игра подключится снова, когда сеть станет стабильной.",
    TextKey.OfflineCheckNetwork to "Проверьте Wi-Fi или мобильный интернет", TextKey.OfflineNotMaintenance to "Это проблема соединения, а не техобслуживание сервера.",
    TextKey.RetryConnection to "ПОДКЛЮЧИТЬСЯ СНОВА", TextKey.OfflinePractice to "ТРЕНИРОВКА ОФЛАЙН", TextKey.NoNetwork to "Нет подключения к сети",
    TextKey.TutorialTitle to "КАК ИГРАТЬ", TextKey.Skip to "Пропустить", TextKey.TutorialStep to "ШАГ {current} / {total}",
    TextKey.TutorialFindNumbersTitle to "Быстро находите числа", TextKey.TutorialFindNumbersDescription to "Нажимайте числа от 1 до 50 по порядку. Цель всегда выделена над полем.",
    TextKey.TutorialFindNumbersHint to "Ошибочные нажатия учитываются в статистике точности.", TextKey.TutorialSharedTargetTitle to "Одна общая цель",
    TextKey.TutorialSharedTargetDescription to "Оба игрока видят одно число. Более быстрый получает очки и блокирует число на обоих полях.",
    TextKey.TutorialSharedTargetHint to "За каждый верный ход даётся 10 очков.", TextKey.TutorialChooseModeTitle to "Выберите режим",
    TextKey.TutorialChooseModeDescription to "Тренируйтесь офлайн, играйте обычно или участвуйте в рейтинговых матчах с изменением Elo.",
    TextKey.TutorialChooseModeHint to "Эту инструкцию можно снова открыть в настройках.", TextKey.StartPlaying to "НАЧАТЬ ИГРУ", TextKey.Continue to "ДАЛЕЕ",
    TextKey.VerifyEmailTitle to "Подтвердить почту", TextKey.VerifyEmailDescription to "Введите 6-значный код, отправленный на указанный ниже адрес электронной почты. Он действует 15 минут.",
    TextKey.DevVerificationCode to "Режим разработки — код введён автоматически:", TextKey.VerificationCode to "Код подтверждения",
    TextKey.Verifying to "ПРОВЕРКА…", TextKey.Verify to "ПОДТВЕРДИТЬ", TextKey.ResendCode to "ОТПРАВИТЬ КОД СНОВА", TextKey.Logout to "Выйти",
    TextKey.AuthWelcomeDescription to "Войдите, чтобы синхронизировать Elo, историю и достижения на всех устройствах.",
    TextKey.AuthLoginTitle to "Войти",
    TextKey.Login to "ВОЙТИ", TextKey.LoggingIn to "ВХОД…", TextKey.CreateAccount to "СОЗДАТЬ АККАУНТ", TextKey.PlayAsGuest to "Играть как гость",
    TextKey.Password to "Пароль", TextKey.ForgotPassword to "Забыли пароль?", TextKey.ResetPasswordTitle to "Сбросить пароль",
    TextKey.ResetPasswordDescription to "Введите почту, чтобы получить код сброса, действующий 15 минут.", TextKey.Sending to "ОТПРАВКА…",
    TextKey.SendResetCode to "ОТПРАВИТЬ КОД", TextKey.DevResetCode to "Режим разработки — код введён автоматически:", TextKey.ResetCode to "Код сброса",
    TextKey.NewPassword to "Новый пароль (не менее {minimum} символов)", TextKey.ConfirmNewPassword to "Повторите новый пароль",
    TextKey.Updating to "ОБНОВЛЕНИЕ…", TextKey.ResetPasswordAction to "СБРОСИТЬ ПАРОЛЬ", TextKey.UseDifferentEmail to "Использовать другую почту",
    TextKey.DisplayName to "Псевдоним", TextKey.GenderDefaultAvatar to "ПОЛ · АВАТАР ПО УМОЛЧАНИЮ", TextKey.Male to "Мужской", TextKey.Female to "Женский",
    TextKey.Player to "Игрок", TextKey.PasswordWithMinimum to "Пароль (не менее {minimum} символов)", TextKey.ConfirmPassword to "Повторите пароль",
    TextKey.Creating to "СОЗДАНИЕ…", TextKey.SaveGuestAccountTitle to "Сохранить гостевой аккаунт",
    TextKey.SaveGuestAccountDescription to "Текущие Elo, история, статистика и достижения сохранятся.",
    TextKey.Saving to "СОХРАНЕНИЕ…", TextKey.SaveAndCreateAccount to "СОХРАНИТЬ И СОЗДАТЬ", TextKey.Email to "Эл. почта",
    TextKey.HidePassword to "Скрыть пароль", TextKey.ShowPassword to "Показать пароль",
    TextKey.PasswordTooShort to "Пароль должен содержать не менее {minimum} символов.", TextKey.PasswordTooLong to "Пароль не должен превышать {maximum} символов.",
    TextKey.PasswordMismatch to "Пароли не совпадают.", TextKey.Rooms to "Комнаты", TextKey.Leaderboard to "Рейтинг", TextKey.Clan to "Клан", TextKey.Account to "Аккаунт",
    TextKey.FinishCurrentMatchBeforeChallenge to "Завершите или покиньте текущий матч, прежде чем открыть испытание.",
    TextKey.ModeUnlockLevel to "{mode} откроется на уровне {level}.", TextKey.CannotOpenChallenge to "Не удалось открыть испытание",
    TextKey.Understood to "Понятно", TextKey.ChoosePracticeMode to "Выбрать режим тренировки", TextKey.ShareRoom to "Поделиться комнатой"
)
