package com.hienthai.fastowin.localization.catalogs

import com.hienthai.fastowin.localization.TextKey
import com.hienthai.fastowin.localization.PluralCategory
import com.hienthai.fastowin.localization.QuantityKey

internal val englishSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} player", PluralCategory.OTHER to "{count} players"),
    QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} clan", PluralCategory.OTHER to "{count} clans"),
    QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} member", PluralCategory.OTHER to "{count} members")
)
internal val vietnameseSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "{count} chiến binh"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "{count} bang"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "{count} thành viên")
)
internal val germanSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} Spieler", PluralCategory.OTHER to "{count} Spieler"), QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} Clan", PluralCategory.OTHER to "{count} Clans"), QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} Mitglied", PluralCategory.OTHER to "{count} Mitglieder")
)
internal val japaneseSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "{count}人"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "{count}クラン"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "{count}人のメンバー")
)
internal val simplifiedChineseSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "{count} 名玩家"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "{count} 个战队"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "{count} 名成员")
)
internal val koreanSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "플레이어 {count}명"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "클랜 {count}개"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "멤버 {count}명")
)
internal val spanishSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} jugador", PluralCategory.OTHER to "{count} jugadores"), QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} clan", PluralCategory.OTHER to "{count} clanes"), QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} miembro", PluralCategory.OTHER to "{count} miembros")
)
internal val brazilianPortugueseSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} jogador", PluralCategory.OTHER to "{count} jogadores"), QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} clã", PluralCategory.OTHER to "{count} clãs"), QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} membro", PluralCategory.OTHER to "{count} membros")
)
internal val frenchSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} joueur", PluralCategory.OTHER to "{count} joueurs"), QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} clan", PluralCategory.OTHER to "{count} clans"), QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} membre", PluralCategory.OTHER to "{count} membres")
)
internal val indonesianSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "{count} pemain"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "{count} klan"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "{count} anggota")
)
internal val thaiSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.OTHER to "ผู้เล่น {count} คน"), QuantityKey.Clans to mapOf(PluralCategory.OTHER to "{count} แคลน"), QuantityKey.Members to mapOf(PluralCategory.OTHER to "สมาชิก {count} คน")
)
internal val russianSocialShopQuantities = mapOf(
    QuantityKey.Warriors to mapOf(PluralCategory.ONE to "{count} игрок", PluralCategory.FEW to "{count} игрока", PluralCategory.MANY to "{count} игроков", PluralCategory.OTHER to "{count} игрока"),
    QuantityKey.Clans to mapOf(PluralCategory.ONE to "{count} клан", PluralCategory.FEW to "{count} клана", PluralCategory.MANY to "{count} кланов", PluralCategory.OTHER to "{count} клана"),
    QuantityKey.Members to mapOf(PluralCategory.ONE to "{count} участник", PluralCategory.FEW to "{count} участника", PluralCategory.MANY to "{count} участников", PluralCategory.OTHER to "{count} участника")
)

internal val englishSocialShopTexts = mapOf(
    TextKey.RemoveFriendTitle to "Remove friend?", TextKey.RemoveFriendDescription to "You and {player} will no longer be friends.",
    TextKey.RemoveFriendAction to "REMOVE FRIEND", TextKey.GoBack to "GO BACK",
    TextKey.BlockFriendDescription to "{player} will not be able to send you friend or room invitations.",
    TextKey.YourSquad to "Your squad", TextKey.YourSquadDescription to "Connect with a player code and invite friends to a match.",
    TextKey.RoomInvitations to "Room invitations", TextKey.NewCount to "{count} new",
    TextKey.RoomInvitationSummary to "Invited you to “{room}”", TextKey.FriendRequests to "Friend requests",
    TextKey.PlayerCodeLabel to "Player code", TextKey.PlayerCodeShort to "Code: {code}", TextKey.PlayerCodeExample to "e.g. FTW8X2Q",
    TextKey.BlockPlayerNamed to "Block {player}", TextKey.FriendList to "Friends",
    TextKey.ActiveFriends to "{count} online", TextKey.NoFriendsDescription to "No teammates yet. Enter a player code to send an invitation.",
    TextKey.PendingReplies to "Awaiting replies", TextKey.SentFriendInvitation to "Invitation sent · {code}",
    TextKey.BlockedPlayers to "Blocked", TextKey.Unblock to "UNBLOCK",
    TextKey.PlayerActions to "Actions for {player}", TextKey.InviteSent to "Invited",
    TextKey.SendingInvitation to "Sending…", TextKey.InviteToRoom to "Invite to room",
    TextKey.RoomInvitationTitle to "ROOM INVITATION", TextKey.WaitingForYou to "{player} is waiting for you",
    TextKey.RoomLabel to "ROOM", TextKey.SocialHub to "SOCIAL HUB",

    TextKey.ClanTogetherTitle to "Compete together", TextKey.ClanTogetherDescription to "Join a clan, complete quests and climb the ranks together.",
    TextKey.SearchClan to "Find a clan", TextKey.SearchClanPlaceholder to "Enter clan name…", TextKey.SearchClanAction to "Search clans",
    TextKey.CreateClan to "CREATE CLAN", TextKey.CreateAction to "CREATE", TextKey.ExploreClans to "Explore clans", TextKey.NoClansFound to "No clans found",
    TextKey.NoClansFoundDescription to "Try another keyword or create your own clan.",
    TextKey.ClanSummary to "{members} members · {trophies} trophies", TextKey.PendingApproval to "Pending",
    TextKey.RequestToJoin to "Join", TextKey.CreateClanTitle to "Create Clan",
    TextKey.CreateClanDescription to "Choose a short, memorable name so teammates can find you.",
    TextKey.ClanName to "Clan name", TextKey.ClanDescription to "Clan description",
    TextKey.DefaultClanDescription to "Conquer the leaderboard with your teammates.",
    TextKey.SelectClanLogo to "Choose clan logo", TextKey.ClanLogo to "Clan logo",
    TextKey.JoinRequestsCount to "Join requests ({count})", TextKey.ClanMembers to "Members",
    TextKey.LeaveClan to "LEAVE CLAN", TextKey.LeaveClanTitle to "Leave clan?",
    TextKey.LeaveClanDescription to "You will leave {clan}.", TextKey.RemoveClanMemberTitle to "Remove clan member?",
    TextKey.RemoveClanMemberDescription to "{player} will be removed from {clan}.", TextKey.RemoveClanMemberAction to "REMOVE MEMBER",
    TextKey.ClanTrophies to "Clan trophies", TextKey.MemberTrophies to "Member trophies", TextKey.TotalTrophies to "Total trophies",
    TextKey.WeeklyClanQuest to "WEEKLY QUEST", TextKey.WinClanMatches to "Win {count} matches with your clan",
    TextKey.Approve to "Approve", TextKey.ClanMemberSummary to "{role} · {trophies} trophies",
    TextKey.RemoveClanMemberNamed to "Remove {player} from clan", TextKey.ChooseClanLogo to "Choose Logo",
    TextKey.ChooseClanLogoDescription to "Tap an icon to apply it immediately.",
    TextKey.ClanRoleLeader to "Leader", TextKey.ClanRoleCoLeader to "Co-leader", TextKey.ClanRoleMember to "Member",
    TextKey.ClanLogoShield to "Shield", TextKey.ClanLogoSwords to "Crossed swords", TextKey.ClanLogoFlag to "Flag",
    TextKey.ClanLogoDragon to "Dragon", TextKey.ClanLogoWolf to "Wolf", TextKey.ClanLogoEagle to "Eagle", TextKey.ClanLogoCrown to "Crown", TextKey.ClanLogoNamed to "Logo {logo}",
    TextKey.ClanProgress to "CLAN PROGRESS", TextKey.DonateToClan to "DONATE",
    TextKey.DonateToClanDescription to "Contribute Gold or Gems to grow your clan.",
    TextKey.DonationBalance to "Balance: {amount} {currency}", TextKey.DonationXpPreview to "Clan XP gained: {xp}",
    TextKey.DonationCannotUndo to "Donations cannot be undone.", TextKey.YourContribution to "Your contribution",
    TextKey.MaximumLevel to "Max level", TextKey.DonationApplied to "Your clan gained {xp} XP.",
    TextKey.DonationDuplicate to "This donation was already completed.", TextKey.DonationInvalidAmount to "Choose a valid donation amount.",
    TextKey.DonationInsufficientFunds to "You do not have enough {currency}.", TextKey.DonationMembershipRequired to "Join this clan before donating.",
    TextKey.DonationFailed to "Could not complete the donation. Please try again.",

    TextKey.Individual to "Players", TextKey.FameRace to "Race for glory",
    TextKey.FameRaceDescription to "Climb tiers, protect your win streak and take the top spot.",
    TextKey.CurrentSeason to "Current season", TextKey.PreviousSeason to "Previous season", TextKey.AllTime to "All time", TextKey.History to "History",
    TextKey.TopPlayers to "Top players", TextKey.WarriorsCount to "{count} players",
    TextKey.CurrentSeasonLeaderboardEmpty to "No player has completed placement this season.",
    TextKey.PreviousSeasonLeaderboardEmpty to "No player qualified for the previous season ranking.",
    TextKey.AllTimeLeaderboardEmpty to "No player has completed a match yet.", TextKey.YourPosition to "YOUR POSITION",
    TextKey.StrongestClans to "Strongest clans", TextKey.StrongestClansDescription to "Combined Elo strength of every clan member.",
    TextKey.TopClans to "Top clans", TextKey.ClansCount to "{count} clans", TextKey.ClanLeaderboardEmpty to "No clans are ranked yet.",
    TextKey.YourClan to "YOUR CLAN", TextKey.RankingAwaiting to "The ranking awaits", TextKey.YouSuffix to " · You",
    TextKey.MembersCount to "{count} members", TextKey.TotalElo to "Total Elo",
    TextKey.LeaderboardPlayerSummary to "{tier} · {wins} wins · {rate}%",

    TextKey.KnockoutArena to "Knockout arena", TextKey.KnockoutArenaDescription to "Gather 4, 8 or 16 contenders and reach for the trophy.",
    TextKey.TournamentLobby to "Tournament lobby", TextKey.ChampionName to "Champion: {player}", TextKey.TournamentUpdating to "Updating",
    TextKey.TournamentCancelled to "Tournament cancelled", TextKey.TournamentLobbySummary to "{mode} · {current}/{max} players · {prize} Gold",
    TextKey.BracketInProgress to "The bracket is in progress. Winners advance to the next round.",
    TextKey.TournamentPrizeAwarded to "The {prize} Gold prize has been awarded.", TextKey.CreateAnotherTournament to "You can create another tournament now.",
    TextKey.JoinInvitations to "Invitations", TextKey.RecentTournaments to "Recent tournaments",
    TextKey.TournamentInvitationTitle to "Tournament invitation",
    TextKey.TournamentInvitationDescription to "{host} invited you to “{tournament}” · {mode} · {players} players.",
    TextKey.DecideLater to "LATER", TextKey.ChooseTournamentMode to "Choose tournament mode",
    TextKey.CreatePrivateTournament to "Create private tournament", TextKey.TournamentSize to "Tournament size",
    TextKey.TournamentFourFormat to "4 players • 2 semifinals • 1 final", TextKey.TournamentEightFormat to "8 players • 4 quarterfinals • 2 semifinals • 1 final",
    TextKey.TournamentSixteenFormat to "16 players • 8 round-of-16 • 4 quarterfinals • 2 semifinals • 1 final",
    TextKey.TournamentName to "Tournament name", TextKey.TournamentNameExample to "e.g. Speed Champions Cup",
    TextKey.GameModeLabel to "Game mode", TextKey.EntryFeeGold to "Entry fee (Gold)", TextKey.Free to "Free", TextKey.Custom to "Custom",
    TextKey.EnterEntryFee to "Enter Gold entry fee", TextKey.EntryFeeExample to "e.g. 750", TextKey.CreateTournamentAction to "CREATE TOURNAMENT", TextKey.TournamentNoElo to "Tournament matches do not affect Elo.",
    TextKey.PlayerCountUpper to "{count} PLAYERS", TextKey.EntryFee to "Entry fee", TextKey.Prize to "Prize", TextKey.GoldAmount to "{count} Gold",
    TextKey.Participants to "Participants", TextKey.WaitingForPlayerEllipsis to "Waiting for player…", TextKey.TournamentHost to "Host",
    TextKey.StartTournament to "START TOURNAMENT", TextKey.Bracket to "Bracket", TextKey.CancelTournament to "CANCEL TOURNAMENT",
    TextKey.LeaveTournament to "LEAVE TOURNAMENT", TextKey.AutomaticMatchesDescription to "Matches are created automatically. Winners advance to the next round.",
    TextKey.Champion to "CHAMPION", TextKey.FinalRound to "FINAL", TextKey.SemifinalRound to "SEMIFINALS",
    TextKey.QuarterfinalRound to "QUARTERFINALS", TextKey.RoundOfSixteen to "ROUND OF 16", TextKey.RoundNumber to "ROUND {round}",
    TextKey.MatchPending to "WAITING", TextKey.MatchPlaying to "PLAYING", TextKey.WaitingEllipsis to "Waiting…",
    TextKey.TournamentInviteCompact to "{host} invited you · {mode} · {players} players", TextKey.ChampionCompact to "Champion: {player}",
    TextKey.HideBracket to "Hide bracket", TextKey.TournamentPhaseLobby to "Gathering", TextKey.TournamentPhaseRunning to "In progress",
    TextKey.TournamentPhaseFinished to "Finished", TextKey.TournamentPhaseCancelled to "Cancelled", TextKey.JoinTournament to "JOIN",
    TextKey.InviteAction to "Invite", TextKey.MatchFinished to "DONE",

    TextKey.ClearAllNotificationsTitle to "Clear all notifications?", TextKey.ClearAllNotificationsDescription to "Visible notifications will be removed and synced across your devices.",
    TextKey.ClearAllNotifications to "Clear all", TextKey.ClearAllNotificationsA11y to "Clear all notifications", TextKey.MarkAllRead to "Mark all as read", TextKey.EmptyInbox to "Your inbox is empty",
    TextKey.EmptyInboxDescription to "Invitations, rewards and news will appear here.", TextKey.NotificationsHero to "News for you",
    TextKey.NotificationsHeroDescription to "Follow invitations, rewards and important activity.", TextKey.DeleteNotificationTitle to "Delete notification?",
    TextKey.DeleteNotificationDescription to "“{title}” will be removed from the list.", TextKey.DeleteNotification to "Delete notification",

    TextKey.GemTab to "Gems", TextKey.GoldTab to "Gold", TextKey.NumberSkins to "Number Skins", TextKey.NumberBoards to "Number Boards",
    TextKey.GemVault to "Gem Vault", TextKey.GoldVault to "Gold Exchange", TextKey.ArcadeVault to "Arcade Vault", TextKey.GemVaultDescription to "Gems unlock rare items and sync securely through the Store.",
    TextKey.ArcadeVaultDescription to "Unlock a fresh look and make every match your own.", TextKey.Restocking to "Restocking",
    TextKey.RestockingDescription to "New items will arrive here soon.", TextKey.ChooseGemPackage to "Choose a Gem pack",
    TextKey.GemPackageDescription to "Gems unlock rare items. Prices come from your Store account.", TextKey.LoginToBuyGems to "Sign in to buy and sync Gems across devices.",
    TextKey.PriceUnavailable to "Price unavailable", TextKey.EarnGemsDescription to "You can also earn Gems through check-ins, hard quests and special achievements.",
    TextKey.Popular to "POPULAR", TextKey.EquippingNow to "EQUIPPED", TextKey.Equip to "EQUIP", TextKey.GemAmount to "{count} Gems",
    TextKey.GoldVaultDescription to "Exchange Gems for Gold safely. Every exchange is recorded in your resource history.",
    TextKey.ExchangeGemsForGold to "EXCHANGE", TextKey.GoldExchangeConfirmation to "Use {gems} Gems to receive {gold} Gold?",
    TextKey.NotEnoughGems to "Not enough Gems", TextKey.GoldExchangeGranted to "Received {gold} Gold.",
    TextKey.GoldExchangeAlreadyGranted to "This exchange was already completed.", TextKey.GoldExchangeFailed to "Could not exchange Gold. Please try again.",
    TextKey.ShopItemGoldName to "Golden Number Skin", TextKey.ShopItemDiamondName to "Diamond Number Skin",
    TextKey.ShopBoardDarkName to "Dark Number Board", TextKey.ShopBoardForestName to "Forest Number Board",
    TextKey.BillingPlayNotReady to "Google Play Billing is not ready.", TextKey.BillingPlayReconnecting to "Reconnecting to Google Play…",
    TextKey.BillingPriceLoadFailed to "Could not load prices from Google Play.", TextKey.BillingProductsMissing to "Gem products have not been created in Google Play Console.",
    TextKey.BillingProductUnavailable to "This Gem pack is unavailable on Google Play.", TextKey.BillingLaunchFailed to "Could not open Google Play checkout.",
    TextKey.BillingCancelled to "Payment cancelled.", TextKey.BillingRestoring to "Restoring the previous purchase…",
    TextKey.BillingUnavailable to "Google Play Billing is unavailable on this device.", TextKey.BillingIncomplete to "Payment was not completed.",
    TextKey.BillingVerifying to "Verifying purchase…", TextKey.BillingPending to "Google Play is processing this payment.",
    TextKey.BillingSandboxVerifying to "Verifying sandbox purchase…", TextKey.BillingGemsAdded to "Gems added to your account.",
    TextKey.BillingFinishLater to "Gems were added; the purchase will be finalized later.", TextKey.BillingSandboxActive to "Using test payments.",
    TextKey.BillingStoreKitSandboxNotice to "StoreKit sandbox must be verified on macOS before release.",
    TextKey.BillingAppStoreNotConfigured to "App Store is not configured for production.",
    TextKey.BillingWebUnsupported to "Gem purchases are not supported on Web. Use the Android or iOS app."
)

internal val vietnameseSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.RemoveFriendTitle to "Hủy kết bạn?", TextKey.RemoveFriendDescription to "Bạn và {player} sẽ không còn trong danh sách bạn bè.",
    TextKey.RemoveFriendAction to "Hủy kết bạn", TextKey.GoBack to "Quay lại", TextKey.BlockFriendDescription to "{player} sẽ không thể gửi lời mời kết bạn hoặc lời mời vào phòng cho bạn.",
    TextKey.YourSquad to "Biệt đội của bạn", TextKey.YourSquadDescription to "Kết nối bằng mã người chơi và mời bạn vào trận.", TextKey.RoomInvitations to "Lời mời vào phòng",
    TextKey.NewCount to "{count} mới", TextKey.RoomInvitationSummary to "Mời bạn vào “{room}”", TextKey.FriendRequests to "Lời mời kết bạn",
    TextKey.PlayerCodeLabel to "Mã người chơi", TextKey.PlayerCodeShort to "Mã: {code}", TextKey.PlayerCodeExample to "VD: FTW8X2Q", TextKey.BlockPlayerNamed to "Chặn {player}",
    TextKey.FriendList to "Danh sách bạn bè", TextKey.ActiveFriends to "{count} online", TextKey.NoFriendsDescription to "Chưa có đồng đội. Nhập mã người chơi để gửi lời mời.",
    TextKey.PendingReplies to "Đang chờ phản hồi", TextKey.SentFriendInvitation to "Đã gửi lời mời · {code}", TextKey.BlockedPlayers to "Đã chặn",
    TextKey.Unblock to "BỎ CHẶN", TextKey.PlayerActions to "Thao tác với {player}", TextKey.InviteSent to "Đã mời", TextKey.SendingInvitation to "Đang gửi…",
    TextKey.InviteToRoom to "Mời vào phòng", TextKey.RoomInvitationTitle to "LỜI MỜI VÀO PHÒNG", TextKey.WaitingForYou to "{player} đang chờ bạn", TextKey.RoomLabel to "PHÒNG", TextKey.SocialHub to "TRUNG TÂM BẠN BÈ",
    TextKey.ClanTogetherTitle to "Sát cánh tranh tài", TextKey.ClanTogetherDescription to "Gia nhập bang hội, hoàn thành nhiệm vụ và cùng nhau leo hạng.",
    TextKey.SearchClan to "Tìm bang hội", TextKey.SearchClanPlaceholder to "Nhập tên bang…", TextKey.SearchClanAction to "Tìm kiếm bang hội",
    TextKey.CreateClan to "TẠO BANG HỘI", TextKey.CreateAction to "TẠO", TextKey.ExploreClans to "Khám phá bang hội", TextKey.NoClansFound to "Chưa tìm thấy bang hội",
    TextKey.NoClansFoundDescription to "Thử từ khóa khác hoặc tạo bang của riêng bạn.", TextKey.ClanSummary to "{members} thành viên · {trophies} cúp",
    TextKey.PendingApproval to "Đang chờ", TextKey.RequestToJoin to "Xin vào", TextKey.CreateClanTitle to "Tạo Bang Hội",
    TextKey.CreateClanDescription to "Chọn tên ngắn gọn, dễ nhớ để đồng đội tìm thấy bạn.", TextKey.ClanName to "Tên bang", TextKey.ClanDescription to "Mô tả bang hội",
    TextKey.DefaultClanDescription to "Cùng đồng đội chinh phục bảng xếp hạng.", TextKey.SelectClanLogo to "Chọn logo bang", TextKey.ClanLogo to "Logo bang",
    TextKey.JoinRequestsCount to "Yêu cầu tham gia ({count})", TextKey.ClanMembers to "Thành viên", TextKey.LeaveClan to "RỜI BANG",
    TextKey.LeaveClanTitle to "Rời bang?", TextKey.LeaveClanDescription to "Bạn sẽ rời khỏi {clan}.", TextKey.RemoveClanMemberTitle to "Mời thành viên rời bang?",
    TextKey.RemoveClanMemberDescription to "{player} sẽ bị xóa khỏi bang {clan}.", TextKey.RemoveClanMemberAction to "MỜI RỜI BANG",
    TextKey.ClanTrophies to "Cúp bang", TextKey.MemberTrophies to "Cúp thành viên", TextKey.TotalTrophies to "Tổng cúp",
    TextKey.WeeklyClanQuest to "NHIỆM VỤ TUẦN", TextKey.WinClanMatches to "Thắng {count} trận cùng bang hội", TextKey.Approve to "Duyệt",
    TextKey.ClanMemberSummary to "{role} · {trophies} cúp", TextKey.RemoveClanMemberNamed to "Mời {player} rời bang", TextKey.ChooseClanLogo to "Chọn Logo",
    TextKey.ChooseClanLogoDescription to "Chạm vào biểu tượng để áp dụng ngay.", TextKey.ClanRoleLeader to "Bang chủ", TextKey.ClanRoleCoLeader to "Phó bang",
    TextKey.ClanRoleMember to "Thành viên", TextKey.ClanLogoShield to "Khiên", TextKey.ClanLogoSwords to "Song kiếm", TextKey.ClanLogoFlag to "Cờ",
    TextKey.ClanLogoDragon to "Rồng", TextKey.ClanLogoWolf to "Sói", TextKey.ClanLogoEagle to "Đại bàng", TextKey.ClanLogoCrown to "Vương miện", TextKey.ClanLogoNamed to "Logo {logo}",
    TextKey.ClanProgress to "TIẾN TRÌNH BANG", TextKey.DonateToClan to "QUYÊN GÓP",
    TextKey.DonateToClanDescription to "Góp Vàng hoặc Gem để cùng phát triển bang hội.",
    TextKey.DonationBalance to "Số dư: {amount} {currency}", TextKey.DonationXpPreview to "Bang nhận {xp} XP",
    TextKey.DonationCannotUndo to "Khoản quyên góp không thể hoàn tác.", TextKey.YourContribution to "Bạn đã góp",
    TextKey.MaximumLevel to "Cấp tối đa", TextKey.DonationApplied to "Bang đã nhận {xp} XP.",
    TextKey.DonationDuplicate to "Khoản quyên góp này đã hoàn tất trước đó.", TextKey.DonationInvalidAmount to "Hãy chọn mức quyên góp hợp lệ.",
    TextKey.DonationInsufficientFunds to "Bạn không đủ {currency}.", TextKey.DonationMembershipRequired to "Hãy tham gia bang trước khi quyên góp.",
    TextKey.DonationFailed to "Chưa thể quyên góp. Vui lòng thử lại.",
    TextKey.Individual to "Cá nhân", TextKey.FameRace to "Đường đua danh vọng", TextKey.FameRaceDescription to "Leo bậc, giữ chuỗi thắng và chiếm vị trí cao nhất.",
    TextKey.CurrentSeason to "Hiện tại", TextKey.PreviousSeason to "Mùa trước", TextKey.AllTime to "Toàn thời gian", TextKey.History to "Lịch sử",
    TextKey.TopPlayers to "Top người chơi", TextKey.WarriorsCount to "{count} chiến binh", TextKey.CurrentSeasonLeaderboardEmpty to "Chưa có người chơi hoàn thành phân hạng mùa này.",
    TextKey.PreviousSeasonLeaderboardEmpty to "Mùa trước chưa có người chơi đủ điều kiện xếp hạng.", TextKey.AllTimeLeaderboardEmpty to "Chưa có người chơi hoàn thành trận đấu.",
    TextKey.YourPosition to "VỊ TRÍ CỦA BẠN", TextKey.StrongestClans to "Bang hội mạnh nhất", TextKey.StrongestClansDescription to "Tổng hợp sức mạnh Elo của toàn bộ thành viên.",
    TextKey.TopClans to "Top bang hội", TextKey.ClansCount to "{count} bang", TextKey.ClanLeaderboardEmpty to "Chưa có bang hội nào trên bảng xếp hạng.",
    TextKey.YourClan to "BANG CỦA BẠN", TextKey.RankingAwaiting to "Đường đua đang chờ", TextKey.YouSuffix to " · Bạn", TextKey.MembersCount to "{count} thành viên",
    TextKey.TotalElo to "Tổng Elo", TextKey.LeaderboardPlayerSummary to "{tier} · {wins} thắng · {rate}%",
    TextKey.KnockoutArena to "Đấu trường loại trực tiếp", TextKey.KnockoutArenaDescription to "Tập hợp 4, 8 hoặc 16 chiến binh và chạm tay vào cúp vô địch.",
    TextKey.TournamentLobby to "Sảnh giải đấu", TextKey.ChampionName to "Nhà vô địch: {player}", TextKey.TournamentUpdating to "Đang cập nhật", TextKey.TournamentCancelled to "Giải đấu đã hủy",
    TextKey.TournamentLobbySummary to "{mode} · {current}/{max} người · {prize} vàng", TextKey.BracketInProgress to "Nhánh đấu đang diễn ra. Người thắng sẽ tiến vào vòng tiếp theo.",
    TextKey.TournamentPrizeAwarded to "Phần thưởng {prize} vàng đã được trao.", TextKey.CreateAnotherTournament to "Bạn có thể tạo một giải đấu mới ngay bây giờ.",
    TextKey.JoinInvitations to "Lời mời tham gia", TextKey.RecentTournaments to "Giải gần đây", TextKey.TournamentInvitationTitle to "Lời mời đấu giải",
    TextKey.TournamentInvitationDescription to "{host} mời bạn tham gia “{tournament}” · {mode} · {players} người.", TextKey.DecideLater to "ĐỂ SAU",
    TextKey.ChooseTournamentMode to "Chọn chế độ đấu giải", TextKey.CreatePrivateTournament to "Tạo giải riêng", TextKey.TournamentSize to "Quy mô giải",
    TextKey.TournamentFourFormat to "4 người • 2 bán kết • 1 chung kết", TextKey.TournamentEightFormat to "8 người • 4 tứ kết • 2 bán kết • 1 chung kết",
    TextKey.TournamentSixteenFormat to "16 người • 8 vòng 1/8 • 4 tứ kết • 2 bán kết • 1 chung kết", TextKey.TournamentName to "Tên giải đấu",
    TextKey.TournamentNameExample to "VD: Cúp Chiến Thần", TextKey.GameModeLabel to "Chế độ chơi", TextKey.EntryFeeGold to "Lệ phí tham gia (Vàng)",
    TextKey.Free to "Miễn phí", TextKey.Custom to "Tùy chỉnh", TextKey.EnterEntryFee to "Nhập số vàng lệ phí", TextKey.EntryFeeExample to "VD: 750", TextKey.CreateTournamentAction to "BẮT ĐẦU TẠO GIẢI",
    TextKey.TournamentNoElo to "Các trận đấu giải không ảnh hưởng Elo.", TextKey.PlayerCountUpper to "{count} NGƯỜI", TextKey.EntryFee to "Lệ phí",
    TextKey.Prize to "Giải thưởng", TextKey.GoldAmount to "{count} Vàng", TextKey.Participants to "Người tham gia", TextKey.WaitingForPlayerEllipsis to "Đang chờ người chơi…",
    TextKey.TournamentHost to "Chủ giải", TextKey.StartTournament to "BẮT ĐẦU GIẢI ĐẤU", TextKey.Bracket to "Nhánh đấu", TextKey.CancelTournament to "HỦY GIẢI ĐẤU",
    TextKey.LeaveTournament to "RỜI KHỎI GIẢI", TextKey.AutomaticMatchesDescription to "Các trận đấu được tạo tự động. Người thắng sẽ tiến vào vòng tiếp theo.",
    TextKey.Champion to "NHÀ VÔ ĐỊCH", TextKey.FinalRound to "TRẬN CHUNG KẾT", TextKey.SemifinalRound to "VÒNG BÁN KẾT",
    TextKey.QuarterfinalRound to "VÒNG TỨ KẾT", TextKey.RoundOfSixteen to "VÒNG 1/8", TextKey.RoundNumber to "VÒNG {round}",
    TextKey.MatchPending to "CHỜ", TextKey.MatchPlaying to "ĐANG ĐẤU", TextKey.WaitingEllipsis to "Đang chờ…",
    TextKey.TournamentInviteCompact to "{host} mời bạn · {mode} · {players} người", TextKey.ChampionCompact to "Vô địch: {player}", TextKey.HideBracket to "Ẩn nhánh đấu",
    TextKey.TournamentPhaseLobby to "Đang tập hợp", TextKey.TournamentPhaseRunning to "Đang diễn ra", TextKey.TournamentPhaseFinished to "Đã kết thúc", TextKey.TournamentPhaseCancelled to "Đã hủy",
    TextKey.JoinTournament to "THAM GIA", TextKey.InviteAction to "Mời", TextKey.MatchFinished to "XONG",
    TextKey.ClearAllNotificationsTitle to "Xóa tất cả thông báo?", TextKey.ClearAllNotificationsDescription to "Các thông báo đang hiển thị sẽ bị xóa và đồng bộ trên mọi thiết bị.",
    TextKey.ClearAllNotifications to "Xóa tất cả", TextKey.ClearAllNotificationsA11y to "Xóa tất cả thông báo", TextKey.MarkAllRead to "Đánh dấu tất cả đã đọc", TextKey.EmptyInbox to "Hộp thư đang trống",
    TextKey.EmptyInboxDescription to "Lời mời, phần thưởng và tin mới sẽ xuất hiện tại đây.", TextKey.NotificationsHero to "Tin mới dành cho bạn",
    TextKey.NotificationsHeroDescription to "Theo dõi lời mời, phần thưởng và hoạt động quan trọng.", TextKey.DeleteNotificationTitle to "Xóa thông báo?",
    TextKey.DeleteNotificationDescription to "Thông báo “{title}” sẽ bị xóa khỏi danh sách.", TextKey.DeleteNotification to "Xóa thông báo",
    TextKey.GemTab to "Gem", TextKey.GoldTab to "Vàng", TextKey.NumberSkins to "Mặt số", TextKey.NumberBoards to "Bàn số", TextKey.GemVault to "Kho Gem", TextKey.GoldVault to "Đổi Vàng", TextKey.ArcadeVault to "Kho báu Arcade",
    TextKey.GemVaultDescription to "Gem mở khóa vật phẩm hiếm và đồng bộ an toàn qua Store.", TextKey.ArcadeVaultDescription to "Mở khóa diện mạo mới và tạo dấu ấn riêng trong mỗi trận đấu.",
    TextKey.Restocking to "Đang nhập hàng", TextKey.RestockingDescription to "Vật phẩm mới sẽ sớm xuất hiện tại quầy này.", TextKey.ChooseGemPackage to "Chọn gói Gem",
    TextKey.GemPackageDescription to "Gem mở khóa vật phẩm hiếm. Giá được hiển thị theo tài khoản Store của bạn.", TextKey.LoginToBuyGems to "Đăng nhập để mua và đồng bộ Gem trên các thiết bị.",
    TextKey.PriceUnavailable to "Chưa có giá", TextKey.EarnGemsDescription to "Bạn cũng có thể săn Gem qua điểm danh, nhiệm vụ khó và thành tích đặc biệt.",
    TextKey.Popular to "PHỔ BIẾN", TextKey.EquippingNow to "ĐANG TRANG BỊ", TextKey.Equip to "TRANG BỊ", TextKey.GemAmount to "{count} Gem",
    TextKey.GoldVaultDescription to "Đổi Gem lấy Vàng an toàn. Mọi giao dịch đều được lưu trong lịch sử tài sản.",
    TextKey.ExchangeGemsForGold to "ĐỔI NGAY", TextKey.GoldExchangeConfirmation to "Dùng {gems} Gem để nhận {gold} Vàng?",
    TextKey.NotEnoughGems to "Không đủ Gem", TextKey.GoldExchangeGranted to "Đã nhận {gold} Vàng.",
    TextKey.GoldExchangeAlreadyGranted to "Giao dịch này đã hoàn tất trước đó.", TextKey.GoldExchangeFailed to "Chưa thể đổi Vàng. Vui lòng thử lại.",
    TextKey.ShopItemGoldName to "Mặt số Hoàng Kim", TextKey.ShopItemDiamondName to "Mặt số Kim Cương", TextKey.ShopBoardDarkName to "Bàn số Bóng Đêm", TextKey.ShopBoardForestName to "Bàn số Rừng Xanh",
    TextKey.BillingPlayNotReady to "Google Play Billing chưa sẵn sàng.", TextKey.BillingPlayReconnecting to "Đang kết nối lại Google Play…",
    TextKey.BillingPriceLoadFailed to "Không tải được giá từ Google Play.", TextKey.BillingProductsMissing to "Các gói Gem chưa được tạo trên Google Play Console.",
    TextKey.BillingProductUnavailable to "Gói Gem này chưa sẵn sàng trên Google Play.", TextKey.BillingLaunchFailed to "Không thể mở thanh toán Google Play.",
    TextKey.BillingCancelled to "Đã hủy thanh toán.", TextKey.BillingRestoring to "Đang khôi phục giao dịch trước…", TextKey.BillingUnavailable to "Google Play Billing không khả dụng trên thiết bị.",
    TextKey.BillingIncomplete to "Thanh toán chưa hoàn tất.", TextKey.BillingVerifying to "Đang xác thực giao dịch…", TextKey.BillingPending to "Thanh toán đang chờ Google Play xử lý.",
    TextKey.BillingSandboxVerifying to "Đang xác thực giao dịch sandbox…", TextKey.BillingGemsAdded to "Đã cộng Gem vào tài khoản.",
    TextKey.BillingFinishLater to "Gem đã được cộng; giao dịch sẽ được hoàn tất lại sau.", TextKey.BillingSandboxActive to "Đang dùng thanh toán thử nghiệm.",
    TextKey.BillingStoreKitSandboxNotice to "StoreKit sandbox cần được xác nhận trên macOS trước khi phát hành.",
    TextKey.BillingAppStoreNotConfigured to "App Store chưa được cấu hình cho bản production.", TextKey.BillingWebUnsupported to "Mua Gem trên web chưa được hỗ trợ. Hãy dùng ứng dụng Android hoặc iOS."
)

internal val germanSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Maximalstufe",
    TextKey.RoomInvitations to "Raumeinladungen", TextKey.FriendRequests to "Freundschaftsanfragen",
    TextKey.SearchClan to "Clan finden", TextKey.ClanMembers to "Mitglieder", TextKey.JoinInvitations to "Einladungen",
    TextKey.MarkAllRead to "Alle als gelesen markieren", TextKey.GemTab to "Juwelen", TextKey.GoldTab to "Gold",
    TextKey.SearchClanAction to "Clans suchen", TextKey.CreateClan to "CLAN ERSTELLEN", TextKey.RequestToJoin to "Beitreten",
    TextKey.LeaveClan to "CLAN VERLASSEN", TextKey.StartTournament to "TURNIER STARTEN", TextKey.CreateTournamentAction to "TURNIER ERSTELLEN",
    TextKey.ClearAllNotifications to "Alle löschen",
    TextKey.RemoveFriendTitle to "Freund entfernen?", TextKey.NoClansFound to "Keine Clans gefunden", TextKey.LeaveClanTitle to "Clan verlassen?",
    TextKey.RemoveClanMemberTitle to "Clanmitglied entfernen?", TextKey.TournamentCancelled to "Turnier abgesagt",
    TextKey.ClearAllNotificationsTitle to "Alle Benachrichtigungen löschen?", TextKey.DeleteNotificationTitle to "Benachrichtigung löschen?",
    TextKey.YourSquadDescription to "Verbinde dich per Spielercode und lade Freunde zu einem Match ein.",
    TextKey.NoFriendsDescription to "Noch keine Mitspieler. Gib einen Spielercode ein, um eine Einladung zu senden.",
    TextKey.ClanTogetherDescription to "Tritt einem Clan bei, erfülle Aufgaben und steigt gemeinsam auf.",
    TextKey.NoClansFoundDescription to "Versuche ein anderes Stichwort oder erstelle deinen eigenen Clan.",
    TextKey.KnockoutArenaDescription to "Versammle 4, 8 oder 16 Teilnehmer und kämpfe um den Pokal.",
    TextKey.EmptyInboxDescription to "Einladungen, Belohnungen und Neuigkeiten erscheinen hier.", TextKey.RestockingDescription to "Neue Gegenstände sind bald verfügbar.",
    TextKey.ClanProgress to "CLANFORTSCHRITT", TextKey.DonateToClan to "SPENDEN",
    TextKey.DonateToClanDescription to "Spende Gold oder Juwelen, um deinen Clan zu stärken.",
    TextKey.DonationBalance to "Guthaben: {amount} {currency}", TextKey.DonationXpPreview to "Erhaltene Clan-XP: {xp}", TextKey.YourContribution to "Dein Beitrag",
    TextKey.DonationCannotUndo to "Spenden können nicht rückgängig gemacht werden.", TextKey.DonationApplied to "Dein Clan hat {xp} XP erhalten.",
    TextKey.DonationDuplicate to "Diese Spende wurde bereits abgeschlossen.", TextKey.DonationInvalidAmount to "Wähle einen gültigen Spendenbetrag.",
    TextKey.DonationInsufficientFunds to "Du hast nicht genug {currency}.", TextKey.DonationMembershipRequired to "Tritt diesem Clan bei, bevor du spendest.",
    TextKey.DonationFailed to "Die Spende konnte nicht abgeschlossen werden. Versuche es erneut.",
    TextKey.RoomInvitationSummary to "Hat dich in „{room}“ eingeladen", TextKey.RoomInvitationTitle to "RAUMEINLADUNG",
    TextKey.WaitingForYou to "{player} wartet auf dich", TextKey.RoomLabel to "RAUM", TextKey.TournamentInvitationTitle to "Turniereinladung",
    TextKey.TournamentInvitationDescription to "{host} hat dich zu „{tournament}“ eingeladen · {mode} · {players} Spieler.",
    TextKey.TournamentInviteCompact to "Einladung von {host} · {mode} · {players} Spieler",
    TextKey.JoinRequestsCount to "Beitrittsanfragen ({count})", TextKey.Approve to "Genehmigen",
    TextKey.ClanMemberSummary to "{role} · {trophies} Trophäen", TextKey.RemoveClanMemberNamed to "{player} aus dem Clan entfernen",
    TextKey.ChooseClanLogo to "Logo wählen", TextKey.ClanRoleLeader to "Anführer", TextKey.ClanRoleCoLeader to "Co-Anführer", TextKey.ClanRoleMember to "Mitglied",
    TextKey.TournamentUpdating to "Wird aktualisiert", TextKey.TournamentPhaseLobby to "Teilnehmer werden gesammelt",
    TextKey.TournamentPhaseRunning to "Läuft", TextKey.TournamentPhaseFinished to "Beendet", TextKey.TournamentPhaseCancelled to "Abgesagt",
    TextKey.MatchPending to "WARTET", TextKey.MatchPlaying to "LÄUFT", TextKey.MatchFinished to "FERTIG",
    TextKey.PlayerCodeExample to "z. B. FTW8X2Q", TextKey.YourSquad to "Dein Team", TextKey.FriendList to "Freunde", TextKey.ClanTogetherTitle to "Gemeinsam antreten", TextKey.ExploreClans to "Clans entdecken", TextKey.FameRace to "Rennen um Ruhm", TextKey.CurrentSeason to "Aktuelle Saison", TextKey.KnockoutArena to "K.-o.-Arena", TextKey.RecentTournaments to "Letzte Turniere", TextKey.NotificationsHero to "Neuigkeiten für dich", TextKey.EmptyInbox to "Dein Postfach ist leer", TextKey.NumberSkins to "Zahlenflächen", TextKey.NumberBoards to "Zahlenbretter", TextKey.GemVault to "Gem-Tresor", TextKey.ArcadeVault to "Arcade-Tresor", TextKey.Restocking to "Nachschub unterwegs", TextKey.Equip to "AUSRÜSTEN"
)
internal val japaneseSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "最大レベル",
    TextKey.RoomInvitations to "ルーム招待", TextKey.FriendRequests to "フレンド申請",
    TextKey.SearchClan to "クランを探す", TextKey.ClanMembers to "メンバー", TextKey.JoinInvitations to "招待",
    TextKey.MarkAllRead to "すべて既読にする", TextKey.GemTab to "ジェム", TextKey.GoldTab to "ゴールド",
    TextKey.SearchClanAction to "クラン検索", TextKey.CreateClan to "クラン作成", TextKey.RequestToJoin to "参加",
    TextKey.LeaveClan to "クランを脱退", TextKey.StartTournament to "トーナメント開始", TextKey.CreateTournamentAction to "トーナメント作成",
    TextKey.ClearAllNotifications to "すべて削除",
    TextKey.RemoveFriendTitle to "フレンドを削除しますか？", TextKey.NoClansFound to "クランが見つかりません", TextKey.LeaveClanTitle to "クランを脱退しますか？",
    TextKey.RemoveClanMemberTitle to "クランメンバーを除名しますか？", TextKey.TournamentCancelled to "トーナメントは中止されました",
    TextKey.ClearAllNotificationsTitle to "すべての通知を削除しますか？", TextKey.DeleteNotificationTitle to "通知を削除しますか？",
    TextKey.YourSquadDescription to "プレイヤーコードでつながり、フレンドを対戦に招待しましょう。",
    TextKey.NoFriendsDescription to "まだ仲間がいません。プレイヤーコードを入力して招待を送りましょう。",
    TextKey.ClanTogetherDescription to "クランに参加し、ミッションを達成して仲間とランクを上げましょう。",
    TextKey.NoClansFoundDescription to "別のキーワードを試すか、自分のクランを作成してください。",
    TextKey.KnockoutArenaDescription to "4人、8人、16人の挑戦者を集め、優勝を目指しましょう。",
    TextKey.EmptyInboxDescription to "招待、報酬、新着情報がここに表示されます。", TextKey.RestockingDescription to "新しい商品がまもなく登場します。",
    TextKey.ClanProgress to "クラン進捗", TextKey.DonateToClan to "寄付",
    TextKey.DonateToClanDescription to "ゴールドまたはジェムを寄付してクランを成長させましょう。",
    TextKey.DonationBalance to "残高：{amount} {currency}", TextKey.DonationXpPreview to "獲得クランXP：{xp}", TextKey.YourContribution to "あなたの貢献",
    TextKey.DonationCannotUndo to "寄付は取り消せません。", TextKey.DonationApplied to "クランが {xp} XPを獲得しました。",
    TextKey.DonationDuplicate to "この寄付はすでに完了しています。", TextKey.DonationInvalidAmount to "有効な寄付額を選択してください。",
    TextKey.DonationInsufficientFunds to "{currency}が足りません。", TextKey.DonationMembershipRequired to "寄付する前にこのクランに参加してください。",
    TextKey.DonationFailed to "寄付を完了できませんでした。もう一度お試しください。",
    TextKey.RoomInvitationSummary to "「{room}」に招待されました", TextKey.RoomInvitationTitle to "ルーム招待",
    TextKey.WaitingForYou to "{player}があなたを待っています", TextKey.RoomLabel to "ルーム", TextKey.TournamentInvitationTitle to "トーナメント招待",
    TextKey.TournamentInvitationDescription to "{host}が「{tournament}」に招待しました · {mode} · {players}人。",
    TextKey.TournamentInviteCompact to "{host}からの招待 · {mode} · {players}人",
    TextKey.JoinRequestsCount to "参加申請（{count}）", TextKey.Approve to "承認",
    TextKey.ClanMemberSummary to "{role} · トロフィー{trophies}個", TextKey.RemoveClanMemberNamed to "{player}をクランから除名",
    TextKey.ChooseClanLogo to "ロゴを選択", TextKey.ClanRoleLeader to "リーダー", TextKey.ClanRoleCoLeader to "サブリーダー", TextKey.ClanRoleMember to "メンバー",
    TextKey.TournamentUpdating to "更新中", TextKey.TournamentPhaseLobby to "参加者募集中",
    TextKey.TournamentPhaseRunning to "進行中", TextKey.TournamentPhaseFinished to "終了", TextKey.TournamentPhaseCancelled to "中止",
    TextKey.MatchPending to "待機中", TextKey.MatchPlaying to "対戦中", TextKey.MatchFinished to "完了",
    TextKey.PlayerCodeExample to "例：FTW8X2Q", TextKey.YourSquad to "あなたのチーム", TextKey.FriendList to "フレンド", TextKey.ClanTogetherTitle to "仲間と挑戦", TextKey.ExploreClans to "クランを探す", TextKey.FameRace to "栄光へのレース", TextKey.CurrentSeason to "今シーズン", TextKey.KnockoutArena to "勝ち抜きアリーナ", TextKey.RecentTournaments to "最近の大会", TextKey.NotificationsHero to "あなたへのお知らせ", TextKey.EmptyInbox to "通知はありません", TextKey.NumberSkins to "数字スキン", TextKey.NumberBoards to "数字ボード", TextKey.GemVault to "ジェム保管庫", TextKey.ArcadeVault to "アーケード保管庫", TextKey.Restocking to "入荷準備中", TextKey.Equip to "装備"
)
internal val simplifiedChineseSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "最高等级",
    TextKey.RoomInvitations to "房间邀请", TextKey.FriendRequests to "好友请求",
    TextKey.SearchClan to "查找战队", TextKey.ClanMembers to "成员", TextKey.JoinInvitations to "邀请",
    TextKey.MarkAllRead to "全部标为已读", TextKey.GemTab to "宝石", TextKey.GoldTab to "金币",
    TextKey.SearchClanAction to "搜索战队", TextKey.CreateClan to "创建战队", TextKey.RequestToJoin to "加入",
    TextKey.LeaveClan to "退出战队", TextKey.StartTournament to "开始锦标赛", TextKey.CreateTournamentAction to "创建锦标赛",
    TextKey.ClearAllNotifications to "全部清除",
    TextKey.RemoveFriendTitle to "删除好友？", TextKey.NoClansFound to "未找到战队", TextKey.LeaveClanTitle to "退出战队？",
    TextKey.RemoveClanMemberTitle to "移除战队成员？", TextKey.TournamentCancelled to "锦标赛已取消",
    TextKey.ClearAllNotificationsTitle to "清除所有通知？", TextKey.DeleteNotificationTitle to "删除通知？",
    TextKey.YourSquadDescription to "通过玩家代码添加好友并邀请他们参加对战。",
    TextKey.NoFriendsDescription to "还没有队友。输入玩家代码发送邀请。",
    TextKey.ClanTogetherDescription to "加入战队、完成任务，与队友一起攀登排行榜。",
    TextKey.NoClansFoundDescription to "尝试其他关键词，或创建自己的战队。",
    TextKey.KnockoutArenaDescription to "召集4、8或16名选手，向奖杯发起冲击。",
    TextKey.EmptyInboxDescription to "邀请、奖励和新消息会显示在这里。", TextKey.RestockingDescription to "新商品即将上架。",
    TextKey.ClanProgress to "战队进度", TextKey.DonateToClan to "捐献",
    TextKey.DonateToClanDescription to "捐献金币或宝石，助力战队成长。",
    TextKey.DonationBalance to "余额：{amount} {currency}", TextKey.DonationXpPreview to "获得战队经验：{xp}", TextKey.YourContribution to "你的贡献",
    TextKey.DonationCannotUndo to "捐献无法撤销。", TextKey.DonationApplied to "你的战队获得了 {xp} 经验。",
    TextKey.DonationDuplicate to "该捐献已完成。", TextKey.DonationInvalidAmount to "请选择有效的捐献数量。",
    TextKey.DonationInsufficientFunds to "你的 {currency} 不足。", TextKey.DonationMembershipRequired to "请先加入该战队再进行捐献。",
    TextKey.DonationFailed to "无法完成捐献，请重试。",
    TextKey.RoomInvitationSummary to "邀请你加入“{room}”", TextKey.RoomInvitationTitle to "房间邀请",
    TextKey.WaitingForYou to "{player} 正在等你", TextKey.RoomLabel to "房间", TextKey.TournamentInvitationTitle to "锦标赛邀请",
    TextKey.TournamentInvitationDescription to "{host} 邀请你参加“{tournament}” · {mode} · {players} 名玩家。",
    TextKey.TournamentInviteCompact to "{host} 邀请你 · {mode} · {players} 名玩家",
    TextKey.JoinRequestsCount to "加入申请（{count}）", TextKey.Approve to "批准",
    TextKey.ClanMemberSummary to "{role} · {trophies} 个奖杯", TextKey.RemoveClanMemberNamed to "将 {player} 移出战队",
    TextKey.ChooseClanLogo to "选择徽标", TextKey.ClanRoleLeader to "队长", TextKey.ClanRoleCoLeader to "副队长", TextKey.ClanRoleMember to "成员",
    TextKey.TournamentUpdating to "更新中", TextKey.TournamentPhaseLobby to "集结中",
    TextKey.TournamentPhaseRunning to "进行中", TextKey.TournamentPhaseFinished to "已结束", TextKey.TournamentPhaseCancelled to "已取消",
    TextKey.MatchPending to "等待中", TextKey.MatchPlaying to "对战中", TextKey.MatchFinished to "完成",
    TextKey.PlayerCodeExample to "例如：FTW8X2Q", TextKey.YourSquad to "你的队伍", TextKey.FriendList to "好友列表", TextKey.ClanTogetherTitle to "并肩竞技", TextKey.ExploreClans to "探索战队", TextKey.FameRace to "荣耀竞速", TextKey.CurrentSeason to "当前赛季", TextKey.KnockoutArena to "淘汰赛场", TextKey.RecentTournaments to "最近赛事", TextKey.NotificationsHero to "你的新消息", TextKey.EmptyInbox to "暂无消息", TextKey.NumberSkins to "数字皮肤", TextKey.NumberBoards to "数字棋盘", TextKey.GemVault to "宝石仓库", TextKey.ArcadeVault to "街机仓库", TextKey.Restocking to "补货中", TextKey.Equip to "装备"
)
internal val koreanSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "최고 레벨",
    TextKey.RoomInvitations to "방 초대", TextKey.FriendRequests to "친구 요청",
    TextKey.SearchClan to "클랜 찾기", TextKey.ClanMembers to "멤버", TextKey.JoinInvitations to "초대",
    TextKey.MarkAllRead to "모두 읽음으로 표시", TextKey.GemTab to "젬", TextKey.GoldTab to "골드",
    TextKey.SearchClanAction to "클랜 검색", TextKey.CreateClan to "클랜 만들기", TextKey.RequestToJoin to "가입",
    TextKey.LeaveClan to "클랜 탈퇴", TextKey.StartTournament to "토너먼트 시작", TextKey.CreateTournamentAction to "토너먼트 만들기",
    TextKey.ClearAllNotifications to "모두 삭제",
    TextKey.RemoveFriendTitle to "친구를 삭제할까요?", TextKey.NoClansFound to "클랜을 찾을 수 없습니다", TextKey.LeaveClanTitle to "클랜에서 탈퇴할까요?",
    TextKey.RemoveClanMemberTitle to "클랜 멤버를 추방할까요?", TextKey.TournamentCancelled to "토너먼트가 취소되었습니다",
    TextKey.ClearAllNotificationsTitle to "모든 알림을 삭제할까요?", TextKey.DeleteNotificationTitle to "알림을 삭제할까요?",
    TextKey.YourSquadDescription to "플레이어 코드로 친구를 연결하고 대전에 초대하세요.",
    TextKey.NoFriendsDescription to "아직 동료가 없습니다. 플레이어 코드를 입력해 초대를 보내세요.",
    TextKey.ClanTogetherDescription to "클랜에 가입하고 임무를 완료하며 함께 순위를 올리세요.",
    TextKey.NoClansFoundDescription to "다른 검색어를 시도하거나 직접 클랜을 만드세요.",
    TextKey.KnockoutArenaDescription to "4명, 8명 또는 16명의 도전자를 모아 우승에 도전하세요.",
    TextKey.EmptyInboxDescription to "초대, 보상, 새로운 소식이 여기에 표시됩니다.", TextKey.RestockingDescription to "새로운 상품이 곧 추가됩니다.",
    TextKey.ClanProgress to "클랜 진행도", TextKey.DonateToClan to "기부",
    TextKey.DonateToClanDescription to "골드 또는 젬을 기부해 클랜을 성장시키세요.",
    TextKey.DonationBalance to "잔액: {amount} {currency}", TextKey.DonationXpPreview to "획득 클랜 XP: {xp}", TextKey.YourContribution to "나의 기여",
    TextKey.DonationCannotUndo to "기부는 취소할 수 없습니다.", TextKey.DonationApplied to "클랜이 {xp} XP를 획득했습니다.",
    TextKey.DonationDuplicate to "이미 완료된 기부입니다.", TextKey.DonationInvalidAmount to "올바른 기부 금액을 선택하세요.",
    TextKey.DonationInsufficientFunds to "{currency}이(가) 부족합니다.", TextKey.DonationMembershipRequired to "기부하기 전에 이 클랜에 가입하세요.",
    TextKey.DonationFailed to "기부를 완료할 수 없습니다. 다시 시도하세요.",
    TextKey.RoomInvitationSummary to "“{room}” 방으로 초대했습니다", TextKey.RoomInvitationTitle to "방 초대",
    TextKey.WaitingForYou to "{player}님이 기다리고 있습니다", TextKey.RoomLabel to "방", TextKey.TournamentInvitationTitle to "토너먼트 초대",
    TextKey.TournamentInvitationDescription to "{host}님이 “{tournament}”에 초대했습니다 · {mode} · {players}명.",
    TextKey.TournamentInviteCompact to "{host}님의 초대 · {mode} · {players}명",
    TextKey.JoinRequestsCount to "가입 요청 ({count})", TextKey.Approve to "승인",
    TextKey.ClanMemberSummary to "{role} · 트로피 {trophies}개", TextKey.RemoveClanMemberNamed to "{player}님을 클랜에서 추방",
    TextKey.ChooseClanLogo to "로고 선택", TextKey.ClanRoleLeader to "클랜장", TextKey.ClanRoleCoLeader to "부클랜장", TextKey.ClanRoleMember to "멤버",
    TextKey.TournamentUpdating to "업데이트 중", TextKey.TournamentPhaseLobby to "참가자 모집 중",
    TextKey.TournamentPhaseRunning to "진행 중", TextKey.TournamentPhaseFinished to "종료", TextKey.TournamentPhaseCancelled to "취소됨",
    TextKey.MatchPending to "대기 중", TextKey.MatchPlaying to "경기 중", TextKey.MatchFinished to "완료",
    TextKey.PlayerCodeExample to "예: FTW8X2Q", TextKey.YourSquad to "내 스쿼드", TextKey.FriendList to "친구", TextKey.ClanTogetherTitle to "함께 경쟁하세요", TextKey.ExploreClans to "클랜 탐색", TextKey.FameRace to "명예의 레이스", TextKey.CurrentSeason to "현재 시즌", TextKey.KnockoutArena to "토너먼트 아레나", TextKey.RecentTournaments to "최근 토너먼트", TextKey.NotificationsHero to "새 소식", TextKey.EmptyInbox to "알림이 없습니다", TextKey.NumberSkins to "숫자 스킨", TextKey.NumberBoards to "숫자 보드", TextKey.GemVault to "젬 보관소", TextKey.ArcadeVault to "아케이드 보관소", TextKey.Restocking to "상품 준비 중", TextKey.Equip to "장착"
)
internal val spanishSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Nivel máximo",
    TextKey.RoomInvitations to "Invitaciones a salas", TextKey.FriendRequests to "Solicitudes de amistad",
    TextKey.SearchClan to "Buscar un clan", TextKey.ClanMembers to "Miembros", TextKey.JoinInvitations to "Invitaciones",
    TextKey.MarkAllRead to "Marcar todo como leído", TextKey.GemTab to "Gemas", TextKey.GoldTab to "Oro",
    TextKey.SearchClanAction to "Buscar clanes", TextKey.CreateClan to "CREAR CLAN", TextKey.RequestToJoin to "Unirse",
    TextKey.LeaveClan to "ABANDONAR CLAN", TextKey.StartTournament to "INICIAR TORNEO", TextKey.CreateTournamentAction to "CREAR TORNEO",
    TextKey.ClearAllNotifications to "Borrar todo",
    TextKey.RemoveFriendTitle to "¿Eliminar amigo?", TextKey.NoClansFound to "No se encontraron clanes", TextKey.LeaveClanTitle to "¿Abandonar el clan?",
    TextKey.RemoveClanMemberTitle to "¿Expulsar miembro del clan?", TextKey.TournamentCancelled to "Torneo cancelado",
    TextKey.ClearAllNotificationsTitle to "¿Borrar todas las notificaciones?", TextKey.DeleteNotificationTitle to "¿Eliminar notificación?",
    TextKey.YourSquadDescription to "Conecta con un código de jugador e invita a tus amigos a una partida.",
    TextKey.NoFriendsDescription to "Aún no tienes compañeros. Introduce un código de jugador para enviar una invitación.",
    TextKey.ClanTogetherDescription to "Únete a un clan, completa misiones y sube de rango en equipo.",
    TextKey.NoClansFoundDescription to "Prueba otra palabra o crea tu propio clan.",
    TextKey.KnockoutArenaDescription to "Reúne a 4, 8 o 16 participantes y ve por el trofeo.",
    TextKey.EmptyInboxDescription to "Aquí aparecerán invitaciones, recompensas y novedades.", TextKey.RestockingDescription to "Pronto llegarán nuevos artículos.",
    TextKey.ClanProgress to "PROGRESO DEL CLAN", TextKey.DonateToClan to "DONAR",
    TextKey.DonateToClanDescription to "Aporta oro o gemas para hacer crecer tu clan.",
    TextKey.DonationBalance to "Saldo: {amount} {currency}", TextKey.DonationXpPreview to "XP de clan obtenida: {xp}", TextKey.YourContribution to "Tu contribución",
    TextKey.DonationCannotUndo to "Las donaciones no se pueden deshacer.", TextKey.DonationApplied to "Tu clan ha obtenido {xp} XP.",
    TextKey.DonationDuplicate to "Esta donación ya se completó.", TextKey.DonationInvalidAmount to "Elige una cantidad de donación válida.",
    TextKey.DonationInsufficientFunds to "No tienes suficiente {currency}.", TextKey.DonationMembershipRequired to "Únete a este clan antes de donar.",
    TextKey.DonationFailed to "No se pudo completar la donación. Inténtalo de nuevo.",
    TextKey.RoomInvitationSummary to "Te invitó a “{room}”", TextKey.RoomInvitationTitle to "INVITACIÓN A SALA",
    TextKey.WaitingForYou to "{player} te está esperando", TextKey.RoomLabel to "SALA", TextKey.TournamentInvitationTitle to "Invitación a torneo",
    TextKey.TournamentInvitationDescription to "{host} te invitó a “{tournament}” · {mode} · {players} jugadores.",
    TextKey.TournamentInviteCompact to "Invitación de {host} · {mode} · {players} jugadores",
    TextKey.JoinRequestsCount to "Solicitudes de ingreso ({count})", TextKey.Approve to "Aprobar",
    TextKey.ClanMemberSummary to "{role} · {trophies} trofeos", TextKey.RemoveClanMemberNamed to "Expulsar a {player} del clan",
    TextKey.ChooseClanLogo to "Elegir logo", TextKey.ClanRoleLeader to "Líder", TextKey.ClanRoleCoLeader to "Colíder", TextKey.ClanRoleMember to "Miembro",
    TextKey.TournamentUpdating to "Actualizando", TextKey.TournamentPhaseLobby to "Reuniendo jugadores",
    TextKey.TournamentPhaseRunning to "En curso", TextKey.TournamentPhaseFinished to "Finalizado", TextKey.TournamentPhaseCancelled to "Cancelado",
    TextKey.MatchPending to "EN ESPERA", TextKey.MatchPlaying to "EN JUEGO", TextKey.MatchFinished to "HECHO",
    TextKey.PlayerCodeExample to "p. ej., FTW8X2Q", TextKey.YourSquad to "Tu equipo", TextKey.FriendList to "Amigos", TextKey.ClanTogetherTitle to "Compitan juntos", TextKey.ExploreClans to "Explorar clanes", TextKey.FameRace to "Carrera por la gloria", TextKey.CurrentSeason to "Temporada actual", TextKey.KnockoutArena to "Arena eliminatoria", TextKey.RecentTournaments to "Torneos recientes", TextKey.NotificationsHero to "Novedades para ti", TextKey.EmptyInbox to "Tu bandeja está vacía", TextKey.NumberSkins to "Diseños de números", TextKey.NumberBoards to "Tableros numéricos", TextKey.GemVault to "Cámara de Gemas", TextKey.ArcadeVault to "Cámara Arcade", TextKey.Restocking to "Reponiendo", TextKey.Equip to "EQUIPAR"
)
internal val brazilianPortugueseSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Nível máximo",
    TextKey.RoomInvitations to "Convites para salas", TextKey.FriendRequests to "Solicitações de amizade",
    TextKey.SearchClan to "Encontrar um clã", TextKey.ClanMembers to "Membros", TextKey.JoinInvitations to "Convites",
    TextKey.MarkAllRead to "Marcar tudo como lido", TextKey.GemTab to "Gemas", TextKey.GoldTab to "Ouro",
    TextKey.SearchClanAction to "Buscar clãs", TextKey.CreateClan to "CRIAR CLÃ", TextKey.RequestToJoin to "Entrar",
    TextKey.LeaveClan to "SAIR DO CLÃ", TextKey.StartTournament to "INICIAR TORNEIO", TextKey.CreateTournamentAction to "CRIAR TORNEIO",
    TextKey.ClearAllNotifications to "Limpar tudo",
    TextKey.RemoveFriendTitle to "Remover amigo?", TextKey.NoClansFound to "Nenhum clã encontrado", TextKey.LeaveClanTitle to "Sair do clã?",
    TextKey.RemoveClanMemberTitle to "Remover membro do clã?", TextKey.TournamentCancelled to "Torneio cancelado",
    TextKey.ClearAllNotificationsTitle to "Limpar todas as notificações?", TextKey.DeleteNotificationTitle to "Excluir notificação?",
    TextKey.YourSquadDescription to "Conecte-se com um código de jogador e convide amigos para uma partida.",
    TextKey.NoFriendsDescription to "Ainda não há companheiros. Digite um código de jogador para enviar um convite.",
    TextKey.ClanTogetherDescription to "Entre em um clã, cumpra missões e suba no ranking com sua equipe.",
    TextKey.NoClansFoundDescription to "Tente outra palavra ou crie seu próprio clã.",
    TextKey.KnockoutArenaDescription to "Reúna 4, 8 ou 16 competidores e dispute o troféu.",
    TextKey.EmptyInboxDescription to "Convites, recompensas e novidades aparecerão aqui.", TextKey.RestockingDescription to "Novos itens chegarão em breve.",
    TextKey.ClanProgress to "PROGRESSO DO CLÃ", TextKey.DonateToClan to "DOAR",
    TextKey.DonateToClanDescription to "Contribua com Ouro ou Gemas para fortalecer seu clã.",
    TextKey.DonationBalance to "Saldo: {amount} {currency}", TextKey.DonationXpPreview to "XP do clã recebida: {xp}", TextKey.YourContribution to "Sua contribuição",
    TextKey.DonationCannotUndo to "As doações não podem ser desfeitas.", TextKey.DonationApplied to "Seu clã recebeu {xp} XP.",
    TextKey.DonationDuplicate to "Esta doação já foi concluída.", TextKey.DonationInvalidAmount to "Escolha um valor de doação válido.",
    TextKey.DonationInsufficientFunds to "Você não tem {currency} suficiente.", TextKey.DonationMembershipRequired to "Entre neste clã antes de doar.",
    TextKey.DonationFailed to "Não foi possível concluir a doação. Tente novamente.",
    TextKey.RoomInvitationSummary to "Convidou você para “{room}”", TextKey.RoomInvitationTitle to "CONVITE PARA SALA",
    TextKey.WaitingForYou to "{player} está esperando por você", TextKey.RoomLabel to "SALA", TextKey.TournamentInvitationTitle to "Convite para torneio",
    TextKey.TournamentInvitationDescription to "{host} convidou você para “{tournament}” · {mode} · {players} jogadores.",
    TextKey.TournamentInviteCompact to "Convite de {host} · {mode} · {players} jogadores",
    TextKey.JoinRequestsCount to "Solicitações de entrada ({count})", TextKey.Approve to "Aprovar",
    TextKey.ClanMemberSummary to "{role} · {trophies} troféus", TextKey.RemoveClanMemberNamed to "Remover {player} do clã",
    TextKey.ChooseClanLogo to "Escolher logo", TextKey.ClanRoleLeader to "Líder", TextKey.ClanRoleCoLeader to "Vice-líder", TextKey.ClanRoleMember to "Membro",
    TextKey.TournamentUpdating to "Atualizando", TextKey.TournamentPhaseLobby to "Reunindo jogadores",
    TextKey.TournamentPhaseRunning to "Em andamento", TextKey.TournamentPhaseFinished to "Encerrado", TextKey.TournamentPhaseCancelled to "Cancelado",
    TextKey.MatchPending to "AGUARDANDO", TextKey.MatchPlaying to "EM JOGO", TextKey.MatchFinished to "CONCLUÍDO",
    TextKey.PlayerCodeExample to "ex.: FTW8X2Q", TextKey.YourSquad to "Seu esquadrão", TextKey.FriendList to "Amigos", TextKey.ClanTogetherTitle to "Compitam juntos", TextKey.ExploreClans to "Explorar clãs", TextKey.FameRace to "Corrida pela glória", TextKey.CurrentSeason to "Temporada atual", TextKey.KnockoutArena to "Arena eliminatória", TextKey.RecentTournaments to "Torneios recentes", TextKey.NotificationsHero to "Novidades para você", TextKey.EmptyInbox to "Sua caixa está vazia", TextKey.NumberSkins to "Visuais de números", TextKey.NumberBoards to "Tabuleiros numéricos", TextKey.GemVault to "Cofre de Gemas", TextKey.ArcadeVault to "Cofre Arcade", TextKey.Restocking to "Repondo estoque", TextKey.Equip to "EQUIPAR"
)
internal val frenchSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Niveau maximum",
    TextKey.RoomInvitations to "Invitations de salon", TextKey.FriendRequests to "Demandes d’amitié",
    TextKey.SearchClan to "Trouver un clan", TextKey.ClanMembers to "Membres", TextKey.JoinInvitations to "Invitations",
    TextKey.MarkAllRead to "Tout marquer comme lu", TextKey.GemTab to "Gemmes", TextKey.GoldTab to "Or",
    TextKey.SearchClanAction to "Rechercher des clans", TextKey.CreateClan to "CRÉER UN CLAN", TextKey.RequestToJoin to "Rejoindre",
    TextKey.LeaveClan to "QUITTER LE CLAN", TextKey.StartTournament to "LANCER LE TOURNOI", TextKey.CreateTournamentAction to "CRÉER LE TOURNOI",
    TextKey.ClearAllNotifications to "Tout effacer",
    TextKey.RemoveFriendTitle to "Supprimer cet ami ?", TextKey.NoClansFound to "Aucun clan trouvé", TextKey.LeaveClanTitle to "Quitter le clan ?",
    TextKey.RemoveClanMemberTitle to "Exclure ce membre du clan ?", TextKey.TournamentCancelled to "Tournoi annulé",
    TextKey.ClearAllNotificationsTitle to "Effacer toutes les notifications ?", TextKey.DeleteNotificationTitle to "Supprimer la notification ?",
    TextKey.YourSquadDescription to "Ajoute des joueurs avec leur code et invite tes amis à jouer.",
    TextKey.NoFriendsDescription to "Aucun coéquipier pour le moment. Saisis un code joueur pour envoyer une invitation.",
    TextKey.ClanTogetherDescription to "Rejoins un clan, accomplis des missions et grimpe au classement en équipe.",
    TextKey.NoClansFoundDescription to "Essaie un autre mot-clé ou crée ton propre clan.",
    TextKey.KnockoutArenaDescription to "Réunis 4, 8 ou 16 participants et vise le trophée.",
    TextKey.EmptyInboxDescription to "Les invitations, récompenses et nouveautés apparaîtront ici.", TextKey.RestockingDescription to "De nouveaux objets arriveront bientôt.",
    TextKey.ClanProgress to "PROGRESSION DU CLAN", TextKey.DonateToClan to "DONNER",
    TextKey.DonateToClanDescription to "Donne de l’Or ou des Gemmes pour développer ton clan.",
    TextKey.DonationBalance to "Solde : {amount} {currency}", TextKey.DonationXpPreview to "XP de clan gagnée : {xp}", TextKey.YourContribution to "Ta contribution",
    TextKey.DonationCannotUndo to "Les dons ne peuvent pas être annulés.", TextKey.DonationApplied to "Ton clan a gagné {xp} XP.",
    TextKey.DonationDuplicate to "Ce don a déjà été effectué.", TextKey.DonationInvalidAmount to "Choisis un montant de don valide.",
    TextKey.DonationInsufficientFunds to "Tu n’as pas assez de {currency}.", TextKey.DonationMembershipRequired to "Rejoins ce clan avant de faire un don.",
    TextKey.DonationFailed to "Impossible d’effectuer le don. Réessaie.",
    TextKey.RoomInvitationSummary to "T’a invité dans « {room} »", TextKey.RoomInvitationTitle to "INVITATION DE SALON",
    TextKey.WaitingForYou to "{player} t’attend", TextKey.RoomLabel to "SALON", TextKey.TournamentInvitationTitle to "Invitation à un tournoi",
    TextKey.TournamentInvitationDescription to "{host} t’a invité au tournoi « {tournament} » · {mode} · {players} joueurs.",
    TextKey.TournamentInviteCompact to "Invitation de {host} · {mode} · {players} joueurs",
    TextKey.JoinRequestsCount to "Demandes d’adhésion ({count})", TextKey.Approve to "Approuver",
    TextKey.ClanMemberSummary to "{role} · {trophies} trophées", TextKey.RemoveClanMemberNamed to "Exclure {player} du clan",
    TextKey.ChooseClanLogo to "Choisir le logo", TextKey.ClanRoleLeader to "Chef", TextKey.ClanRoleCoLeader to "Chef adjoint", TextKey.ClanRoleMember to "Membre",
    TextKey.TournamentUpdating to "Mise à jour", TextKey.TournamentPhaseLobby to "Rassemblement",
    TextKey.TournamentPhaseRunning to "En cours", TextKey.TournamentPhaseFinished to "Terminé", TextKey.TournamentPhaseCancelled to "Annulé",
    TextKey.MatchPending to "EN ATTENTE", TextKey.MatchPlaying to "EN JEU", TextKey.MatchFinished to "TERMINÉ",
    TextKey.PlayerCodeExample to "ex. : FTW8X2Q", TextKey.YourSquad to "Ton équipe", TextKey.FriendList to "Amis", TextKey.ClanTogetherTitle to "Jouez ensemble", TextKey.ExploreClans to "Explorer les clans", TextKey.FameRace to "Course à la gloire", TextKey.CurrentSeason to "Saison actuelle", TextKey.KnockoutArena to "Arène à élimination", TextKey.RecentTournaments to "Tournois récents", TextKey.NotificationsHero to "Tes nouveautés", TextKey.EmptyInbox to "Ta boîte est vide", TextKey.NumberSkins to "Styles de nombres", TextKey.NumberBoards to "Plateaux numériques", TextKey.GemVault to "Coffre de Gemmes", TextKey.ArcadeVault to "Coffre Arcade", TextKey.Restocking to "Réapprovisionnement", TextKey.Equip to "ÉQUIPER"
)
internal val indonesianSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Level maksimum",
    TextKey.RoomInvitations to "Undangan ruang", TextKey.FriendRequests to "Permintaan pertemanan",
    TextKey.SearchClan to "Cari klan", TextKey.ClanMembers to "Anggota", TextKey.JoinInvitations to "Undangan",
    TextKey.MarkAllRead to "Tandai semua sudah dibaca", TextKey.GemTab to "Gem", TextKey.GoldTab to "Emas",
    TextKey.SearchClanAction to "Cari klan", TextKey.CreateClan to "BUAT KLAN", TextKey.RequestToJoin to "Gabung",
    TextKey.LeaveClan to "KELUAR KLAN", TextKey.StartTournament to "MULAI TURNAMEN", TextKey.CreateTournamentAction to "BUAT TURNAMEN",
    TextKey.ClearAllNotifications to "Hapus semua",
    TextKey.RemoveFriendTitle to "Hapus teman?", TextKey.NoClansFound to "Klan tidak ditemukan", TextKey.LeaveClanTitle to "Keluar dari klan?",
    TextKey.RemoveClanMemberTitle to "Keluarkan anggota klan?", TextKey.TournamentCancelled to "Turnamen dibatalkan",
    TextKey.ClearAllNotificationsTitle to "Hapus semua notifikasi?", TextKey.DeleteNotificationTitle to "Hapus notifikasi?",
    TextKey.YourSquadDescription to "Terhubung dengan kode pemain dan undang teman ke pertandingan.",
    TextKey.NoFriendsDescription to "Belum ada rekan tim. Masukkan kode pemain untuk mengirim undangan.",
    TextKey.ClanTogetherDescription to "Gabung klan, selesaikan misi, dan naik peringkat bersama.",
    TextKey.NoClansFoundDescription to "Coba kata kunci lain atau buat klanmu sendiri.",
    TextKey.KnockoutArenaDescription to "Kumpulkan 4, 8, atau 16 peserta dan raih trofi.",
    TextKey.EmptyInboxDescription to "Undangan, hadiah, dan kabar baru akan muncul di sini.", TextKey.RestockingDescription to "Item baru akan segera hadir.",
    TextKey.ClanProgress to "PROGRES KLAN", TextKey.DonateToClan to "DONASI",
    TextKey.DonateToClanDescription to "Sumbangkan Emas atau Gem untuk mengembangkan klanmu.",
    TextKey.DonationBalance to "Saldo: {amount} {currency}", TextKey.DonationXpPreview to "XP klan diperoleh: {xp}", TextKey.YourContribution to "Kontribusimu",
    TextKey.DonationCannotUndo to "Donasi tidak dapat dibatalkan.", TextKey.DonationApplied to "Klanmu memperoleh {xp} XP.",
    TextKey.DonationDuplicate to "Donasi ini sudah selesai.", TextKey.DonationInvalidAmount to "Pilih jumlah donasi yang valid.",
    TextKey.DonationInsufficientFunds to "{currency} milikmu tidak cukup.", TextKey.DonationMembershipRequired to "Gabung klan ini sebelum berdonasi.",
    TextKey.DonationFailed to "Donasi tidak dapat diselesaikan. Coba lagi.",
    TextKey.RoomInvitationSummary to "Mengundangmu ke “{room}”", TextKey.RoomInvitationTitle to "UNDANGAN RUANG",
    TextKey.WaitingForYou to "{player} sedang menunggumu", TextKey.RoomLabel to "RUANG", TextKey.TournamentInvitationTitle to "Undangan turnamen",
    TextKey.TournamentInvitationDescription to "{host} mengundangmu ke “{tournament}” · {mode} · {players} pemain.",
    TextKey.TournamentInviteCompact to "Undangan dari {host} · {mode} · {players} pemain",
    TextKey.JoinRequestsCount to "Permintaan bergabung ({count})", TextKey.Approve to "Setujui",
    TextKey.ClanMemberSummary to "{role} · {trophies} trofi", TextKey.RemoveClanMemberNamed to "Keluarkan {player} dari klan",
    TextKey.ChooseClanLogo to "Pilih logo", TextKey.ClanRoleLeader to "Pemimpin", TextKey.ClanRoleCoLeader to "Wakil pemimpin", TextKey.ClanRoleMember to "Anggota",
    TextKey.TournamentUpdating to "Memperbarui", TextKey.TournamentPhaseLobby to "Mengumpulkan pemain",
    TextKey.TournamentPhaseRunning to "Sedang berlangsung", TextKey.TournamentPhaseFinished to "Selesai", TextKey.TournamentPhaseCancelled to "Dibatalkan",
    TextKey.MatchPending to "MENUNGGU", TextKey.MatchPlaying to "BERMAIN", TextKey.MatchFinished to "SELESAI",
    TextKey.PlayerCodeExample to "mis. FTW8X2Q", TextKey.YourSquad to "Skuadmu", TextKey.FriendList to "Teman", TextKey.ClanTogetherTitle to "Bertanding bersama", TextKey.ExploreClans to "Jelajahi klan", TextKey.FameRace to "Perebutan kejayaan", TextKey.CurrentSeason to "Musim saat ini", TextKey.KnockoutArena to "Arena eliminasi", TextKey.RecentTournaments to "Turnamen terbaru", TextKey.NotificationsHero to "Kabar untukmu", TextKey.EmptyInbox to "Kotak masukmu kosong", TextKey.NumberSkins to "Skin angka", TextKey.NumberBoards to "Papan angka", TextKey.GemVault to "Brankas Gem", TextKey.ArcadeVault to "Brankas Arcade", TextKey.Restocking to "Mengisi stok", TextKey.Equip to "PAKAI"
)
internal val thaiSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "เลเวลสูงสุด",
    TextKey.RoomInvitations to "คำเชิญเข้าห้อง", TextKey.FriendRequests to "คำขอเป็นเพื่อน",
    TextKey.SearchClan to "ค้นหาแคลน", TextKey.ClanMembers to "สมาชิก", TextKey.JoinInvitations to "คำเชิญ",
    TextKey.MarkAllRead to "ทำเครื่องหมายว่าอ่านแล้วทั้งหมด", TextKey.GemTab to "เจม", TextKey.GoldTab to "ทอง",
    TextKey.SearchClanAction to "ค้นหาแคลน", TextKey.CreateClan to "สร้างแคลน", TextKey.RequestToJoin to "เข้าร่วม",
    TextKey.LeaveClan to "ออกจากแคลน", TextKey.StartTournament to "เริ่มทัวร์นาเมนต์", TextKey.CreateTournamentAction to "สร้างทัวร์นาเมนต์",
    TextKey.ClearAllNotifications to "ล้างทั้งหมด",
    TextKey.RemoveFriendTitle to "ลบเพื่อนหรือไม่?", TextKey.NoClansFound to "ไม่พบแคลน", TextKey.LeaveClanTitle to "ออกจากแคลนหรือไม่?",
    TextKey.RemoveClanMemberTitle to "นำสมาชิกออกจากแคลนหรือไม่?", TextKey.TournamentCancelled to "ยกเลิกทัวร์นาเมนต์แล้ว",
    TextKey.ClearAllNotificationsTitle to "ลบการแจ้งเตือนทั้งหมดหรือไม่?", TextKey.DeleteNotificationTitle to "ลบการแจ้งเตือนหรือไม่?",
    TextKey.YourSquadDescription to "เชื่อมต่อด้วยรหัสผู้เล่นและชวนเพื่อนเข้าร่วมการแข่งขัน",
    TextKey.NoFriendsDescription to "ยังไม่มีเพื่อนร่วมทีม กรอกรหัสผู้เล่นเพื่อส่งคำเชิญ",
    TextKey.ClanTogetherDescription to "เข้าร่วมแคลน ทำภารกิจ และไต่อันดับไปด้วยกัน",
    TextKey.NoClansFoundDescription to "ลองใช้คำค้นอื่นหรือสร้างแคลนของคุณเอง",
    TextKey.KnockoutArenaDescription to "รวมผู้เข้าแข่งขัน 4, 8 หรือ 16 คน แล้วมุ่งสู่ถ้วยรางวัล",
    TextKey.EmptyInboxDescription to "คำเชิญ รางวัล และข่าวสารจะแสดงที่นี่", TextKey.RestockingDescription to "ไอเทมใหม่กำลังจะมาเร็ว ๆ นี้",
    TextKey.ClanProgress to "ความคืบหน้าแคลน", TextKey.DonateToClan to "บริจาค",
    TextKey.DonateToClanDescription to "บริจาคทองหรือเจมเพื่อพัฒนาแคลนของคุณ",
    TextKey.DonationBalance to "ยอดคงเหลือ: {amount} {currency}", TextKey.DonationXpPreview to "XP แคลนที่ได้รับ: {xp}", TextKey.YourContribution to "ผลงานของคุณ",
    TextKey.DonationCannotUndo to "ไม่สามารถยกเลิกการบริจาคได้", TextKey.DonationApplied to "แคลนของคุณได้รับ {xp} XP",
    TextKey.DonationDuplicate to "การบริจาคนี้เสร็จสิ้นแล้ว", TextKey.DonationInvalidAmount to "เลือกจำนวนบริจาคที่ถูกต้อง",
    TextKey.DonationInsufficientFunds to "คุณมี {currency} ไม่เพียงพอ", TextKey.DonationMembershipRequired to "เข้าร่วมแคลนนี้ก่อนบริจาค",
    TextKey.DonationFailed to "ไม่สามารถดำเนินการบริจาคได้ โปรดลองอีกครั้ง",
    TextKey.RoomInvitationSummary to "เชิญคุณเข้าร่วม “{room}”", TextKey.RoomInvitationTitle to "คำเชิญเข้าห้อง",
    TextKey.WaitingForYou to "{player} กำลังรอคุณ", TextKey.RoomLabel to "ห้อง", TextKey.TournamentInvitationTitle to "คำเชิญเข้าร่วมทัวร์นาเมนต์",
    TextKey.TournamentInvitationDescription to "{host} เชิญคุณเข้าร่วม “{tournament}” · {mode} · {players} คน",
    TextKey.TournamentInviteCompact to "คำเชิญจาก {host} · {mode} · {players} คน",
    TextKey.JoinRequestsCount to "คำขอเข้าร่วม ({count})", TextKey.Approve to "อนุมัติ",
    TextKey.ClanMemberSummary to "{role} · {trophies} ถ้วย", TextKey.RemoveClanMemberNamed to "นำ {player} ออกจากแคลน",
    TextKey.ChooseClanLogo to "เลือกโลโก้", TextKey.ClanRoleLeader to "หัวหน้า", TextKey.ClanRoleCoLeader to "รองหัวหน้า", TextKey.ClanRoleMember to "สมาชิก",
    TextKey.TournamentUpdating to "กำลังอัปเดต", TextKey.TournamentPhaseLobby to "กำลังรวมผู้เล่น",
    TextKey.TournamentPhaseRunning to "กำลังดำเนินการ", TextKey.TournamentPhaseFinished to "เสร็จสิ้น", TextKey.TournamentPhaseCancelled to "ยกเลิกแล้ว",
    TextKey.MatchPending to "รอ", TextKey.MatchPlaying to "กำลังเล่น", TextKey.MatchFinished to "เสร็จแล้ว",
    TextKey.PlayerCodeExample to "เช่น FTW8X2Q", TextKey.YourSquad to "ทีมของคุณ", TextKey.FriendList to "เพื่อน", TextKey.ClanTogetherTitle to "แข่งขันไปด้วยกัน", TextKey.ExploreClans to "สำรวจแคลน", TextKey.FameRace to "เส้นทางแห่งเกียรติยศ", TextKey.CurrentSeason to "ฤดูกาลปัจจุบัน", TextKey.KnockoutArena to "สนามน็อกเอาต์", TextKey.RecentTournaments to "ทัวร์นาเมนต์ล่าสุด", TextKey.NotificationsHero to "ข่าวสารสำหรับคุณ", TextKey.EmptyInbox to "กล่องข้อความว่าง", TextKey.NumberSkins to "สกินตัวเลข", TextKey.NumberBoards to "กระดานตัวเลข", TextKey.GemVault to "คลัง Gem", TextKey.ArcadeVault to "คลัง Arcade", TextKey.Restocking to "กำลังเติมสินค้า", TextKey.Equip to "สวมใส่"
)
internal val russianSocialShopTexts = englishSocialShopTexts + mapOf(
    TextKey.MaximumLevel to "Максимальный уровень",
    TextKey.RoomInvitations to "Приглашения в комнаты", TextKey.FriendRequests to "Заявки в друзья",
    TextKey.SearchClan to "Найти клан", TextKey.ClanMembers to "Участники", TextKey.JoinInvitations to "Приглашения",
    TextKey.MarkAllRead to "Отметить все как прочитанные", TextKey.GemTab to "Кристаллы", TextKey.GoldTab to "Золото",
    TextKey.SearchClanAction to "Искать кланы", TextKey.CreateClan to "СОЗДАТЬ КЛАН", TextKey.RequestToJoin to "Вступить",
    TextKey.LeaveClan to "ПОКИНУТЬ КЛАН", TextKey.StartTournament to "НАЧАТЬ ТУРНИР", TextKey.CreateTournamentAction to "СОЗДАТЬ ТУРНИР",
    TextKey.ClearAllNotifications to "Очистить все",
    TextKey.RemoveFriendTitle to "Удалить друга?", TextKey.NoClansFound to "Кланы не найдены", TextKey.LeaveClanTitle to "Покинуть клан?",
    TextKey.RemoveClanMemberTitle to "Исключить участника клана?", TextKey.TournamentCancelled to "Турнир отменён",
    TextKey.ClearAllNotificationsTitle to "Удалить все уведомления?", TextKey.DeleteNotificationTitle to "Удалить уведомление?",
    TextKey.YourSquadDescription to "Добавляйте друзей по коду игрока и приглашайте их в матч.",
    TextKey.NoFriendsDescription to "У вас пока нет товарищей. Введите код игрока, чтобы отправить приглашение.",
    TextKey.ClanTogetherDescription to "Вступайте в клан, выполняйте задания и поднимайтесь в рейтинге вместе.",
    TextKey.NoClansFoundDescription to "Попробуйте другое слово или создайте собственный клан.",
    TextKey.KnockoutArenaDescription to "Соберите 4, 8 или 16 участников и сразитесь за кубок.",
    TextKey.EmptyInboxDescription to "Здесь появятся приглашения, награды и новости.", TextKey.RestockingDescription to "Новые предметы скоро появятся.",
    TextKey.ClanProgress to "ПРОГРЕСС КЛАНА", TextKey.DonateToClan to "ПОЖЕРТВОВАТЬ",
    TextKey.DonateToClanDescription to "Жертвуйте золото или кристаллы для развития клана.",
    TextKey.DonationBalance to "Баланс: {amount} {currency}", TextKey.DonationXpPreview to "Получено опыта клана: {xp}", TextKey.YourContribution to "Ваш вклад",
    TextKey.DonationCannotUndo to "Пожертвования нельзя отменить.", TextKey.DonationApplied to "Ваш клан получил {xp} опыта.",
    TextKey.DonationDuplicate to "Это пожертвование уже выполнено.", TextKey.DonationInvalidAmount to "Выберите допустимую сумму пожертвования.",
    TextKey.DonationInsufficientFunds to "У вас недостаточно {currency}.", TextKey.DonationMembershipRequired to "Вступите в этот клан перед пожертвованием.",
    TextKey.DonationFailed to "Не удалось выполнить пожертвование. Попробуйте ещё раз.",
    TextKey.RoomInvitationSummary to "Приглашает вас в «{room}»", TextKey.RoomInvitationTitle to "ПРИГЛАШЕНИЕ В КОМНАТУ",
    TextKey.WaitingForYou to "{player} ждёт вас", TextKey.RoomLabel to "КОМНАТА", TextKey.TournamentInvitationTitle to "Приглашение на турнир",
    TextKey.TournamentInvitationDescription to "{host} приглашает вас на «{tournament}» · {mode} · {players} игроков.",
    TextKey.TournamentInviteCompact to "Приглашение от {host} · {mode} · {players} игроков",
    TextKey.JoinRequestsCount to "Заявки на вступление ({count})", TextKey.Approve to "Одобрить",
    TextKey.ClanMemberSummary to "{role} · {trophies} трофеев", TextKey.RemoveClanMemberNamed to "Исключить {player} из клана",
    TextKey.ChooseClanLogo to "Выбрать эмблему", TextKey.ClanRoleLeader to "Лидер", TextKey.ClanRoleCoLeader to "Заместитель", TextKey.ClanRoleMember to "Участник",
    TextKey.TournamentUpdating to "Обновление", TextKey.TournamentPhaseLobby to "Сбор участников",
    TextKey.TournamentPhaseRunning to "Идёт", TextKey.TournamentPhaseFinished to "Завершён", TextKey.TournamentPhaseCancelled to "Отменён",
    TextKey.MatchPending to "ОЖИДАНИЕ", TextKey.MatchPlaying to "ИГРА", TextKey.MatchFinished to "ГОТОВО",
    TextKey.PlayerCodeExample to "например, FTW8X2Q", TextKey.YourSquad to "Твоя команда", TextKey.FriendList to "Друзья", TextKey.ClanTogetherTitle to "Сражайтесь вместе", TextKey.ExploreClans to "Поиск кланов", TextKey.FameRace to "Гонка за славой", TextKey.CurrentSeason to "Текущий сезон", TextKey.KnockoutArena to "Арена на выбывание", TextKey.RecentTournaments to "Недавние турниры", TextKey.NotificationsHero to "Новости для тебя", TextKey.EmptyInbox to "Уведомлений нет", TextKey.NumberSkins to "Скины чисел", TextKey.NumberBoards to "Числовые поля", TextKey.GemVault to "Хранилище самоцветов", TextKey.ArcadeVault to "Аркадное хранилище", TextKey.Restocking to "Скоро пополнение", TextKey.Equip to "НАДЕТЬ"
)
