package com.hienthai.fastowin.localization

/** Stable keys shared by clients and the backend. Never use player input as a key. */
enum class TextKey {
    Back, Cancel, Confirm, Retry, Close, Save, Delete, Loading, UnknownError, WelcomePlayer,
    SettingsTitle, LanguageTitle, ChooseLanguageTitle, SystemLanguage, ResolvedSystemLanguage,
    AppearanceTitle, AppearanceSubtitle,

    Gold, Gems, Notifications, ViewMoreCount,
    UpdateGameTitle, UpdateAvailableSubtitle, UpdateHeroTitle, UpdateDescription,
    UpdateAutoReload, UpdateProgressPreserved, UpdateNow, Later,
    MaintenanceBadge, MaintenanceTitle, MaintenanceDefaultMessage, MaintenanceAutoResume,
    MaintenanceNoAction,
    OfflineBadge, OfflineTitle, OfflineDescription, OfflineCheckNetwork, OfflineNotMaintenance,
    RetryConnection, OfflinePractice, NoNetwork,
    TutorialTitle, Skip, TutorialStep,
    TutorialFindNumbersTitle, TutorialFindNumbersDescription, TutorialFindNumbersHint,
    TutorialSharedTargetTitle, TutorialSharedTargetDescription, TutorialSharedTargetHint,
    TutorialChooseModeTitle, TutorialChooseModeDescription, TutorialChooseModeHint,
    StartPlaying, Continue,

    VerifyEmailTitle, VerifyEmailDescription, DevVerificationCode, VerificationCode,
    Verifying, Verify, ResendCode, Logout,
    AuthWelcomeDescription, AuthLoginTitle, Login, LoggingIn, CreateAccount, PlayAsGuest, Password,
    ForgotPassword, ResetPasswordTitle, ResetPasswordDescription, Sending, SendResetCode,
    DevResetCode, ResetCode, NewPassword, ConfirmNewPassword, Updating, ResetPasswordAction,
    UseDifferentEmail, DisplayName, GenderDefaultAvatar, Male, Female, Player,
    PasswordWithMinimum, ConfirmPassword, Creating, SaveGuestAccountTitle,
    SaveGuestAccountDescription, Saving, SaveAndCreateAccount, Email, HidePassword,
    ShowPassword, PasswordTooShort, PasswordTooLong, PasswordMismatch,

    Rooms, Leaderboard, Clan, Account,
    FinishCurrentMatchBeforeChallenge, ModeUnlockLevel, CannotOpenChallenge, Understood,
    ChoosePracticeMode, ShareRoom,

    ModeClassicTitle, ModeClassicDescription, ModeRandomTitle, ModeRandomDescription,
    ModeTimeBonusTitle, ModeTimeBonusDescription, ModeSpeedUpTitle, ModeSpeedUpDescription,
    ModeSurvivalTitle, ModeSurvivalDescription, ModeComboTitle, ModeComboDescription,
    ModeTimeAttackTitle, ModeTimeAttackDescription, ModeTeamTitle, ModeTeamDescription,

    ChooseMatchType, ChooseRankedMode, ChooseCasualMode, GuestMode, Ranked, Casual,
    RegisterToPlayOnline, CasualOrRankedDescription, LoginToPlay, PlayNow,
    Explore, FeaturesAndActivities, Tournament, RegisterToJoin, TournamentDescription,
    Shop, ShopDiscoveryDescription, OfflinePracticeTitle, OfflinePracticeDescription,
    SaveProgress, SaveProgressDescription, ExitGuestMode, ChooseCompetitionType,
    CreateRoom, JoinRoom, Friends, RegisterToAddFriends, OnlineFriends,
    YourRank, ViewEloLeaderboard, Level, PlacementPending,
    DailyCheckInSevenDays, CheckInStreak, DayLabel, ClaimDayReward, Home,
    HarderModesUnlock, UnlockAtLevel, ChooseMatchScoring, CasualMatch,
    CasualMatchDescription, RankedMatch, RankedMatchDescription,
    ConnectionDisconnected, ConnectionConnecting, ConnectionAuthenticating,
    ConnectionConnected, ConnectionReconnecting,

    GreetingPlayer, ReadyForRecord, GameRooms, Ready, Matchmaking, MatchFound,
    FindingOpponent, RankedMatchmakingHint, CasualMatchmakingHint, EloRange, NoEloImpact,
    CancelMatchmaking, GuestNameTitle, GuestNameDescription, EnterNickname,
    SaveNameProgressDescription, RoomLinkUnavailable, ChooseRoomType, DefaultRoomName,
    PublicRooms, FindOpponent, PublicRoomsDescription, SaveProgressEmail, SearchRooms,
    All, Waiting, RoomCount, Reconnecting, AuthenticatingSession, Connecting,
    NoWaitingRooms, NoMatchingRooms, EnterRoomCode, PasteRoomCode, RoomCode,
    FindRoom, RoomCodeNotFound, CreateNewRoom, YouAreHost, RoomName, Public, Private,
    PrivatePasswordRequired, PublicNoPassword, RoomPassword, RankedEloImpact,
    CasualNoEloImpact, PrivateRoom, PublicRoom, RoomListSummary, EnterRoom,
    JoinPrivateRoom, JoinRoomTitle, PrivateJoinDescription, PublicJoinDescription,
    JoinedRoomCode, JoinedRoom, ShareCodeHint, WaitHostStart, PlayersTitle,
    BlueTeam, RedTeam, You, TeammateNumber, Teammate, OpponentNumber, Opponent,
    WaitingPlayer, HostYou, Guest, Host, WaitingForPlayer, ModeNumberCount,
    ShareRoomCode, ShareSheetError, CancelReady, ReadyAction, WaitingForReady,
    InviteFriends, Kick, CloseRoom, LeaveRoom, ReadyStatus, WaitingStatus,
    LatencyGood, LatencyStable, LatencySlow, OpponentReady, MatchStarting,
    LocalPlayerLabel, OpponentLabel,

    ReactionHappy, ReactionLaugh, ReactionFire, ReactionVictory, ReactionLove,
    ReactionSpeed, ExitMatchTitle, ForfeitCasualDescription, ForfeitRankedDescription,
    ExitMatch, ContinuePlaying, GameHeader, GameDefaultRoom, GameDisconnected,
    GameReconnecting, TieScoreWarning, CloseScoreWarning, LivesCount, PaceProgress,
    SpeedValue, SendReaction, CorrectWrongSummary, Measuring, YourTeam, OpponentTeam,
    Versus, NextNumber,

    BlockPlayerTitle, BlockPlayerDescription, Block, RematchInviteTitle,
    RematchInviteDescription, Processing, Accept, Decline, DrawResult, VictoryResult,
    DefeatResult, ForfeitResultDescription, DrawResultDescription, VictoryResultDescription,
    OpposingTeamVictoryDescription, OpponentVictoryDescription, MatchResultTitle,
    GameResultSubtitle, ShareResult, ShareResultError, ReturnToLobby, PlayerYou,
    Draw, Win, Loss, ResultLabel, PlacementProgress, MatchReward, FinalMatch,
    SemifinalMatch, TournamentFinishedDescription, BracketUpdatedDescription,
    ViewBracket, YourSummary, AverageReaction, Accuracy, CorrectWrongDuration,
    PaceAnalysis, InsufficientPaceAnalysis, PaceSegmentHint, Fastest, Slowest,
    TurnRange, RankedNoRematch, Rematch, ResponseSeconds, OpponentLeft,
    WaitingForResponse, Invited, SendingShort, InviteRematch, LoginForSocial,
    AddFriend, AcceptFriend, FriendRequestSent, AlreadyFriends, Blocked, LoadingInfo,
    ShareResultCaption, ShareTimeLabel, ShareAccuracyLabel, ShareSlogan,
    ShareResultSheetTitle,

    PracticeHeader, OfflineNoElo, CorrectBoardCompleted, CorrectNextTarget,
    WrongNeedTarget, Target, Score, Remaining, Time, Lives, ComboLabel, Pace,
    EndPractice, FoundAllNumbers, SurvivalEnded, SpeedUpEnded, TimeBonusEnded,
    TimeAttackEnded, ChallengeEnded, Completed, PracticeCompletionSummary,
    ChallengeCode, ChallengeCodeHint, PracticeNoElo, ShareChallenge, ReplaySameBoard,
    CreateNewChallenge, ReturnHome, Reaction, CorrectWrong, AveragePerNumber,
    PracticeHeroTitle, PracticeHeroDescription, PracticeNoServerNeeded,
    StartNewPractice, HaveChallengeCode, PlayChallenge, InvalidChallengeCode,
    ChallengeModeUnlock, ChallengeShareText, ShareChallengeSheetTitle, RoomShareText,
    InvalidRoomIdCode, InvalidChallengeCodeCode,

    ProfileTitle, ExternalPlayerTitle, ProfileLoadError, InviteToClan, EditProfile,
    Nickname, Avatar, UploadImage, Matches, Wins, FeaturedAchievements, BestStreak,
    AverageReactionShort, Activity, StatisticsAchievements, PerformanceMilestones,
    WalletHistory, WalletHistorySubtitle, CheckInHistory, CheckInHistorySubtitle,
    MissionsSubtitle, CollectionTitle, CollectionSubtitle, RecentMatches, MatchHistory,
    SettingsAccount, AppSettings, LoginDevices, AccountSecurity, Copied, Rookie,
    TitleValue, PlayerCodeValue, CopyPlayerCode, ProfilePerformanceHero,
    ProfilePerformanceDescription, WalletFlowHero, WalletFlowDescription,
    AttendanceJourney, AttendanceJourneyDescription, TodayMissions, TodayMissionsDescription,
    PersonalCollectionHero, PersonalCollectionDescription, RecentCompetitionHero,
    RecentCompetitionDescription, Received, Used, NoWalletTransactions,
    NoWalletTransactionsForFilter, DailyCheckInSource, MissionRewardSource,
    MatchRewardSource, ClanRewardSource, ShopPurchaseSource, WalletOtherSource,
    DailyMissions, WeeklyMissions, NoMissions, MissionProgress, Claimed,
    Claiming, ClaimReward, MissionCompleted, DifficultyEasy, DifficultyNormal,
    DifficultyHard, DifficultyElite, EmptyCollection, Titles, Equipping, Equipped,
    TapToEquip, Unlocked, UnlockRequirement, Locked, RecentFilterAll,
    RecentFilterWins, RecentFilterLosses, NoCompletedMatches, NoMatchesForFilter,
    LogoutTitle, LogoutDescription, LogoutAction, AccountSecurityTitle,
    AccountSecurityDescription, ChangePassword, CurrentPassword, NewPasswordLabel,
    ConfirmNewPasswordLabel, NewPasswordMustDiffer, UpdatingPassword, DangerZone,
    DeleteAccountWarning, PasswordToConfirm, RequestDeleteAccount, DeletingAccount,
    LoginDevicesTitle, LoginDevicesDescription, NoActiveSessions, CurrentDevice,
    LogoutAllDevices, LogoutAllDevicesTitle, LogoutAllDevicesDescription,
    RevokeDeviceTitle, RevokeCurrentDeviceTitle, RevokeCurrentDeviceDescription,
    RevokeOtherDeviceDescription, UnknownDevice, JustNow, MinutesAgo, HoursAgo,
    DaysAgo, SessionExpiresInDays, ActivityTime, CheckIn, StreakDays,
    CheckInCalendarDescription, PreviousMonth, NextMonth, MonthYear, CheckedIn,
    CheckInMilestones, CheckInSummary, ConsecutiveDays, TotalCheckIns,
    SteadyStartAchievement, DiligentTitle, PersistentFrame,
    SeasonHistoryTitle, RankedJourney, SeasonsPlayed, SeasonHistoryDescription,
    LoadingSeasonHistory, SeasonAchievements, SeasonHistoryRefreshHint,
    NoSeasonHistory, NoSeasonHistoryDescription, Unranked, Latest,
    SeasonSummaryLine, HighestTier, HighestElo, FinalElo, FinalRank, NotRanked,
    SeasonRewardReceived, SeasonRewardProcessing, NoPlacementReward,
    SeasonProgressPlacement, HighestTierReached, EloToNextTier, HideTierRewards,
    ViewTierRewards, FinishPlacementHint, SeasonPeakElo, HeldReward,
    ReachedHighestTier, PassedTier, TierStartsAtElo, RewardReceiptDescription,
    SeasonRewardAdded, SeasonSummaryTitle, SeasonSummaryCongratulations, Great,
    SeasonRewardAvatarName, AddedToCollection, ExclusiveSeasonFrame,
    ExclusiveSeasonTitle, ExclusiveSeasonCosmetic, SeasonEnded, DaysRemaining,
    DaysHoursRemaining, HoursMinutesRemaining, MinutesRemaining,
    AvatarOfPlayer, SeasonalFrame, BronzeFrame, SilverFrame, GoldFrame,
    PerfectFrame, PersistentFrameName, BasicFrame, PresenceOffline,
    PresenceOnline, PresenceInRoom, PresencePlaying, WalletBalanceDescription,
    RewardGoldDescription, RewardXpDescription, RewardGemsDescription,
    WalletReceivedGold, WalletUsedGold, WalletReceivedXp, WalletUsedXp,
    WalletReceivedGems, WalletUsedGems, RankBronze, RankSilver, RankGold,
    RankPlatinum, RankDiamond, RankMaster, RankChallenger,
    NoWalletActivity, WalletRewardsAppear, WalletNoActivityInFilter,
    WinRate, AccuracyLabel, RecentFormTen, EloChange, PointsCount, Overview,
    Losses, DrawsLabel, HighScore, CorrectWrongLabel, ModeStatistics,
    AchievementsTitle, NoAchievements, Frames, CurrentSessionDuration,
    MissionPlayThree, MissionWinOne, MissionCorrectHundred, MissionPerfectWin,
    WeekMonday, WeekTuesday, WeekWednesday, WeekThursday, WeekFriday,
    WeekSaturday, WeekSunday, ModeWinRate, ModeMatchSummary, ScoreAverage,
    LoadingMatch, MatchDetails, ReactionLabel, NoEloChange, MatchTapSummary,
    NoReplayData, ReplayTurn, CorrectSelection, WrongSelectionNeed,
    StopReplay, Replay, Previous, Next, LockedCosmetic, UnlockLevel,
    UnlockPerfectFrame, UnlockPersistentFrame, UnlockChampionTitle,
    UnlockSpeedTitle, UnlockDiligentTitle, UnlockCheckInAvatar,
    AchievementFirstWinTitle, AchievementFirstWinDescription,
    AchievementWinTenTitle, AchievementWinTenDescription,
    AchievementPerfectTitle, AchievementPerfectDescription,
    AchievementSpeedTitle, AchievementSpeedDescription,
    AchievementCheckInTitle, AchievementCheckInDescription, MissionsTitle,
    ClanMissionSource, CosmeticPurchaseSource, TournamentEntrySource,
    TournamentPrizeSource, SeasonRewardSource, GemTopUpSource, WalletAdjustmentSource,

    RemoveFriendTitle, RemoveFriendDescription, RemoveFriendAction, GoBack,
    BlockFriendDescription, YourSquad, YourSquadDescription, RoomInvitations,
    NewCount, RoomInvitationSummary, FriendRequests, PlayerCodeLabel, PlayerCodeShort, PlayerCodeExample,
    BlockPlayerNamed, FriendList, ActiveFriends, NoFriendsDescription, PendingReplies,
    SentFriendInvitation, BlockedPlayers, Unblock, PlayerActions, InviteSent,
    SendingInvitation, InviteToRoom, RoomInvitationTitle, WaitingForYou, RoomLabel, SocialHub,

    ClanTogetherTitle, ClanTogetherDescription, SearchClan, SearchClanPlaceholder,
    SearchClanAction, CreateClan, CreateAction, ExploreClans, NoClansFound, NoClansFoundDescription,
    ClanSummary, PendingApproval, RequestToJoin, CreateClanTitle, CreateClanDescription,
    ClanName, ClanDescription, DefaultClanDescription, SelectClanLogo, ClanLogo,
    JoinRequestsCount, ClanMembers, LeaveClan, LeaveClanTitle, LeaveClanDescription,
    RemoveClanMemberTitle, RemoveClanMemberDescription, RemoveClanMemberAction,
    ClanTrophies, MemberTrophies, TotalTrophies, WeeklyClanQuest, WinClanMatches,
    Approve, ClanMemberSummary, RemoveClanMemberNamed, ChooseClanLogo,
    ChooseClanLogoDescription, ClanRoleLeader, ClanRoleCoLeader, ClanRoleMember,
    ClanLogoShield, ClanLogoSwords, ClanLogoFlag, ClanLogoDragon, ClanLogoWolf,
    ClanLogoEagle, ClanLogoCrown, ClanLogoNamed,

    Individual, FameRace, FameRaceDescription, CurrentSeason, PreviousSeason,
    AllTime, History, TopPlayers, WarriorsCount, CurrentSeasonLeaderboardEmpty,
    PreviousSeasonLeaderboardEmpty, AllTimeLeaderboardEmpty, YourPosition,
    StrongestClans, StrongestClansDescription, TopClans, ClansCount,
    ClanLeaderboardEmpty, YourClan, RankingAwaiting, YouSuffix, MembersCount,
    TotalElo, LeaderboardPlayerSummary,

    KnockoutArena, KnockoutArenaDescription, TournamentLobby, ChampionName,
    TournamentUpdating, TournamentCancelled, TournamentLobbySummary, BracketInProgress,
    TournamentPrizeAwarded, CreateAnotherTournament, JoinInvitations,
    RecentTournaments, TournamentInvitationTitle, TournamentInvitationDescription,
    DecideLater, ChooseTournamentMode, CreatePrivateTournament, TournamentSize,
    TournamentFourFormat, TournamentEightFormat, TournamentSixteenFormat,
    TournamentName, TournamentNameExample, GameModeLabel, EntryFeeGold,
    Free, Custom, EnterEntryFee, EntryFeeExample, CreateTournamentAction, TournamentNoElo,
    PlayerCountUpper, EntryFee, Prize, GoldAmount, Participants, WaitingForPlayerEllipsis,
    TournamentHost, StartTournament, Bracket, CancelTournament, LeaveTournament,
    AutomaticMatchesDescription, Champion, FinalRound, SemifinalRound,
    QuarterfinalRound, RoundOfSixteen, RoundNumber, MatchPending, MatchPlaying,
    WaitingEllipsis, TournamentInviteCompact, ChampionCompact, HideBracket,
    TournamentPhaseLobby, TournamentPhaseRunning, TournamentPhaseFinished,
    TournamentPhaseCancelled, JoinTournament, InviteAction, MatchFinished,

    ClearAllNotificationsTitle, ClearAllNotificationsDescription,
    ClearAllNotifications, ClearAllNotificationsA11y, MarkAllRead, EmptyInbox, EmptyInboxDescription,
    NotificationsHero, NotificationsHeroDescription, DeleteNotificationTitle,
    DeleteNotificationDescription, DeleteNotification,

    GemTab, NumberSkins, NumberBoards, GemVault, ArcadeVault,
    GemVaultDescription, ArcadeVaultDescription, Restocking, RestockingDescription,
    ChooseGemPackage, GemPackageDescription, LoginToBuyGems, PriceUnavailable,
    EarnGemsDescription, Popular, EquippingNow, Equip, GemAmount,
    ShopItemGoldName, ShopItemDiamondName, ShopBoardDarkName, ShopBoardForestName,
    BillingPlayNotReady, BillingPlayReconnecting, BillingPriceLoadFailed,
    BillingProductsMissing, BillingProductUnavailable, BillingLaunchFailed,
    BillingCancelled, BillingRestoring, BillingUnavailable, BillingIncomplete,
    BillingVerifying, BillingPending, BillingSandboxVerifying, BillingGemsAdded,
    BillingFinishLater, BillingSandboxActive, BillingStoreKitSandboxNotice,
    BillingAppStoreNotConfigured, BillingWebUnsupported,

    ServerAuthRequired, ServerRateLimited, ServerInvalidRequest,
    ServerSessionExpired, ServerProtocolMismatch, ServerEmailNotVerified,
    ServerRoomNotFound, ServerWrongPassword, ServerRoomFull, ServerNotInRoom,
    ServerHostRequired, ServerModeLocked, ServerNotEnoughGold, ServerPlayerBusy,
    ServerResourceNotFound, ServerAlreadyExists, ServerUnavailable,
    ServerActionFailed, ServerInvalidInput, ServerInvitationExpired,
    PasswordChanged, PasswordResetSent, PasswordResetCompleted,
    EmailVerificationSent, EmailVerified, SessionRevoked, AllSessionsRevoked,
    AccountDeleted,
    NotificationFriendRequestMessage, NotificationRoomInvitationMessage,
    NotificationAchievementMessage, NotificationCosmeticMessage, NotificationMissionMessage,
    TournamentCreatedNotice, TournamentInvitationSentNotice, TournamentInvitationDeclinedNotice,
    TournamentInvitationDeclinedByFriendNotice, TournamentJoinedNotice,
    TournamentCancelledNotice, TournamentLeftNotice,
    FriendRequestSentNotice, FriendRequestCancelledNotice, FriendRequestAcceptedNotice,
    FriendRequestDeclinedNotice, FriendRemovedNotice, PlayerBlockedNotice, PlayerUnblockedNotice,
    RoomInvitationDeclinedNotice, RoomInvitationDeclinedByFriendNotice,
    RoomKickedNotice, ResultsLeftNotice, RoomHostLeftNotice, RoomPlayerLeftNotice,
    RoomDisconnectedTooLongNotice,
    ClanCreatedNotice, ClanJoinRequestedNotice, ClanJoinApprovedOwnerNotice,
    ClanJoinRejectedOwnerNotice, ClanJoinApprovedNotice, ClanJoinRejectedNotice, ClanLeftNotice,
    SeasonDefaultName, SeasonDefaultRewardDescription
}
