package com.hienthai.fastowin.localization

/** Stable keys shared by clients and the backend. Never use player input as a key. */
enum class TextKey {
    Back, Cancel, Confirm, Retry, Close, Save, Delete, Loading, UnknownError, WelcomePlayer,
    SettingsTitle, LanguageTitle, ChooseLanguageTitle, SystemLanguage, ResolvedSystemLanguage,
    AppearanceTitle, AppearanceSubtitle,

    Gold, Gems, Notifications, ViewMoreCount,
    UpdateGameTitle, UpdateAvailableSubtitle, UpdateHeroTitle, UpdateDescription,
    UpdateAutoReload, UpdateProgressPreserved, UpdateNow, Later,
    MaintenanceBadge, MaintenanceTitle, MaintenanceDefaultMessage, MaintenanceAutoResume,
    MaintenanceNoAction,
    OfflineBadge, OfflineTitle, OfflineDescription, OfflineCheckNetwork, OfflineNotMaintenance,
    RetryConnection, OfflinePractice, NoNetwork,
    TutorialTitle, Skip, TutorialStep,
    TutorialFindNumbersTitle, TutorialFindNumbersDescription, TutorialFindNumbersHint,
    TutorialSharedTargetTitle, TutorialSharedTargetDescription, TutorialSharedTargetHint,
    TutorialChooseModeTitle, TutorialChooseModeDescription, TutorialChooseModeHint,
    StartPlaying, Continue,

    VerifyEmailTitle, VerifyEmailDescription, DevVerificationCode, VerificationCode,
    Verifying, Verify, ResendCode, Logout,
    AuthWelcomeDescription, AuthLoginTitle, Login, LoggingIn, CreateAccount, PlayAsGuest, Password,
    ForgotPassword, ResetPasswordTitle, ResetPasswordDescription, Sending, SendResetCode,
    DevResetCode, ResetCode, NewPassword, ConfirmNewPassword, Updating, ResetPasswordAction,
    UseDifferentEmail, DisplayName, GenderDefaultAvatar, Male, Female, Player,
    PasswordWithMinimum, ConfirmPassword, Creating, SaveGuestAccountTitle,
    SaveGuestAccountDescription, Saving, SaveAndCreateAccount, Email, HidePassword,
    ShowPassword, PasswordTooShort, PasswordTooLong, PasswordMismatch,

    Rooms, Leaderboard, Clan, Account,
    FinishCurrentMatchBeforeChallenge, ModeUnlockLevel, CannotOpenChallenge, Understood,
    ChoosePracticeMode, ShareRoom,

    ModeClassicTitle, ModeClassicDescription, ModeRandomTitle, ModeRandomDescription,
    ModeTimeBonusTitle, ModeTimeBonusDescription, ModeSpeedUpTitle, ModeSpeedUpDescription,
    ModeSurvivalTitle, ModeSurvivalDescription, ModeComboTitle, ModeComboDescription,
    ModeTimeAttackTitle, ModeTimeAttackDescription, ModeTeamTitle, ModeTeamDescription,

    ChooseMatchType, ChooseRankedMode, ChooseCasualMode, GuestMode, Ranked, Casual,
    RegisterToPlayOnline, CasualOrRankedDescription, LoginToPlay, PlayNow,
    Explore, FeaturesAndActivities, Tournament, RegisterToJoin, TournamentDescription,
    Shop, ShopDiscoveryDescription, OfflinePracticeTitle, OfflinePracticeDescription,
    SaveProgress, SaveProgressDescription, ExitGuestMode, ChooseCompetitionType,
    CreateRoom, JoinRoom, Friends, RegisterToAddFriends, OnlineFriends,
    YourRank, ViewEloLeaderboard, Level, PlacementPending,
    DailyCheckInSevenDays, CheckInStreak, DayLabel, ClaimDayReward, Home,
    HarderModesUnlock, UnlockAtLevel, ChooseMatchScoring, CasualMatch,
    CasualMatchDescription, RankedMatch, RankedMatchDescription,
    ConnectionDisconnected, ConnectionConnecting, ConnectionAuthenticating,
    ConnectionConnected, ConnectionReconnecting,

    GreetingPlayer, ReadyForRecord, GameRooms, Ready, Matchmaking, MatchFound,
    FindingOpponent, RankedMatchmakingHint, CasualMatchmakingHint, EloRange, NoEloImpact,
    CancelMatchmaking, GuestNameTitle, GuestNameDescription, EnterNickname,
    SaveNameProgressDescription, RoomLinkUnavailable, ChooseRoomType, DefaultRoomName,
    PublicRooms, FindOpponent, PublicRoomsDescription, SaveProgressEmail, SearchRooms,
    All, Waiting, RoomCount, Reconnecting, AuthenticatingSession, Connecting,
    NoWaitingRooms, NoMatchingRooms, EnterRoomCode, PasteRoomCode, RoomCode,
    FindRoom, RoomCodeNotFound, CreateNewRoom, YouAreHost, RoomName, Public, Private,
    PrivatePasswordRequired, PublicNoPassword, RoomPassword, RankedEloImpact,
    CasualNoEloImpact, PrivateRoom, PublicRoom, RoomListSummary, EnterRoom,
    JoinPrivateRoom, JoinRoomTitle, PrivateJoinDescription, PublicJoinDescription,
    JoinedRoomCode, JoinedRoom, ShareCodeHint, WaitHostStart, PlayersTitle,
    BlueTeam, RedTeam, You, TeammateNumber, Teammate, OpponentNumber, Opponent,
    WaitingPlayer, HostYou, Guest, Host, WaitingForPlayer, ModeNumberCount,
    ShareRoomCode, ShareSheetError, CancelReady, ReadyAction, WaitingForReady,
    InviteFriends, Kick, CloseRoom, LeaveRoom, ReadyStatus, WaitingStatus,
    LatencyGood, LatencyStable, LatencySlow, OpponentReady, MatchStarting,
    LocalPlayerLabel, OpponentLabel,

    ReactionHappy, ReactionLaugh, ReactionFire, ReactionVictory, ReactionLove,
    ReactionSpeed, ExitMatchTitle, ForfeitCasualDescription, ForfeitRankedDescription,
    ExitMatch, ContinuePlaying, GameHeader, GameDefaultRoom, GameDisconnected,
    GameReconnecting, TieScoreWarning, CloseScoreWarning, LivesCount, PaceProgress,
    SpeedValue, SendReaction, CorrectWrongSummary, Measuring, YourTeam, OpponentTeam,
    Versus, NextNumber,

    BlockPlayerTitle, BlockPlayerDescription, Block, RematchInviteTitle,
    RematchInviteDescription, Processing, Accept, Decline, DrawResult, VictoryResult,
    DefeatResult, ForfeitResultDescription, DrawResultDescription, VictoryResultDescription,
    OpposingTeamVictoryDescription, OpponentVictoryDescription, MatchResultTitle,
    GameResultSubtitle, ShareResult, ShareResultError, ReturnToLobby, PlayerYou,
    Draw, Win, Loss, ResultLabel, PlacementProgress, MatchReward, FinalMatch,
    SemifinalMatch, TournamentFinishedDescription, BracketUpdatedDescription,
    ViewBracket, YourSummary, AverageReaction, Accuracy, CorrectWrongDuration,
    PaceAnalysis, InsufficientPaceAnalysis, PaceSegmentHint, Fastest, Slowest,
    TurnRange, RankedNoRematch, Rematch, ResponseSeconds, OpponentLeft,
    WaitingForResponse, Invited, SendingShort, InviteRematch, LoginForSocial,
    AddFriend, AcceptFriend, FriendRequestSent, AlreadyFriends, Blocked, LoadingInfo,
    ShareResultCaption, ShareTimeLabel, ShareAccuracyLabel, ShareSlogan,
    ShareResultSheetTitle,

    PracticeHeader, OfflineNoElo, CorrectBoardCompleted, CorrectNextTarget,
    WrongNeedTarget, Target, Score, Remaining, Time, Lives, ComboLabel, Pace,
    EndPractice, FoundAllNumbers, SurvivalEnded, SpeedUpEnded, TimeBonusEnded,
    TimeAttackEnded, ChallengeEnded, Completed, PracticeCompletionSummary,
    ChallengeCode, ChallengeCodeHint, PracticeNoElo, ShareChallenge, ReplaySameBoard,
    CreateNewChallenge, ReturnHome, Reaction, CorrectWrong, AveragePerNumber,
    PracticeHeroTitle, PracticeHeroDescription, PracticeNoServerNeeded,
    StartNewPractice, HaveChallengeCode, PlayChallenge, InvalidChallengeCode,
    ChallengeModeUnlock, ChallengeShareText, ShareChallengeSheetTitle, RoomShareText,
    InvalidRoomIdCode, InvalidChallengeCodeCode
}
